#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: src/usr.sbin/rarpd/Makefile,v 1.14.30.1 2009/04/15 03:14:26 kensmith Exp $

PROG=	rarpd
MAN=	rarpd.8

WARNS?=	3
# This breaks with format strings returned by expand_syslog_m().. argh!
#FORMAT_AUDIT?=	1

.include <bsd.prog.mk>
