// $FreeBSD$

#define LLVM_REVISION "llvmorg-14-init-11187-g222442ec2d71"
#define LLVM_REPOSITORY "https://github.com/llvm/llvm-project.git"

#define CLANG_REVISION "llvmorg-14-init-11187-g222442ec2d71"
#define CLANG_REPOSITORY "https://github.com/llvm/llvm-project.git"

// <Upstream revision at import>-<Local identifier in __FreeBSD_version style>
#define LLD_REVISION "llvmorg-14-init-11187-g222442ec2d71-1400003"
#define LLD_REPOSITORY "FreeBSD"

#define LLDB_REVISION "llvmorg-14-init-11187-g222442ec2d71"
#define LLDB_REPOSITORY "https://github.com/llvm/llvm-project.git"
