// $FreeBSD$

#define LLVM_REVISION "llvmorg-11.0.0-rc2-91-g6e042866c30"
#define LLVM_REPOSITORY "git@github.com:llvm/llvm-project.git"

#define CLANG_REVISION "llvmorg-11.0.0-rc2-91-g6e042866c30"
#define CLANG_REPOSITORY "git@github.com:llvm/llvm-project.git"

// <Upstream revision at import>-<Local identifier in __FreeBSD_version style>
#define LLD_REVISION "llvmorg-11.0.0-rc2-91-g6e042866c30-1200012"
#define LLD_REPOSITORY "FreeBSD"

#define LLDB_REVISION "llvmorg-11.0.0-rc2-91-g6e042866c30"
#define LLDB_REPOSITORY "git@github.com:llvm/llvm-project.git"
