// $FreeBSD$

#define LLVM_REVISION "c1a0a213378a458fbea1a5c77b315c7dce08fd05"
#define LLVM_REPOSITORY "git@github.com:llvm/llvm-project.git"

#define CLANG_REVISION "c1a0a213378a458fbea1a5c77b315c7dce08fd05"
#define CLANG_REPOSITORY "git@github.com:llvm/llvm-project.git"

// <Upstream revision at import>-<Local identifier in __FreeBSD_version style>
#define LLD_REVISION "c1a0a213378a458fbea1a5c77b315c7dce08fd05-1300006"
#define LLD_REPOSITORY "FreeBSD"

#define LLDB_REVISION "c1a0a213378a458fbea1a5c77b315c7dce08fd05"
#define LLDB_REPOSITORY "git@github.com:llvm/llvm-project.git"
