# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: src/usr.sbin/amd/wire-test/Makefile,v 1.3.2.1 2001/04/25 12:09:16 ru Exp $
#

.PATH:		${.CURDIR}/../../../contrib/amd/wire-test

PROG=		wire-test
MAN=		wire-test.8

DPADD+=		${LIBAMU}
LDADD+=		${LIBAMU}

.include <bsd.prog.mk>
