#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/vgrind/RETEST/Makefile,v 1.3.22.1.4.1 2010/06/14 02:09:06 kensmith Exp $

PROG=	retest
SRCS=	regexp.c retest.c
.PATH:	${.CURDIR}/..
NO_MAN=

install:

.include <bsd.prog.mk>
