# $FreeBSD: src/gnu/usr.bin/texinfo/install-info/Makefile,v 1.12.36.1.6.1 2010/12/21 17:09:25 kensmith Exp $

PROG=	install-info

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/util ${TXIDIR}/doc
