# $FreeBSD: src/share/doc/psd/25.xdrrfc/Makefile,v 1.6.24.1 2010/02/10 00:26:20 kensmith Exp $

VOLUME=		psd/25.xdrrfc
SRCS=		stubs xdr.rfc.ms
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
