# $FreeBSD: src/share/doc/psd/25.xdrrfc/Makefile,v 1.6.22.1.4.1 2010/06/14 02:09:06 kensmith Exp $

VOLUME=		psd/25.xdrrfc
SRCS=		stubs xdr.rfc.ms
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
