#
# /src/NTP/REPOSITORY/v3/kernel/Makefile.tmpl,v 3.6 1994/01/25 19:04:35 kardel Exp
#
# parse routine that could be used in two places
#
COMPILER= cc
COPTS= -O
AUTHDEFS=-DDES
LIBDEFS= -DBIG_ENDIAN
RANLIB=		ranlib
INSTALL= install
CLOCKDEFS=
DEFS=
DEFS_OPT=
DEFS_LOCAL=
CLK_VDOBJS=clkinit.o tty_clk_STREAMS.o
CHU_VDOBJS=chuinit.o tty_chu_STREAMS.o
INCL=-I../include
CFLAGS=	$(COPTS) $(DEFS) $(DEFS_LOCAL) $(INCL) -DKERNEL
CC=		$(COMPILER)
#

all:
	@echo $(DEFS) $(DEFS_LOCAL) $(CLOCKDEFS) | \
		awk '/-DREFCLOCK/ && ( /-D.*CLK/ || /-D.*PPS/ ) { makeit=1; }\
			END { if (makeit) \
				{ print ""; \
				  print "### STREAMS kernel modules ppsclock, ppsclocd or line disciplines must"; \
			 	  print "### be installed manually if needed"; \
				  print "### see kernel/README* for details"; \
				  print "### The parse refclock implementation has their own support in"; \
				  print "### parse/*."; } }'

loadable: clk.o chu.o

clk.o:	${CLK_VDOBJS}
	ld -r ${OBJS} -o clk.o

clk.h:	
	echo "#define NCLK	2" > clk.h

tty_clk_STREAMS.o: clk.h tty_clk_STREAMS.c
	cc ${CFLAGS} tty_clk_STREAMS.c -c tty_clk_STREAMS.o

chu.o:	${CHU_VDOBJS}
	ld -r ${OBJS} -o chu.o

chu.h:	
	echo "#define NCHU	2" > chu.h

tty_chu_STREAMS.o: chu.h tty_chu_STREAMS.c
	cc ${CFLAGS} tty_chu_STREAMS.c -c tty_chu_STREAMS.o

clean:
	-@rm -f *~ *.o *.out *.ln make.log Makefile.bak \
		lintlib.errs lint.errs

distclean:	clean
	-@rm -f *.orig *.rej .version Makefile
