# $FreeBSD: src/gnu/usr.bin/texinfo/libtxi/Makefile,v 1.10.24.1 2010/02/10 00:26:20 kensmith Exp $

LIB=	txi
INTERNALLIB=

SRCS=   substring.c xexit.c xmalloc.c xstrdup.c

.include <bsd.lib.mk>

.PATH: ${TXIDIR}/lib
