.\" @(#)bootparamd.8
.\" $FreeBSD: src/usr.sbin/bootparamd/bootparamd/bootparamd.8,v 1.9 2000/03/01 14:09:03 sheldonh Exp $
.Dd November 8, 1989
.Dt BOOTPARAMD 8
.Os
.Sh NAME
.Nm bootparamd
.Nd boot parameter server
.Sh SYNOPSIS
.Nm
.Op Fl ds
.Op Fl r Ar router
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm Bootparamd
is a server process that provides information to diskless clients
necessary for booting.
It consults the
.Pa /etc/bootparams
file. 
.Pp
This version will allow the use of aliases on the hostname in the
.Pa /etc/bootparams
file.
The returned hostname to the whoami request done by the booting client
will be the name that appears in 
.Pa /etc/bootparams
and not the canonical name.
In this way you can keep the answer short enough
so that machines that can not handle long hostnames won't fail during boot.
.Sh OPTIONS
.Bl -tag -width Fl
.It Fl d
Display the debugging information.
.It Fl s
Log the debugging information with syslog. 
.It Fl r Ar router
The default router (a machine or an IP-address).
This defaults to the machine running the server.
.It Fl f Ar file
The file to use as boot parameter file instead of
.Pa /etc/bootparams .
.El
.Sh FILES
.Bl -tag -width /etc/bootparams -compact
.It /etc/bootparams
.El
.Sh BUGS
You may find the syslog loggings to be verbose.
.Sh AUTHORS
Written by
.An Klas Heggemann Aq klas@nada.kth.se
