# The FreeBSD Russian Documentation Project
#
# $FreeBSD: src/release/doc/ru_RU.KOI8-R/hardware/Makefile,v 1.2.10.1.4.1 2010/06/14 02:09:06 kensmith Exp $
# $FreeBSDru: frdp/release/doc/ru_RU.KOI8-R/hardware/Makefile,v 1.1 2004/05/27 06:09:42 den Exp $
#
# Original revision: 1.6

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR= amd64
SUBDIR+= ia64
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
