#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/diskperf/Makefile,v 1.7.16.1 2008/10/02 02:57:24 kensmith Exp $

VOLUME=		papers
DOC=		diskperf
SRCS=		abs.ms motivation.ms equip.ms methodology.ms tests.ms \
		results.ms conclusions.ms appendix.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
