#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/diskperf/Makefile,v 1.7.24.1 2010/02/10 00:26:20 kensmith Exp $

VOLUME=		papers
DOC=		diskperf
SRCS=		abs.ms motivation.ms equip.ms methodology.ms tests.ms \
		results.ms conclusions.ms appendix.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
