# $FreeBSD: src/sys/modules/libalias/libalias/Makefile,v 1.3.2.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../../netinet/libalias

KMOD=	libalias
SRCS=	alias.c alias_db.c alias_proxy.c alias_util.c alias_mod.c alias_sctp.c

.include <bsd.kmod.mk>
