# $FreeBSD: src/usr.sbin/pcvt/Misc/Etc/Makefile,v 1.8.8.1 2005/02/13 07:23:44 obrien Exp $

NOOBJ=
FILES=	Termcap Terminfo pcvt.el xmodmap-german pcvt.sh
FILESDIR=	${BINDIR}/Etc

.include <bsd.prog.mk>
