# $FreeBSD: src/usr.sbin/fifolog/Makefile,v 1.1.2.1.6.1 2010/02/10 00:26:20 kensmith Exp $

VERSION_MAJOR = 1
VERSION_MINOR = 1

SUBDIR	=	lib fifolog_create fifolog_writer fifolog_reader

.include <bsd.subdir.mk>

test:	_SUBDIR
