#!/bin/sh
name=$1

. ./ipflib.sh

test_init

echo "$name...";
input=`expr $name : 'bpf-\(.*\)'`
/bin/cp /dev/null results/$name
( while read rule; do
	echo "$rule" | ../ipftest -Rbr - -i input/$input >> results/$name
	if [ $? -ne 0 ] ; then
		exit 1;
	fi
	echo "--------" >> results/$name
done ) < regress/$name
check_results $name
exit $status
