#!/bin/sh

# Copyright (c) 2001 Proofpoint, Inc. and its suppliers.
#	All rights reserved.
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the sendmail distribution.
#
#
#	$Id: Build,v 1.2 2013-11-22 20:52:01 ca Exp $

exec sh ../devtools/bin/Build $*
