# $NetBSD: Makefile,v 1.1 2012/03/17 16:33:15 jruoho Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/sort

TESTS_SH=	t_sort

FILESDIR=	${TESTSDIR}
FILES=		d_any_char_dflag_out.txt
FILES+=		d_any_char_fflag_out.txt
FILES+=		d_any_char_iflag_out.txt
FILES+=		d_any_char_in.txt

.include <bsd.test.mk>
