# $FreeBSD: src/sys/modules/s3/Makefile,v 1.5.30.1 2008/10/02 02:57:24 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/fb

KMOD=	s3
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h \
	s3_pci.c

.include <bsd.kmod.mk>
