# $FreeBSD: src/sys/modules/ipw/Makefile,v 1.1 2005/04/18 18:47:38 damien Exp $

.PATH: ${.CURDIR}/../../dev/ipw

KMOD    = if_ipw
SRCS    = if_ipw.c opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
