# $FreeBSD: src/sys/modules/aic7xxx/aicasm/Makefile,v 1.8.16.1 2008/10/02 02:57:24 kensmith Exp $

MAKESRCPATH=	${.CURDIR}/../../../dev/aic7xxx/aicasm

install:

.include "${.CURDIR}/../../../dev/aic7xxx/aicasm/Makefile"

build-tools: ${PROG}
