# $FreeBSD: src/sys/modules/aic7xxx/aicasm/Makefile,v 1.8.18.1 2008/11/25 02:59:29 kensmith Exp $

MAKESRCPATH=	${.CURDIR}/../../../dev/aic7xxx/aicasm

install:

.include "${.CURDIR}/../../../dev/aic7xxx/aicasm/Makefile"

build-tools: ${PROG}
