# $FreeBSD: src/sys/modules/aic7xxx/aicasm/Makefile,v 1.8.24.1 2010/02/10 00:26:20 kensmith Exp $

MAKESRCPATH=	${.CURDIR}/../../../dev/aic7xxx/aicasm

install:

.include "${.CURDIR}/../../../dev/aic7xxx/aicasm/Makefile"

build-tools: ${PROG}
