
PACKAGE=	tests

ATF_TESTS_SH=	diff3_test
${PACKAGE}FILES+=	\
	1.txt \
	1cr.txt \
	2.txt \
	3.txt \
	long-m.txt \
	long-o.txt \
	long-y.txt \
	1.out \
	1t.out \
	2.out \
	3.out \
	4.out \
	5.out \
	6.out \
	7.out \
	8.out \
	9.out \
	long-ed.out \
	long-A.out \
	long-merge.out \

.include <bsd.test.mk>
