.TH curs_termattrs 3 ""
.SH NAME
\fBbaudrate\fR, \fBerasechar\fR, \fBhas_ic\fR,
\fBhas_il\fR, \fBkillchar\fR, \fBlongname\fR, \fBtermattrs\fR,
\fBtermname\fR - \fBncurses\fR environment query routines
.SH SYNOPSIS
\fB#include <ncurses.h>\fR

\fBint baudrate(void);\fR
.br
\fBchar erasechar(void);\fR
.br
\fBint has_ic(void);\fR
.br
\fBint has_il(void);\fR
.br
\fBchar killchar(void);\fR
.br
\fBchar *longname(void);\fR
.br
\fBchtype termattrs(void);\fR
.br
\fBchar *termname(void);\fR
.br
.SH DESCRIPTION
The \fBbaudrate\fR routine returns the output speed of the terminal.  The
number returned is in bits per second, for example \fB9600\fR, and is an
integer.

The \fBerasechar\fR routine returns the user's current erase character.

The \fBhas_ic\fR routine is true if the terminal has insert- and delete-
character capabilities.

The \fBhas_il\fR routine is true if the terminal has insert- and delete-line
capabilities, or can simulate them using scrolling regions.  This might
be used to determine if it would be appropriate to turn on physical
scrolling using \fBscrollok\fR.

The \fBkillchar\fR routine returns the user's current line kill character.

The \fBlongname\fR routine returns a pointer to a static area
containing a verbose description of the current terminal.  The maximum
length of a verbose description is 128 characters.  It is defined only
after the call to \fBinitscr\fR or \fBnewterm\fR.  The area is
overwritten by each call to \fBnewterm\fR and is not restored by
\fBset_term\fR, so the value should be saved between calls to
\fBnewterm\fR if \fBlongname\fR is going to be used with multiple
terminals.

If a given terminal doesn't support a video attribute that an
application program is trying to use, \fBncurses\fR may substitute a
different video attribute for it.  The \fBtermattrs\fR function
returns a logical \fBOR\fR of all video attributes supported by the
terminal.  This information is useful when a \fBncurses\fR program
needs complete control over the appearance of the screen.

The \fBtermname\fR routine returns the value of the environment
variable \fBTERM\fR (truncated to 14 characters).
.SH RETURN VALUE
\fBlongname\fR and \fBtermname\fR return \fBNULL\fR on error.

Routines that return an integer return \fBERR\fR upon failure and an integer
value other than \fBERR\fR upon successful completion.
.SH NOTES
Note that \fBtermattrs\fR may be a macro.
.SH SEE ALSO
\fBncurses\fR(3), \fBcurs_initscr\fR(3), \fBcurs_outopts\fR(3)
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
