.\"
.\"    $Id$
.\"
.TH curs_instr 3 ""
.SH NAME
\fBinstr\fR, \fBinnstr\fR, \fBwinstr\fR, \fBwinnstr\fR,
\fBmvinstr\fR, \fBmvinnstr\fR, \fBmvwinstr\fR, 
\fBmvwinnstr\fR - get a string of characters from a \fBncurses\fR window
.SH SYNOPSIS
\fB#include <ncurses.h>\fR

\fBint instr(char *str);\fR
.br
\fBint innstr(char *str, int n);\fR
.br
\fBint winstr(WINDOW *win, char *str);\fR
.br
\fBint winnstr(WINDOW *win, char *str, int n);\fR
.br
\fBint mvinstr(int y, int x, char *str);\fR
.br
\fBint mvinnstr(int y, int x, char *str, int n);\fR
.br
\fBint mvwinstr(WINDOW *win, int y, int x, char *str);\fR
.br
\fBint mvwinnstr(WINDOW *win, int y, int x, char *str, int n);\fR
.br
.SH DESCRIPTION
These routines return a string of characters in \fIstr\fR, extracted starting
at the current cursor position in the named window and ending at the right
margin of the window.  Attributes are stripped from the characters.  The four
functions with \fIn\fR as the last argument return a leading substring at most
\fIn\fR characters long.
.SH RETURN VALUE
All routines return the integer \fBERR\fR upon failure and an integer value
other than \fBERR\fR upon successful completion.
.SH NOTES
Note that all routines except \fBwinnstr\fR may be macros.
.SH SEE ALSO
\fBncurses\fR(3).
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"
.\"# End:

