# $FreeBSD$
# All the dts files for am335x systems we support.
DTS=	\
	beaglebone.dts \
	beaglebone-black.dts \
	ufw.dts

LINKS= \
	${DTBDIR}/beaglebone.dtb ${DTBDIR}/am335x-bone.dtb \
	${DTBDIR}/beaglebone-black.dtb ${DTBDIR}/am335x-boneblack.dtb

.include <bsd.dtb.mk>
