# $FreeBSD$
# All the dts files for am335x systems we support.
DTS=	\
	am335x-bone.dts \
	am335x-boneblack.dts \
	am335x-bonegreen.dts \
	ufw.dts

LINKS= \
	${DTBDIR}/am3335x-bone.dtb ${DTBDIR}/beaglebone.dtb \
	${DTBDIR}/am3335x-boneblack.dtb ${DTBDIR}/beaglebone-black.dtb

.include <bsd.dtb.mk>
