# $FreeBSD$

PROG = l2ping

WARNS ?= 2

LDADD += -lbluetooth

DIRDEP= gnu/lib/csu gnu/lib/libgcc include include/arpa lib/csu/MACHINE_ARCH lib/libbluetooth lib/libc stage sys/MACHINE_ARCH/include sys/netgraph/bluetooth/include sys/netinet sys/netinet6 sys/sys
.include <bsd.prog.mk>
