# $Id: Makefile,v 1.5 2003/08/14 20:06:00 max Exp $
# $FreeBSD: src/usr.sbin/bluetooth/bt3cfw/Makefile,v 1.4.16.1 2008/10/02 02:57:24 kensmith Exp $

PROG=		bt3cfw
MAN=		bt3cfw.8
WARNS?=		2

DPADD=		${LIBNETGRAPH}
LDADD=		-lnetgraph

.include <bsd.prog.mk>
