# $FreeBSD: src/sys/boot/i386/zfsloader/Makefile,v 1.1.4.3.2.1 2010/12/21 17:10:29 kensmith Exp $

.PATH:	${.CURDIR}/../loader

LOADER=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" x86
LOADER_ZFS_SUPPORT=yes
LOADER_ONLY=	yes
NO_MAN=		yes

.include "${.CURDIR}/../loader/Makefile"

