# $Id: Makefile 3083 2014-09-02 22:08:01Z kaiwang27 $

TOP=	../../../..

TS_SRCS=	dwarf_attrlist.c
TS_DATA=	dt32-g1 dt64-g1 ec32-g1 ec64-g1 ld_symver.o-64-g1

.include "${TOP}/mk/elftoolchain.tet.mk"
