.\"
.\" Copyright (c) 1997, 1999 Hellmuth Michaelis. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: isdntrace.8,v 1.12 1999/12/13 22:11:55 hm Exp $
.\"
.\" $FreeBSD: src/usr.sbin/i4b/isdntrace/isdntrace.8,v 1.9 2000/03/02 14:53:42 sheldonh Exp $
.\"
.\"	last edit-date: [Mon Dec 13 23:08:17 1999]
.\"
.Dd October 19, 1998
.Dt ISDNTRACE 8
.Os
.Sh NAME
.Nm isdntrace
.Nd isdn4bsd ISDN protocol trace utility
.Sh SYNOPSIS
.Nm isdntrace
.Op Fl a
.Op Fl b
.Op Fl d
.Op Fl f Ar filename
.Op Fl h
.Op Fl i
.Op Fl l
.Op Fl n Ar number
.Op Fl o
.Op Fl p Ar filename
.Op Fl r
.Op Fl u Ar number
.Op Fl B
.Op Fl F
.Op Fl P
.Op Fl R Ar unit
.Op Fl T Ar unit
.Sh DESCRIPTION
.Nm isdntrace
is part of the isdn4bsd package and is used to provide the user with a 
mnemonic display of the layers 1, 2 and 3 protocol activities on 
the D channel and hex dump of the B channel(s) activities.
.Pp
Together with two passive supported cards and an easy to build cable it can
also be used to monitor the complete traffic on a S0 bus providing S0 bus
analyzer features.
.Pp
The
.Nm
utility is only available for passive supported cards.
.Pp
The following options can be used:
.Bl -tag -width Ds
.It Fl a
Run
.Nm
in analyzer mode by using two passive cards and a custom cable which can
be build as described in the file
.Em cable.txt
in the isdn4bsd source distribution.
One card acts as a receiver for the
transmitting direction on the S0 bus while the other card acts as a receiver
for the receiving direction on the S0 bus.
Complete traffic monitoring is
possible using this setup.
.It Fl b
switch B channel tracing on (default off).
.It Fl d
switch D channel tracing off (default on).
.It Fl f
Use 
.Ar filename
as the name of a file into which to write tracing output (default filename is
isdntrace<n> where n is the number of the unit to trace).
.It Fl h
switch display of header off (default on).
.It Fl i
print layer 1 (I.430) INFO signals to monitor layer 1 activity (default off).
.It Fl l
switch displaying of Layer 2 (Q.921) frames off (default on).
.It Fl n
This option takes a numeric argument specifying the minimum 
frame size in octetts a frame must have to be displayed.
(default 0)
.It Fl o
switch off writing trace output to a file (default on).
.It Fl p
Use 
.Ar filename
as the name of a file used for the -B and -P options (default filename
is isdntracebin<n> where n is the number of the unit to trace).
.It Fl r
Switch off printing a raw hexadecimal dump of the packets preceding
the decoded protocol information (default on).
.It Fl u
Use 
.Ar number
as the unit number of the controller card to trace (default 0).
.It Fl B
Write undecoded binary trace data to a file for later or remote 
analyzing (default off).
.It Fl F
This option can only be used when option -P (playback from binary data file)
is used.
The -F option causes playback not to stop at end of file but rather
to wait for additional data to be available from the input file.
.Pp
This option is useful when trace data is accumulated in binary format (to
save disk space) but a monitoring functionality is desired.
(default off).
.It Fl P
Read undecoded binary trace data from file instead from device (default off).
.It Fl R
Use
.Ar unit
as the receiving interface unit number in analyze mode.
.It Fl T
Use
.Ar unit
as the transmitting interface unit number in analyze mode.
.El
.Pp
When the USR1 signal is sent to a
.Nm
process, the currently used logfiles are reopened, so that logfile
rotation becomes possible.
.Pp
The trace output should be obvious.
It is very handy to have the following
standard texts available when tracing ISDN protocols:
.Pp
.Bl -tag -width Ds -compact -offset indent
.It Ar I.430
ISDN BRI layer 1 protocol description.
.It Ar Q.921
ISDN D-channel layer 2 protocol description.
.It Ar Q.931
ISDN D-channel layer 3 protocol description.
.It Ar 1TR6
German-specific ISDN layer 3 protocol description.
(NOTICE: decoding
of the 1TR6 protocol is included but not supported since i dont have
any longer access to a 1TR6 based ISDN installation.)
.El
.Pp

.Nm Isdntrace
automatically detects the layer 3 protocol being used by looking at the
Protocol Discriminator (see: Q.931/1993 pp. 53).
.Pp


.Sh FILES
.Bl -tag -width daddeldi -compact
.It Pa /dev/i4btrc<n>
The devicefile(s) used to get the trace messages for ISDN card unit <n>
out of the kernel.
.El

.Sh EXAMPLES
The command:
.Bd -literal -offset indent
isdntrace -f /var/tmp/isdn.trace
.Ed
.Pp
will start D channel tracing on passive controller 0 with all except B
channel tracing enabled and logs everything into the output file 
/tmp/isdn.trace.

.Sh SEE ALSO
.Xr isdnd 8

.Sh BUGS
Still some or more left.

.Sh STANDARDS
ITU Recommendations I.430, Q.920, Q.921, Q.930, Q.931
.Pp
FTZ Richtlinie 1TR3, Band III
.Pp
ITU Recommendation Q.932 (03/93), Q.950 (03/93)
.Pp
ETSI Recommendation ETS 300 179 (10/92), ETS 300 180 (10/92)
.Pp
ETSI Recommendation ETS 300 181 (04/93), ETS 300 182 (04/93)
.Pp
ITU Recommendation X.208, X.209

.Sh AUTHOR
The
.Nm
utility was written by 
.An Gary Jennejohn 
and 
.An Hellmuth Michaelis .
.Pp
This manual page was written by 
.An Hellmuth Michaelis Aq hm@kts.org .

