# $FreeBSD: src/usr.sbin/i4b/isdntrace/Makefile,v 1.2.2.2 2001/08/01 17:45:08 obrien Exp $

PROG=	isdntrace
MAN=	isdntrace.8
SRCS=	q921.c q931.c q931_util.c q932_fac.c 1tr6.c trace.c \
	pcause_1tr6.c pcause_q850.c unknownl3.c

.include <bsd.prog.mk>

