#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/xinstall/Makefile,v 1.23.24.1 2010/02/10 00:26:20 kensmith Exp $

PROG=		xinstall
PROGNAME=	install
MAN=		install.1
WARNS?=		6

.include <bsd.prog.mk>
