# $FreeBSD: src/usr.bin/less/Makefile.common,v 1.4.36.1 2010/12/21 17:10:29 kensmith Exp $

LSDIR=	${.CURDIR}/../../contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${.CURDIR}/../less -I${LSDIR}

.SUFFIXES: .nro .1

.nro.1:
	cat ${.IMPSRC} > ${.TARGET}
