#	$FreeBSD: src/usr.bin/usbhidaction/Makefile,v 1.3.18.1 2008/11/25 02:59:29 kensmith Exp $
#	$NetBSD: Makefile,v 1.4 2002/02/02 16:54:26 veego Exp $

PROG=	usbhidaction

LDADD=	-lusbhid
DPADD=	${LIBUSBHID}

.include <bsd.prog.mk>
