#
# $Id: Makefile,v 1.7 1996/10/13 17:37:02 peter Exp $
#

# The order of some of these are rather important.  Some depend on previous
# subdirs.

SUBDIR= cc_tools cc_int cpp cc1 cc cc1obj cc1plus c++ f77 libgcc c++filt doc

.include <bsd.subdir.mk>
