# $FreeBSD: src/share/doc/psd/23.rpc/Makefile,v 1.6.20.1 2009/04/15 03:14:26 kensmith Exp $

VOLUME=		psd/23.rpc
SRCS=		stubs rpc.prog.ms
MACROS=		-ms
USE_TBL=
USE_PIC=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
