# $FreeBSD: src/usr.sbin/bsnmpd/gensnmptree/Makefile,v 1.3 2005/01/28 16:08:09 ru Exp $
#
# Author: Harti Brandt <harti@freebsd.org>

CONTRIB=${.CURDIR}/../../../contrib/bsnmp
.PATH: ${CONTRIB}/gensnmptree

PROG=	gensnmptree
CFLAGS+= -I${CONTRIB}/lib

.include <bsd.prog.mk>
