#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/locate/bigram/Makefile,v 1.6.20.1 2009/04/15 03:14:26 kensmith Exp $

PROG=	locate.bigram
NO_MAN=
BINDIR=	${LIBEXECDIR}
CFLAGS+= -I${.CURDIR}/../locate

.include <bsd.prog.mk>
