# $FreeBSD: src/release/doc/en_US.ISO8859-1/relnotes/Makefile,v 1.6 2003/06/27 03:50:36 bmah Exp $

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= amd64
SUBDIR+= ia64
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
