# $FreeBSD: src/gnu/usr.bin/groff/src/libs/libbib/Makefile,v 1.4.20.1 2009/04/15 03:14:26 kensmith Exp $

LIB=		bib
INTERNALLIB=
SRCS=		common.cpp index.cpp linear.cpp search.cpp map.c

.include <bsd.lib.mk>
