# $FreeBSD: src/gnu/usr.bin/groff/src/libs/libbib/Makefile,v 1.4.22.1.6.1 2010/12/21 17:09:25 kensmith Exp $

LIB=		bib
INTERNALLIB=
SRCS=		common.cpp index.cpp linear.cpp search.cpp map.c

.include <bsd.lib.mk>
