# $FreeBSD: src/usr.bin/lesskey/Makefile,v 1.2.2.2 2001/04/25 11:29:26 ru Exp $

PROG=	lesskey
SRCS=	lesskey.c version.c
CLEANFILES= lesskey.1

.include "${.CURDIR}/../less/Makefile.common"
.include <bsd.prog.mk>
