.\" $FreeBSD$ 
.SH "FreeBSD NOTES"

.SH DISPLAY OF THREADS
The '-H' option will toggle the display of kernel visible thread contexts.
At runtime the 'H' key will toggle this mode. The default is OFF.

.SH DESCRIPTION OF MEMORY
Mem: 9220K Active, 1M Inact, 3284K Wired, 1M Cache, 2M Buf, 1320K Free
Swap: 91M Total, 79M Free, 13% Inuse, 80K In, 104K Out
.TP
.B K:
Kilobyte
.TP
.B M:
Megabyte
.TP
.B G:
Gigabyte
.TP
.B %:
1/100
.TP
.B Active:
number of bytes active
.TP
.B Inact:
number of bytes inactive
.TP
.B Wired:
number of bytes wired down, including cached file data pages
.TP
.B Cache:
number of clean bytes caching data that are available for
immediate reallocation
.TP
.B Buf:
number of bytes used for BIO-level disk caching
.TP
.B Free: 
number of bytes free
.TP
.B Total: 
total available swap usage
.TP 
.B Free: 
total free swap usage
.TP 
.B Inuse: 
swap usage
.TP 
.B In: 
bytes paged in from swap devices (last interval)
.TP
.B Out: 
bytes paged out to swap devices (last interval)
