# $FreeBSD: src/lib/libpam/modules/Makefile.inc,v 1.5.2.4 2002/07/19 18:46:30 ru Exp $

PAMDIR=         ${.CURDIR}/../../../../contrib/libpam
SHLIB_NAME=     ${LIB}.so
NOINSTALLLIB=	yes
NOPROFILE=	yes
