# $FreeBSD: src/sys/modules/sound/driver/cs4281/Makefile,v 1.3.28.1 2008/10/02 02:57:24 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_cs4281
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	cs4281.c

.include <bsd.kmod.mk>
