# $FreeBSD: src/sys/modules/wpi/Makefile,v 1.3.2.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
