# $FreeBSD: src/sys/modules/wpi/Makefile,v 1.2.2.1.10.1 2010/12/21 17:10:29 kensmith Exp $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
