# $FreeBSD: src/sys/modules/wpi/Makefile,v 1.3.2.1.6.1 2010/12/21 17:09:25 kensmith Exp $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
