.\" Copyright (C) 2004, 2005 Internet Systems Consortium, Inc. ("ISC")
.\" Copyright (C) 2000, 2001 Internet Software Consortium.
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH
.\" REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
.\" LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
.\" OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.\" $Id: lwres_hstrerror.3,v 1.13.2.1.8.5 2005/10/13 02:33:53 marka Exp $
.\"
.hy 0
.ad l
.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "LWRES_HSTRERROR" "3" "Jun 30, 2000" "BIND9" "BIND9"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lwres_herror, lwres_hstrerror \- lightweight resolver error message generation
.SH "SYNOPSIS"
.nf
#include <lwres/netdb.h>
.fi
.HP 18
\fBvoid\ \fBlwres_herror\fR\fR\fB(\fR\fBconst\ char\ *s\fR\fB);\fR
.HP 29
\fBconst\ char\ *\ \fBlwres_hstrerror\fR\fR\fB(\fR\fBint\ err\fR\fB);\fR
.SH "DESCRIPTION"
.PP
\fBlwres_herror()\fR
prints the string
\fIs\fR
on
\fBstderr\fR
followed by the string generated by
\fBlwres_hstrerror()\fR
for the error code stored in the global variable
\fBlwres_h_errno\fR.
.PP
\fBlwres_hstrerror()\fR
returns an appropriate string for the error code gievn by
\fIerr\fR. The values of the error codes and messages are as follows:
.TP
\fBNETDB_SUCCESS\fR
Resolver Error 0 (no error)
.TP
\fBHOST_NOT_FOUND\fR
Unknown host
.TP
\fBTRY_AGAIN\fR
Host name lookup failure
.TP
\fBNO_RECOVERY\fR
Unknown server error
.TP
\fBNO_DATA\fR
No address associated with name
.SH "RETURN VALUES"
.PP
The string
Unknown resolver error
is returned by
\fBlwres_hstrerror()\fR
when the value of
\fBlwres_h_errno\fR
is not a valid error code.
.SH "SEE ALSO"
.PP
\fBherror\fR(3),
\fBlwres_hstrerror\fR(3).
