# $FreeBSD: src/tools/regression/kgssapi/Makefile,v 1.1.2.1.4.1 2010/06/14 02:09:06 kensmith Exp $

PROG=	gsstest
NO_MAN=
WARNS?=	2
LDADD=	-lgssapi -lgssapi_krb5
DEBUG_FLAGS= -g -O0

.include <bsd.prog.mk>
