#	$NetBSD: Makefile,v 1.21 2016/04/08 10:09:16 gson Exp $
#

.include <bsd.own.mk>

TESTSDIR=       ${TESTSBASE}/usr.bin

TESTS_SUBDIRS=	awk basename bzip2 cc cmp config cut \
		diff dirname find gdb grep gzip id \
		infocmp jot ld m4 make mkdep \
		nbperf netpgpverify pr rump_server shmif_dumpbus sdiff \
		sed sort tmux tr unifdef vmstat xlint

.include <bsd.test.mk>
