# $FreeBSD: src/sys/modules/sound/driver/neomagic/Makefile,v 1.3.38.1 2010/12/21 17:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_neomagic
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	neomagic.c

.include <bsd.kmod.mk>
