# $FreeBSD: src/tools/tools/net80211/wlanstats/Makefile,v 1.3.12.1 2010/02/10 00:26:20 kensmith Exp $

PROG=	wlanstats
BINDIR=	/usr/local/bin
NO_MAN=

SRCS=	statfoo.c wlanstats.c main.c

.include <bsd.prog.mk>
