# $FreeBSD: src/usr.sbin/mrouted/common/Makefile,v 1.8.12.1 2008/10/02 02:57:24 kensmith Exp $

S=	${.CURDIR}/..
.PATH: $S

LIB=	mrouted
INTERNALLIB=
SRCS=	igmp.c inet.c kern.c

CFLAGS+= -I$S

.include <bsd.lib.mk>
