# $FreeBSD$

.PATH: ${NCURSES_DIR}/ncurses/tinfo

BINDIR = ${STAGEDIR}/buildtools/ncurses

PROG = make_keys

HOSTPROG =

BUILTFILES += names.c

names.c:
	${AWK} -f ${NCURSES_DIR}/ncurses/tinfo/MKnames.awk bigstrings=${USE_BIG_STRINGS} ${NCURSES_DIR}/include/Caps > ${.TARGET}

.include <bsd.prog.mk>
