# $FreeBSD$

LIB=	llvminstrumentation

SRCDIR=	lib/Transforms/Instrumentation
SRCS=	BlockProfiling.cpp EdgeProfiling.cpp ProfilingUtils.cpp \
	RSProfiling.cpp

TGHDRS=	Intrinsics

.include "../../clang.lib.mk"
