# $FreeBSD: src/sys/modules/fxp/Makefile,v 1.18 2005/09/27 18:10:34 mlaier Exp $

.PATH: ${.CURDIR}/../../dev/fxp

KMOD=	if_fxp
SRCS=	if_fxp.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
