# $FreeBSD: src/etc/namedb/Makefile,v 1.5.10.1.2.1 2009/10/25 01:10:29 kensmith Exp $

SUBDIR=	master

FILES=	named.conf named.root

NO_OBJ=
FILESDIR=	/etc/namedb
FILESMODE=	644

.include <bsd.prog.mk>
