#!/bin/sh
#
# $FreeBSD: src/etc/namedb/make-localhost,v 1.4 1999/08/27 23:24:01 peter Exp $
#
# make-localhost - edit the appropriate local information into
# /etc/namedb/localhost.rev
#

if [ "`hostname -s`" != "`hostname`" ]; then
	# hostname must contain domain

	host=`hostname -s`
	fullhost=`hostname`
	domain=`echo $fullhost | sed "s/^$host\.//"`
else
	host=`hostname`

	if [ -z "$1" ]; then
		echo -n 'Enter your domain name: '
		read domain
	else
		domain="$1"
	fi

	# strip trailing dot, if any
	domain=`echo $domain | sed 's/\.$//'`
	fullhost="$host.$domain"
fi

date=`date +"%Y%m%d"`

mv -f localhost.rev localhost.rev.BAK 2>/dev/null

exec sed -e "s/@host@/$fullhost/g" \
	-e "s/@domain@/$domain/g" \
	-e "s/@date@/$date/g" \
	< PROTO.localhost.rev > localhost.rev
