# $Id: Makefile.inc,v 1.3 1998/09/01 00:41:24 msmith Exp $

SRCS+=	boot.c commands.c console.c devopen.c interp.c interp_backslash.c
SRCS+=	interp_parse.c load_aout.c ls.c misc.c module.c panic.c # pnp.c
