#	From: @(#)Makefile	5.1 (Berkeley) 6/25/90
#	$Id: Makefile,v 1.2 1994/07/19 19:23:46 g89r4222 Exp $

PROG=	kdb_destroy
CFLAGS+=-DKERBEROS -DDEBUG -I${.CURDIR}/../include
NOMAN=	noman

.include <bsd.prog.mk>
