PROG   = gctags
DEFS   = -DGLOBAL -DYACC
CC     = gcc
CFLAGS = -O $(DEFS) -I../lib -I/usr/include/db
LIBS   = -L../lib -lutil -ldb
OBJS   = C.o assembler.o ctags.o fortran.o lisp.o print.o tree.o yacc.o
BINDIR = /usr/bin
MANDIR = /usr/man

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) -o $(PROG) $(OBJS) $(LIBS)
install:
	cp $(PROG) $(BINDIR)
	chmod 755 $(BINDIR)/$(PROG)
	cp $(PROG).1 $(MANDIR)/man1
	chmod 644 $(MANDIR)/man1/$(PROG).1
clean:
	rm -f $(PROG) $(OBJS)
