#! /bin/sh
# $FreeBSD: src/usr.sbin/ctm/mkCTM/dequeue,v 1.4.56.1.4.1 2010/06/14 02:09:06 kensmith Exp $

L=/home/ctm/log.dequeue
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-cvs-cur
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-src-cur
