#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/fortune/unstr/Makefile,v 1.3.8.1 2005/02/13 07:23:05 obrien Exp $

PROG=	unstr
NOMAN=
CFLAGS+=-Wall -I${.CURDIR}/../strfile

.include <bsd.prog.mk>
