#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/fortune/unstr/Makefile,v 1.3 2001/02/21 06:12:38 bde Exp $

PROG=	unstr
NOMAN=	noman
CFLAGS+=-Wall -I${.CURDIR}/../strfile

.include <bsd.prog.mk>
