# $FreeBSD$

KYUA_VERSION=	0.13

KYUA_CONFDIR=	/etc/kyua
KYUA_DOCDIR=	/nonexistant
KYUA_EGDIR=	/usr/share/examples/kyua
KYUA_MISCDIR=	/usr/share/kyua/misc
KYUA_STOREDIR=	/usr/share/kyua/store

KYUA_SRCDIR=	${SRCTOP}/contrib/kyua
