# $FreeBSD: src/tools/tools/net80211/wesside/dics/Makefile,v 1.1.14.1 2010/12/21 17:10:29 kensmith Exp $

PROG=	dics
BINDIR=	/usr/local/bin
DPADD=	${LIBZ}
LDADD=	-lz
CFLAGS=-g
NO_MAN=

.include <bsd.prog.mk>
