#!/bin/sh
#
# $NetBSD: bootparams,v 1.6 2002/03/22 04:33:58 thorpej Exp $
# $FreeBSD: src/etc/rc.d/bootparams,v 1.7 2004/10/07 13:55:25 mtm Exp $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
rcvar=`set_rcvar`
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
