#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/cron,v 1.8.2.2.2.1 2012/03/03 06:15:13 kensmith Exp $
#

# PROVIDE: cron
# REQUIRE: LOGIN cleanvar
# BEFORE: securelevel
# KEYWORD: shutdown

. /etc/rc.subr

name="cron"
rcvar="cron_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
if checkyesno cron_dst
then
	cron_flags="$cron_flags -s"
fi
run_rc_command "$1"
