#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/devd,v 1.6.2.1 2004/10/10 09:50:53 mtm Exp $
#

# PROVIDE: devd
# REQUIRE: NETWORKING
# BEFORE: mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="devd"
rcvar=`set_rcvar`
command="/sbin/devd"

load_rc_config $name
run_rc_command "$1"

# If devd is disabled, turn it off in the kernel to avoid memory leaks.
if ! checkyesno ${rcvar}; then
    sysctl hw.bus.devctl_disable=1
fi
