#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/FILESYSTEMS,v 1.2.2.2.4.1 2008/10/02 02:57:24 kensmith Exp $
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal

#	This is a dummy dependency, for services which require file systems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other file systems than /.
