#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: idmapd
# REQUIRE: rpcbind
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="idmapd"

load_rc_config $name
rcvar="idmapd_enable"
command="${idmapd:-/sbin/${name}}"
eval ${name}_flags=\"${idmapd_flags}\"
run_rc_command "$1"
