#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/idmapd,v 1.1.6.1 2008/11/25 02:59:29 kensmith Exp $
#

# PROVIDE: idmapd
# REQUIRE: rpcbind
# KEYWORD: nojail

. /etc/rc.subr

name="idmapd"

load_rc_config $name
rcvar="idmapd_enable"
command="${idmapd:-/sbin/${name}}"
eval ${name}_flags=\"${idmapd_flags}\"
run_rc_command "$1"
