#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ike,v 1.4 2004/10/07 13:55:26 mtm Exp $
#

# PROVIDE: ike
# REQUIRE: root mountcritlocal
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ike"
rcvar=`set_rcvar`
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
