#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ike
# REQUIRE: root beforenetlkm mountcritlocal
# BEFORE:  DAEMON
# KEYWORD: FreeBSD

. /etc/rc.subr

name="ike"
rcvar=`set_rcvar`
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
