#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/inetd,v 1.5.2.1.2.1 2008/10/02 02:57:24 kensmith Exp $
#

# PROVIDE: inetd
# REQUIRE: DAEMON LOGIN cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="inetd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
