#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ipxrouted,v 1.2.2.1 2004/10/10 09:50:53 mtm Exp $
#

# PROVIDE: ipxrouted
# REQUIRE: SERVERS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ipxrouted"
rcvar=`set_rcvar`
command="/usr/sbin/IPXrouted"
command_args="> /dev/null 2>&1"

load_rc_config $name
run_rc_command "$1"
