#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/kadmind,v 1.4.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $
#

# PROVIDE: kadmin
# REQUIRE: kerberos
# BEFORE: DAEMON

. /etc/rc.subr

name="kadmind5"
load_rc_config $name
rcvar="kadmind5_server_enable"
unset start_cmd
command="${kadmind5_server}"
command_args="&"
required_vars="kerberos5_server_enable"

run_rc_command "$1"
