#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/lpd,v 1.8.2.2.4.1 2010/02/10 00:26:20 kensmith Exp $
#

# PROVIDE: lpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="lpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
required_files="/etc/printcap"
start_precmd="chkprintcap"

chkprintcap()
{
	if checkyesno chkprintcap_enable ; then
		/usr/sbin/chkprintcap ${chkprintcap_flags}
	fi
}

load_rc_config $name
run_rc_command "$1"
