#!/bin/sh
#
# $NetBSD: mrouted,v 1.6 2002/03/22 04:33:59 thorpej Exp $
# $FreeBSD$
#

# PROVIDE: mrouted
# REQUIRE: netif routing cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
