#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/mrouted,v 1.10.4.1 2008/01/28 07:58:31 dougb Exp $
#

# PROVIDE: mrouted
# REQUIRE: netif routing cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar=`set_rcvar`
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
