#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/NETWORKING,v 1.13.4.1 2008/01/28 07:58:31 dougb Exp $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netoptions routing network_ipv6 isdnd ppp
# REQUIRE: routed mrouted route6d mroute6d resolv

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
