#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/nfsserver,v 1.5.8.1 2009/04/15 03:14:26 kensmith Exp $
#

# PROVIDE: nfsserver
# REQUIRE: NETWORKING mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="nfsserver"
rcvar="nfs_server_enable"
start_cmd=":"
stop_cmd=":"
required_modules="nfsserver"

load_rc_config $name
run_rc_command "$1"
