#!/bin/sh -
#
# PC-card startup script
# HOSOKAWA, Tatsumi <hosokawa@mt.cs.keio.ac.jp>
#

if [ "X$pccard_enable" = X"YES" ] ; then
	if [ "x$pccard_mem" != "xDEFAULT" ] ; then
		pccardc pccardmem $pccard_mem
	else
		pccardc pccardmem 0xd0000
	fi
	echo "Enable PC-card." 
	pccardd &
fi
