#!/bin/sh
#
# $NetBSD: pwcheck,v 1.3 2000/07/26 00:11:49 lukem Exp $
#

# PROVIDE: pwcheck
# REQUIRE: mountcritremote syslogd
# BEFORE:  DAEMON

. /etc/rc.subr

name="pwcheck"
start_cmd="pwcheck_start"
stop_cmd=":"

pwcheck_start()
{
	#	check the password temp/lock file
	#
	if [ -f /etc/ptmp ]; then
		logger -s -p auth.err \
		    "password file may be incorrect -- /etc/ptmp exists"
	fi
}

load_rc_config $name
run_rc_command "$1"
