#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.14.2.1.6.1 2010/12/21 17:09:25 kensmith Exp $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
