#!/bin/sh
#
# $NetBSD: rwho,v 1.5 2002/03/22 04:34:00 thorpej Exp $
# $FreeBSD$
#

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN

. /etc/rc.subr

name="rwhod"
rcvar="`set_rcvar`"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
