#!/bin/sh
#
# $NetBSD: nfslocking,v 1.6 2002/03/24 15:52:41 lukem Exp $
# $FreeBSD$
#

# PROVIDE: nfslocking
# REQUIRE: nfsserver nfsclient nfsd
# BEFORE:  DAEMON
# KEYWORD: FreeBSD NetBSD

. /etc/rc.subr

arg=$1

case ${OSTYPE} in
FreeBSD)
	RCVAR_SERVER="nfs_server_enable"
	RCVAR_CLIENT="nfs_client_enable"
	RCVAR_STATD="rpc_statd_enable"
	RCVAR_LOCKD="rpc_lockd_enable"
	;;
NetBSD)
	RCVAR_SERVER="nfs_server"
	RCVAR_CLIENT="nfs_client"
	RCVAR_STATD="statd"
	RCVAR_LOCKD="lockd"
	;;
esac

start_precmd="checkyesno ${RCVAR_SERVER} || checkyesno ${RCVAR_CLIENT}
		[ -n "$rc_force" ]"
stop_precmd=$start_precmd
status_precmd=$start_precmd

name="statd"
rcvar=${RCVAR_STATD}
command="/usr/sbin/rpc.${name}"
load_rc_config $name
run_rc_command "$arg"

name="lockd"
rcvar=${RCVAR_LOCKD}
command="/usr/sbin/rpc.${name}"
load_rc_config $name
run_rc_command "$arg"
