#!/bin/sh
#
# $NetBSD: virecover,v 1.5 2001/04/11 21:02:44 aymeric Exp $
#

# PROVIDE: virecover
# REQUIRE: mountcritremote
# BEFORE:  DAEMON
#
# XXX: should require `mail'!

. /etc/rc.subr

name="virecover"
command="/usr/libexec/${name}"
stop_cmd=":"
reload_cmd=":"

load_rc_config $name
run_rc_command "$1"
