#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ypupdated,v 1.7.2.2.2.1 2012/03/03 06:15:13 kensmith Exp $
#

# PROVIDE: ypupdated
# REQUIRE: rpcbind ypserv
# KEYWORD: shutdown

. /etc/rc.subr

name="ypupdated"
rcvar="rpc_ypupdated_enable"

load_rc_config $name

command="/usr/sbin/rpc.${name}"
start_precmd="rpc_ypupdated_precmd"

rpc_ypupdated_precmd()
{
	local _domain

	force_depend rpcbind || return 1
	force_depend ypserv nis_server || return 1

	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "NIS domainname(1) is not set."
		return 1
	fi
}

run_rc_command "$1"
