# $FreeBSD$

PACKAGE=	tests

NETBSD_ATF_TESTS_SH=	grep_test

${PACKAGE}FILES+=		d_basic.out
${PACKAGE}FILES+=		d_begin_end_a.out
${PACKAGE}FILES+=		d_begin_end_b.out
${PACKAGE}FILES+=		d_binary.out
${PACKAGE}FILES+=		d_context2_a.out
${PACKAGE}FILES+=		d_context2_b.out
${PACKAGE}FILES+=		d_context2_c.out
${PACKAGE}FILES+=		d_context_a.in
${PACKAGE}FILES+=		d_context_a.out
${PACKAGE}FILES+=		d_context_b.in
${PACKAGE}FILES+=		d_context_b.out
${PACKAGE}FILES+=		d_context_c.out
${PACKAGE}FILES+=		d_context_d.out
${PACKAGE}FILES+=		d_egrep.out
${PACKAGE}FILES+=		d_file_exp.in
${PACKAGE}FILES+=		d_file_exp.out
${PACKAGE}FILES+=		d_ignore_case.out
${PACKAGE}FILES+=		d_input
${PACKAGE}FILES+=		d_invert.in
${PACKAGE}FILES+=		d_invert.out
${PACKAGE}FILES+=		d_recurse.out
${PACKAGE}FILES+=		d_recurse_symlink.err
${PACKAGE}FILES+=		d_recurse_symlink.out
${PACKAGE}FILES+=		d_whole_line.out
${PACKAGE}FILES+=		d_word_regexps.out
${PACKAGE}FILES+=		d_zgrep.out

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
