# $FreeBSD: src/etc/namedb/master/Makefile,v 1.1.14.1 2010/02/10 00:26:20 kensmith Exp $

FILES=	empty.db localhost-forward.db localhost-reverse.db

NO_OBJ=
FILESDIR=	/etc/namedb/master
FILESMODE=	644

.include <bsd.prog.mk>
