# $FreeBSD: src/sys/modules/lge/Makefile,v 1.2.6.1 2008/11/25 02:59:29 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/lge

KMOD=	if_lge
SRCS=	if_lge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
