#
# $FreeBSD: src/usr.sbin/pmccontrol/Makefile,v 1.2.20.1 2009/04/15 03:14:26 kensmith Exp $
#

PROG=	pmccontrol
MAN=	pmccontrol.8

DPADD=	${LIBPMC}
LDADD=	-lpmc

WARNS?=	6

SRCS=	pmccontrol.c

.include <bsd.prog.mk>
