# $FreeBSD: src/sys/modules/syscons/logo/Makefile,v 1.8.36.1.8.1 2012/03/03 06:15:13 kensmith Exp $

.PATH:	${.CURDIR}/../../../dev/syscons/logo

KMOD=	logo_saver
SRCS=	logo_saver.c logo.c

.include <bsd.kmod.mk>
