# $FreeBSD: src/sys/modules/nfe/Makefile,v 1.2.10.1 2009/04/15 03:14:26 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/nfe

KMOD=	if_nfe
SRCS=	if_nfe.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
