# $FreeBSD: head/lib/clang/libllvmarchive/Makefile 231057 2012-02-05 23:56:22Z dim $

LIB=	llvmarchive

SRCDIR=	lib/Archive
SRCS=	Archive.cpp \
	ArchiveReader.cpp \
	ArchiveWriter.cpp

.include "../clang.lib.mk"
