# $FreeBSD: src/sys/modules/sound/driver/via82c686/Makefile,v 1.3.34.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_via82c686
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	via82c686.c

.include <bsd.kmod.mk>
