#	@(#)Makefile	5.4 (Berkeley) 5/11/90
#
# $FreeBSD: src/sbin/slattach/Makefile,v 1.9 1999/08/28 00:14:24 peter Exp $

PROG=	slattach
SRCS=   slattach.c
MAN8=	slattach.8
MLINKS=	slattach.8 slip.8
LDADD=	-lutil
DPADD=	${LIBUTIL}

.include <bsd.prog.mk>
