#	@(#)Makefile	5.4 (Berkeley) 5/11/90
#
#	$Header: /a/cvs/386BSD/src/sbin/slattach/Makefile,v 1.5 1993/08/29 18:11:14 rgrimes Exp $

PROG=	slattach
MAN8=	slattach.8
MLINKS=	slattach.8 slip.8
LDADD=	-lutil
DPADD=	${LIBUTIL}

.include <bsd.prog.mk>
