# $FreeBSD: src/lib/libbsnmp/modules/Makefile,v 1.1 2003/11/10 09:17:33 harti Exp $

.PATH: ${.CURDIR}/../../../contrib/bsnmp/snmpd

SUBDIR=	snmp_mibII \
	snmp_netgraph

INCS=	snmpmod.h
INCSDIR= ${INCLUDEDIR}/bsnmp

.include <bsd.prog.mk>
