#	@(#)Makefile.inc	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/Makefile.inc,v 1.3.30.1 2008/10/02 02:57:24 kensmith Exp $

BINDIR?=	/usr/bin

# Commented out for the time being.
# I intend to make this default at some stage.
#WARNS?=		2
