#	@(#)Makefile.inc	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/Makefile.inc,v 1.3 2002/02/06 18:13:12 markm Exp $

BINDIR?=	/usr/bin

# Commented out for the time being.
# I intend to make this default at some stage.
#WARNS?=		2
