#	@(#)Makefile	5.8.1.1 (Berkeley) 5/8/91
#

SUBDIR=	ar basename bdes biff cal calendar checknr chat chpass cksum cmp col \
	colcrt colrm column comm compress crontab ctags cut dirname \
	du elvis elvisrecover env error expand false file find finger fmt \
	fold fpr from fsplit fstat ftp getopt gprof groups head hexdump id \
	indent join ktrace last lastcomm leave lex locate lock logger \
	login logname look lorder m4 machine mail make mesg mkdep mkfifo \
	mkstr more msgs mt netstat nfsstat nice nm nohup pagesize \
	passwd paste printenv printf quota ranlib rdist ref renice rev rlogin \
	rpcgen rpcinfo rsh rup ruptime rusers rwall rwho script sed shar \
	showmount size soelim split strings strip su symorder syscons tail \
	talk tcopy tee telnet tftp time tip tn3270 touch tput tr true tset \
	tsort tty ul uname unexpand unifdef uniq unvis users uudecode uuencode \
	vacation vgrind vis vmstat w wall wc what whereis which who whoami \
	whois window write xargs xinstall xstr yacc yes
	
.include <bsd.subdir.mk>
