# $FreeBSD: src/sys/modules/k8temp/Makefile,v 1.1.2.1.2.1 2008/11/25 02:59:29 kensmith Exp $

.PATH:	${.CURDIR}/../../dev/k8temp

KMOD=	k8temp
SRCS=	k8temp.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
