#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/ktrace/Makefile,v 1.6.50.1 2008/10/02 02:57:24 kensmith Exp $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
