#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/ktrace/Makefile,v 1.6.52.1 2008/11/25 02:59:29 kensmith Exp $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
