# $FreeBSD: src/sys/modules/syscons/dragon/Makefile,v 1.3.32.1 2008/10/02 02:57:24 kensmith Exp $

.PATH:	${.CURDIR}/../../../dev/syscons/dragon

KMOD=	dragon_saver
SRCS= 	dragon_saver.c

.include <bsd.kmod.mk>
