# $FreeBSD: src/sys/modules/drm/Makefile,v 1.6.10.1.6.1 2010/12/21 17:09:25 kensmith Exp $

SUBDIR = \
	drm \
	i915 \
	mach64 \
	mga \
	r128 \
	radeon \
	savage \
	sis \
	tdfx

.include <bsd.subdir.mk>
