#	@(#)Makefile	8.1 (Berkeley) 5/31/93
#	$Id: Makefile,v 1.1 1998/01/23 02:45:53 ShimonR Exp ShimonR $

PROG=	dpt_led
SRCS=	dpt_led.c

CFLAGS+=-Wall -I../../../sys -I/usr/src/sys
BINMODE=500
BINOWN=	root
MAN8=	dpt_led.8

.include <bsd.prog.mk>
