# $FreeBSD: src/sys/modules/gx/Makefile,v 1.1 2001/10/19 02:21:16 jlemon Exp $

.PATH: ${.CURDIR}/../../dev/gx

KMOD=	if_gx
SRCS=	if_gx.c opt_bdg.h device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
