# $FreeBSD: src/sys/modules/siba_bwn/Makefile,v 1.1.2.2.4.1 2010/12/21 17:09:25 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/siba

KMOD=	siba_bwn
SRCS=	siba_core.c siba_bwn.c sibareg.h sibavar.h
SRCS+=	device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
