#	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/libexec/fingerd/Makefile,v 1.11.30.1.8.1 2012/03/03 06:15:13 kensmith Exp $

PROG=	fingerd
DPADD=	${LIBUTIL}
LDADD=	-lutil
MAN=	fingerd.8
WARNS?=	2

WFORMAT=0

.include <bsd.prog.mk>
