# $FreeBSD$

CALENDAR_FILE="-f ${SRCDIR}/calendar.cond"
CALENDAR_BIN="calendar"

CALENDAR="${CALENDAR_BIN} ${CALENDAR_FILE}"

REGRESSION_START($1)

echo 1..1

REGRESSION_TEST(`cond',`$CALENDAR -t 01.01.2020 -A 30')

REGRESSION_END()
