# $FreeBSD: src/usr.sbin/ctm/ctm_dequeue/Makefile,v 1.3.8.1 2005/02/13 07:23:41 obrien Exp $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_dequeue
NOMAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

.include <bsd.prog.mk>
