# $FreeBSD: src/usr.sbin/ctm/ctm_dequeue/Makefile,v 1.5.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_dequeue
NO_MAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

.include <bsd.prog.mk>
