# $FreeBSD: src/gnu/usr.bin/groff/font/Makefile.dev,v 2.12.30.1 2008/11/25 02:59:29 kensmith Exp $

FILES=		${DEVFILES}
FILESDIR?=	${fontdir}/dev${DEV}
SCRIPTS=	${DEVSCRIPTS}
SCRIPTSDIR?=	${fontdir}/dev${DEV}
.for script in ${SCRIPTS}
SCRIPTSNAME_${script:T}= ${script:T}
.endfor

.include <bsd.prog.mk>
