# $FreeBSD: src/gnu/usr.bin/groff/font/Makefile.dev,v 2.12.36.1 2010/02/10 00:26:20 kensmith Exp $

FILES=		${DEVFILES}
FILESDIR?=	${fontdir}/dev${DEV}
SCRIPTS=	${DEVSCRIPTS}
SCRIPTSDIR?=	${fontdir}/dev${DEV}
.for script in ${SCRIPTS}
SCRIPTSNAME_${script:T}= ${script:T}
.endfor

.include <bsd.prog.mk>
