# $FreeBSD: src/usr.sbin/ctm/ctm_rmail/Makefile,v 1.8.34.1.2.1 2009/10/25 01:10:29 kensmith Exp $

PROG=	ctm_rmail
MLINKS=	ctm_rmail.1 ctm_smail.1 \
	ctm_rmail.1 ctm_dequeue.1
SRCS=	ctm_rmail.c error.c

.include <bsd.prog.mk>
