# $FreeBSD: src/libexec/rpc.rwalld/Makefile,v 1.7.24.1 2008/10/02 02:57:24 kensmith Exp $

PROG =	rpc.rwalld
SRCS =	rwalld.c
MAN =	rpc.rwalld.8

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
