# $FreeBSD: src/libexec/rpc.rwalld/Makefile,v 1.7.28.1 2009/04/15 03:14:26 kensmith Exp $

PROG =	rpc.rwalld
SRCS =	rwalld.c
MAN =	rpc.rwalld.8

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
