# $FreeBSD: src/sys/modules/jme/Makefile,v 1.1.6.1.6.1 2010/12/21 17:09:25 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/jme

KMOD=	if_jme
SRCS=	if_jme.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
