#	From: @(#)Makefile	8.1 (Berkeley) 6/5/93
#	$Id: Makefile,v 1.2 1996/09/16 17:04:22 wollman Exp $

PROG=	rtquery
MAN8=	rtquery.8
LDADD+=	-lmd
DPADD+=	${LIBMD}
#COPTS=	-g -DDEBUG -Wall

.include <bsd.prog.mk>
