# $FreeBSD: src/sys/modules/syscons/daemon/Makefile,v 1.13.36.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH:	${.CURDIR}/../../../dev/syscons/daemon

KMOD=	daemon_saver
SRCS=	daemon_saver.c

.include <bsd.kmod.mk>
