# i386 headers installed on amd64

.PATH: ${SRCTOP}/sys/i386/include
INCS=	\
	asm.h \
	asmacros.h \
	atomic.h \
	cpufunc.h \
	pmap.h \
	proc.h \
	profile.h \
	segments.h \
	vmparam.h
INCSDIR=	${INCLUDEDIR}/i386

.include <bsd.prog.mk>
