# $FreeBSD: src/sys/modules/nge/Makefile,v 1.4.10.1.2.1 2009/10/25 01:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/nge

KMOD=	if_nge
SRCS=	if_nge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
