# $FreeBSD: src/sys/modules/sound/driver/atiixp/Makefile,v 1.1.2.1 2005/12/30 19:55:55 netchild Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_atiixp
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	atiixp.c

.include <bsd.kmod.mk>
