#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/malloc/Makefile,v 1.5.36.1.2.1 2009/10/25 01:10:29 kensmith Exp $

VOLUME=	papers
DOC=	malloc
SRCS=	abs.ms intro.ms kernel.ms malloc.ms problems.ms alternatives.ms \
	performance.ms implementation.ms conclusion.ms
MACROS=	-ms

.include <bsd.doc.mk>
