# $FreeBSD: src/sys/modules/netgraph/async/Makefile,v 1.9 2002/01/11 15:48:51 ru Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=	ng_async
SRCS= 	ng_async.c

.include <bsd.kmod.mk>
