.\" -*- nroff -*-
.\"
.TH UMAD_OPEN_PORT 3  "May 21, 2007" "OpenIB" "OpenIB Programmer\'s Manual"
.SH "NAME"
umad_open_port \- open InfiniBand device port for umad access
.SH "SYNOPSIS"
.nf
.B #include <infiniband/umad.h>
.sp
.BI "int umad_open_port(char " "*ca_name" ", int " "portnum" );
.fi
.SH "DESCRIPTION"
.B umad_open_port()
opens the port
.I portnum
of the IB device
.I ca_name
for umad access. The port is selected by the library if not all parameters
are provided (see
.B umad_get_port()
for details).
.fi
.SH "RETURN VALUE"
.B umad_open_port()
returns 0 or an unique positive value of umad device descriptor on success, and a negative value on error as follows:
 -ENODEV IB device can\'t be resolved
 -EINVAL port is not valid (bad
.I portnum\fR
or no umad device)
 -EIO    umad device for this port can\'t be opened
.SH "SEE ALSO"
.BR umad_close_port (3),
.BR umad_get_cas_names (3),
.BR umad_get_port (3)
.SH "AUTHOR"
.TP
Hal Rosenstock <halr@voltaire.com>
