# $FreeBSD$

NOOBJ=	noobj
FILES=	Acknowledgements Bibliography BugList ChangeLog CharGen \
	Charsets EscapeSequences Keyboard.HP Keyboard.VT \
	Manifest NotesAndHints TestedHardware ToDo
FILESDIR=	${BINDIR}/Doc

.include <bsd.prog.mk>
