# $FreeBSD: src/gnu/usr.bin/groff/src/utils/addftinfo/Makefile,v 1.4.30.1 2008/11/25 02:59:29 kensmith Exp $

PROG_CXX=	addftinfo
SRCS=		addftinfo.cpp guess.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
