#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lastcomm/Makefile,v 1.5.14.1 2010/12/21 17:10:29 kensmith Exp $

PROG=	lastcomm
SRCS=	lastcomm.c readrec.c
WARNS?= 6

.include <bsd.prog.mk>
