# $FreeBSD: src/sys/modules/cxgb/cxgb_t3fw/Makefile,v 1.2.2.2.2.1 2008/11/25 02:59:29 kensmith Exp $

CXGB = ${.CURDIR}/../../../dev/cxgb
.PATH: ${CXGB} 

KMOD= cxgb_t3fw
SRCS+= cxgb_t3fw.c

.include <bsd.kmod.mk>
