#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/lpr/filters/Makefile,v 1.3 2003/07/15 07:01:01 gad Exp $

BINDIR=	/usr/libexec/lpr

PROG=	lpf
NOMAN=	noman

CFLAGS+= -I${.CURDIR}/../common_source

.include <bsd.prog.mk>
