# Makefile for building the sample syscall module
# $FreeBSD: src/share/examples/kld/syscall/module/Makefile,v 1.2.40.1 2010/12/21 17:10:29 kensmith Exp $

KMOD=	syscall
SRCS=	syscall.c

.include <bsd.kmod.mk>
