# $FreeBSD: src/sbin/mdmfs/Makefile,v 1.6.24.1 2010/02/10 00:26:20 kensmith Exp $

PROG=		mdmfs
LINKS=		${BINDIR}/${PROG} ${BINDIR}/mount_mfs
MAN=		mdmfs.8
MLINKS+=	mdmfs.8 mount_mfs.8
WARNS?=		6

.include <bsd.prog.mk>
