.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" from: X Version 11 Release 4, May 30, 1991
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)xroach.6	8.2 (Berkeley) 4/19/94
.\"
.TH XROACH 6 "April 19, 1994" "X Version 11 Release 4"
.SH NAME
xroach \- cockroaches hide under your windows
.SH SYNOPSIS
.B xroach
[-option .,..]
.SH DESCRIPTION
.I Xroach
displays disgusting cockroaches on your root window. These creepy crawlies
scamper
around until they find a window to hide under. Whenever you move or iconify
a window, the exposed beetles again scamper for cover.
.SH OPTIONS
.TP 8
.B \-display \fIdisplay_name\fB
Drop the roaches on the given display. Make sure the display is nearby, so you
can hear the screams.
.TP 8
.B \-rc \fIroach_color\fB
Use the given string as the color for the bugs instead of the default "black".
.TP 8
.B \-speed \fIroach_speed\fB
Use the given speed for the insects instead of the default 20.0. For example,
in winter the speed should be set to 5.0. In summer, 30.0 might be about
right.
.TP 8
.B \-roaches \fInum_roaches\fB
This is the number of the little critters. Default is 10.
.SH BUGS
As given by the -roaches option. Default is 10.
.SH COPYRIGHT
Copyright 1991 by J.T. Anderson
.SH AUTHORS
J.T. Anderson
(jta@locus.com)
.SH DEDICATION
Greg McFarlane
(gregm@otc.otca.oz.au)
.SH "SEE ALSO"
xroachmotel(1), xddt(1)
