# $FreeBSD: src/sys/modules/vesa/Makefile,v 1.14.34.1 2009/04/15 03:14:26 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/syscons ${.CURDIR}/../../i386/isa

KMOD=	vesa
SRCS=	vesa.c scvesactl.c opt_vga.h opt_vesa.h

.include <bsd.kmod.mk>
