# Trigger growfs on GEOM size changes.

notify 200 {
	match "system" "GEOM";
	match "subsystem" "DEV";
	match "type" "SIZECHANGE";
	action "lockf -k /var/run/growfs_postboot.lock service growfs_postboot quietstart $cdev 2>&1 | logger -t growfs_postboot &";
};
