# $FreeBSD: src/sys/modules/vge/Makefile,v 1.2.10.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/vge

KMOD=	if_vge
SRCS=	if_vge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
