.\"
.\" Copyright (c) 1997, 1999 Hellmuth Michaelis. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: isdnd.rates.5,v 1.10 1999/12/13 22:11:55 hm Exp $
.\"
.\" $FreeBSD$
.\"
.\"     last edit-date: [Mon Dec 13 22:59:31 1999]
.\"
.Dd September 11, 1998
.Dt ISDND.RATES 5
.Os
.Sh NAME
.Nm isdnd.rates
.Nd isdn4bsd ISDN management daemon rates description file
.Sh DESCRIPTION
The file
.Pa isdnd.rates
contains descriptions how long charging units last at a given time of day,
day of week and the distance to the destination.
If this file is available,
this information may be used by the
.Xr isdnd 8
ISDN connection management daemon to calculate the short hold time for a
connection.
.Pp
The format of a rate entry line is as follows:
.Pp
The first field, the
.Pq Fa rate-code
defines a collection of rates (for each day of the week) which can be
referenced in the
.Xr isdnd 8
configuration file
.Xr isdnd.rc 5 .
This field must start with the identifier
.Dq ra
followed by a digit in the range of zero to four.
.Pp
The second field, the
.Pq Fa day-number
selects the day of week for which this entry defines the rates, where 0 stands
for Sunday, 1 for Monday and so on until the digit 6 which stands for Saturday.
.Pp
The rest of the line consists of one or more space separated fields which have
the following syntax:
.Bd -ragged -offset indent
start_hour.start_minutes-end_hour.end_minutes:charge_unit_length
.Ed
.Pp
Start_hour and start_minutes define the begin of a time section and end_hour
and end_minutes define the end.
Charge_unit_length define the length of a
charging unit in the previously defined time section.
No spaces or tabs are
allowed inside this field.
The hour and minutes specifications MUST have
exactly 2 digits, in case just one digit is needed, a leading 0 must be used.
.Pp
For example,
.Bd -ragged -offset indent
14.00-18.00:90
.Ed
.Pp
defines, that between 2:00 PM and 6:00 PM the length of one charging unit
lasts 90 seconds.
.Sh FILES
.Bl -tag -width /etc/isdn/isdnd.rates -compact
.It Pa /etc/isdn/isdnd.rates
The default rates specification file for the
.Nm isdnd
ISDN daemon.
.El
.Sh EXAMPLES
The line:
.Bd -literal
ra0 0 00.00-05.00:240 05.00-21.00:150 21.00-24.00:240
.Ed
.Pp
defines the unit lengths for a Sunday.
.Sh SEE ALSO
.Xr isdnd.rc 5 ,
.Xr isdnd 8
.Sh AUTHORS
.An -nosplit
The rates subsystem for the
.Xr isdnd 8
daemon to which
.Nm
belongs was designed and written by
.An Gary Jennejohn .
.Pp
The
.Xr isdnd 8
daemon and this manual page were written by
.An Hellmuth Michaelis Aq hm@kts.org .
