
# $FreeBSD: src/usr.bin/global/gctags/Makefile,v 1.6 1999/08/28 01:01:47 peter Exp $

GLOBAL_DIR=	${.CURDIR}/../../../contrib/global
.PATH:		${GLOBAL_DIR}/gctags

CFLAGS+=	-I${GLOBAL_DIR}/gctags

PROG=	gctags
SRCS=	C.c assembler.c gctags.c java.c

.include <bsd.prog.mk>

