# $FreeBSD: src/share/examples/smbfs/Makefile,v 1.5.22.1.4.1 2010/06/14 02:09:06 kensmith Exp $

NO_OBJ=
BINDIR=	/usr/share/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${.CURDIR}/../../../contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
