# $FreeBSD: src/share/examples/smbfs/Makefile,v 1.5.24.1 2010/02/10 00:26:20 kensmith Exp $

NO_OBJ=
BINDIR=	/usr/share/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${.CURDIR}/../../../contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
