# $FreeBSD: src/sys/modules/sound/driver/es137x/Makefile,v 1.3.30.1 2008/11/25 02:59:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_es137x
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	es137x.c

.include <bsd.kmod.mk>
