#define ENABLE_SK_INTERNAL /**/
#define HAVE_FIDO_ASSERT_SET_CLIENTDATA 1
#define HAVE_FIDO_CRED_PROT 1
#define HAVE_FIDO_CRED_SET_CLIENTDATA 1
#define HAVE_FIDO_CRED_SET_PROT 1
#define HAVE_FIDO_DEV_GET_TOUCH_BEGIN 1
#define HAVE_FIDO_DEV_GET_TOUCH_STATUS 1
#define HAVE_FIDO_DEV_SUPPORTS_CRED_PROT 1
