/*
 * This file was machine-@generated.  Do not edit manually.
 * Run crypto/openssh/freebsd-namespace.sh to regenerate.
 */
#define Blowfish_decipher			Fssh_Blowfish_decipher
#define Blowfish_encipher			Fssh_Blowfish_encipher
#define Blowfish_expand0state			Fssh_Blowfish_expand0state
#define Blowfish_expandstate			Fssh_Blowfish_expandstate
#define Blowfish_initstate			Fssh_Blowfish_initstate
#define Blowfish_stream2word			Fssh_Blowfish_stream2word
#define Decode					Fssh_Decode
#define EVP_CIPHER_CTX_get_iv			Fssh_EVP_CIPHER_CTX_get_iv
#define EVP_CIPHER_CTX_set_iv			Fssh_EVP_CIPHER_CTX_set_iv
#define Encode					Fssh_Encode
#define Hide					Fssh_Hide
#define Rq_mult_small				Fssh_Rq_mult_small
#define Short_random				Fssh_Short_random
#define _ssh__compat_glob			Fssh__ssh__compat_glob
#define _ssh__compat_globfree			Fssh__ssh__compat_globfree
#define _ssh_exchange_banner			Fssh__ssh_exchange_banner
#define _ssh_host_key_sign			Fssh__ssh_host_key_sign
#define _ssh_host_private_key			Fssh__ssh_host_private_key
#define _ssh_host_public_key			Fssh__ssh_host_public_key
#define _ssh_order_hostkeyalgs			Fssh__ssh_order_hostkeyalgs
#define _ssh_read_banner			Fssh__ssh_read_banner
#define _ssh_send_banner			Fssh__ssh_send_banner
#define _ssh_verify_host_key			Fssh__ssh_verify_host_key
#define a2port					Fssh_a2port
#define a2tun					Fssh_a2tun
#define add_host_to_hostfile			Fssh_add_host_to_hostfile
#define add_p1p1				Fssh_add_p1p1
#define addargs					Fssh_addargs
#define addr_and				Fssh_addr_and
#define addr_cmp				Fssh_addr_cmp
#define addr_host_is_all0s			Fssh_addr_host_is_all0s
#define addr_hostmask				Fssh_addr_hostmask
#define addr_invert				Fssh_addr_invert
#define addr_is_all0s				Fssh_addr_is_all0s
#define addr_match_cidr_list			Fssh_addr_match_cidr_list
#define addr_match_list				Fssh_addr_match_list
#define addr_netmask				Fssh_addr_netmask
#define addr_netmatch				Fssh_addr_netmatch
#define addr_ntop				Fssh_addr_ntop
#define addr_pton				Fssh_addr_pton
#define addr_pton_cidr				Fssh_addr_pton_cidr
#define addr_sa_pton				Fssh_addr_sa_pton
#define addr_sa_to_xaddr			Fssh_addr_sa_to_xaddr
#define addr_unicast_masklen			Fssh_addr_unicast_masklen
#define addr_xaddr_to_sa			Fssh_addr_xaddr_to_sa
#define argv_assemble				Fssh_argv_assemble
#define argv_consume				Fssh_argv_consume
#define argv_free				Fssh_argv_free
#define argv_next				Fssh_argv_next
#define argv_split				Fssh_argv_split
#define ask_permission				Fssh_ask_permission
#define asmprintf				Fssh_asmprintf
#define atoi_err				Fssh_atoi_err
#define atomicio				Fssh_atomicio
#define atomicio6				Fssh_atomicio6
#define atomiciov				Fssh_atomiciov
#define atomiciov6				Fssh_atomiciov6
#define bandwidth_limit				Fssh_bandwidth_limit
#define bandwidth_limit_init			Fssh_bandwidth_limit_init
#define barrett_reduce				Fssh_barrett_reduce
#define baud_to_speed				Fssh_baud_to_speed
#define bcrypt_hash				Fssh_bcrypt_hash
#define bcrypt_pbkdf				Fssh_bcrypt_pbkdf
#define bitmap_clear_bit			Fssh_bitmap_clear_bit
#define bitmap_free				Fssh_bitmap_free
#define bitmap_from_string			Fssh_bitmap_from_string
#define bitmap_nbits				Fssh_bitmap_nbits
#define bitmap_nbytes				Fssh_bitmap_nbytes
#define bitmap_new				Fssh_bitmap_new
#define bitmap_set_bit				Fssh_bitmap_set_bit
#define bitmap_test_bit				Fssh_bitmap_test_bit
#define bitmap_to_string			Fssh_bitmap_to_string
#define bitmap_zero				Fssh_bitmap_zero
#define blf_cbc_decrypt				Fssh_blf_cbc_decrypt
#define blf_cbc_encrypt				Fssh_blf_cbc_encrypt
#define blf_dec					Fssh_blf_dec
#define blf_ecb_decrypt				Fssh_blf_ecb_decrypt
#define blf_ecb_encrypt				Fssh_blf_ecb_encrypt
#define blf_enc					Fssh_blf_enc
#define blf_key					Fssh_blf_key
#define blob_section				Fssh_blob_section
#define cert_free				Fssh_cert_free
#define chacha_encrypt_bytes			Fssh_chacha_encrypt_bytes
#define chacha_ivsetup				Fssh_chacha_ivsetup
#define chacha_keysetup				Fssh_chacha_keysetup
#define chan_ibuf_empty				Fssh_chan_ibuf_empty
#define chan_is_dead				Fssh_chan_is_dead
#define chan_mark_dead				Fssh_chan_mark_dead
#define chan_obuf_empty				Fssh_chan_obuf_empty
#define chan_rcvd_eow				Fssh_chan_rcvd_eow
#define chan_rcvd_ieof				Fssh_chan_rcvd_ieof
#define chan_rcvd_oclose			Fssh_chan_rcvd_oclose
#define chan_read_failed			Fssh_chan_read_failed
#define chan_send_eof2				Fssh_chan_send_eof2
#define chan_shutdown_extended_read		Fssh_chan_shutdown_extended_read
#define chan_shutdown_read			Fssh_chan_shutdown_read
#define chan_shutdown_write			Fssh_chan_shutdown_write
#define chan_write_failed			Fssh_chan_write_failed
#define channel_add_permission			Fssh_channel_add_permission
#define channel_after_select			Fssh_channel_after_select
#define channel_by_id				Fssh_channel_by_id
#define channel_by_remote_id			Fssh_channel_by_remote_id
#define channel_cancel_cleanup			Fssh_channel_cancel_cleanup
#define channel_cancel_lport_listener		Fssh_channel_cancel_lport_listener
#define channel_cancel_rport_listener		Fssh_channel_cancel_rport_listener
#define channel_clear_permission		Fssh_channel_clear_permission
#define channel_close_all			Fssh_channel_close_all
#define channel_close_fd			Fssh_channel_close_fd
#define channel_connect_by_listen_address	Fssh_channel_connect_by_listen_address
#define channel_connect_by_listen_path		Fssh_channel_connect_by_listen_path
#define channel_connect_stdio_fwd		Fssh_channel_connect_stdio_fwd
#define channel_connect_to_path			Fssh_channel_connect_to_path
#define channel_connect_to_port			Fssh_channel_connect_to_port
#define channel_decode_socks4			Fssh_channel_decode_socks4
#define channel_decode_socks5			Fssh_channel_decode_socks5
#define channel_disable_admin			Fssh_channel_disable_admin
#define channel_find_open			Fssh_channel_find_open
#define channel_format_extended_usage		Fssh_channel_format_extended_usage
#define channel_free				Fssh_channel_free
#define channel_free_all			Fssh_channel_free_all
#define channel_fwd_bind_addr			Fssh_channel_fwd_bind_addr
#define channel_handler				Fssh_channel_handler
#define channel_init_channels			Fssh_channel_init_channels
#define channel_input_data			Fssh_channel_input_data
#define channel_input_extended_data		Fssh_channel_input_extended_data
#define channel_input_ieof			Fssh_channel_input_ieof
#define channel_input_oclose			Fssh_channel_input_oclose
#define channel_input_open_confirmation		Fssh_channel_input_open_confirmation
#define channel_input_open_failure		Fssh_channel_input_open_failure
#define channel_input_status_confirm		Fssh_channel_input_status_confirm
#define channel_input_window_adjust		Fssh_channel_input_window_adjust
#define channel_lookup				Fssh_channel_lookup
#define channel_new				Fssh_channel_new
#define channel_not_very_much_buffered_data	Fssh_channel_not_very_much_buffered_data
#define channel_open_message			Fssh_channel_open_message
#define channel_output_poll			Fssh_channel_output_poll
#define channel_parse_id			Fssh_channel_parse_id
#define channel_permit_all			Fssh_channel_permit_all
#define channel_post_auth_listener		Fssh_channel_post_auth_listener
#define channel_post_connecting			Fssh_channel_post_connecting
#define channel_post_mux_client			Fssh_channel_post_mux_client
#define channel_post_mux_listener		Fssh_channel_post_mux_listener
#define channel_post_open			Fssh_channel_post_open
#define channel_post_port_listener		Fssh_channel_post_port_listener
#define channel_post_x11_listener		Fssh_channel_post_x11_listener
#define channel_pre_connecting			Fssh_channel_pre_connecting
#define channel_pre_dynamic			Fssh_channel_pre_dynamic
#define channel_pre_listener			Fssh_channel_pre_listener
#define channel_pre_mux_client			Fssh_channel_pre_mux_client
#define channel_pre_open			Fssh_channel_pre_open
#define channel_pre_x11_open			Fssh_channel_pre_x11_open
#define channel_prepare_select			Fssh_channel_prepare_select
#define channel_proxy_downstream		Fssh_channel_proxy_downstream
#define channel_proxy_upstream			Fssh_channel_proxy_upstream
#define channel_register_cleanup		Fssh_channel_register_cleanup
#define channel_register_fds			Fssh_channel_register_fds
#define channel_register_filter			Fssh_channel_register_filter
#define channel_register_open_confirm		Fssh_channel_register_open_confirm
#define channel_register_status_confirm		Fssh_channel_register_status_confirm
#define channel_request_remote_forwarding	Fssh_channel_request_remote_forwarding
#define channel_request_rforward_cancel		Fssh_channel_request_rforward_cancel
#define channel_request_start			Fssh_channel_request_start
#define channel_send_open			Fssh_channel_send_open
#define channel_send_window_changes		Fssh_channel_send_window_changes
#define channel_set_af				Fssh_channel_set_af
#define channel_set_fds				Fssh_channel_set_fds
#define channel_set_x11_refuse_time		Fssh_channel_set_x11_refuse_time
#define channel_setup_fwd_listener_streamlocal	Fssh_channel_setup_fwd_listener_streamlocal
#define channel_setup_fwd_listener_tcpip	Fssh_channel_setup_fwd_listener_tcpip
#define channel_setup_local_fwd_listener	Fssh_channel_setup_local_fwd_listener
#define channel_setup_remote_fwd_listener	Fssh_channel_setup_remote_fwd_listener
#define channel_still_open			Fssh_channel_still_open
#define channel_stop_listening			Fssh_channel_stop_listening
#define channel_update_permission		Fssh_channel_update_permission
#define check_hostkeys_by_key_or_type		Fssh_check_hostkeys_by_key_or_type
#define check_key_in_hostkeys			Fssh_check_key_in_hostkeys
#define child_set_env				Fssh_child_set_env
#define choose_dh				Fssh_choose_dh
#define choose_t				Fssh_choose_t
#define chop					Fssh_chop
#define cipher_alg_list				Fssh_cipher_alg_list
#define cipher_authlen				Fssh_cipher_authlen
#define cipher_blocksize			Fssh_cipher_blocksize
#define cipher_by_name				Fssh_cipher_by_name
#define cipher_crypt				Fssh_cipher_crypt
#define cipher_ctx_is_plaintext			Fssh_cipher_ctx_is_plaintext
#define cipher_free				Fssh_cipher_free
#define cipher_get_keyiv			Fssh_cipher_get_keyiv
#define cipher_get_keyiv_len			Fssh_cipher_get_keyiv_len
#define cipher_get_length			Fssh_cipher_get_length
#define cipher_init				Fssh_cipher_init
#define cipher_is_cbc				Fssh_cipher_is_cbc
#define cipher_ivlen				Fssh_cipher_ivlen
#define cipher_keylen				Fssh_cipher_keylen
#define cipher_seclen				Fssh_cipher_seclen
#define cipher_set_keyiv			Fssh_cipher_set_keyiv
#define cipher_warning_message			Fssh_cipher_warning_message
#define ciphers_valid				Fssh_ciphers_valid
#define cleanhostname				Fssh_cleanhostname
#define cleanup_exit				Fssh_cleanup_exit
#define colon					Fssh_colon
#define compare					Fssh_compare
#define compare_gps				Fssh_compare_gps
#define compat_banner				Fssh_compat_banner
#define compat_cipher_proposal			Fssh_compat_cipher_proposal
#define compat_kex_proposal			Fssh_compat_kex_proposal
#define compat_pkalg_proposal			Fssh_compat_pkalg_proposal
#define compression_alg_list			Fssh_compression_alg_list
#define connect_next				Fssh_connect_next
#define connect_to_helper			Fssh_connect_to_helper
#define convtime				Fssh_convtime
#define crypto_hash_sha512			Fssh_crypto_hash_sha512
#define crypto_kem_sntrup761_dec		Fssh_crypto_kem_sntrup761_dec
#define crypto_kem_sntrup761_enc		Fssh_crypto_kem_sntrup761_enc
#define crypto_kem_sntrup761_keypair		Fssh_crypto_kem_sntrup761_keypair
#define crypto_scalarmult_curve25519		Fssh_crypto_scalarmult_curve25519
#define crypto_sign_ed25519			Fssh_crypto_sign_ed25519
#define crypto_sign_ed25519_keypair		Fssh_crypto_sign_ed25519_keypair
#define crypto_sign_ed25519_open		Fssh_crypto_sign_ed25519_open
#define crypto_sign_ed25519_ref_double_scalarmult_vartime Fssh_crypto_sign_ed25519_ref_double_scalarmult_vartime
#define crypto_sign_ed25519_ref_fe25519_add	Fssh_crypto_sign_ed25519_ref_fe25519_add
#define crypto_sign_ed25519_ref_fe25519_cmov	Fssh_crypto_sign_ed25519_ref_fe25519_cmov
#define crypto_sign_ed25519_ref_fe25519_freeze	Fssh_crypto_sign_ed25519_ref_fe25519_freeze
#define crypto_sign_ed25519_ref_fe25519_getparity Fssh_crypto_sign_ed25519_ref_fe25519_getparity
#define crypto_sign_ed25519_ref_fe25519_invert	Fssh_crypto_sign_ed25519_ref_fe25519_invert
#define crypto_sign_ed25519_ref_fe25519_iseq_vartime Fssh_crypto_sign_ed25519_ref_fe25519_iseq_vartime
#define crypto_sign_ed25519_ref_fe25519_iszero	Fssh_crypto_sign_ed25519_ref_fe25519_iszero
#define crypto_sign_ed25519_ref_fe25519_mul	Fssh_crypto_sign_ed25519_ref_fe25519_mul
#define crypto_sign_ed25519_ref_fe25519_neg	Fssh_crypto_sign_ed25519_ref_fe25519_neg
#define crypto_sign_ed25519_ref_fe25519_pack	Fssh_crypto_sign_ed25519_ref_fe25519_pack
#define crypto_sign_ed25519_ref_fe25519_pow2523 Fssh_crypto_sign_ed25519_ref_fe25519_pow2523
#define crypto_sign_ed25519_ref_fe25519_setone	Fssh_crypto_sign_ed25519_ref_fe25519_setone
#define crypto_sign_ed25519_ref_fe25519_setzero Fssh_crypto_sign_ed25519_ref_fe25519_setzero
#define crypto_sign_ed25519_ref_fe25519_square	Fssh_crypto_sign_ed25519_ref_fe25519_square
#define crypto_sign_ed25519_ref_fe25519_sub	Fssh_crypto_sign_ed25519_ref_fe25519_sub
#define crypto_sign_ed25519_ref_fe25519_unpack	Fssh_crypto_sign_ed25519_ref_fe25519_unpack
#define crypto_sign_ed25519_ref_isneutral_vartime Fssh_crypto_sign_ed25519_ref_isneutral_vartime
#define crypto_sign_ed25519_ref_pack		Fssh_crypto_sign_ed25519_ref_pack
#define crypto_sign_ed25519_ref_sc25519_2interleave2 Fssh_crypto_sign_ed25519_ref_sc25519_2interleave2
#define crypto_sign_ed25519_ref_sc25519_add	Fssh_crypto_sign_ed25519_ref_sc25519_add
#define crypto_sign_ed25519_ref_sc25519_from32bytes Fssh_crypto_sign_ed25519_ref_sc25519_from32bytes
#define crypto_sign_ed25519_ref_sc25519_from64bytes Fssh_crypto_sign_ed25519_ref_sc25519_from64bytes
#define crypto_sign_ed25519_ref_sc25519_from_shortsc Fssh_crypto_sign_ed25519_ref_sc25519_from_shortsc
#define crypto_sign_ed25519_ref_sc25519_isshort_vartime Fssh_crypto_sign_ed25519_ref_sc25519_isshort_vartime
#define crypto_sign_ed25519_ref_sc25519_iszero_vartime Fssh_crypto_sign_ed25519_ref_sc25519_iszero_vartime
#define crypto_sign_ed25519_ref_sc25519_lt_vartime Fssh_crypto_sign_ed25519_ref_sc25519_lt_vartime
#define crypto_sign_ed25519_ref_sc25519_mul	Fssh_crypto_sign_ed25519_ref_sc25519_mul
#define crypto_sign_ed25519_ref_sc25519_mul_shortsc Fssh_crypto_sign_ed25519_ref_sc25519_mul_shortsc
#define crypto_sign_ed25519_ref_sc25519_sub_nored Fssh_crypto_sign_ed25519_ref_sc25519_sub_nored
#define crypto_sign_ed25519_ref_sc25519_to32bytes Fssh_crypto_sign_ed25519_ref_sc25519_to32bytes
#define crypto_sign_ed25519_ref_sc25519_window3 Fssh_crypto_sign_ed25519_ref_sc25519_window3
#define crypto_sign_ed25519_ref_sc25519_window5 Fssh_crypto_sign_ed25519_ref_sc25519_window5
#define crypto_sign_ed25519_ref_scalarmult_base Fssh_crypto_sign_ed25519_ref_scalarmult_base
#define crypto_sign_ed25519_ref_shortsc25519_from16bytes Fssh_crypto_sign_ed25519_ref_shortsc25519_from16bytes
#define crypto_sign_ed25519_ref_unpackneg_vartime Fssh_crypto_sign_ed25519_ref_unpackneg_vartime
#define crypto_verify_32			Fssh_crypto_verify_32
#define daemonized				Fssh_daemonized
#define dangerous_locale			Fssh_dangerous_locale
#define dbl_p1p1				Fssh_dbl_p1p1
#define default_key_sign			Fssh_default_key_sign
#define dh_estimate				Fssh_dh_estimate
#define dh_gen_key				Fssh_dh_gen_key
#define dh_new_group				Fssh_dh_new_group
#define dh_new_group1				Fssh_dh_new_group1
#define dh_new_group14				Fssh_dh_new_group14
#define dh_new_group16				Fssh_dh_new_group16
#define dh_new_group18				Fssh_dh_new_group18
#define dh_new_group_asc			Fssh_dh_new_group_asc
#define dh_new_group_fallback			Fssh_dh_new_group_fallback
#define dh_pub_is_valid				Fssh_dh_pub_is_valid
#define dh_set_moduli_file			Fssh_dh_set_moduli_file
#define dispatch_protocol_error			Fssh_dispatch_protocol_error
#define dispatch_protocol_ignore		Fssh_dispatch_protocol_ignore
#define do_log					Fssh_do_log
#define dollar_expand				Fssh_dollar_expand
#define ecdsa_do_sign				Fssh_ecdsa_do_sign
#define encode_constraints			Fssh_encode_constraints
#define exited_cleanly				Fssh_exited_cleanly
#define export_dns_rr				Fssh_export_dns_rr
#define filter_list				Fssh_filter_list
#define fingerprint_b64				Fssh_fingerprint_b64
#define fingerprint_hex				Fssh_fingerprint_hex
#define fmprintf				Fssh_fmprintf
#define fmt_scaled				Fssh_fmt_scaled
#define fmt_timeframe				Fssh_fmt_timeframe
#define format_absolute_time			Fssh_format_absolute_time
#define forward_equals				Fssh_forward_equals
#define free_hostkeys				Fssh_free_hostkeys
#define freeargs				Fssh_freeargs
#define freerrset				Fssh_freerrset
#define freezero				Fssh_freezero
#define fwd_ident				Fssh_fwd_ident
#define gen_candidates				Fssh_gen_candidates
#define get_hram				Fssh_get_hram
#define get_local_ipaddr			Fssh_get_local_ipaddr
#define get_local_name				Fssh_get_local_name
#define get_local_port				Fssh_get_local_port
#define get_peer_ipaddr				Fssh_get_peer_ipaddr
#define get_peer_port				Fssh_get_peer_port
#define get_rdomain				Fssh_get_rdomain
#define get_sock_af				Fssh_get_sock_af
#define get_sock_port				Fssh_get_sock_port
#define get_socket_address			Fssh_get_socket_address
#define get_u16					Fssh_get_u16
#define get_u32					Fssh_get_u32
#define get_u32_le				Fssh_get_u32_le
#define get_u64					Fssh_get_u64
#define getrrsetbyname				Fssh_getrrsetbyname
#define glob0					Fssh_glob0
#define glob2					Fssh_glob2
#define globexp1				Fssh_globexp1
#define globextend				Fssh_globextend
#define host_delete				Fssh_host_delete
#define host_hash				Fssh_host_hash
#define hostfile_create_user_ssh_dir		Fssh_hostfile_create_user_ssh_dir
#define hostfile_read_key			Fssh_hostfile_read_key
#define hostfile_replace_entries		Fssh_hostfile_replace_entries
#define hostkeys_foreach			Fssh_hostkeys_foreach
#define hostkeys_foreach_file			Fssh_hostkeys_foreach_file
#define hpdelim					Fssh_hpdelim
#define hpdelim2				Fssh_hpdelim2
#define init_hostkeys				Fssh_init_hostkeys
#define input_kex_dh_gex_group			Fssh_input_kex_dh_gex_group
#define input_kex_dh_gex_init			Fssh_input_kex_dh_gex_init
#define input_kex_dh_gex_reply			Fssh_input_kex_dh_gex_reply
#define input_kex_dh_gex_request		Fssh_input_kex_dh_gex_request
#define input_kex_gen_init			Fssh_input_kex_gen_init
#define input_kex_gen_reply			Fssh_input_kex_gen_reply
#define iptos2str				Fssh_iptos2str
#define ipv64_normalise_mapped			Fssh_ipv64_normalise_mapped
#define is_key_revoked				Fssh_is_key_revoked
#define kex_alg_by_name				Fssh_kex_alg_by_name
#define kex_alg_list				Fssh_kex_alg_list
#define kex_assemble_names			Fssh_kex_assemble_names
#define kex_buf2prop				Fssh_kex_buf2prop
#define kex_c25519_dec				Fssh_kex_c25519_dec
#define kex_c25519_enc				Fssh_kex_c25519_enc
#define kex_c25519_keypair			Fssh_kex_c25519_keypair
#define kex_derive_keys				Fssh_kex_derive_keys
#define kex_dh_compute_key			Fssh_kex_dh_compute_key
#define kex_dh_dec				Fssh_kex_dh_dec
#define kex_dh_enc				Fssh_kex_dh_enc
#define kex_dh_keygen				Fssh_kex_dh_keygen
#define kex_dh_keypair				Fssh_kex_dh_keypair
#define kex_ecdh_dec				Fssh_kex_ecdh_dec
#define kex_ecdh_dec_key_group			Fssh_kex_ecdh_dec_key_group
#define kex_ecdh_enc				Fssh_kex_ecdh_enc
#define kex_ecdh_keypair			Fssh_kex_ecdh_keypair
#define kex_exchange_identification		Fssh_kex_exchange_identification
#define kex_free				Fssh_kex_free
#define kex_free_newkeys			Fssh_kex_free_newkeys
#define kex_gen_client				Fssh_kex_gen_client
#define kex_gen_hash				Fssh_kex_gen_hash
#define kex_gen_server				Fssh_kex_gen_server
#define kex_input_ext_info			Fssh_kex_input_ext_info
#define kex_input_kexinit			Fssh_kex_input_kexinit
#define kex_input_newkeys			Fssh_kex_input_newkeys
#define kex_kem_sntrup761x25519_dec		Fssh_kex_kem_sntrup761x25519_dec
#define kex_kem_sntrup761x25519_enc		Fssh_kex_kem_sntrup761x25519_enc
#define kex_kem_sntrup761x25519_keypair		Fssh_kex_kem_sntrup761x25519_keypair
#define kex_load_hostkey			Fssh_kex_load_hostkey
#define kex_names_cat				Fssh_kex_names_cat
#define kex_names_valid				Fssh_kex_names_valid
#define kex_new					Fssh_kex_new
#define kex_prop2buf				Fssh_kex_prop2buf
#define kex_prop_free				Fssh_kex_prop_free
#define kex_protocol_error			Fssh_kex_protocol_error
#define kex_ready				Fssh_kex_ready
#define kex_send_kexinit			Fssh_kex_send_kexinit
#define kex_send_newkeys			Fssh_kex_send_newkeys
#define kex_setup				Fssh_kex_setup
#define kex_start_rekex				Fssh_kex_start_rekex
#define kex_verify_host_key			Fssh_kex_verify_host_key
#define kexc25519_keygen			Fssh_kexc25519_keygen
#define kexc25519_shared_key			Fssh_kexc25519_shared_key
#define kexc25519_shared_key_ext		Fssh_kexc25519_shared_key_ext
#define kexgex_client				Fssh_kexgex_client
#define kexgex_hash				Fssh_kexgex_hash
#define kexgex_server				Fssh_kexgex_server
#define krl_dump				Fssh_krl_dump
#define load_hostkeys				Fssh_load_hostkeys
#define load_hostkeys_file			Fssh_load_hostkeys_file
#define log_change_level			Fssh_log_change_level
#define log_facility_name			Fssh_log_facility_name
#define log_facility_number			Fssh_log_facility_number
#define log_init				Fssh_log_init
#define log_is_on_stderr			Fssh_log_is_on_stderr
#define log_level_get				Fssh_log_level_get
#define log_level_name				Fssh_log_level_name
#define log_level_number			Fssh_log_level_number
#define log_redirect_stderr_to			Fssh_log_redirect_stderr_to
#define log_verbose_add				Fssh_log_verbose_add
#define log_verbose_reset			Fssh_log_verbose_reset
#define lookup_env_in_list			Fssh_lookup_env_in_list
#define lookup_key_in_hostkeys_by_type		Fssh_lookup_key_in_hostkeys_by_type
#define lookup_marker_in_hostkeys		Fssh_lookup_marker_in_hostkeys
#define lowercase				Fssh_lowercase
#define mac_alg_list				Fssh_mac_alg_list
#define mac_check				Fssh_mac_check
#define mac_clear				Fssh_mac_clear
#define mac_compute				Fssh_mac_compute
#define mac_init				Fssh_mac_init
#define mac_setup				Fssh_mac_setup
#define mac_valid				Fssh_mac_valid
#define match_filter_allowlist			Fssh_match_filter_allowlist
#define match_filter_denylist			Fssh_match_filter_denylist
#define match_host_and_ip			Fssh_match_host_and_ip
#define match_hostname				Fssh_match_hostname
#define match_list				Fssh_match_list
#define match_pattern				Fssh_match_pattern
#define match_pattern_list			Fssh_match_pattern_list
#define match_user				Fssh_match_user
#define match_usergroup_pattern_list		Fssh_match_usergroup_pattern_list
#define mktemp_proto				Fssh_mktemp_proto
#define mm_choose_dh				Fssh_mm_choose_dh
#define mm_receive_fd				Fssh_mm_receive_fd
#define mm_send_fd				Fssh_mm_send_fd
#define mm_sshkey_sign				Fssh_mm_sshkey_sign
#define monotime				Fssh_monotime
#define monotime_double				Fssh_monotime_double
#define monotime_ts				Fssh_monotime_ts
#define monotime_tv				Fssh_monotime_tv
#define mprintf					Fssh_mprintf
#define ms_subtract_diff			Fssh_ms_subtract_diff
#define ms_to_timeval				Fssh_ms_to_timeval
#define msetlocale				Fssh_msetlocale
#define newkeys_from_blob			Fssh_newkeys_from_blob
#define newkeys_to_blob				Fssh_newkeys_to_blob
#define nh_aux					Fssh_nh_aux
#define nh_final				Fssh_nh_final
#define note_key				Fssh_note_key
#define notify_complete				Fssh_notify_complete
#define notify_start				Fssh_notify_start
#define open_preamble				Fssh_open_preamble
#define opt_array_append			Fssh_opt_array_append
#define opt_array_append2			Fssh_opt_array_append2
#define opt_dequote				Fssh_opt_dequote
#define opt_flag				Fssh_opt_flag
#define opt_match				Fssh_opt_match
#define ossl_error				Fssh_ossl_error
#define parse_absolute_time			Fssh_parse_absolute_time
#define parse_ipqos				Fssh_parse_ipqos
#define parse_prime				Fssh_parse_prime
#define parse_uri				Fssh_parse_uri
#define parse_user_host_path			Fssh_parse_user_host_path
#define parse_user_host_port			Fssh_parse_user_host_port
#define path_absolute				Fssh_path_absolute
#define pem_passphrase_cb			Fssh_pem_passphrase_cb
#define percent_dollar_expand			Fssh_percent_dollar_expand
#define percent_expand				Fssh_percent_expand
#define permission_set_add			Fssh_permission_set_add
#define permitopen_port				Fssh_permitopen_port
#define pkcs11_add_provider			Fssh_pkcs11_add_provider
#define pkcs11_del_provider			Fssh_pkcs11_del_provider
#define pkcs11_ecdsa_wrap			Fssh_pkcs11_ecdsa_wrap
#define pkcs11_fetch_certs			Fssh_pkcs11_fetch_certs
#define pkcs11_fetch_keys			Fssh_pkcs11_fetch_keys
#define pkcs11_find				Fssh_pkcs11_find
#define pkcs11_get_key				Fssh_pkcs11_get_key
#define pkcs11_init				Fssh_pkcs11_init
#define pkcs11_k11_free				Fssh_pkcs11_k11_free
#define pkcs11_login_slot			Fssh_pkcs11_login_slot
#define pkcs11_provider_finalize		Fssh_pkcs11_provider_finalize
#define pkcs11_provider_unref			Fssh_pkcs11_provider_unref
#define pkcs11_rsa_private_decrypt		Fssh_pkcs11_rsa_private_decrypt
#define pkcs11_rsa_private_encrypt		Fssh_pkcs11_rsa_private_encrypt
#define pkcs11_rsa_wrap				Fssh_pkcs11_rsa_wrap
#define pkcs11_terminate			Fssh_pkcs11_terminate
#define plain_key_blob				Fssh_plain_key_blob
#define platform_disable_tracing		Fssh_platform_disable_tracing
#define platform_pledge_agent			Fssh_platform_pledge_agent
#define platform_pledge_mux			Fssh_platform_pledge_mux
#define platform_pledge_sftp_server		Fssh_platform_pledge_sftp_server
#define platform_sys_dir_uid			Fssh_platform_sys_dir_uid
#define pledge					Fssh_pledge
#define poly1305_auth				Fssh_poly1305_auth
#define poly64					Fssh_poly64
#define poly_hash				Fssh_poly_hash
#define port_open_helper			Fssh_port_open_helper
#define prime_test				Fssh_prime_test
#define private2_uudecode			Fssh_private2_uudecode
#define put_host_port				Fssh_put_host_port
#define put_u16					Fssh_put_u16
#define put_u32					Fssh_put_u32
#define put_u32_le				Fssh_put_u32_le
#define put_u64					Fssh_put_u64
#define pwcopy					Fssh_pwcopy
#define qfileout				Fssh_qfileout
#define read_mux				Fssh_read_mux
#define read_passphrase				Fssh_read_passphrase
#define recallocarray				Fssh_recallocarray
#define record_hostkey				Fssh_record_hostkey
#define reduce_add_sub				Fssh_reduce_add_sub
#define refresh_progress_meter			Fssh_refresh_progress_meter
#define replacearg				Fssh_replacearg
#define revoke_blob				Fssh_revoke_blob
#define revoked_blob_tree_RB_REMOVE		Fssh_revoked_blob_tree_RB_REMOVE
#define revoked_certs_for_ca_key		Fssh_revoked_certs_for_ca_key
#define revoked_serial_tree_RB_REMOVE		Fssh_revoked_serial_tree_RB_REMOVE
#define rijndaelEncrypt				Fssh_rijndaelEncrypt
#define rijndaelKeySetupEnc			Fssh_rijndaelKeySetupEnc
#define rtrim					Fssh_rtrim
#define safe_path				Fssh_safe_path
#define safe_path_fd				Fssh_safe_path_fd
#define sanitise_stdfd				Fssh_sanitise_stdfd
#define scan_scaled				Fssh_scan_scaled
#define seed_rng				Fssh_seed_rng
#define send_error				Fssh_send_error
#define set_log_handler				Fssh_set_log_handler
#define set_nodelay				Fssh_set_nodelay
#define set_nonblock				Fssh_set_nonblock
#define set_rdomain				Fssh_set_rdomain
#define set_reuseaddr				Fssh_set_reuseaddr
#define set_sock_tos				Fssh_set_sock_tos
#define sftp_realpath				Fssh_sftp_realpath
#define shadow_pw				Fssh_shadow_pw
#define sieve_large				Fssh_sieve_large
#define sig_alarm				Fssh_sig_alarm
#define sig_winch				Fssh_sig_winch
#define skip_space				Fssh_skip_space
#define snmprintf				Fssh_snmprintf
#define sock_set_v6only				Fssh_sock_set_v6only
#define speed_to_baud				Fssh_speed_to_baud
#define ssh_add_hostkey				Fssh_ssh_add_hostkey
#define ssh_add_identity_constrained		Fssh_ssh_add_identity_constrained
#define ssh_agent_has_key			Fssh_ssh_agent_has_key
#define ssh_agent_sign				Fssh_ssh_agent_sign
#define ssh_alloc_session_state			Fssh_ssh_alloc_session_state
#define ssh_clear_newkeys			Fssh_ssh_clear_newkeys
#define ssh_close_authentication_socket		Fssh_ssh_close_authentication_socket
#define ssh_compatible_openssl			Fssh_ssh_compatible_openssl
#define ssh_digest_alg_by_name			Fssh_ssh_digest_alg_by_name
#define ssh_digest_alg_name			Fssh_ssh_digest_alg_name
#define ssh_digest_blocksize			Fssh_ssh_digest_blocksize
#define ssh_digest_buffer			Fssh_ssh_digest_buffer
#define ssh_digest_bytes			Fssh_ssh_digest_bytes
#define ssh_digest_copy_state			Fssh_ssh_digest_copy_state
#define ssh_digest_final			Fssh_ssh_digest_final
#define ssh_digest_free				Fssh_ssh_digest_free
#define ssh_digest_memory			Fssh_ssh_digest_memory
#define ssh_digest_start			Fssh_ssh_digest_start
#define ssh_digest_update			Fssh_ssh_digest_update
#define ssh_digest_update_buffer		Fssh_ssh_digest_update_buffer
#define ssh_dispatch_init			Fssh_ssh_dispatch_init
#define ssh_dispatch_range			Fssh_ssh_dispatch_range
#define ssh_dispatch_run			Fssh_ssh_dispatch_run
#define ssh_dispatch_run_fatal			Fssh_ssh_dispatch_run_fatal
#define ssh_dispatch_set			Fssh_ssh_dispatch_set
#define ssh_dss_sign				Fssh_ssh_dss_sign
#define ssh_dss_verify				Fssh_ssh_dss_verify
#define ssh_ecdsa_sign				Fssh_ssh_ecdsa_sign
#define ssh_ecdsa_verify			Fssh_ssh_ecdsa_verify
#define ssh_ed25519_sign			Fssh_ssh_ed25519_sign
#define ssh_ed25519_verify			Fssh_ssh_ed25519_verify
#define ssh_err					Fssh_ssh_err
#define ssh_fetch_identitylist			Fssh_ssh_fetch_identitylist
#define ssh_free				Fssh_ssh_free
#define ssh_free_identitylist			Fssh_ssh_free_identitylist
#define ssh_gai_strerror			Fssh_ssh_gai_strerror
#define ssh_get_app_data			Fssh_ssh_get_app_data
#define ssh_get_authentication_socket		Fssh_ssh_get_authentication_socket
#define ssh_get_authentication_socket_path	Fssh_ssh_get_authentication_socket_path
#define ssh_get_progname			Fssh_ssh_get_progname
#define ssh_hmac_bytes				Fssh_ssh_hmac_bytes
#define ssh_hmac_final				Fssh_ssh_hmac_final
#define ssh_hmac_free				Fssh_ssh_hmac_free
#define ssh_hmac_init				Fssh_ssh_hmac_init
#define ssh_hmac_start				Fssh_ssh_hmac_start
#define ssh_hmac_update				Fssh_ssh_hmac_update
#define ssh_hmac_update_buffer			Fssh_ssh_hmac_update_buffer
#define ssh_init				Fssh_ssh_init
#define ssh_input_append			Fssh_ssh_input_append
#define ssh_input_space				Fssh_ssh_input_space
#define ssh_krl_check_key			Fssh_ssh_krl_check_key
#define ssh_krl_file_contains_key		Fssh_ssh_krl_file_contains_key
#define ssh_krl_free				Fssh_ssh_krl_free
#define ssh_krl_from_blob			Fssh_ssh_krl_from_blob
#define ssh_krl_init				Fssh_ssh_krl_init
#define ssh_krl_revoke_cert_by_key_id		Fssh_ssh_krl_revoke_cert_by_key_id
#define ssh_krl_revoke_cert_by_serial		Fssh_ssh_krl_revoke_cert_by_serial
#define ssh_krl_revoke_cert_by_serial_range	Fssh_ssh_krl_revoke_cert_by_serial_range
#define ssh_krl_revoke_key			Fssh_ssh_krl_revoke_key
#define ssh_krl_revoke_key_explicit		Fssh_ssh_krl_revoke_key_explicit
#define ssh_krl_revoke_key_sha1			Fssh_ssh_krl_revoke_key_sha1
#define ssh_krl_revoke_key_sha256		Fssh_ssh_krl_revoke_key_sha256
#define ssh_krl_set_comment			Fssh_ssh_krl_set_comment
#define ssh_krl_set_version			Fssh_ssh_krl_set_version
#define ssh_krl_to_blob				Fssh_ssh_krl_to_blob
#define ssh_libcrypto_init			Fssh_ssh_libcrypto_init
#define ssh_local_ipaddr			Fssh_ssh_local_ipaddr
#define ssh_local_port				Fssh_ssh_local_port
#define ssh_lock_agent				Fssh_ssh_lock_agent
#define ssh_msg_recv				Fssh_ssh_msg_recv
#define ssh_msg_send				Fssh_ssh_msg_send
#define ssh_output_consume			Fssh_ssh_output_consume
#define ssh_output_ptr				Fssh_ssh_output_ptr
#define ssh_output_space			Fssh_ssh_output_space
#define ssh_packet_check_rekey			Fssh_ssh_packet_check_rekey
#define ssh_packet_clear_keys			Fssh_ssh_packet_clear_keys
#define ssh_packet_close			Fssh_ssh_packet_close
#define ssh_packet_close_internal		Fssh_ssh_packet_close_internal
#define ssh_packet_connection_af		Fssh_ssh_packet_connection_af
#define ssh_packet_connection_is_on_socket	Fssh_ssh_packet_connection_is_on_socket
#define ssh_packet_disconnect			Fssh_ssh_packet_disconnect
#define ssh_packet_enable_delayed_compress	Fssh_ssh_packet_enable_delayed_compress
#define ssh_packet_get_bytes			Fssh_ssh_packet_get_bytes
#define ssh_packet_get_connection_in		Fssh_ssh_packet_get_connection_in
#define ssh_packet_get_connection_out		Fssh_ssh_packet_get_connection_out
#define ssh_packet_get_input			Fssh_ssh_packet_get_input
#define ssh_packet_get_maxsize			Fssh_ssh_packet_get_maxsize
#define ssh_packet_get_mux			Fssh_ssh_packet_get_mux
#define ssh_packet_get_output			Fssh_ssh_packet_get_output
#define ssh_packet_get_protocol_flags		Fssh_ssh_packet_get_protocol_flags
#define ssh_packet_get_rekey_timeout		Fssh_ssh_packet_get_rekey_timeout
#define ssh_packet_get_state			Fssh_ssh_packet_get_state
#define ssh_packet_have_data_to_write		Fssh_ssh_packet_have_data_to_write
#define ssh_packet_inc_alive_timeouts		Fssh_ssh_packet_inc_alive_timeouts
#define ssh_packet_is_interactive		Fssh_ssh_packet_is_interactive
#define ssh_packet_is_rekeying			Fssh_ssh_packet_is_rekeying
#define ssh_packet_log_type			Fssh_ssh_packet_log_type
#define ssh_packet_need_rekeying		Fssh_ssh_packet_need_rekeying
#define ssh_packet_next				Fssh_ssh_packet_next
#define ssh_packet_not_very_much_data_to_write	Fssh_ssh_packet_not_very_much_data_to_write
#define ssh_packet_payload			Fssh_ssh_packet_payload
#define ssh_packet_process_incoming		Fssh_ssh_packet_process_incoming
#define ssh_packet_put				Fssh_ssh_packet_put
#define ssh_packet_rdomain_in			Fssh_ssh_packet_rdomain_in
#define ssh_packet_read				Fssh_ssh_packet_read
#define ssh_packet_read_expect			Fssh_ssh_packet_read_expect
#define ssh_packet_read_poll2			Fssh_ssh_packet_read_poll2
#define ssh_packet_read_poll_seqnr		Fssh_ssh_packet_read_poll_seqnr
#define ssh_packet_read_seqnr			Fssh_ssh_packet_read_seqnr
#define ssh_packet_remaining			Fssh_ssh_packet_remaining
#define ssh_packet_send2			Fssh_ssh_packet_send2
#define ssh_packet_send2_wrapped		Fssh_ssh_packet_send2_wrapped
#define ssh_packet_send_debug			Fssh_ssh_packet_send_debug
#define ssh_packet_set_alive_timeouts		Fssh_ssh_packet_set_alive_timeouts
#define ssh_packet_set_authenticated		Fssh_ssh_packet_set_authenticated
#define ssh_packet_set_connection		Fssh_ssh_packet_set_connection
#define ssh_packet_set_input_hook		Fssh_ssh_packet_set_input_hook
#define ssh_packet_set_interactive		Fssh_ssh_packet_set_interactive
#define ssh_packet_set_log_preamble		Fssh_ssh_packet_set_log_preamble
#define ssh_packet_set_maxsize			Fssh_ssh_packet_set_maxsize
#define ssh_packet_set_mux			Fssh_ssh_packet_set_mux
#define ssh_packet_set_nonblocking		Fssh_ssh_packet_set_nonblocking
#define ssh_packet_set_protocol_flags		Fssh_ssh_packet_set_protocol_flags
#define ssh_packet_set_rekey_limits		Fssh_ssh_packet_set_rekey_limits
#define ssh_packet_set_server			Fssh_ssh_packet_set_server
#define ssh_packet_set_state			Fssh_ssh_packet_set_state
#define ssh_packet_set_timeout			Fssh_ssh_packet_set_timeout
#define ssh_packet_set_tos			Fssh_ssh_packet_set_tos
#define ssh_packet_start_discard		Fssh_ssh_packet_start_discard
#define ssh_packet_stop_discard			Fssh_ssh_packet_stop_discard
#define ssh_packet_write_poll			Fssh_ssh_packet_write_poll
#define ssh_packet_write_wait			Fssh_ssh_packet_write_wait
#define ssh_remote_ipaddr			Fssh_ssh_remote_ipaddr
#define ssh_remote_port				Fssh_ssh_remote_port
#define ssh_remove_all_identities		Fssh_ssh_remove_all_identities
#define ssh_remove_identity			Fssh_ssh_remove_identity
#define ssh_request_reply			Fssh_ssh_request_reply
#define ssh_rsa_complete_crt_parameters		Fssh_ssh_rsa_complete_crt_parameters
#define ssh_rsa_sign				Fssh_ssh_rsa_sign
#define ssh_rsa_verify				Fssh_ssh_rsa_verify
#define ssh_set_app_data			Fssh_ssh_set_app_data
#define ssh_set_newkeys				Fssh_ssh_set_newkeys
#define ssh_set_verify_host_key_callback	Fssh_ssh_set_verify_host_key_callback
#define ssh_signal				Fssh_ssh_signal
#define ssh_tty_make_modes			Fssh_ssh_tty_make_modes
#define ssh_tty_parse_modes			Fssh_ssh_tty_parse_modes
#define ssh_update_card				Fssh_ssh_update_card
#define sshbuf_alloc				Fssh_sshbuf_alloc
#define sshbuf_allocate				Fssh_sshbuf_allocate
#define sshbuf_avail				Fssh_sshbuf_avail
#define sshbuf_b64tod				Fssh_sshbuf_b64tod
#define sshbuf_check_reserve			Fssh_sshbuf_check_reserve
#define sshbuf_cmp				Fssh_sshbuf_cmp
#define sshbuf_consume				Fssh_sshbuf_consume
#define sshbuf_consume_end			Fssh_sshbuf_consume_end
#define sshbuf_dtob16				Fssh_sshbuf_dtob16
#define sshbuf_dtob64				Fssh_sshbuf_dtob64
#define sshbuf_dtob64_string			Fssh_sshbuf_dtob64_string
#define sshbuf_dtourlb64			Fssh_sshbuf_dtourlb64
#define sshbuf_dump				Fssh_sshbuf_dump
#define sshbuf_dump_data			Fssh_sshbuf_dump_data
#define sshbuf_dup_string			Fssh_sshbuf_dup_string
#define sshbuf_find				Fssh_sshbuf_find
#define sshbuf_free				Fssh_sshbuf_free
#define sshbuf_from				Fssh_sshbuf_from
#define sshbuf_fromb				Fssh_sshbuf_fromb
#define sshbuf_froms				Fssh_sshbuf_froms
#define sshbuf_get				Fssh_sshbuf_get
#define sshbuf_get_bignum2			Fssh_sshbuf_get_bignum2
#define sshbuf_get_bignum2_bytes_direct		Fssh_sshbuf_get_bignum2_bytes_direct
#define sshbuf_get_cstring			Fssh_sshbuf_get_cstring
#define sshbuf_get_ec				Fssh_sshbuf_get_ec
#define sshbuf_get_eckey			Fssh_sshbuf_get_eckey
#define sshbuf_get_string			Fssh_sshbuf_get_string
#define sshbuf_get_string_direct		Fssh_sshbuf_get_string_direct
#define sshbuf_get_stringb			Fssh_sshbuf_get_stringb
#define sshbuf_get_u16				Fssh_sshbuf_get_u16
#define sshbuf_get_u32				Fssh_sshbuf_get_u32
#define sshbuf_get_u64				Fssh_sshbuf_get_u64
#define sshbuf_get_u8				Fssh_sshbuf_get_u8
#define sshbuf_len				Fssh_sshbuf_len
#define sshbuf_load_fd				Fssh_sshbuf_load_fd
#define sshbuf_load_file			Fssh_sshbuf_load_file
#define sshbuf_max_size				Fssh_sshbuf_max_size
#define sshbuf_mutable_ptr			Fssh_sshbuf_mutable_ptr
#define sshbuf_new				Fssh_sshbuf_new
#define sshbuf_parent				Fssh_sshbuf_parent
#define sshbuf_peek_string_direct		Fssh_sshbuf_peek_string_direct
#define sshbuf_peek_u16				Fssh_sshbuf_peek_u16
#define sshbuf_peek_u32				Fssh_sshbuf_peek_u32
#define sshbuf_peek_u64				Fssh_sshbuf_peek_u64
#define sshbuf_peek_u8				Fssh_sshbuf_peek_u8
#define sshbuf_poke				Fssh_sshbuf_poke
#define sshbuf_poke_u16				Fssh_sshbuf_poke_u16
#define sshbuf_poke_u32				Fssh_sshbuf_poke_u32
#define sshbuf_poke_u64				Fssh_sshbuf_poke_u64
#define sshbuf_poke_u8				Fssh_sshbuf_poke_u8
#define sshbuf_ptr				Fssh_sshbuf_ptr
#define sshbuf_put				Fssh_sshbuf_put
#define sshbuf_put_bignum2			Fssh_sshbuf_put_bignum2
#define sshbuf_put_bignum2_bytes		Fssh_sshbuf_put_bignum2_bytes
#define sshbuf_put_cstring			Fssh_sshbuf_put_cstring
#define sshbuf_put_ec				Fssh_sshbuf_put_ec
#define sshbuf_put_eckey			Fssh_sshbuf_put_eckey
#define sshbuf_put_string			Fssh_sshbuf_put_string
#define sshbuf_put_stringb			Fssh_sshbuf_put_stringb
#define sshbuf_put_u16				Fssh_sshbuf_put_u16
#define sshbuf_put_u32				Fssh_sshbuf_put_u32
#define sshbuf_put_u64				Fssh_sshbuf_put_u64
#define sshbuf_put_u8				Fssh_sshbuf_put_u8
#define sshbuf_putb				Fssh_sshbuf_putb
#define sshbuf_putf				Fssh_sshbuf_putf
#define sshbuf_putfv				Fssh_sshbuf_putfv
#define sshbuf_refcount				Fssh_sshbuf_refcount
#define sshbuf_reserve				Fssh_sshbuf_reserve
#define sshbuf_reset				Fssh_sshbuf_reset
#define sshbuf_set_max_size			Fssh_sshbuf_set_max_size
#define sshbuf_set_parent			Fssh_sshbuf_set_parent
#define sshbuf_write_file			Fssh_sshbuf_write_file
#define sshfatal				Fssh_sshfatal
#define sshkey_advance_past_options		Fssh_sshkey_advance_past_options
#define sshkey_alg_list				Fssh_sshkey_alg_list
#define sshkey_cert_check_authority		Fssh_sshkey_cert_check_authority
#define sshkey_cert_check_authority_now		Fssh_sshkey_cert_check_authority_now
#define sshkey_cert_check_host			Fssh_sshkey_cert_check_host
#define sshkey_cert_copy			Fssh_sshkey_cert_copy
#define sshkey_cert_type			Fssh_sshkey_cert_type
#define sshkey_certify				Fssh_sshkey_certify
#define sshkey_certify_custom			Fssh_sshkey_certify_custom
#define sshkey_check_cert_sigtype		Fssh_sshkey_check_cert_sigtype
#define sshkey_check_revoked			Fssh_sshkey_check_revoked
#define sshkey_check_sigtype			Fssh_sshkey_check_sigtype
#define sshkey_curve_name_to_nid		Fssh_sshkey_curve_name_to_nid
#define sshkey_curve_nid_to_bits		Fssh_sshkey_curve_nid_to_bits
#define sshkey_curve_nid_to_name		Fssh_sshkey_curve_nid_to_name
#define sshkey_drop_cert			Fssh_sshkey_drop_cert
#define sshkey_dump_ec_key			Fssh_sshkey_dump_ec_key
#define sshkey_dump_ec_point			Fssh_sshkey_dump_ec_point
#define sshkey_ec_nid_to_hash_alg		Fssh_sshkey_ec_nid_to_hash_alg
#define sshkey_ec_validate_private		Fssh_sshkey_ec_validate_private
#define sshkey_ec_validate_public		Fssh_sshkey_ec_validate_public
#define sshkey_ecdsa_bits_to_nid		Fssh_sshkey_ecdsa_bits_to_nid
#define sshkey_ecdsa_key_to_nid			Fssh_sshkey_ecdsa_key_to_nid
#define sshkey_ecdsa_nid_from_name		Fssh_sshkey_ecdsa_nid_from_name
#define sshkey_enable_maxsign			Fssh_sshkey_enable_maxsign
#define sshkey_equal				Fssh_sshkey_equal
#define sshkey_equal_public			Fssh_sshkey_equal_public
#define sshkey_fingerprint			Fssh_sshkey_fingerprint
#define sshkey_fingerprint_raw			Fssh_sshkey_fingerprint_raw
#define sshkey_format_cert_validity		Fssh_sshkey_format_cert_validity
#define sshkey_format_text			Fssh_sshkey_format_text
#define sshkey_free				Fssh_sshkey_free
#define sshkey_from_blob			Fssh_sshkey_from_blob
#define sshkey_from_blob_internal		Fssh_sshkey_from_blob_internal
#define sshkey_from_private			Fssh_sshkey_from_private
#define sshkey_fromb				Fssh_sshkey_fromb
#define sshkey_froms				Fssh_sshkey_froms
#define sshkey_generate				Fssh_sshkey_generate
#define sshkey_get_sigtype			Fssh_sshkey_get_sigtype
#define sshkey_in_file				Fssh_sshkey_in_file
#define sshkey_is_cert				Fssh_sshkey_is_cert
#define sshkey_is_shielded			Fssh_sshkey_is_shielded
#define sshkey_is_sk				Fssh_sshkey_is_sk
#define sshkey_load_cert			Fssh_sshkey_load_cert
#define sshkey_load_private			Fssh_sshkey_load_private
#define sshkey_load_private_cert		Fssh_sshkey_load_private_cert
#define sshkey_load_private_type		Fssh_sshkey_load_private_type
#define sshkey_load_private_type_fd		Fssh_sshkey_load_private_type_fd
#define sshkey_load_public			Fssh_sshkey_load_public
#define sshkey_names_valid2			Fssh_sshkey_names_valid2
#define sshkey_new				Fssh_sshkey_new
#define sshkey_parse_private2			Fssh_sshkey_parse_private2
#define sshkey_parse_private_fileblob		Fssh_sshkey_parse_private_fileblob
#define sshkey_parse_private_fileblob_type	Fssh_sshkey_parse_private_fileblob_type
#define sshkey_parse_pubkey_from_private_fileblob_type Fssh_sshkey_parse_pubkey_from_private_fileblob_type
#define sshkey_perm_ok				Fssh_sshkey_perm_ok
#define sshkey_plain_to_blob			Fssh_sshkey_plain_to_blob
#define sshkey_private_deserialize		Fssh_sshkey_private_deserialize
#define sshkey_private_serialize		Fssh_sshkey_private_serialize
#define sshkey_private_serialize_maxsign	Fssh_sshkey_private_serialize_maxsign
#define sshkey_private_serialize_opt		Fssh_sshkey_private_serialize_opt
#define sshkey_private_to_blob2			Fssh_sshkey_private_to_blob2
#define sshkey_private_to_fileblob		Fssh_sshkey_private_to_fileblob
#define sshkey_putb				Fssh_sshkey_putb
#define sshkey_putb_plain			Fssh_sshkey_putb_plain
#define sshkey_puts				Fssh_sshkey_puts
#define sshkey_puts_opts			Fssh_sshkey_puts_opts
#define sshkey_read				Fssh_sshkey_read
#define sshkey_save_private			Fssh_sshkey_save_private
#define sshkey_save_public			Fssh_sshkey_save_public
#define sshkey_set_filename			Fssh_sshkey_set_filename
#define sshkey_shield_private			Fssh_sshkey_shield_private
#define sshkey_sig_details_free			Fssh_sshkey_sig_details_free
#define sshkey_sigalg_by_name			Fssh_sshkey_sigalg_by_name
#define sshkey_sign				Fssh_sshkey_sign
#define sshkey_signatures_left			Fssh_sshkey_signatures_left
#define sshkey_size				Fssh_sshkey_size
#define sshkey_ssh_name				Fssh_sshkey_ssh_name
#define sshkey_ssh_name_plain			Fssh_sshkey_ssh_name_plain
#define sshkey_to_base64			Fssh_sshkey_to_base64
#define sshkey_to_blob				Fssh_sshkey_to_blob
#define sshkey_to_certified			Fssh_sshkey_to_certified
#define sshkey_try_load_public			Fssh_sshkey_try_load_public
#define sshkey_type				Fssh_sshkey_type
#define sshkey_type_from_name			Fssh_sshkey_type_from_name
#define sshkey_type_is_cert			Fssh_sshkey_type_is_cert
#define sshkey_type_plain			Fssh_sshkey_type_plain
#define sshkey_unshield_private			Fssh_sshkey_unshield_private
#define sshkey_verify				Fssh_sshkey_verify
#define sshkey_write				Fssh_sshkey_write
#define sshlog					Fssh_sshlog
#define sshlogdie				Fssh_sshlogdie
#define sshlogdirect				Fssh_sshlogdirect
#define sshlogv					Fssh_sshlogv
#define sshpkt_add_padding			Fssh_sshpkt_add_padding
#define sshpkt_disconnect			Fssh_sshpkt_disconnect
#define sshpkt_fatal				Fssh_sshpkt_fatal
#define sshpkt_fmt_connection_id		Fssh_sshpkt_fmt_connection_id
#define sshpkt_get				Fssh_sshpkt_get
#define sshpkt_get_bignum2			Fssh_sshpkt_get_bignum2
#define sshpkt_get_cstring			Fssh_sshpkt_get_cstring
#define sshpkt_get_ec				Fssh_sshpkt_get_ec
#define sshpkt_get_end				Fssh_sshpkt_get_end
#define sshpkt_get_string			Fssh_sshpkt_get_string
#define sshpkt_get_string_direct		Fssh_sshpkt_get_string_direct
#define sshpkt_get_u32				Fssh_sshpkt_get_u32
#define sshpkt_get_u64				Fssh_sshpkt_get_u64
#define sshpkt_get_u8				Fssh_sshpkt_get_u8
#define sshpkt_getb_froms			Fssh_sshpkt_getb_froms
#define sshpkt_msg_ignore			Fssh_sshpkt_msg_ignore
#define sshpkt_peek_string_direct		Fssh_sshpkt_peek_string_direct
#define sshpkt_ptr				Fssh_sshpkt_ptr
#define sshpkt_put				Fssh_sshpkt_put
#define sshpkt_put_bignum2			Fssh_sshpkt_put_bignum2
#define sshpkt_put_cstring			Fssh_sshpkt_put_cstring
#define sshpkt_put_ec				Fssh_sshpkt_put_ec
#define sshpkt_put_string			Fssh_sshpkt_put_string
#define sshpkt_put_stringb			Fssh_sshpkt_put_stringb
#define sshpkt_put_u32				Fssh_sshpkt_put_u32
#define sshpkt_put_u64				Fssh_sshpkt_put_u64
#define sshpkt_put_u8				Fssh_sshpkt_put_u8
#define sshpkt_putb				Fssh_sshpkt_putb
#define sshpkt_send				Fssh_sshpkt_send
#define sshpkt_start				Fssh_sshpkt_start
#define sshpkt_vfatal				Fssh_sshpkt_vfatal
#define sshsigdie				Fssh_sshsigdie
#define start_progress_meter			Fssh_start_progress_meter
#define stdfd_devnull				Fssh_stdfd_devnull
#define stop_progress_meter			Fssh_stop_progress_meter
#define stravis					Fssh_stravis
#define strdelim				Fssh_strdelim
#define strdelim_internal			Fssh_strdelim_internal
#define strdelimw				Fssh_strdelimw
#define strnvis					Fssh_strnvis
#define strvis					Fssh_strvis
#define strvisx					Fssh_strvisx
#define subprocess				Fssh_subprocess
#define sys_tun_open				Fssh_sys_tun_open
#define tilde_expand				Fssh_tilde_expand
#define tilde_expand_filename			Fssh_tilde_expand_filename
#define timeout_connect				Fssh_timeout_connect
#define to_blob					Fssh_to_blob
#define to_blob_buf				Fssh_to_blob_buf
#define tohex					Fssh_tohex
#define tun_open				Fssh_tun_open
#define umac128_delete				Fssh_umac128_delete
#define umac128_final				Fssh_umac128_final
#define umac128_new				Fssh_umac128_new
#define umac128_update				Fssh_umac128_update
#define umac_delete				Fssh_umac_delete
#define umac_final				Fssh_umac_final
#define umac_new				Fssh_umac_new
#define umac_update				Fssh_umac_update
#define unix_listener				Fssh_unix_listener
#define unset_nonblock				Fssh_unset_nonblock
#define urldecode				Fssh_urldecode
#define valid_domain				Fssh_valid_domain
#define valid_env_name				Fssh_valid_env_name
#define vasnmprintf				Fssh_vasnmprintf
#define vdollar_percent_expand			Fssh_vdollar_percent_expand
#define verify_host_key_dns			Fssh_verify_host_key_dns
#define vfmprintf				Fssh_vfmprintf
#define vis					Fssh_vis
#define waitfd					Fssh_waitfd
#define waitrfd					Fssh_waitrfd
#define write_host_entry			Fssh_write_host_entry
#define x11_connect_display			Fssh_x11_connect_display
#define x11_create_display_inet			Fssh_x11_create_display_inet
#define x11_request_forwarding_with_spoofing	Fssh_x11_request_forwarding_with_spoofing
#define xasprintf				Fssh_xasprintf
#define xcalloc					Fssh_xcalloc
#define xcrypt					Fssh_xcrypt
#define xextendf				Fssh_xextendf
#define xmalloc					Fssh_xmalloc
#define xreallocarray				Fssh_xreallocarray
#define xrecallocarray				Fssh_xrecallocarray
#define xstrdup					Fssh_xstrdup
#define xvasprintf				Fssh_xvasprintf
