# $FreeBSD: src/lib/libalias/modules/Makefile,v 1.2.10.1.6.1 2010/12/21 17:09:25 kensmith Exp $

.include "${.CURDIR}/../../../sys/modules/libalias/modules/modules.inc"

SUBDIR=	${MODULES}

.include <bsd.subdir.mk>
