#
#      The FreeBSD Documentation Project
#      The FreeBSD French Documentation Project
#
#      $Id$
#      $FreeBSD: src/release/doc/fr_FR.ISO8859-1/hardware/Makefile,v 1.1.2.1 2002/10/19 14:56:31 gioria Exp $
#      Original revision: 1.2.2.1

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= i386

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
