#
#      The FreeBSD Documentation Project
#      The FreeBSD French Documentation Project
#
#      $Id$
#      $FreeBSD: src/release/doc/fr_FR.ISO8859-1/hardware/Makefile,v 1.1.38.1.4.1 2010/06/14 02:09:06 kensmith Exp $
#      Original revision: 1.4

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
