.\"
.\" kbdcontrol - a utility for manipulating the syscons keyboard driver section
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\"     @(#)kbdcontrol.1
.\"
.TH kbdcontrol 1 "May 22, 1994" "" "FreeBSD"

.SH NAME
kbdcontrol - a utility for manipulating the syscons keyboard driver section.
.SH SYNOPSIS
.na
.B kbdcontrol
.RB [options]
.SH DESCRIPTION
The
.B kbdcontrol
command is used to set various keyboard related options for the syscons 
console driver, such as keymap, keyboard repeat & delay rates, bell 
characteristics etc.
.SH OPTIONS
.TP
The following command line options are supported.
.TP
.BI "\-b\ " [ duration.pitch ]
Set the bell duration and pitch values.
.TP
.BI "\-r\ " [ delay.repeat | slow | fast | normal ]
Set keyboard
.I delay
and
.I repeat
rates, or use presets for
.I slow,
.I fast
or
.I normal.
.TP
.BI "\-l\ " mapfile
Install keyboard map file from
.I mapfile
.TP
.BI "\-d\ " 
Dump the current keyboard map onto stdout
.TP
.BI "\-f\ " #\ string
Set function key number
.I #
to send
.I string
.
.TP
.BI "\-F\ "
Set function keys back to the standard definitions.
.TP
.B \-v
Turns on verbose output.
.PP
.SH FILES
/usr/share/syscons/keymaps
.SH "BUGS"
Report when found.
.SH "SEE ALSO"
.BR vidcontrol (1) ,
.BR keyboard (4) ,
.BR screen (4) ,
.BR /sys/i386/conf/SYSCONS
.SH AUTHORS
Søren Schmidt (sos@login.dkuug.dk)
