# $FreeBSD: src/secure/lib/libcrypto/engines/lib4758cca/Makefile,v 1.1.10.1.2.1 2009/10/25 01:10:29 kensmith Exp $

SHLIB_NAME?= lib4758cca.so
SRCS=	e_4758cca.c
NO_MAN=	# For now

.include <bsd.lib.mk>
