#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/ctags/Makefile,v 1.5.38.1 2010/02/10 00:26:20 kensmith Exp $

PROG=	ctags
SRCS=	C.c ctags.c fortran.c lisp.c print.c tree.c yacc.c
CFLAGS+=-I${.CURDIR}

.include <bsd.prog.mk>
