#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/ctags/Makefile,v 1.5.32.1 2008/11/25 02:59:29 kensmith Exp $

PROG=	ctags
SRCS=	C.c ctags.c fortran.c lisp.c print.c tree.c yacc.c
CFLAGS+=-I${.CURDIR}

.include <bsd.prog.mk>
