# $FreeBSD$

.include <bsd.own.mk>

LIB=	llvmmcparser

SRCDIR=	lib/MC/MCParser
SRCS=	AsmLexer.cpp \
	AsmParser.cpp \
	COFFAsmParser.cpp \
	DarwinAsmParser.cpp \
	ELFAsmParser.cpp \
	MCAsmLexer.cpp \
	MCAsmParser.cpp \
	MCAsmParserExtension.cpp \
	MCTargetAsmParser.cpp

.include "../clang.lib.mk"
