#	$Id: Makefile,v 1.19 1995/01/17 19:28:56 ache Exp $

SUBDIR= as awk bc cc cpio cvs dc dialog diff diff3 gdb \
	grep ngroff gzip ld man patch perl ptx rcs sdiff send-pr \
	sort tar texinfo

.include <bsd.subdir.mk>
