#	$Id: Makefile,v 1.32 1996/09/10 14:04:37 peter Exp $

SUBDIR= as awk bc bison cc cpio cvs dc dialog diff diff3 gdb genclass gperf \
	grep groff gzip ld man patch perl ptx rcs sdiff send-pr \
	sort tar texinfo

.include <bsd.subdir.mk>
