# $FreeBSD: src/usr.sbin/kgzip/Makefile,v 1.11.26.1 2008/10/02 02:57:24 kensmith Exp $

PROG=	kgzip
MAN=	kgzip.8
SRCS=	kgzip.c aouthdr.c elfhdr.c kgzcmp.c kgzld.c xio.c

WARNS?=	3

.include <bsd.prog.mk>
