#!/bin/sh -
#
#	$Id: netstart,v 1.7 1993/11/07 01:19:02 wollman Exp $
#	From: @(#)netstart	5.9 (Berkeley) 3/30/91

routedflags=-q
timedflags=NO
xntpdflags="NO"
ntpdate="NO"
rwhod=NO
sendmail_flags="-bd -q30m"
#kerberos_server=YES
#nfs_server=YES
#name_server=YES
#gated=YES

# my-name is my symbolic name
# my-netmask is specified in /etc/networks
#
hostname=`cat /etc/myname`
hostname $hostname

# ifconfig ie0 inet $hostname netmask my-netmask
# ifconfig is0 inet $hostname netmask my-netmask
# ifconfig ed0 inet $hostname netmask my-netmask

# set the address for the loopback interface
ifconfig lo0 inet localhost

# use loopback, not the wire
# route add $hostname localhost
