# $FreeBSD: src/sys/modules/sound/driver/Makefile,v 1.5.2.12 2002/08/24 08:34:20 nsayer Exp $

SUBDIR = ad1816 als4000 cmi cs4281 csa ds1 emu10k1 es137x ess fm801 ich
SUBDIR += maestro maestro3 mss neomagic sb16 sb8 sbc solo t4dwave
SUBDIR += uaudio via8233 via82c686 vibes

.include <bsd.subdir.mk>
