#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/cmp/Makefile,v 1.7.10.1.8.1 2012/03/03 06:15:13 kensmith Exp $

PROG=	cmp
SRCS=	cmp.c link.c misc.c regular.c special.c

.include <bsd.prog.mk>
