#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojail

. /etc/rc.subr

name="bsnmpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/snmpd.pid"

load_rc_config $name
run_rc_command "$1"
