# Makefile for acpi tools
# $Id: Makefile,v 1.1 2000/07/14 18:16:22 iwasaki Exp $
# $FreeBSD: src/usr.sbin/acpi/Makefile,v 1.3.32.1.6.1 2010/12/21 17:09:25 kensmith Exp $

SUBDIR= acpiconf acpidb acpidump iasl

.include <bsd.subdir.mk>
