Hello, world via cout
Hello, world via cerr
enter a char:c = "a"
enter three integers (short, int, long):first  = 123 via dec =      123
second = 4567 via form = 4567 = 010727 via cout.form = 4567 = 0x11d7
third  = 89012 via hex = 15bb4
enter a float then a double:first  = 123.456
second = -0.012
enter 5 characters separated with spaces:first  = 1
rest   =  2 3 4 5

Making streams sout and sin...contents of file:
Thisfilehasonelinetestingoutputstreams.
Making File tf ... first line of file:
This is the first and only line of this file.
next char = 10
reopening tempfile, appending: Now there is a second line.
First 10 chars via raw system read after reopen for input:
This is th
Contents after raw lseek to pos 5:
is the first and only line of this file.
Now there is a second line.

Making SFile rf...odd elements of file in reverse order:
(i = 9 c = j d = 0.009)
(i = 7 c = h d = 0.007)
(i = 5 c = f d = 0.005)
(i = 3 c = d d = 0.003)
(i = 1 c = b d = 0.001)

Making PlotFile pf ...(You may delete or attempt to plot plot.out)
creating ostrstream...
with contents:
This is a string-based stream.
With two lines.
using it to create istrstream...
with contents:
This is a string-based stream.
With two lines.

Making filebuf streams fout and fin...contents of file:
Thisfilehasonelinetestingoutputstreams.

Final names & states:
cin:      (stdin)	0
cout:     (stdout)	0
cerr:     (stderr)	0

end of test.
