#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/primes/Makefile,v 1.3.22.1.2.1 2009/10/25 01:10:29 kensmith Exp $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c
NO_MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
