#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/primes/Makefile,v 1.3.16.1 2008/10/02 02:57:24 kensmith Exp $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c
NO_MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
