# $FreeBSD$

LIB=	clangdriver

SRCDIR=	tools/clang/lib/Driver
SRCS=	Action.cpp Arg.cpp ArgList.cpp Compilation.cpp Driver.cpp \
	HostInfo.cpp Job.cpp OptTable.cpp Option.cpp Phases.cpp \
	Tool.cpp ToolChain.cpp ToolChains.cpp Tools.cpp Types.cpp

TGHDRS=	DiagnosticCommonKinds DiagnosticDriverKinds

.include "../../clang.lib.mk"
