#	From: @(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: src/share/doc/psd/12.make/Makefile,v 1.7.32.1 2008/11/25 02:59:29 kensmith Exp $

VOLUME=	psd/12.make
SRCS=	stubs tutorial.ms
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/make/PSD.doc

.include <bsd.doc.mk>
