# $FreeBSD: src/share/doc/psd/27.nfsrpc/Makefile,v 1.6 2004/10/24 15:32:43 ru Exp $

VOLUME=		psd/27.nfsrfc
SRCS=		stubs nfs.rfc.ms
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
