# $FreeBSD$

INCDIR = ${STAGEDIR}/usr/include/nfs4client
COMMONDIR =

INCS = \
	nfs4.h \
	nfs4_dev.h \
	nfs4_idmap.h \
	nfs4_vfs.h \
	nfs4_vn.h \
	nfs4m_subs.h

DIRDEP= stage
.include <bsd.headers.mk>
