.include <src.opts.mk>

PACKAGE=	ntp
FILESDIR=	${SHAREDIR}/doc/ntp/drivers/icons

.if ${MK_HTML} != "no"
FILES=	home.gif mail2.gif
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/drivers/icons

.include <bsd.prog.mk>
