#	@(#)Makefile	8.1 (Berkeley) 6/5/93
#	$FreeBSD: src/usr.sbin/rip6query/Makefile,v 1.1 1999/12/28 02:37:07 shin Exp $

PROG=	rip6query
MAN8=	rip6query.8

CFLAGS+=-DINET6 -I${.CURDIR}/../route6d

.include <bsd.prog.mk>
