# $FreeBSD: src/sys/modules/ums/Makefile,v 1.7.2.1 2004/03/01 00:07:25 julian Exp $ 

MAINTAINER=	n_hibma@freebsd.org

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	ums
SRCS=	bus_if.h device_if.h vnode_if.h opt_usb.h ums.c

.include <bsd.kmod.mk>
