# $FreeBSD: src/sys/modules/ums/Makefile,v 1.14.20.1 2009/04/15 03:14:26 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	ums
SRCS=	bus_if.h device_if.h opt_usb.h ums.c usbdevs.h

.include <bsd.kmod.mk>
