.\"
.\" Copyright (C) 2000
.\" Dr. Duncan McLennan Barclay, dmlb@ragnet.demon.co.uk.
.\"
.\"  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the author nor the names of any co-contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY DUNCAN BARCLAY AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL DUNCAN BARCLAY OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Copyright (c) 1997, 1998, 1999
.\"	Bill Paul <wpaul@ctr.columbia.edu> All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Bill Paul.
.\" 4. Neither the name of the author nor the names of any co-contributors
.\"    may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY Bill Paul AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL Bill Paul OR THE VOICES IN HIS HEAD
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
.\" THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd March 21, 2000
.Dt RAYCONTROL 8
.Os
.Sh NAME
.Nm raycontrol
.Nd configure Raytheon Raylink/Webgear Aviator devices
.Sh SYNOPSIS
.Nm
.Fl i Ar iface Op Fl o
.Nm
.Fl i Ar iface Fl t Ar tx rate
.Nm
.Fl i Ar iface Fl n Ar network name
.Nm
.Fl i Ar iface Fl c Ar ap status
.Nm
.Fl i Ar iface Fl p Ar port type
.Nm
.Fl i Ar iface Fl m Ar mac address
.Nm
.Fl i Ar iface Fl d Ar max data length
.Nm
.Fl i Ar iface Fl r Ar RTS threshold
.Nm
.Fl i Ar iface Fl f Ar hopset
.Nm
.Fl i Ar iface Fl P Ar 0|1
.Nm
.Fl i Ar iface Fl S Ar max_sleep_duration
.Nm
.Fl i Ar iface Fl Z Ar zero signal cache
.Nm
.Fl i Ar iface Fl C Ar display signal cache
.Sh DESCRIPTION
The
.Nm
utility controls the operation of Raylink/Webgear wireless networking
devices via the
.Xr ray 4
driver.
Most of the parameters that can be changed relate to the
IEEE 802.11 protocol which the card implements.
This includes
the station name, whether the station is operating in ad-hoc
or infrastructure mode, and the network name of a service
set to join - the BSS in ad-hoc mode or ESS if infrastructure mode is enabled.
The
.Nm
utility can also be used to view the current settings of these parameters
and to dump out the values of the card's statistics counters.
.Pp
The
.Ar iface
argument given to
.Nm
should be the logical interface name associated with the Raylink/Webgear
device (ray0, ray1, ...).
.Sh OPTIONS
The options are as follows:
.Bl -tag -width Fl
.It Fl i Ar iface Op Fl o
Display the current settings of the specified Raylink/Webgear interface.
This retrieves the current card settings from the driver and prints them
out.
The results from this command are a snapshot of the card settings.
Using the additional
.Fl o
flag will cause
.Nm
to print out the statistics counters instead of the card settings.
.It Fl i Ar iface Fl t Ar tx rate
Set the transmit rate of the specified interface.
The
NICs support a maximum transmit rate of 2Mbps.
The following table shows the
legal transmit rate settings and the corresponding transmit speeds:
.Bl -column "TX rate " "NIC speed " -offset indent
.Em "TX rate	NIC speed"
1	Very Low (0.5Mbps)
2	Low (1Mbps)
3	Medium (1.5Mbps)
4	High (2Mbps)
.El
.Pp
The version 4 firmware may ignore this setting.
Note, that the IEEE 802.11
standard
only allows 1Mbps or 2Mbps operation, and that the generally accepted
reading of the IEEE 802.11 standard is that 2Mbps is only allowed in
infrastructure mode.
.It Fl i Ar iface Fl n Ar network name
Set the name of the service set that this station wishes to
join.
The
.Ar network name
can be any text string up to 32 characters in length.
The default name
is the string "NETWORK_NAME" which should allow the station to connect to
the default Webgear ad-hoc network.
.It Fl i Ar iface Fl p Ar port type
Set the
.Ar port type
for a specified interface.
The legal values for
.Ar port type
are 0 (ad-hoc mode) and 1 (infrastructure mode).
In ad-hoc mode, the station can
communicate directly with any other stations within direct radio range
(provided that they are also operating in ad-hoc mode).
In infrastructure mode,
hosts must associate with a service set controlled by an access point,
that relays traffic between end stations.
The default setting is 0
(ad-hoc mode).
.Pp
When in ad-hoc mode the station will create a BSS with the network name
specified by the
.Fl n
option if it cannot find an existing network of that name on the
currently configured hopset (see the
.Fl f
option).
.It Fl i Ar iface Fl m Ar mac address
Set the station address for the specified interface.
The
.Ar mac address
is specified as a series of six hexadecimal values separated by colons,
e.g.: 00:60:1d:12:34:56.
This programs the new address into the card
and updates the interface as well.
.It Fl i Ar iface Fl d Ar max_data_length
Set the maximum transmit frame size for a specified interface.
The
.Ar max data length
can be any number from 350 to 2304 or -1 to disable fragmentation.
The default is -1.
.It Fl i Ar iface Fl r Ar RTS threshold
Set the RTS/CTS threshold for a given interface.
This controls the
number of bytes used for the RTS/CTS handshake boundary.
The
.Ar RTS threshold
can be any value between -1 and 2047.
The default is -1 (disable).
.It Fl i Ar iface Fl f Ar hopset
Set the radio hopset of a given interface.
The
.Ar hopset
should be specified as a country code as shown in the table below.
The
hopset varies both the number of RF channels and their frequencies
and is dependent on radio regulations specified
by regional authorities.
.Bl -column "Hopset ID " "Country " -offset indent
.Em "Hopset ID	Country"
1	USA
2	Europe
3	Japan
4	Korea
5	Spain
6	France
7	Israel
8	Australia
9	Japan Test
.El
.Pp
Whilst the card can be programmed to work with any hopset it makes
sense to use the hopset for your own region to avoid interference from
and interfering with other users of the RF spectrum (in places like
France this is the military).
.Pp
Note that all stations must be set to the same hopset in order to
communicate.
.It Fl i Ar iface Fl P Ar 0|1
Enable or disable power management on a given interface.
Enabling
power management uses an alternating sleep/wake protocol to help
conserve power on mobile stations, at the cost of some increased
receive latency.
Power management is off by default.
.Pp
Note that power
management requires the cooperation of an access point in order to
function; it is not functional in ad-hoc mode.
Legal
values for this parameter are 0 (off) and 1 (on).
.It Fl i Ar iface Fl S Ar max_sleep_interval
Specify the sleep interval to use when power management is enabled.
The
.Ar max_sleep_interval
is specified in milliseconds.
The default is 100.
.It Fl i Ar iface Fl Z
Clear the signal strength cache maintained internally by the
.Xr ray 4
driver.
.It Fl i Ar iface Fl C
Display the cached signal strength information maintained by the
.Xr ray 4
driver.
The driver retains information about signal strength and
noise level for packets received from different hosts.
For
infrastructure networks the cache stores the signal strength of the
access point.
.Pp
The driver also uses the cache to pick the best antenna when
transmitting.
.El
.Sh SEE ALSO
.Xr ray 4 ,
.Xr ifconfig 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 4.0 .
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Duncan Barclay Aq dmlb@ragnet.demon.co.uk
and based on the
.Nm wicontrol
utility by
.An Bill Paul Aq wpaul@ctr.columbia.edu .
.Sh BUGS
The
.Fl m ,
.Fl P ,
.Fl S
and
.Fl Z
options aren't implemented yet.
No access point was available for testing
against.
.Pp
Not tested with Version 5 firmware.
.Pp
Hopset changing may not work with version 4 firmware.
.Pp
The
.Fl W
option is un-documented on purpose.
