# $FreeBSD: src/sys/modules/mmc/Makefile,v 1.1.10.1.2.1 2009/10/25 01:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmc
SRCS=	mmc.c mmcbr_if.h mmcbus_if.h device_if.h bus_if.h

.include <bsd.kmod.mk>
