#define O_ALTNOTATION 0
#define O_ALTWERASE 1
#define O_AUTOINDENT 2
#define O_AUTOPRINT 3
#define O_AUTOWRITE 4
#define O_BACKUP 5
#define O_BEAUTIFY 6
#define O_CDPATH 7
#define O_CEDIT 8
#define O_COLUMNS 9
#define O_COMBINED 10
#define O_COMMENT 11
#define O_TMPDIR 12
#define O_EDCOMPATIBLE 13
#define O_ERRORBELLS 14
#define O_ESCAPETIME 15
#define O_EXPANDTAB 16
#define O_EXRC 17
#define O_EXTENDED 18
#define O_FILEC 19
#define O_FILEENCODING 20
#define O_FLASH 21
#define O_HARDTABS 22
#define O_ICLOWER 23
#define O_IGNORECASE 24
#define O_INPUTENCODING 25
#define O_KEYTIME 26
#define O_LEFTRIGHT 27
#define O_LINES 28
#define O_LISP 29
#define O_LIST 30
#define O_LOCKFILES 31
#define O_MAGIC 32
#define O_MATCHCHARS 33
#define O_MATCHTIME 34
#define O_MESG 35
#define O_MODELINE 36
#define O_MSGCAT 37
#define O_NOPRINT 38
#define O_NUMBER 39
#define O_OCTAL 40
#define O_OPEN 41
#define O_OPTIMIZE 42
#define O_PARAGRAPHS 43
#define O_PATH 44
#define O_PRINT 45
#define O_PROMPT 46
#define O_READONLY 47
#define O_RECDIR 48
#define O_REDRAW 49
#define O_REMAP 50
#define O_REPORT 51
#define O_RULER 52
#define O_SCROLL 53
#define O_SEARCHINCR 54
#define O_SECTIONS 55
#define O_SECURE 56
#define O_SHELL 57
#define O_SHELLMETA 58
#define O_SHIFTWIDTH 59
#define O_SHOWFILENAME 60
#define O_SHOWMATCH 61
#define O_SHOWMODE 62
#define O_SIDESCROLL 63
#define O_SLOWOPEN 64
#define O_SOURCEANY 65
#define O_TABSTOP 66
#define O_TAGLENGTH 67
#define O_TAGS 68
#define O_TERM 69
#define O_TERSE 70
#define O_TILDEOP 71
#define O_TIMEOUT 72
#define O_TTYWERASE 73
#define O_VERBOSE 74
#define O_W1200 75
#define O_W300 76
#define O_W9600 77
#define O_WARN 78
#define O_WINDOW 79
#define O_WINDOWNAME 80
#define O_WRAPLEN 81
#define O_WRAPMARGIN 82
#define O_WRAPSCAN 83
#define O_WRITEANY 84
#define O_OPTIONCOUNT 85
