
xxx {
	host.hostname = "xxx.yyy";	# hostname
	path = "/vm/$name";		# root directory

	exec.clean;
	exec.system_user = "root";
	exec.jail_user = "root";

	#
	# NB: Below lines required
	#
	vnet;
	# netgraph
	vnet.interface = "ng0_$name";		# vnet interface(s)
	exec.prestart += "jng bridge $name em0";	# bridge interface(s)
	exec.prestop += "ifconfig ng0_$name -vnet $name";	# return ifnet(s)
	exec.poststop += "jng shutdown $name";	# destroy interface(s)
	# if_bridge
	#vnet.interface = "e0b_$name";		# vnet interface(s)
	#exec.prestart += "jib addm $name em0";	# bridge interface(s)
	#exec.poststop += "jib destroy $name";	# destroy interface(s)

	# Standard recipe
	exec.start += "/bin/sh /etc/rc";
	exec.stop = "/bin/sh /etc/rc.shutdown jail";
	exec.consolelog = "/var/log/jail_${name}_console.log";
	mount.devfs;	# mount devfs

	# Optional (default off)
	#devfs_ruleset = "11";		# rule to unhide bpf for DHCP
	#allow.mount;			# mount /etc/fstab.$name
	#allow.set_hostname = 1;	# Allow hostname to change
	#allow.sysvipc = 1;		# Allow SysV Interprocess Comm.
}
