# $FreeBSD: src/share/doc/psd/24.xdr/Makefile,v 1.6.22.1.6.1 2010/12/21 17:09:25 kensmith Exp $

VOLUME=		psd/24.xdr
SRCS=		stubs xdr.nts.ms
MACROS=		-ms
USE_EQN=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
