# $FreeBSD: src/sys/modules/geom/geom_raid3/Makefile,v 1.1.30.1.2.1 2009/10/25 01:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../geom/raid3

KMOD=	geom_raid3
SRCS=	g_raid3.c
SRCS+=	g_raid3_ctl.c

.include <bsd.kmod.mk>
