# $FreeBSD: src/tools/tools/npe/npestats/Makefile,v 1.1.2.1.6.1 2010/12/21 17:09:25 kensmith Exp $

PROG=	npestats
SRCS=	main.c statfoo.c npestats.c
BINDIR=	/usr/local/bin
NO_MAN=	true

.include <bsd.prog.mk>
