# $FreeBSD: src/tools/tools/npe/npestats/Makefile,v 1.1.2.1.8.1 2012/03/03 06:15:13 kensmith Exp $

PROG=	npestats
SRCS=	main.c statfoo.c npestats.c
BINDIR=	/usr/local/bin
NO_MAN=	true

.include <bsd.prog.mk>
