# $FreeBSD: src/tools/tools/hcomp/Makefile,v 1.1.30.1 2009/04/15 03:14:26 kensmith Exp $

BINDIR		?= ${HOME}/bin
BINOWN		?= ${USER}
BINGRP		?= ${USER}
SCRIPTS		 = hcomp.pl

MANDIR		?= ${HOME}/man/man
MANOWN		?= ${USER}
MANGRP		?= ${USER}
MAN		 = # empty

.include <bsd.prog.mk>
