# $FreeBSD: src/tools/tools/hcomp/Makefile,v 1.1.32.1.8.1 2012/03/03 06:15:13 kensmith Exp $

BINDIR		?= ${HOME}/bin
BINOWN		?= ${USER}
BINGRP		?= ${USER}
SCRIPTS		 = hcomp.pl

MANDIR		?= ${HOME}/man/man
MANOWN		?= ${USER}
MANGRP		?= ${USER}
MAN		 = # empty

.include <bsd.prog.mk>
