.\" $FreeBSD$
.Dd June 24, 1999
.Dt NCPLIST 1
.Os
.Sh NAME
.Nm ncplist
.Nd displays various information about ncplib and NetWare servers
.Sh SYNOPSIS
.Nm
.Ar command
.Op Ar args
.Sh DESCRIPTION
The
.Nm
command used to display state of ncplib and NetWare servers.
The first argument
is a one letter
.Ar command
following by optional
.Ar args .
.Pp
The commands are:
.Bl -tag -width indent
.It b Ar server Ar type Op Ar pattern
Lists bindery objects of
.Ar type
on a specified
.Ar server .
The
.Ar type
argument
can be one of the following:
.Bd -literal -offset indent
Type	Meaning
user	bindery users
group	bindery groups
pserver	bindery print servers
tree	tree name hosted by given server
.Ed
.Pp
Note that if you are not logged in to the specified server,
the list may be incomplete or empty.
.It c
List active NCP connections on the local machine.
.It s Op Ar server
Display
.Tn NetWare
servers known to a given
.Ar server .
If no server is specified, the nearest server will be used.
.It u Ar server
Displays a list of users logged in on a given
.Ar server .
If you are not logged in to the specified server,
the list will be empty.
.It q Ar server Op Ar pattern
Displays bindery queues on a given
.Ar server .
.It v Ar server
Displays mounted volumes on a given
.Ar server .
.El
.Sh IMPLEMENTATION NOTES
This utility is provided mostly for educational purposes.
.Sh FILES
.Bl -tag -width /var/log/wtmp -compact
.It Pa ~/.nwfsrc
keeps description for each connection.
See
.Pa /usr/share/examples/nwclient/dot.nwfsrc
for details.
.El
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 4.0 .
.Sh AUTHORS
.An Boris Popov Aq bp@butya.kz ,
.Aq rbp@chat.ru
.Sh BUGS
Please report any bugs to the author.
