.\" Copyright (c) 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)uname.1	8.3 (Berkeley) 4/8/94
.\"
.Dd "April 8, 1994"
.Dt UNAME 1
.Os
.Sh NAME
.Nm uname
.Nd display information about the system
.Sh SYNOPSIS
.Nm uname
.Op Fl amnrsv
.Sh DESCRIPTION
The
.Nm uname
command writes the name of the operating system implementation to
standard output.
When options are specified, strings representing one or more system
characteristics are written to standard output.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
Behave as though the options
.Fl m ,
.Fl n ,
.Fl r ,
.Fl s ,
and
.Fl v
were specified.
.It Fl m
Write the type of the current hardware platform to standard output.
.It Fl n
Write the name of the system to standard output.
.It Fl r
Write the current release level of the operating system
to standard output.
.It Fl s
Write the name of the operating system implementation to standard output.
.It Fl v
Write the version level of this release of the operating system
to standard output.
.El
.Pp
If the
.Fl a
flag is specified, or multiple flags are specified, all
output is written on a single line, separated by spaces.
.Pp
The
.Nm uname
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr sysctl 3 ,
.Xr uname 3 ,
.Xr sysctl 8
.Sh HISTORY
The
.Nm uname
command appeared in
.Bx 4.4 .
.Sh STANDARDS
The
.Nm uname
command is expected to conform to the
.St -p1003.2
specification.
