# $FreeBSD$

PACKAGE=	tests
FILESGROUPS=	TESTS
TESTSPACKAGE=	${PACKAGE}

ATF_TESTS_SH=	soelim

FILES=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out
FILESDIR=	${TESTSDIR}

.include <bsd.test.mk>
