# $Id: Makefile,v 1.4 2003/08/14 20:07:13 max Exp $
# $FreeBSD: src/usr.bin/bluetooth/bthost/Makefile,v 1.2.24.1 2010/02/10 00:26:20 kensmith Exp $

PROG=		bthost
WARNS?=		2

DPADD=		${LIBBLUETOOTH}
LDADD=		-lbluetooth 

.include <bsd.prog.mk>
