# $FreeBSD: src/sys/modules/netgraph/netflow/Makefile,v 1.1.22.1 2009/04/15 03:14:26 kensmith Exp $
#
# Author: Gleb Smirnoff <glebius@freebsd.org>
#

.PATH: ${.CURDIR}/../../../netgraph/netflow

KMOD=   ng_netflow
SRCS=   ng_netflow.c netflow.c

.include <bsd.kmod.mk>
