# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2007-2022 Intel Corporation
.PATH: ${SRCTOP}/sys/contrib/dev/qat

KMOD= qat_c4xxx_fw

FIRMWS= qat_c4xxx.bin:qat_c4xxx_fw:111 qat_c4xxx_mmp.bin:qat_c4xxx_mmp_fw:111

.include <bsd.kmod.mk>
