# $FreeBSD: src/sys/modules/mac_partition/Makefile,v 1.1.36.1.6.1 2010/12/21 17:09:25 kensmith Exp $

.PATH: ${.CURDIR}/../../security/mac_partition

KMOD=	mac_partition
SRCS=	vnode_if.h \
	mac_partition.c

.include <bsd.kmod.mk>
