# $FreeBSD: src/sys/modules/mac_partition/Makefile,v 1.1.30.1 2008/10/02 02:57:24 kensmith Exp $

.PATH: ${.CURDIR}/../../security/mac_partition

KMOD=	mac_partition
SRCS=	vnode_if.h \
	mac_partition.c

.include <bsd.kmod.mk>
