struct ebpf_probe ebpf_syscall_probe[] = {
	[SYS_syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "syscall",
		.name = "enter",
	}},
	[SYS_exit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "exit",
		.name = "enter",
	}},
	[SYS_fork] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fork",
		.name = "enter",
	}},
	[SYS_read] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "read",
		.name = "enter",
	}},
	[SYS_write] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "write",
		.name = "enter",
	}},
	[SYS_open] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "open",
		.name = "enter",
	}},
	[SYS_close] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "close",
		.name = "enter",
	}},
	[SYS_wait4] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "wait4",
		.name = "enter",
	}},
	[SYS_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "link",
		.name = "enter",
	}},
	[SYS_unlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "unlink",
		.name = "enter",
	}},
	[SYS_chdir] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "chdir",
		.name = "enter",
	}},
	[SYS_fchdir] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fchdir",
		.name = "enter",
	}},
	[SYS_chmod] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "chmod",
		.name = "enter",
	}},
	[SYS_chown] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "chown",
		.name = "enter",
	}},
	[SYS_break] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "break",
		.name = "enter",
	}},
	[SYS_getpid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getpid",
		.name = "enter",
	}},
	[SYS_mount] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mount",
		.name = "enter",
	}},
	[SYS_unmount] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "unmount",
		.name = "enter",
	}},
	[SYS_setuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setuid",
		.name = "enter",
	}},
	[SYS_getuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getuid",
		.name = "enter",
	}},
	[SYS_geteuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "geteuid",
		.name = "enter",
	}},
	[SYS_ptrace] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ptrace",
		.name = "enter",
	}},
	[SYS_recvmsg] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "recvmsg",
		.name = "enter",
	}},
	[SYS_sendmsg] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sendmsg",
		.name = "enter",
	}},
	[SYS_recvfrom] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "recvfrom",
		.name = "enter",
	}},
	[SYS_accept] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "accept",
		.name = "enter",
	}},
	[SYS_getpeername] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getpeername",
		.name = "enter",
	}},
	[SYS_getsockname] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getsockname",
		.name = "enter",
	}},
	[SYS_access] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "access",
		.name = "enter",
	}},
	[SYS_chflags] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "chflags",
		.name = "enter",
	}},
	[SYS_fchflags] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fchflags",
		.name = "enter",
	}},
	[SYS_sync] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sync",
		.name = "enter",
	}},
	[SYS_kill] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kill",
		.name = "enter",
	}},
	[SYS_getppid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getppid",
		.name = "enter",
	}},
	[SYS_dup] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "dup",
		.name = "enter",
	}},
	[SYS_getegid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getegid",
		.name = "enter",
	}},
	[SYS_profil] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "profil",
		.name = "enter",
	}},
	[SYS_ktrace] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ktrace",
		.name = "enter",
	}},
	[SYS_getgid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getgid",
		.name = "enter",
	}},
	[SYS_getlogin] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getlogin",
		.name = "enter",
	}},
	[SYS_setlogin] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setlogin",
		.name = "enter",
	}},
	[SYS_acct] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "acct",
		.name = "enter",
	}},
	[SYS_sigaltstack] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigaltstack",
		.name = "enter",
	}},
	[SYS_ioctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ioctl",
		.name = "enter",
	}},
	[SYS_reboot] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "reboot",
		.name = "enter",
	}},
	[SYS_revoke] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "revoke",
		.name = "enter",
	}},
	[SYS_symlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "symlink",
		.name = "enter",
	}},
	[SYS_readlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "readlink",
		.name = "enter",
	}},
	[SYS_execve] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "execve",
		.name = "enter",
	}},
	[SYS_umask] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "umask",
		.name = "enter",
	}},
	[SYS_chroot] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "chroot",
		.name = "enter",
	}},
	[SYS_msync] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "msync",
		.name = "enter",
	}},
	[SYS_vfork] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "vfork",
		.name = "enter",
	}},
	[SYS_sbrk] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sbrk",
		.name = "enter",
	}},
	[SYS_sstk] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sstk",
		.name = "enter",
	}},
	[SYS_munmap] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "munmap",
		.name = "enter",
	}},
	[SYS_mprotect] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mprotect",
		.name = "enter",
	}},
	[SYS_madvise] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "madvise",
		.name = "enter",
	}},
	[SYS_mincore] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mincore",
		.name = "enter",
	}},
	[SYS_getgroups] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getgroups",
		.name = "enter",
	}},
	[SYS_setgroups] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setgroups",
		.name = "enter",
	}},
	[SYS_getpgrp] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getpgrp",
		.name = "enter",
	}},
	[SYS_setpgid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setpgid",
		.name = "enter",
	}},
	[SYS_setitimer] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setitimer",
		.name = "enter",
	}},
	[SYS_swapon] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "swapon",
		.name = "enter",
	}},
	[SYS_getitimer] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getitimer",
		.name = "enter",
	}},
	[SYS_getdtablesize] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getdtablesize",
		.name = "enter",
	}},
	[SYS_dup2] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "dup2",
		.name = "enter",
	}},
	[SYS_fcntl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fcntl",
		.name = "enter",
	}},
	[SYS_select] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "select",
		.name = "enter",
	}},
	[SYS_fsync] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fsync",
		.name = "enter",
	}},
	[SYS_setpriority] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setpriority",
		.name = "enter",
	}},
	[SYS_socket] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "socket",
		.name = "enter",
	}},
	[SYS_connect] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "connect",
		.name = "enter",
	}},
	[SYS_getpriority] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getpriority",
		.name = "enter",
	}},
	[SYS_bind] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "bind",
		.name = "enter",
	}},
	[SYS_setsockopt] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setsockopt",
		.name = "enter",
	}},
	[SYS_listen] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "listen",
		.name = "enter",
	}},
	[SYS_gettimeofday] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "gettimeofday",
		.name = "enter",
	}},
	[SYS_getrusage] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getrusage",
		.name = "enter",
	}},
	[SYS_getsockopt] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getsockopt",
		.name = "enter",
	}},
	[SYS_readv] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "readv",
		.name = "enter",
	}},
	[SYS_writev] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "writev",
		.name = "enter",
	}},
	[SYS_settimeofday] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "settimeofday",
		.name = "enter",
	}},
	[SYS_fchown] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fchown",
		.name = "enter",
	}},
	[SYS_fchmod] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fchmod",
		.name = "enter",
	}},
	[SYS_setreuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setreuid",
		.name = "enter",
	}},
	[SYS_setregid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setregid",
		.name = "enter",
	}},
	[SYS_rename] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rename",
		.name = "enter",
	}},
	[SYS_flock] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "flock",
		.name = "enter",
	}},
	[SYS_mkfifo] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mkfifo",
		.name = "enter",
	}},
	[SYS_sendto] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sendto",
		.name = "enter",
	}},
	[SYS_shutdown] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shutdown",
		.name = "enter",
	}},
	[SYS_socketpair] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "socketpair",
		.name = "enter",
	}},
	[SYS_mkdir] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mkdir",
		.name = "enter",
	}},
	[SYS_rmdir] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rmdir",
		.name = "enter",
	}},
	[SYS_utimes] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "utimes",
		.name = "enter",
	}},
	[SYS_adjtime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "adjtime",
		.name = "enter",
	}},
	[SYS_setsid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setsid",
		.name = "enter",
	}},
	[SYS_quotactl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "quotactl",
		.name = "enter",
	}},
	[SYS_nlm_syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "nlm_syscall",
		.name = "enter",
	}},
	[SYS_nfssvc] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "nfssvc",
		.name = "enter",
	}},
	[SYS_lgetfh] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lgetfh",
		.name = "enter",
	}},
	[SYS_getfh] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getfh",
		.name = "enter",
	}},
	[SYS_sysarch] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sysarch",
		.name = "enter",
	}},
	[SYS_rtprio] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rtprio",
		.name = "enter",
	}},
	[SYS_semsys] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "semsys",
		.name = "enter",
	}},
	[SYS_msgsys] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "msgsys",
		.name = "enter",
	}},
	[SYS_shmsys] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shmsys",
		.name = "enter",
	}},
	[SYS_setfib] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setfib",
		.name = "enter",
	}},
	[SYS_ntp_adjtime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ntp_adjtime",
		.name = "enter",
	}},
	[SYS_setgid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setgid",
		.name = "enter",
	}},
	[SYS_setegid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setegid",
		.name = "enter",
	}},
	[SYS_seteuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "seteuid",
		.name = "enter",
	}},
	[SYS_pathconf] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pathconf",
		.name = "enter",
	}},
	[SYS_fpathconf] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fpathconf",
		.name = "enter",
	}},
	[SYS_getrlimit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getrlimit",
		.name = "enter",
	}},
	[SYS_setrlimit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setrlimit",
		.name = "enter",
	}},
	[SYS___syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__syscall",
		.name = "enter",
	}},
	[SYS___sysctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__sysctl",
		.name = "enter",
	}},
	[SYS_mlock] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mlock",
		.name = "enter",
	}},
	[SYS_munlock] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "munlock",
		.name = "enter",
	}},
	[SYS_undelete] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "undelete",
		.name = "enter",
	}},
	[SYS_futimes] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "futimes",
		.name = "enter",
	}},
	[SYS_getpgid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getpgid",
		.name = "enter",
	}},
	[SYS_poll] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "poll",
		.name = "enter",
	}},
	[SYS_semget] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "semget",
		.name = "enter",
	}},
	[SYS_semop] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "semop",
		.name = "enter",
	}},
	[SYS_msgget] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "msgget",
		.name = "enter",
	}},
	[SYS_msgsnd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "msgsnd",
		.name = "enter",
	}},
	[SYS_msgrcv] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "msgrcv",
		.name = "enter",
	}},
	[SYS_shmat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shmat",
		.name = "enter",
	}},
	[SYS_shmdt] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shmdt",
		.name = "enter",
	}},
	[SYS_shmget] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shmget",
		.name = "enter",
	}},
	[SYS_clock_gettime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "clock_gettime",
		.name = "enter",
	}},
	[SYS_clock_settime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "clock_settime",
		.name = "enter",
	}},
	[SYS_clock_getres] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "clock_getres",
		.name = "enter",
	}},
	[SYS_ktimer_create] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ktimer_create",
		.name = "enter",
	}},
	[SYS_ktimer_delete] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ktimer_delete",
		.name = "enter",
	}},
	[SYS_ktimer_settime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ktimer_settime",
		.name = "enter",
	}},
	[SYS_ktimer_gettime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ktimer_gettime",
		.name = "enter",
	}},
	[SYS_ktimer_getoverrun] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ktimer_getoverrun",
		.name = "enter",
	}},
	[SYS_nanosleep] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "nanosleep",
		.name = "enter",
	}},
	[SYS_ffclock_getcounter] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ffclock_getcounter",
		.name = "enter",
	}},
	[SYS_ffclock_setestimate] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ffclock_setestimate",
		.name = "enter",
	}},
	[SYS_ffclock_getestimate] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ffclock_getestimate",
		.name = "enter",
	}},
	[SYS_clock_nanosleep] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "clock_nanosleep",
		.name = "enter",
	}},
	[SYS_clock_getcpuclockid2] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "clock_getcpuclockid2",
		.name = "enter",
	}},
	[SYS_ntp_gettime] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ntp_gettime",
		.name = "enter",
	}},
	[SYS_minherit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "minherit",
		.name = "enter",
	}},
	[SYS_rfork] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rfork",
		.name = "enter",
	}},
	[SYS_issetugid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "issetugid",
		.name = "enter",
	}},
	[SYS_lchown] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lchown",
		.name = "enter",
	}},
	[SYS_aio_read] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_read",
		.name = "enter",
	}},
	[SYS_aio_write] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_write",
		.name = "enter",
	}},
	[SYS_lio_listio] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lio_listio",
		.name = "enter",
	}},
	[SYS_lchmod] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lchmod",
		.name = "enter",
	}},
	[SYS_lutimes] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lutimes",
		.name = "enter",
	}},
	[SYS_preadv] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "preadv",
		.name = "enter",
	}},
	[SYS_pwritev] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pwritev",
		.name = "enter",
	}},
	[SYS_fhopen] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fhopen",
		.name = "enter",
	}},
	[SYS_modnext] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "modnext",
		.name = "enter",
	}},
	[SYS_modstat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "modstat",
		.name = "enter",
	}},
	[SYS_modfnext] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "modfnext",
		.name = "enter",
	}},
	[SYS_modfind] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "modfind",
		.name = "enter",
	}},
	[SYS_kldload] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldload",
		.name = "enter",
	}},
	[SYS_kldunload] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldunload",
		.name = "enter",
	}},
	[SYS_kldfind] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldfind",
		.name = "enter",
	}},
	[SYS_kldnext] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldnext",
		.name = "enter",
	}},
	[SYS_kldstat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldstat",
		.name = "enter",
	}},
	[SYS_kldfirstmod] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldfirstmod",
		.name = "enter",
	}},
	[SYS_getsid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getsid",
		.name = "enter",
	}},
	[SYS_setresuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setresuid",
		.name = "enter",
	}},
	[SYS_setresgid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setresgid",
		.name = "enter",
	}},
	[SYS_aio_return] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_return",
		.name = "enter",
	}},
	[SYS_aio_suspend] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_suspend",
		.name = "enter",
	}},
	[SYS_aio_cancel] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_cancel",
		.name = "enter",
	}},
	[SYS_aio_error] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_error",
		.name = "enter",
	}},
	[SYS_yield] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "yield",
		.name = "enter",
	}},
	[SYS_mlockall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mlockall",
		.name = "enter",
	}},
	[SYS_munlockall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "munlockall",
		.name = "enter",
	}},
	[SYS___getcwd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__getcwd",
		.name = "enter",
	}},
	[SYS_sched_setparam] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_setparam",
		.name = "enter",
	}},
	[SYS_sched_getparam] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_getparam",
		.name = "enter",
	}},
	[SYS_sched_setscheduler] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_setscheduler",
		.name = "enter",
	}},
	[SYS_sched_getscheduler] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_getscheduler",
		.name = "enter",
	}},
	[SYS_sched_yield] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_yield",
		.name = "enter",
	}},
	[SYS_sched_get_priority_max] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_get_priority_max",
		.name = "enter",
	}},
	[SYS_sched_get_priority_min] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_get_priority_min",
		.name = "enter",
	}},
	[SYS_sched_rr_get_interval] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sched_rr_get_interval",
		.name = "enter",
	}},
	[SYS_utrace] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "utrace",
		.name = "enter",
	}},
	[SYS_kldsym] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldsym",
		.name = "enter",
	}},
	[SYS_jail] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "jail",
		.name = "enter",
	}},
	[SYS_nnpfs_syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "nnpfs_syscall",
		.name = "enter",
	}},
	[SYS_sigprocmask] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigprocmask",
		.name = "enter",
	}},
	[SYS_sigsuspend] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigsuspend",
		.name = "enter",
	}},
	[SYS_sigpending] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigpending",
		.name = "enter",
	}},
	[SYS_sigtimedwait] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigtimedwait",
		.name = "enter",
	}},
	[SYS_sigwaitinfo] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigwaitinfo",
		.name = "enter",
	}},
	[SYS___acl_get_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_get_file",
		.name = "enter",
	}},
	[SYS___acl_set_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_set_file",
		.name = "enter",
	}},
	[SYS___acl_get_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_get_fd",
		.name = "enter",
	}},
	[SYS___acl_set_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_set_fd",
		.name = "enter",
	}},
	[SYS___acl_delete_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_delete_file",
		.name = "enter",
	}},
	[SYS___acl_delete_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_delete_fd",
		.name = "enter",
	}},
	[SYS___acl_aclcheck_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_aclcheck_file",
		.name = "enter",
	}},
	[SYS___acl_aclcheck_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_aclcheck_fd",
		.name = "enter",
	}},
	[SYS_extattrctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattrctl",
		.name = "enter",
	}},
	[SYS_extattr_set_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_set_file",
		.name = "enter",
	}},
	[SYS_extattr_get_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_get_file",
		.name = "enter",
	}},
	[SYS_extattr_delete_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_delete_file",
		.name = "enter",
	}},
	[SYS_aio_waitcomplete] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_waitcomplete",
		.name = "enter",
	}},
	[SYS_getresuid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getresuid",
		.name = "enter",
	}},
	[SYS_getresgid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getresgid",
		.name = "enter",
	}},
	[SYS_kqueue] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kqueue",
		.name = "enter",
	}},
	[SYS_extattr_set_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_set_fd",
		.name = "enter",
	}},
	[SYS_extattr_get_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_get_fd",
		.name = "enter",
	}},
	[SYS_extattr_delete_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_delete_fd",
		.name = "enter",
	}},
	[SYS___setugid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__setugid",
		.name = "enter",
	}},
	[SYS_eaccess] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "eaccess",
		.name = "enter",
	}},
	[SYS_afs3_syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "afs3_syscall",
		.name = "enter",
	}},
	[SYS_nmount] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "nmount",
		.name = "enter",
	}},
	[SYS___mac_get_proc] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_get_proc",
		.name = "enter",
	}},
	[SYS___mac_set_proc] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_set_proc",
		.name = "enter",
	}},
	[SYS___mac_get_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_get_fd",
		.name = "enter",
	}},
	[SYS___mac_get_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_get_file",
		.name = "enter",
	}},
	[SYS___mac_set_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_set_fd",
		.name = "enter",
	}},
	[SYS___mac_set_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_set_file",
		.name = "enter",
	}},
	[SYS_kenv] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kenv",
		.name = "enter",
	}},
	[SYS_lchflags] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lchflags",
		.name = "enter",
	}},
	[SYS_uuidgen] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "uuidgen",
		.name = "enter",
	}},
	[SYS_sendfile] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sendfile",
		.name = "enter",
	}},
	[SYS_mac_syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mac_syscall",
		.name = "enter",
	}},
	[SYS_ksem_close] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_close",
		.name = "enter",
	}},
	[SYS_ksem_post] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_post",
		.name = "enter",
	}},
	[SYS_ksem_wait] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_wait",
		.name = "enter",
	}},
	[SYS_ksem_trywait] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_trywait",
		.name = "enter",
	}},
	[SYS_ksem_init] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_init",
		.name = "enter",
	}},
	[SYS_ksem_open] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_open",
		.name = "enter",
	}},
	[SYS_ksem_unlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_unlink",
		.name = "enter",
	}},
	[SYS_ksem_getvalue] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_getvalue",
		.name = "enter",
	}},
	[SYS_ksem_destroy] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_destroy",
		.name = "enter",
	}},
	[SYS___mac_get_pid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_get_pid",
		.name = "enter",
	}},
	[SYS___mac_get_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_get_link",
		.name = "enter",
	}},
	[SYS___mac_set_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_set_link",
		.name = "enter",
	}},
	[SYS_extattr_set_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_set_link",
		.name = "enter",
	}},
	[SYS_extattr_get_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_get_link",
		.name = "enter",
	}},
	[SYS_extattr_delete_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_delete_link",
		.name = "enter",
	}},
	[SYS___mac_execve] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__mac_execve",
		.name = "enter",
	}},
	[SYS_sigaction] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigaction",
		.name = "enter",
	}},
	[SYS_sigreturn] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigreturn",
		.name = "enter",
	}},
	[SYS_getcontext] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getcontext",
		.name = "enter",
	}},
	[SYS_setcontext] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setcontext",
		.name = "enter",
	}},
	[SYS_swapcontext] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "swapcontext",
		.name = "enter",
	}},
	[SYS_swapoff] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "swapoff",
		.name = "enter",
	}},
	[SYS___acl_get_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_get_link",
		.name = "enter",
	}},
	[SYS___acl_set_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_set_link",
		.name = "enter",
	}},
	[SYS___acl_delete_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_delete_link",
		.name = "enter",
	}},
	[SYS___acl_aclcheck_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__acl_aclcheck_link",
		.name = "enter",
	}},
	[SYS_sigwait] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigwait",
		.name = "enter",
	}},
	[SYS_thr_create] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_create",
		.name = "enter",
	}},
	[SYS_thr_exit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_exit",
		.name = "enter",
	}},
	[SYS_thr_self] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_self",
		.name = "enter",
	}},
	[SYS_thr_kill] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_kill",
		.name = "enter",
	}},
	[SYS_jail_attach] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "jail_attach",
		.name = "enter",
	}},
	[SYS_extattr_list_fd] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_list_fd",
		.name = "enter",
	}},
	[SYS_extattr_list_file] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_list_file",
		.name = "enter",
	}},
	[SYS_extattr_list_link] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "extattr_list_link",
		.name = "enter",
	}},
	[SYS_ksem_timedwait] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ksem_timedwait",
		.name = "enter",
	}},
	[SYS_thr_suspend] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_suspend",
		.name = "enter",
	}},
	[SYS_thr_wake] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_wake",
		.name = "enter",
	}},
	[SYS_kldunloadf] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kldunloadf",
		.name = "enter",
	}},
	[SYS_audit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "audit",
		.name = "enter",
	}},
	[SYS_auditon] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "auditon",
		.name = "enter",
	}},
	[SYS_getauid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getauid",
		.name = "enter",
	}},
	[SYS_setauid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setauid",
		.name = "enter",
	}},
	[SYS_getaudit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getaudit",
		.name = "enter",
	}},
	[SYS_setaudit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setaudit",
		.name = "enter",
	}},
	[SYS_getaudit_addr] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getaudit_addr",
		.name = "enter",
	}},
	[SYS_setaudit_addr] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setaudit_addr",
		.name = "enter",
	}},
	[SYS_auditctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "auditctl",
		.name = "enter",
	}},
	[SYS__umtx_op] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "_umtx_op",
		.name = "enter",
	}},
	[SYS_thr_new] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_new",
		.name = "enter",
	}},
	[SYS_sigqueue] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigqueue",
		.name = "enter",
	}},
	[SYS_kmq_open] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kmq_open",
		.name = "enter",
	}},
	[SYS_kmq_setattr] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kmq_setattr",
		.name = "enter",
	}},
	[SYS_kmq_timedreceive] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kmq_timedreceive",
		.name = "enter",
	}},
	[SYS_kmq_timedsend] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kmq_timedsend",
		.name = "enter",
	}},
	[SYS_kmq_notify] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kmq_notify",
		.name = "enter",
	}},
	[SYS_kmq_unlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kmq_unlink",
		.name = "enter",
	}},
	[SYS_abort2] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "abort2",
		.name = "enter",
	}},
	[SYS_thr_set_name] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_set_name",
		.name = "enter",
	}},
	[SYS_aio_fsync] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_fsync",
		.name = "enter",
	}},
	[SYS_rtprio_thread] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rtprio_thread",
		.name = "enter",
	}},
	[SYS_sctp_peeloff] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sctp_peeloff",
		.name = "enter",
	}},
	[SYS_sctp_generic_sendmsg] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sctp_generic_sendmsg",
		.name = "enter",
	}},
	[SYS_sctp_generic_sendmsg_iov] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sctp_generic_sendmsg_iov",
		.name = "enter",
	}},
	[SYS_sctp_generic_recvmsg] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sctp_generic_recvmsg",
		.name = "enter",
	}},
	[SYS_pread] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pread",
		.name = "enter",
	}},
	[SYS_pwrite] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pwrite",
		.name = "enter",
	}},
	[SYS_mmap] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mmap",
		.name = "enter",
	}},
	[SYS_lseek] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lseek",
		.name = "enter",
	}},
	[SYS_truncate] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "truncate",
		.name = "enter",
	}},
	[SYS_ftruncate] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ftruncate",
		.name = "enter",
	}},
	[SYS_thr_kill2] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "thr_kill2",
		.name = "enter",
	}},
	[SYS_shm_unlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shm_unlink",
		.name = "enter",
	}},
	[SYS_cpuset] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset",
		.name = "enter",
	}},
	[SYS_cpuset_setid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset_setid",
		.name = "enter",
	}},
	[SYS_cpuset_getid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset_getid",
		.name = "enter",
	}},
	[SYS_cpuset_getaffinity] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset_getaffinity",
		.name = "enter",
	}},
	[SYS_cpuset_setaffinity] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset_setaffinity",
		.name = "enter",
	}},
	[SYS_faccessat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "faccessat",
		.name = "enter",
	}},
	[SYS_fchmodat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fchmodat",
		.name = "enter",
	}},
	[SYS_fchownat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fchownat",
		.name = "enter",
	}},
	[SYS_fexecve] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fexecve",
		.name = "enter",
	}},
	[SYS_futimesat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "futimesat",
		.name = "enter",
	}},
	[SYS_linkat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "linkat",
		.name = "enter",
	}},
	[SYS_mkdirat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mkdirat",
		.name = "enter",
	}},
	[SYS_mkfifoat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mkfifoat",
		.name = "enter",
	}},
	[SYS_openat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "openat",
		.name = "enter",
	}},
	[SYS_readlinkat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "readlinkat",
		.name = "enter",
	}},
	[SYS_renameat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "renameat",
		.name = "enter",
	}},
	[SYS_symlinkat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "symlinkat",
		.name = "enter",
	}},
	[SYS_unlinkat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "unlinkat",
		.name = "enter",
	}},
	[SYS_posix_openpt] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "posix_openpt",
		.name = "enter",
	}},
	[SYS_gssd_syscall] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "gssd_syscall",
		.name = "enter",
	}},
	[SYS_jail_get] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "jail_get",
		.name = "enter",
	}},
	[SYS_jail_set] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "jail_set",
		.name = "enter",
	}},
	[SYS_jail_remove] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "jail_remove",
		.name = "enter",
	}},
	[SYS_closefrom] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "closefrom",
		.name = "enter",
	}},
	[SYS___semctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__semctl",
		.name = "enter",
	}},
	[SYS_msgctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "msgctl",
		.name = "enter",
	}},
	[SYS_shmctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shmctl",
		.name = "enter",
	}},
	[SYS_lpathconf] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "lpathconf",
		.name = "enter",
	}},
	[SYS___cap_rights_get] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__cap_rights_get",
		.name = "enter",
	}},
	[SYS_cap_enter] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_enter",
		.name = "enter",
	}},
	[SYS_cap_getmode] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_getmode",
		.name = "enter",
	}},
	[SYS_pdfork] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pdfork",
		.name = "enter",
	}},
	[SYS_pdkill] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pdkill",
		.name = "enter",
	}},
	[SYS_pdgetpid] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pdgetpid",
		.name = "enter",
	}},
	[SYS_pdwait4] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pdwait4",
		.name = "enter",
	}},
	[SYS_pselect] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pselect",
		.name = "enter",
	}},
	[SYS_getloginclass] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getloginclass",
		.name = "enter",
	}},
	[SYS_setloginclass] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "setloginclass",
		.name = "enter",
	}},
	[SYS_rctl_get_racct] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rctl_get_racct",
		.name = "enter",
	}},
	[SYS_rctl_get_rules] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rctl_get_rules",
		.name = "enter",
	}},
	[SYS_rctl_get_limits] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rctl_get_limits",
		.name = "enter",
	}},
	[SYS_rctl_add_rule] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rctl_add_rule",
		.name = "enter",
	}},
	[SYS_rctl_remove_rule] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "rctl_remove_rule",
		.name = "enter",
	}},
	[SYS_posix_fallocate] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "posix_fallocate",
		.name = "enter",
	}},
	[SYS_posix_fadvise] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "posix_fadvise",
		.name = "enter",
	}},
	[SYS_wait6] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "wait6",
		.name = "enter",
	}},
	[SYS_cap_rights_limit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_rights_limit",
		.name = "enter",
	}},
	[SYS_cap_ioctls_limit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_ioctls_limit",
		.name = "enter",
	}},
	[SYS_cap_ioctls_get] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_ioctls_get",
		.name = "enter",
	}},
	[SYS_cap_fcntls_limit] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_fcntls_limit",
		.name = "enter",
	}},
	[SYS_cap_fcntls_get] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cap_fcntls_get",
		.name = "enter",
	}},
	[SYS_bindat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "bindat",
		.name = "enter",
	}},
	[SYS_connectat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "connectat",
		.name = "enter",
	}},
	[SYS_chflagsat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "chflagsat",
		.name = "enter",
	}},
	[SYS_accept4] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "accept4",
		.name = "enter",
	}},
	[SYS_pipe2] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "pipe2",
		.name = "enter",
	}},
	[SYS_aio_mlock] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "aio_mlock",
		.name = "enter",
	}},
	[SYS_procctl] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "procctl",
		.name = "enter",
	}},
	[SYS_ppoll] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "ppoll",
		.name = "enter",
	}},
	[SYS_futimens] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "futimens",
		.name = "enter",
	}},
	[SYS_utimensat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "utimensat",
		.name = "enter",
	}},
	[SYS_fdatasync] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fdatasync",
		.name = "enter",
	}},
	[SYS_fstat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fstat",
		.name = "enter",
	}},
	[SYS_fstatat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fstatat",
		.name = "enter",
	}},
	[SYS_fhstat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fhstat",
		.name = "enter",
	}},
	[SYS_getdirentries] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getdirentries",
		.name = "enter",
	}},
	[SYS_statfs] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "statfs",
		.name = "enter",
	}},
	[SYS_fstatfs] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fstatfs",
		.name = "enter",
	}},
	[SYS_getfsstat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getfsstat",
		.name = "enter",
	}},
	[SYS_fhstatfs] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fhstatfs",
		.name = "enter",
	}},
	[SYS_mknodat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "mknodat",
		.name = "enter",
	}},
	[SYS_kevent] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "kevent",
		.name = "enter",
	}},
	[SYS_cpuset_getdomain] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset_getdomain",
		.name = "enter",
	}},
	[SYS_cpuset_setdomain] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "cpuset_setdomain",
		.name = "enter",
	}},
	[SYS_getrandom] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getrandom",
		.name = "enter",
	}},
	[SYS_getfhat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "getfhat",
		.name = "enter",
	}},
	[SYS_fhlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fhlink",
		.name = "enter",
	}},
	[SYS_fhlinkat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fhlinkat",
		.name = "enter",
	}},
	[SYS_fhreadlink] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "fhreadlink",
		.name = "enter",
	}},
	[SYS_funlinkat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "funlinkat",
		.name = "enter",
	}},
	[SYS_copy_file_range] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "copy_file_range",
		.name = "enter",
	}},
	[SYS___sysctlbyname] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__sysctlbyname",
		.name = "enter",
	}},
	[SYS_shm_open2] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shm_open2",
		.name = "enter",
	}},
	[SYS_shm_rename] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "shm_rename",
		.name = "enter",
	}},
	[SYS_sigfastblock] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "sigfastblock",
		.name = "enter",
	}},
	[SYS___realpathat] = { .name = {
		.tracer = "ebpf",
		.provider = "sc_rewrite",
		.module = "",
		.function = "__realpathat",
		.name = "enter",
	}},
};
