#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/shutdown/Makefile,v 1.9 2005/01/25 08:37:04 delphij Exp $

PROG=	shutdown
MAN=	shutdown.8

WARNS?=	6

BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
