# $FreeBSD: src/usr.sbin/bluetooth/ath3kfw/Makefile,v 1.1.2.2.4.1 2012/03/03 06:15:13 kensmith Exp $

PROG=		ath3kfw
MAN=		ath3kfw.8
WARNS?=		6
DPADD+=		${LIBUSB}
LDADD+=		-lusb

.include <bsd.prog.mk>
