#	From: @(#)Makefile	1.4 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/newvm/Makefile,v 1.6.34.1 2009/04/15 03:14:26 kensmith Exp $

VOLUME=	papers
DOC=	newvm
SRCS=	0.t 1.t a.t
MACROS=	-ms

.include <bsd.doc.mk>
