# $FreeBSD: src/release/doc/ja_JP.eucJP/Makefile,v 1.5.22.1.2.1 2009/10/25 01:10:29 kensmith Exp $
# Original revision: 1.7

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
#SUBDIR+= readme
SUBDIR+= errata
#SUBDIR+= installation

COMPAT_SYMLINK = ja

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
