.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 1999 Sheldon Hearn
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd December 16, 2025
.Dt BUILTIN 1
.Os
.Sh NAME
.Nm builtin ,
.Nm keybinds
.Nd index of FreeBSD shell built-in commands
.Sh SYNOPSIS
See the manual for your shell for operation details.
.Sh DESCRIPTION
This page provides an index of
.Nm
commands, keywords, and keyboard bindings provided by
.Xr csh 1
and
.Xr sh 1 ,
the command line interpreters which comprise the
.Bx
user environment.
.Ss Commands
Below is a table which lists
.Nm
commands and keywords,
whether they exist as standalone utilities,
and the standard shells that provide them.
.Bl -column "uncomplete" "Standalone" "csh(1)" "sh(1)" -offset indent
.It Em Command Ta Em Standalone Ta Xr csh 1 Ta Xr sh 1
.It Ic \&! Ta \&No Ta \&No Ta Yes
.It Ic % Ta \&No Ta Yes Ta \&No
.It Ic \&. Ta \&No Ta \&No Ta Yes
.It Ic \&: Ta \&No Ta Yes Ta Yes
.It Ic @ Ta \&No Ta Yes Ta \&No
.It Ic \&[ Ta Yes Ta \&No Ta Yes
.It Ic { Ta \&No Ta \&No Ta Yes
.It Ic } Ta \&No Ta \&No Ta Yes
.It Ic alias Ta \&No Ta Yes Ta Yes
.It Ic alloc Ta \&No Ta Yes Ta \&No
.It Ic bg Ta \&No Ta Yes Ta Yes
.It Ic bind Ta \&No Ta \&No Ta Yes
.It Ic bindkey Ta \&No Ta Yes Ta \&No
.It Ic break Ta \&No Ta Yes Ta Yes
.It Ic breaksw Ta \&No Ta Yes Ta \&No
.It Ic builtin Ta \&No Ta \&No Ta Yes
.It Ic builtins Ta \&No Ta Yes Ta \&No
.It Ic case Ta \&No Ta Yes Ta Yes
.It Ic cd Ta \&No Ta Yes Ta Yes
.It Ic chdir Ta \&No Ta Yes Ta Yes
.It Ic command Ta \&No Ta \&No Ta Yes
.It Ic complete Ta \&No Ta Yes Ta \&No
.It Ic continue Ta \&No Ta Yes Ta Yes
.It Ic default Ta \&No Ta Yes Ta \&No
.It Ic dirs Ta \&No Ta Yes Ta \&No
.It Ic do Ta \&No Ta \&No Ta Yes
.It Ic done Ta \&No Ta \&No Ta Yes
.It Ic echo Ta Yes Ta Yes Ta Yes
.It Ic echotc Ta \&No Ta Yes Ta \&No
.It Ic elif Ta \&No Ta \&No Ta Yes
.It Ic else Ta \&No Ta Yes Ta Yes
.It Ic end Ta \&No Ta Yes Ta \&No
.It Ic endif Ta \&No Ta Yes Ta \&No
.It Ic endsw Ta \&No Ta Yes Ta \&No
.It Ic esac Ta \&No Ta \&No Ta Yes
.It Ic eval Ta \&No Ta Yes Ta Yes
.It Ic exec Ta \&No Ta Yes Ta Yes
.It Ic exit Ta \&No Ta Yes Ta Yes
.It Ic export Ta \&No Ta \&No Ta Yes
.It Ic false Ta Yes Ta \&No Ta Yes
.It Ic fc Ta \&No Ta \&No Ta Yes
.It Ic fg Ta \&No Ta Yes Ta Yes
.It Ic filetest Ta \&No Ta Yes Ta \&No
.It Ic fi Ta \&No Ta \&No Ta Yes
.It Ic for Ta \&No Ta \&No Ta Yes
.It Ic foreach Ta \&No Ta Yes Ta \&No
.It Ic getopts Ta \&No Ta \&No Ta Yes
.It Ic glob Ta \&No Ta Yes Ta \&No
.It Ic goto Ta \&No Ta Yes Ta \&No
.It Ic hash Ta \&No Ta \&No Ta Yes
.It Ic hashstat Ta \&No Ta Yes Ta \&No
.It Ic history Ta \&No Ta Yes Ta \&No
.It Ic hup Ta \&No Ta Yes Ta \&No
.It Ic if Ta \&No Ta Yes Ta Yes
.It Ic jobid Ta \&No Ta \&No Ta Yes
.It Ic jobs Ta \&No Ta Yes Ta Yes
.It Ic kill Ta Yes Ta Yes Ta Yes
.It Ic limit Ta \&No Ta Yes Ta \&No
.It Ic local Ta \&No Ta \&No Ta Yes
.It Ic log Ta \&No Ta Yes Ta \&No
.It Ic login Ta Yes Ta Yes Ta \&No
.It Ic logout Ta \&No Ta Yes Ta \&No
.It Ic ls-F Ta \&No Ta Yes Ta \&No
.It Ic nice Ta Yes Ta Yes Ta \&No
.It Ic nohup Ta Yes Ta Yes Ta \&No
.It Ic notify Ta \&No Ta Yes Ta \&No
.It Ic onintr Ta \&No Ta Yes Ta \&No
.It Ic popd Ta \&No Ta Yes Ta \&No
.It Ic printenv Ta Yes Ta Yes Ta \&No
.It Ic printf Ta Yes Ta \&No Ta Yes
.It Ic pushd Ta \&No Ta Yes Ta \&No
.It Ic pwd Ta Yes Ta \&No Ta Yes
.It Ic read Ta \&No Ta \&No Ta Yes
.It Ic readonly Ta \&No Ta \&No Ta Yes
.It Ic rehash Ta \&No Ta Yes Ta \&No
.It Ic repeat Ta \&No Ta Yes Ta \&No
.It Ic return Ta \&No Ta \&No Ta Yes
.It Ic sched Ta \&No Ta Yes Ta \&No
.It Ic set Ta \&No Ta Yes Ta Yes
.It Ic setenv Ta \&No Ta Yes Ta \&No
.It Ic settc Ta \&No Ta Yes Ta \&No
.It Ic setty Ta \&No Ta Yes Ta \&No
.It Ic setvar Ta \&No Ta \&No Ta Yes
.It Ic shift Ta \&No Ta Yes Ta Yes
.It Ic source Ta \&No Ta Yes Ta \&No
.It Ic stop Ta \&No Ta Yes Ta \&No
.It Ic suspend Ta \&No Ta Yes Ta \&No
.It Ic switch Ta \&No Ta Yes Ta \&No
.It Ic telltc Ta \&No Ta Yes Ta \&No
.It Ic test Ta Yes Ta \&No Ta Yes
.It Ic then Ta \&No Ta \&No Ta Yes
.It Ic time Ta Yes Ta Yes Ta \&No
.It Ic times Ta \&No Ta \&No Ta Yes
.It Ic trap Ta \&No Ta \&No Ta Yes
.It Ic true Ta Yes Ta \&No Ta Yes
.It Ic type Ta \&No Ta \&No Ta Yes
.It Ic ulimit Ta \&No Ta \&No Ta Yes
.It Ic umask Ta \&No Ta Yes Ta Yes
.It Ic unalias Ta \&No Ta Yes Ta Yes
.It Ic uncomplete Ta \&No Ta Yes Ta \&No
.It Ic unhash Ta \&No Ta Yes Ta \&No
.It Ic unlimit Ta \&No Ta Yes Ta \&No
.It Ic unset Ta \&No Ta Yes Ta Yes
.It Ic unsetenv Ta \&No Ta Yes Ta \&No
.It Ic until Ta \&No Ta \&No Ta Yes
.It Ic wait Ta \&No Ta Yes Ta Yes
.It Ic where Ta \&No Ta Yes Ta \&No
.It Ic which Ta Yes Ta Yes Ta \&No
.It Ic while Ta \&No Ta Yes Ta Yes
.El
.Ss Keybinds
The command line environment also provides the following
default keyboard bindings:
.Bl -column "Process Info (SIGINFO)" "^M | ^J" "^M | ^J" -offset indent
.It Em Signal Ta Xr csh 1 Ta Xr sh 1
.It Ic Backspace Ta ^H Ta ^H
.It Ic Carriage Return Ta ^M | ^J Ta ^M | ^J
.It Ic Tab Ta ^I Ta ^I
.It Ic Beginning of Line Ta ^A Ta ^A
.It Ic End of Line Ta ^E Ta ^E
.It Ic Cursor Forward Ta ^F Ta ^F
.It Ic Cursor Backward Ta ^B Ta ^B
.It Ic Clear Screen Ta ^L Ta ^L
.It Ic Cut Line Ta ^U Ta ^U
.It Ic Cut Word Backwards Ta ^W Ta ^W
.It Ic Cut Rest of Line Ta ^K Ta ^K
.It Ic Paste Last Cut Ta ^Y Ta ^Y
.It Ic Typo Ta ^T Ta ^T
.It End of File Po Ic EOF Pc Ta ^D Ta ^D
.It Interupt Po Ic SIGINT Pc Ta ^C Ta ^C
.It Process info Po Ic SIGINFO Pc Ta ^T Ta ^T
.It Ic Search History Ta \&No Ta ^R
.It Ic Exit Search History Ta \&No Ta ^G
.It Ic Previous Command Ta ^P Ta ^P
.It Ic Next Command Ta ^N Ta ^N
.It Ic Print Next Character Ta ^V Ta ^V
.It Ic Pause Job Ta ^S Ta ^S
.It Ic Resume Job Ta ^Q Ta ^Q
.It Suspend Job Ic (SIGTSTP) Ta ^Z Ta ^Z
.It Ic Scrollback Mode Ta ScrLk* Ta ScrLk*
.El
.Pp
\&*: Bindings marked
.Ql *
are provided by
.Xr vt 4 ,
the console driver.
.Sh SEE ALSO
.Xr csh 1 ,
.Xr echo 1 ,
.Xr false 1 ,
.Xr kill 1 ,
.Xr login 1 ,
.Xr nice 1 ,
.Xr nohup 1 ,
.Xr printenv 1 ,
.Xr printf 1 ,
.Xr pwd 1 ,
.Xr sh 1 ,
.Xr test 1 ,
.Xr time 1 ,
.Xr true 1 ,
.Xr which 1
.Sh HISTORY
The
.Nm
manual page first appeared in
.Fx 3.4 .
.Sh AUTHORS
.An -nosplit
This manual page was written by
.An Alexander Ziaee Aq Mt ziaee@FreeBSD.org
from an earlier version by
.An Sheldon Hearn Aq Mt sheldonh@FreeBSD.org .
.Sh CAVEATS
While
.Nm
commands may exist in more than one shell or standalone,
each may be implemented differently.
.Pp
Standalone utilities and their manuals must be called by their path
from a shell with a
.Nm
command of the same name.
