# $FreeBSD: src/tools/tools/net80211/wesside/wesside/Makefile,v 1.2.6.1 2008/11/25 02:59:29 kensmith Exp $

PROG=	wesside
BINDIR=	/usr/local/bin
DPADD=	${LIBZ}
LDADD=	-lz
CFLAGS=-g
NO_MAN=
SRCS=wesside.c aircrack-ptw-lib.c

.include <bsd.prog.mk>
