#! /sbin/sh
########
#  Product: IP Filter
#  Fileset: IPF-ALL
#  preremove
########
#
# (c) Copyright (C) 2012 by Darren Reed.
#
########

########
# Source control script environment
########

UTILS="/usr/lbin/sw/control_utils"
if [[ ! -f $UTILS ]] ; then
    echo "ERROR: Cannot find $UTILS"
    exit 1
fi
. $UTILS
exitval=$SUCCESS

########
# Kill off inetd first
########

kmadmin -U ipf
exit $exitval
