#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
#	$Id: Makefile,v 1.3 1995/02/19 09:11:30 rgrimes Exp $

.if exists(${.CURDIR}/../../../../games)
VOLUME=	usd/30.rogue
SRCS=	rogue.me
MACROS=	-me
SRCDIR=	${.CURDIR}/../../../../games/rogue/USD.doc
USE_TBL=	yes

.include <bsd.doc.mk>
.else
depend:

obj:

all:

install:

distribute:

clean:

cleandir:

.endif
