#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/usd/30.rogue/Makefile,v 1.8.2.1 2002/07/24 12:48:41 ru Exp $

VOLUME=	usd/30.rogue
SRCS=	rogue.me
MACROS=	-me
SRCDIR=	${.CURDIR}/../../../../games/rogue/USD.doc
USE_TBL=	yes

.include <bsd.doc.mk>
