# 	This file is under a "BSD" copyright (c) by David O'Brien 1998.

# $FreeBSD: src/usr.sbin/amd/doc/Makefile,v 1.8.2.2 1999/08/29 15:39:10 peter Exp $

.PATH: ${.CURDIR}/../../../contrib/amd/doc

INFO=	am-utils

INFOSECTION=	"AMD Documentation"
INFOENTRY= 	"* Am-utils: (am-utils).	The Amd automounter suite of utilities"

MAKEINFOFLAGS+=	-I ${.CURDIR}/../../../contrib/amd/doc

.include <bsd.info.mk>
