#!/bin/sh
#-
# Copyright (c) 2012-2013 Devin Teske
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#
############################################################ INCLUDES

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1
f_dprintf "%s: loading includes..." "$0"
f_include $BSDCFG_SHARE/dialog.subr
f_include $BSDCFG_SHARE/mustberoot.subr

BSDCFG_LIBE="/usr/libexec/bsdconfig" APP_DIR="080.console"
f_include_lang $BSDCFG_LIBE/$APP_DIR/include/messages.subr

ipgm=$( f_index_menusel_keyword $BSDCFG_LIBE/$APP_DIR/INDEX "$pgm" )
[ $? -eq $SUCCESS -a "$ipgm" ] && pgm="$ipgm"

############################################################ FUNCTIONS

# dialog_menu_main
#
# Display the dialog(1)-based application main menu.
#
dialog_menu_main()
{
	local menu_list size
	local hline="$hline_configure_system_console_settings"
	local prompt="$msg_console_menu_text"

	menu_list="
		'X $msg_exit'      '$msg_exit_this_menu'
		'2 $msg_font'      '$msg_choose_alternate_screen_font'
		'3 $msg_keymap'    '$msg_choose_alternate_keyboard_map'
		'4 $msg_repeat'    '$msg_set_repeat_rate'
		'5 $msg_saver'     '$msg_configure_screen_saver'
		'6 $msg_screenmap' '$msg_choose_alternate_screenmap'
		'7 $msg_ttys'      '$msg_choose_console_terminal_type'
	" # END-QUOTE

	size=$( eval f_dialog_menu_size \
	        	\"\$DIALOG_TITLE\"     \
	        	\"\$DIALOG_BACKTITLE\" \
	                \"\$prompt\"           \
	        	\"\$hline\"            \
	        	$menu_list             )

	local dialog_menu
	dialog_menu=$( eval $DIALOG \
		--title \"\$DIALOG_TITLE\"          \
		--backtitle \"\$DIALOG_BACKTITLE\"  \
		--hline \"\$hline\"                 \
		--ok-label \"\$msg_ok\"             \
		--cancel-label \"\$msg_cancel\"     \
		--default-item \"\$DEFAULTITEM_$$\" \
		--menu \"\$prompt\" $size           \
		$menu_list                          \
		2>&1 >&$DIALOG_TERMINAL_PASSTHRU_FD
	)
	local retval=$?
	setvar DEFAULTITEM_$$ "$dialog_menu"
	setvar DIALOG_MENU_$$ "$dialog_menu"
	return $retval
}

############################################################ MAIN

# Incorporate rc-file if it exists
[ -f "$HOME/.bsdconfigrc" ] && f_include "$HOME/.bsdconfigrc"

#
# Process command-line arguments
#
while getopts dD:hSX flag; do
	case "$flag" in
	h|\?) f_usage $BSDCFG_LIBE/$APP_DIR/USAGE "PROGRAM_NAME" "$pgm";;
	esac
done
shift $(( $OPTIND - 1 ))

#
# Initialize
#
f_dialog_title "$msg_system_console_configuration"
f_dialog_backtitle "${ipgm:+bsdconfig }$pgm"
f_mustberoot_init

#
# Launch application main menu
#
while :; do
	dialog_menu_main
	retval=$?
	mtag=$( f_dialog_menutag )

	[ $retval -eq 0 ] || f_die

	case "$mtag" in
	"X $msg_exit") break ;;
	"2 $msg_font") # Choose an alternate screen font
		$BSDCFG_LIBE/$APP_DIR/font ${USE_XDIALOG:+-X} ;;
	"3 $msg_keymap") # Choose an alternate keyboard map
		$BSDCFG_LIBE/$APP_DIR/keymap ${USE_XDIALOG:+-X} ;;
	"4 $msg_repeat") # Set the rate at which keys repeat
		$BSDCFG_LIBE/$APP_DIR/repeat ${USE_XDIALOG:+-X} ;;
	"5 $msg_saver") # Configure the screen saver
		$BSDCFG_LIBE/$APP_DIR/saver ${USE_XDIALOG:+-X} ;;
	"6 $msg_screenmap") # Choose an alternate screenmap
		$BSDCFG_LIBE/$APP_DIR/screenmap ${USE_XDIALOG:+-X} ;;
	"7 $msg_ttys") # Choose console terminal type
		$BSDCFG_LIBE/$APP_DIR/ttys ${USE_XDIALOG:+-X} ;;
	esac

done

exit $SUCCESS

################################################################################
# END
################################################################################
