# $FreeBSD$

.include <bsd.own.mk>

TESTSDIR=${TESTSBASE}/sys/cddl/zfs/tests/utils_test
FILESDIR=${TESTSDIR}

ATF_TESTS_KSH93+=	utils_test_test

FILES+=	utils_test_007_pos.ksh
FILES+=	utils_test_003_pos.ksh
FILES+=	utils_test_006_pos.ksh
FILES+=	utils_test_002_pos.ksh
FILES+=	utils_test.kshlib
FILES+=	cleanup.ksh
FILES+=	utils_test_004_pos.ksh
FILES+=	utils_test_008_pos.ksh
FILES+=	utils_test.cfg
FILES+=	setup.ksh
FILES+=	utils_test_009_pos.ksh
FILES+=	utils_test_005_pos.ksh
FILES+=	utils_test_001_pos.ksh

.include <bsd.test.mk>
