blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/Yubico/libfido2/discussions/new
    about: Share ideas for new features
  - name: Ask a question about libfido2
    url: https://github.com/Yubico/libfido2/discussions/new
    about: Ask the community for help
