# $Id: Makefile,v 1.1 1997/12/15 02:28:22 skynyrd Exp $

GLOBAL_DIR=	${.CURDIR}/../../../contrib/global
.PATH:		${GLOBAL_DIR}/lib

LIB=		globalutil
NOPROFILE=	yes

SRCS=	dbio.c dbname.c find.c getdbpath.c gtagsopen.c locatestring.c \
	lookup.c makepath.c mgets.c strop.c tab.c tag.c test.c

install:	


.include <bsd.lib.mk>
