# $FreeBSD: src/gnu/usr.bin/groff/man/Makefile,v 1.5.8.4 2003/02/14 15:22:13 ru Exp $

MAN=		groff_font.5 groff_out.5 groff_tmac.5
MLINKS=		groff_tmac.5 tmac.5
MAN+=		ditroff.7 groff.7 groff_char.7 groff_diff.7 roff.7
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
