# $FreeBSD: src/lib/libkse/test/sigsuspend_d.exp,v 1.2.14.1 2010/12/21 17:10:29 kensmith Exp $
  -> Suspender thread signal handler caught signal 16
Sigsuspend woke up by signal 16
  -> Suspender thread signal handler caught signal 16
Sigsuspend woke up by signal 16
  -> Suspender thread signal handler caught signal 31
Sigsuspend woke up by signal 31
  -> Suspender thread signal handler caught signal 31
Sigsuspend woke up by signal 31
