#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/smm/06.nfs/Makefile,v 1.5.50.1 2008/10/02 02:57:24 kensmith Exp $

VOLUME=	smm/06.nfs
SRCS=	0.t 1.t 2.t ref.t
MACROS=	-me

.include <bsd.doc.mk>
