# $FreeBSD$

PROG = acpidump

SRCS = \
	acpi.c \
	acpi_user.c \
	acpidump.c

WARNS ?= 6

SRCDIRDEP= sys/sys
DIRDEP= gnu/lib/csu gnu/lib/libgcc include lib/csu/MACHINE_ARCH lib/libc stage sys/MACHINE_ARCH/include
.include <bsd.prog.mk>
