# $FreeBSD: src/share/doc/smm/10.named/Makefile,v 1.4.2.1 2000/12/01 13:52:21 ru Exp $

SRCDIR=	${.CURDIR}/../../../../contrib/bind/doc/bog

VOLUME=	smm/10.named
SRCS=	00macs.me 00title.me intro.me ns.me types.me \
	files.me named.boot.primary \
	named.boot.secondary named.boot.cache resolv.conf \
	root.cache named.local ucbhosts.rev ucbhosts \
	setup.me manage.me build.me ack.me

MACROS=	-me
USE_TBL=yes

.include <bsd.doc.mk>
