#	@(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: src/share/doc/usd/04.csh/Makefile,v 1.7 2004/10/24 15:32:44 ru Exp $

VOLUME=		usd/04.csh
SRCS=		tabs csh.1 csh.2 csh.3 csh.4 csh.a csh.g
MACROS=		-ms
USE_SOELIM=
SRCDIR=		${.CURDIR}/../../../../bin/csh/USD.doc

.include <bsd.doc.mk>
