.\" $FreeBSD$
.\"
.Dd January 16, 2001
.Dt FONTEDIT 1
.Os
.Sh NAME
.Nm fontedit
.Nd "edit fonts"
.Sh SYNOPSIS
.Nm
.Ar file
.Sh DESCRIPTION
The
.Nm
utility is used to edit the down line reloadable character set (DRCS) of a
.Tn VT220
terminal.
The editor has two display areas, one for displaying the
entry currently being manipulated, and one for displaying the complete
DRCS.
Commands to the editor take the form of function keys.
.Pp
The
.Nm
utility
takes one command line parameter, a
.Ar file
name.
This file is used to save the character set.
If the file exists when
.Nm
is invoked, it is read in to initialize the DRCS.
The file is written to when
.Nm
exits.
.Pp
Commands to
.Nm
take the form of function keys.
The current definitions are:
.Bl -tag -width "Cursors"
.It Ic HELP
Display a help screen.
.It Ic F6
Turn the pixel under the cursor on.
.It Ic F7
Turn the pixel under the cursor off.
.It Ic F13
Clear the display area.
.It Ic Find
Save the current font in the font table.
Update the DRCS display.
.It Ic Select
Extract the entry selected by the cursor in the DRCS display.
.It Ic Prev
Move the cursor to the previous entry in the DRCS display.
.It Ic Next
Move the cursor to the next entry in the DRCS display.
.It Ic Insert
Insert a blank line at the current cursor position.
The bottom row is lost.
.It Ic Remove
Remove the row at the current cursor position.
All rows below the
current one are shifted up.
.It Ic Cursors
Move the cursor in the main display area.
.El
.Pp
If the screen gets garbled, press
.Aq control\-L .
.Pp
To exit
.Nm ,
press
.Aq control\-D .
The DRCS will be saved in
.Ar file .
To exit without saving the DRCS, hit interrupt (usually
DEL).
.Sh DIAGNOSTICS
The
.Nm
utility
will issue a warning when the entry being worked on is not saved, and
some potentially destructive command, like
.Ic Select
is used.
To
override the warning message, immediately reissue the command.
.Sh AUTHORS
.An Greg Franks
