.\" $FreeBSD: src/usr.sbin/pcvt/fontedit/fontedit.1,v 1.4 1999/08/28 23:20:49 mpp Exp $
.\"
.TH FONTEDIT 1 LOCAL
.SH NAME
fontedit \- Edit fonts.
.SH SYNOPSIS
.B fontedit file
.SH DESCRIPTION
.I Fontedit
is used to edit the down line reloadable character set (DRCS) of a VT220
terminal.  The editor has two display areas, one for displaying the
entry currently being manipulated, and one for displaying the complete
DRCS.  Commands to the editor take the form of function keys.
.PP
.I Fontedit 
takes one command line parameter, a file name.  This file is
used to save the character set.  If the file exists when \fIfontedit\fP
is invoked, it is read in to initialize the DRCS.  The file is written
to when \fIfontedit\fP exits.
.PP
Commands to fontedit take the form of function keys.  The current
definitions are:
.IP \fBHELP\fP
Display a help screen.
.IP \fBF6\fP
Turn the pixel under the cursor on.
.IP \fBF7\fP
Turn the pixel under the cursor off.
.IP \fBF13\fP
Clear the display area.
.IP \fBFind\fP
Save the current font in the font table.  Update the DRCS display.
.IP \fBSelect\fP
Extract the entry selected by the cursor in the DRCS display.
.IP \fBPrev\fP
Move the cursor to the previous entry in the DRCS display.
.IP \fBNext\fP
Move the cursor to the next entry in the DRCS display.
.IP \fBInsert\fP
Insert a blank line at the current cursor position.  The bottom row is lost.
.IP \fBRemove\fP
Remove the row at the current cursor position.  All rows below the
current one are shifted up.
.IP \fBCursors\fP
Move the cursor in the main display area.
.PP
If the screen gets garbled, press <control-L>.
.PP
To exit \fIfontedit\fP, press <control-D>.  The DRCS will be saved in
\fIfile\fP.  To exit without saving the DRCS, hit interrupt (usually
DEL). 
.SH DIAGNOSTICS
.I Fontedit
will issue a warning when the entry being worked on is not saved, and
some potentially destructive command, like \fBSelect\fP is used.  To
override the warning message, immediately reissue the command.
.SH AUTHOR
Greg Franks.


