# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.301.
# Any changes made here will be lost!
return <<'END';
05be	
05c0	
05c3	
05d0	05ea
05f0	05f4
200f	
fb1d	
fb1f	fb28
fb2a	fb36
fb38	fb3c
fb3e	
fb40	fb41
fb43	fb44
fb46	fb4f
END
