# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.301.
# Any changes made here will be lost!
return <<'END';
0030	0039
0660	0669
06f0	06f9
0966	096f
09e6	09ef
0a66	0a6f
0ae6	0aef
0b66	0b6f
0be7	0bef
0c66	0c6f
0ce6	0cef
0d66	0d6f
0e50	0e59
0ed0	0ed9
0f20	0f29
1040	1049
1369	1371
17e0	17e9
1810	1819
END
