# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.301.
# Any changes made here will be lost!
return <<'END';
005f	
203f	2040
30fb	
fe33	fe34
fe4d	fe4f
ff3f	
ff65	
END
