# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.301.
# Any changes made here will be lost!
return <<'END';
0009	000a
000c	000d
0020	
00a0	
1680	
2000	200b
2028	2029
202f	
3000	
END
