# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!! 
# This file is built by mktables.PL from e.g. Unicode.301.
# Any changes made here will be lost!
return <<'END';
1414	1416
1442	1443
145f	1460
147c	147d
149a	149b
14b4	14b5
14e4	14e5
14fe	14ff
151f	1520
1537	1538
END
