# Makefile for kld char device driver.
# $FreeBSD: src/share/examples/kld/cdev/module/Makefile,v 1.6.34.1 2010/02/10 00:26:20 kensmith Exp $

KMOD=	cdev
SRCS=	cdev.c cdevmod.c

.include <bsd.kmod.mk>
