# $FreeBSD: src/gnu/usr.bin/groff/devX75-12/Makefile,v 1.8 1999/08/27 23:35:42 peter Exp $
#
# Generic groff font makefile

NOOBJ=

.include "${.CURDIR}/../Makefile.inc"
.include "${DIST_DIR}/Makefile.sub"
.include "${.CURDIR}/../Makefile.dev"
