#	$NetBSD: Makefile,v 1.6 2012/07/28 16:08:40 njoly Exp $
#

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/sbin

TESTS_SUBDIRS+=	fsck_ffs ifconfig newfs newfs_msdos resize_ffs route sysctl

.include <bsd.test.mk>
