# $FreeBSD: src/sys/modules/netgraph/bpf/Makefile,v 1.10 2002/01/11 15:48:51 ru Exp $
# $Whistle: Makefile,v 1.1 1999/12/03 01:44:28 archie Exp $

.PATH: ${.CURDIR}/../../../net

KMOD=	ng_bpf
SRCS= 	ng_bpf.c bpf_filter.c

.include <bsd.kmod.mk>
