# Makefile for groff
#
# $FreeBSD: src/gnu/usr.bin/groff/Makefile,v 2.3.2.2 2000/03/13 12:39:46 asmodai Exp $

SUBDIR=		libgroff libdriver libbib \
		addftinfo eqn \
		grodvi groff grog grohtml grolj4 grops grotty \
		indxbib lkbib lookbib man mm nroff \
		pfbtops pic psbb refer tbl tfmtodit tmac troff \
		devX100 devX100-12 devX75 devX75-12 devascii devdvi \
		devhtml devlatin1 devkoi8-r devlj4 devps

# BSD already provides soelim and we don't want xditview compiled be default
MISC=		soelim afmtodit doc hpftodit xditview

.include <bsd.subdir.mk>
