# $FreeBSD: src/gnu/usr.bin/groff/Makefile,v 2.6.2.1 2000/12/07 09:56:58 ru Exp $

SUBDIR=		libgroff libdriver libbib \
		addftinfo afmtodit doc eqn grn \
		grodvi groff grog grohtml grolbp grolj4 grops grotty \
		hpftodit indxbib lkbib lookbib man mm nroff \
		pfbtops pic refer tbl tfmtodit tmac troff \
		devX100 devX100-12 devX75 devX75-12 devascii devcp1047 \
		devdvi devhtml devkoi8-r devlatin1 devlbp devlj4 devps \
		devutf8

# BSD already provides soelim and we don't want xditview compiled by default
MISC=		soelim xditview

.include <bsd.subdir.mk>
