# Makefile for groff
#
# $Id: Makefile,v 2.1 1996/09/08 01:27:08 pst Exp $

SUBDIR=		libgroff libdriver libbib \
		addftinfo eqn \
		grodvi groff grolj4 grops grotty \
		indxbib lkbib lookbib man mm nroff \
		pfbtops pic psbb refer tbl tfmtodit tmac troff \
		devX100 devX100-12 devX75 devX75-12 devascii devdvi \
		devlatin1 devkoi8-r devlj4 devps

# BSD already provides soelim and we don't want xditview compiled be default
MISC=		soelim afmtodit doc grog hpftodit xditview

.include <bsd.subdir.mk>
