# $FreeBSD: src/sys/modules/netgraph/pptpgre/Makefile,v 1.1.2.1 1999/12/08 19:44:11 julian Exp $
# $Whistle: Makefile,v 1.1 1999/11/29 23:14:33 archie Exp $

KMOD=		ng_pptpgre
SRCS= 		ng_pptpgre.c
MAN8=		ng_pptpgre.8
KMODDEPS=	netgraph

.include <bsd.kmod.mk>
