# $FreeBSD: src/usr.sbin/sa/Makefile,v 1.12.10.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../usr.bin/lastcomm

PROG=	sa
MAN=	sa.8
SRCS=	main.c db.c pdb.c usrdb.c readrec.c

WARNS?=	6

.include <bsd.prog.mk>
