freebsd_11_task:
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  install_script: pkg install -y git py27-yaml
  script:
    - fetch http://tetworks.opengroup.org/downloads/38/software/Sources/3.8/tet3.8-src.tar.gz
    - tar -x -C test/tet -f tet3.8-src.tar.gz
    - make

debian_stable_task:
  container:
    image: debian:stable
  setup_script:
    - apt-get update
    - apt-get install -y
      binutils bison bmake curl flex g++ gcc git
      libarchive-dev libbsd-dev libc6-dev libexpat1-dev lsb-release
      m4 perl python-yaml sharutils zlib1g-dev
  script:
    - curl -O http://tetworks.opengroup.org/downloads/38/software/Sources/3.8/tet3.8-src.tar.gz
    - tar -x -C test/tet -z -f tet3.8-src.tar.gz
    - bmake
