# $FreeBSD$

LIB=	clangsema

SRCDIR=	tools/clang/lib/Sema
SRCS=	JumpDiagnostics.cpp IdentifierResolver.cpp ParseAST.cpp \
	Sema.cpp SemaAccess.cpp SemaAttr.cpp SemaCXXScopeSpec.cpp \
	SemaChecking.cpp SemaDecl.cpp SemaDeclAttr.cpp SemaDeclCXX.cpp \
	SemaDeclObjC.cpp SemaExpr.cpp SemaExprCXX.cpp SemaExprObjC.cpp \
	SemaInherit.cpp SemaInit.cpp SemaLookup.cpp SemaNamedCast.cpp \
	SemaOverload.cpp SemaStmt.cpp SemaTemplate.cpp \
	SemaTemplateDeduction.cpp SemaTemplateInstantiateDecl.cpp \
	SemaTemplateInstantiateExpr.cpp \
	SemaTemplateInstantiateStmt.cpp SemaTemplateInstantiate.cpp \
	SemaType.cpp

TGHDRS=	DiagnosticCommonKinds DiagnosticSemaKinds

.include "../../clang.lib.mk"
