# $FreeBSD$
#
# Author: Harti Brandt <harti@freebsd.org>

.PATH: ${BSDSRCTOP}/contrib/bsnmp/lib

LIBDIR = ${STAGEDIR}/lib
INCDIR = ${STAGEDIR}/usr/include/bsnmp

LIB = bsnmp

SRCS = \
	asn1.c \
	snmp.c \
	snmpagent.c \
	snmpclient.c \
	support.c

INCS = \
	asn1.h \
	snmp.h \
	snmpagent.h \
	snmpclient.h

WARNS ?= 6

CFLAGS += -I${CONTRIB} -DHAVE_ERR_H -DHAVE_GETADDRINFO -DHAVE_STRLCPY
CFLAGS += -DHAVE_STDINT_H -DHAVE_INTTYPES_H -DQUADFMT='"llu"' -DQUADXFMT='"llx"'


SRCDIRDEP= contrib/bsnmp/lib
DIRDEP= include include/machine stage sys/MACHINE_ARCH/include sys/netinet sys/netinet6 sys/sys
.include <bsd.lib.mk>
