# $FreeBSD: src/share/doc/legal/intel_wpi/Makefile,v 1.1.2.1.8.1 2010/02/10 00:26:20 kensmith Exp $

NO_OBJ=
FILES=          ${.CURDIR}/../../../../sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal/intel_wpi

.include <bsd.prog.mk>

