# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/release/doc/ru_RU.KOI8-R/Makefile,v 1.7 2004/08/11 10:04:25 den Exp $
# $FreeBSD$
# 
# Original revision: 1.5
#

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
#SUBDIR+= errata
SUBDIR+= installation
SUBDIR+= early-adopter

COMPAT_SYMLINK = ru

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
