# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/release/doc/ru_RU.KOI8-R/Makefile,v 1.2 2004/05/20 07:07:45 den Exp $
# $FreeBSD$
# 
# Original revision: 1.3
#

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
#SUBDIR+= hardware
#SUBDIR+= readme
#SUBDIR+= errata
#SUBDIR+= installation
#SUBDIR+= early-adopter

COMPAT_SYMLINK = ru

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
