# $FreeBSD: src/sys/modules/sdhci/Makefile,v 1.1.2.1.4.1 2010/02/10 00:26:20 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/sdhci

KMOD=	sdhci
SRCS=	sdhci.c sdhci.h device_if.h bus_if.h pci_if.h mmcbr_if.h

.include <bsd.kmod.mk>
