#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/basename/Makefile,v 1.2.6.1 2001/08/02 00:59:28 obrien Exp $

PROG=	basename
WARNS?=	2
MLINKS=	basename.1 dirname.1

.include <bsd.prog.mk>
