# $FreeBSD: src/sys/modules/netgraph/UI/Makefile,v 1.9.40.1 2010/12/21 17:10:29 kensmith Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=	ng_UI
SRCS= 	ng_UI.c

.include <bsd.kmod.mk>
