# $FreeBSD: src/gnu/usr.bin/groff/src/devices/grolbp/Makefile,v 1.1.2.1 2001/04/26 17:08:23 ru Exp $

PROG=		grolbp
SRCS=		lbp.cc
DPADD=		${LIBDRIVER} ${LIBGROFF} ${LIBM}
LDADD=		${LIBDRIVER} ${LIBGROFF} -lm
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
