# $FreeBSD: src/sys/modules/amr/amr_linux/Makefile,v 1.1.8.1 2008/11/25 02:59:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../dev/amr

KMOD=	amr_linux
SRCS=	amr_linux.c device_if.h bus_if.h

.include <bsd.kmod.mk>
