# $Id: Makefile.inc,v 1.10 1994/06/13 21:50:02 ache Exp $

CPLUSPLUSLIB=   yes

# SHLIB major and minor nos. MUST be specified here.
# Do not remove the following 2 lines.
SHLIB_MAJOR=1
SHLIB_MINOR=1

