# $FreeBSD: src/usr.sbin/mrouted/testrsrr/Makefile,v 1.5 2001/07/20 06:20:02 obrien Exp $

S=	${.CURDIR}/..
.PATH: $S

PROG=	testrsrr
NOMAN=	#true
SRCS=	testrsrr.c

CFLAGS+= -I$S

install:

.include <bsd.prog.mk>
