# $FreeBSD$

SUBDIR=		clang

SRCDIR=		${.CURDIR}/../../../contrib/llvm

.PATH: ${SRCDIR} ${SRCDIR}/lib/Support

NO_OBJ=

FILESGROUPS=	TOP
TOP=		LICENSE.TXT COPYRIGHT.regex
TOPDIR=		${DOCDIR}/llvm

.include <bsd.prog.mk>
