.\" Copyright (C) 1998 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	KAME Id: pim6dd.conf.5,v 1.4 2000/07/09 17:26:52 itojun Exp
.\"	$FreeBSD: src/usr.sbin/pim6dd/pim6dd.conf.5,v 1.2.2.4 2000/07/15 07:36:30 kris Exp $
.\"
.Dd Nov 17, 1998
.Dt PIM6DD.CONF 5
.Os
.Sh NAME
.Nm pim6dd.conf
.Nd config file for pim6dd, PIM for IPv6 dense mode daemon
.\"
.Sh DESCRIPTION
The file describes how the
.Xr pim6dd 8
daemon treats each interface on the system.
By default(including the case where there is no configuration file),
PIM will be activated on all interfaces, which can be overridden
by the file.
Lines beginning with
.Ql #
are comments.
.Pp
There are four types of configuration commands:
.Bl -tag -width Ds -compact
.It Xo
.Ic default_source_preference Ar preference
.Xc
Specifies a default preference value when sending a PIM assert message.
Preferences are used by assert elections to determine upstream routers.
Currently
.Xr pim6dd 8
cannot reliably obtain preferences and metrics from the
unicast routing protocols, so a default value may be configured.
.\"
.It Ic default_source_metric Ar metric
Specifies a default metric value when sending a PIM assert message.
It is recommended that preferences be set such that metrics are never
consulted. However, default metrics may also be set and will default to
1024.
.\"
.It Xo
.Ic phyint Ar interface
.Op disable
.Xc
Specifies
.Xr pim6dd 8
to ignore the interface even if the interface is multicast-capable.
Interfaces are specified in the form of "name unit", such as
.Ar gif0
and
.Ar ep1.
.\"
.It Xo
.Ic phyint Ar interface
.Op preference Ar preference
.Op metric Ar metric
.Xc
Specifies the preference and/or metric values when sending a PIM
assert message on the interface.
.\"
.It Xo
.Ic filter Ar groupaddrs Ar interfaces...
.Xc
Specifies an output filter. If an incoming multicast packet's destination
matches the specified
.Ar groupaddrs ,
the packet is not sent on the
.Ar interfaces.
Moreover, if there is no other interface than the specified
interfaces,
.Xr pim6dd 8
sends a prune message to the upstream neighbor.
Valid formats of
.Ar groupaddrs
are as follows.
.Bl -tag -width Ds -compact
.It Ar multicastaddr1-multicastaddr2
specifies a numerical range of a scope.
Multicast addresses
from
.Ar multicastaddr1
to
.Ar multicastaddr2
will be filtered out.
Note that neither a white space nor a tab character must not be
inserted before nor after
.Ql - .
.It Ar multicastaddr/prefixlen
specifies a group prefix of a scope.
Multicast addresses which match the specified prefix will be filtered
out.
If
.Ar prefixlen
is omitted, it means the exact match for
.Ar multicastaddr.
.El
.Ar interfaces
are specified as a blank separated list of interfaces. Each interface is
specified in the form of "name unit".
.El
.\"
.Sh EXAMPLE
.Bd -literal -offset
# phyint gif0 disable
# phyint ep0 preference 101
phyint de0 disable
filter ff15::4000/120 gif1 gif2
filter ff18::1000-ff18::1050 gif3
.Ed
.Sh SEE ALSO
.Xr pim6dd 8
.Sh HISTORY
The
.Xr pim6dd 8
command and the configuration file
.Nm
are based on
.Nm pimdd ,
which is an IPv4 multicast routing daemon
developed at the University of Oregon.
.Nm pimdd
has been derived from PIM sparse-mode
.Nm pimd
developed at University of Southern California.
Part of these two programs above has also been derived from
.Nm mrouted .
.Nm mrouted
is COPYRIGHT 1989 by The Board of Trustees of
Leland Stanford Junior University.
.Pp
IPv6 and IPsec support based on the KAME Project (http://www.kame.net/) stack
was initially integrated into
.Fx 4.0
