#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/finger/Makefile,v 1.1.1.1.14.1 2000/08/24 18:18:26 brian Exp $

PROG=	finger
SRCS=	finger.c lprint.c net.c sprint.c util.c
MAN1=	finger.1
MAN5=	finger.conf.5

.include <bsd.prog.mk>
