# $FreeBSD: src/share/doc/psd/22.rpcgen/Makefile,v 1.6.20.1 2009/04/15 03:14:26 kensmith Exp $

VOLUME=		psd/22.rpcgen
SRCS=		stubs rpcgen.ms
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
