#!/bin/sh

# $Id: linux,v 1.5 1998/09/07 16:15:59 cracauer Exp $

if modstat -n linux_mod > /dev/null ; then
	echo Linux lkm already loaded
	exit 1
else
	modload -e linux_mod -u -q -o /tmp/linux_mod /lkm/linux_mod.o
fi
