# $FreeBSD: src/sys/modules/sound/driver/au88x0/Makefile,v 1.1.26.1 2008/10/02 02:57:24 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_au88x0
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	au88x0.c

.include <bsd.kmod.mk>
