make: "directive-elif.mk" line 47: Unknown directive "elsif"
make: "directive-elif.mk" line 52: This branch is taken.
make: "directive-elif.mk" line 60: Unknown directive "elsif"
make: "directive-elif.mk" line 63: This branch is taken.
make: "directive-elif.mk" line 69: This branch is taken.
make: "directive-elif.mk" line 89: Unknown directive "elsif"
make: "directive-elif.mk" line 90: This misspelling is detected.
make: "directive-elif.mk" line 91: This branch is taken because of the .else.
make: "directive-elif.mk" line 109: What happens on misspelling in a skipped branch?
make: "directive-elif.mk" line 119: else
make: "directive-elif.mk" line 122: What happens on misspelling in a taken branch?
make: "directive-elif.mk" line 124: 1-then
make: "directive-elif.mk" line 125: Unknown directive "elsif"
make: "directive-elif.mk" line 126: 1-elsif
make: "directive-elif.mk" line 127: Unknown directive "elsif"
make: "directive-elif.mk" line 128: 2-elsif
make: "directive-elif.mk" line 134: if-less elif
make: "directive-elif.mk" line 139: warning: extra elif
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
