make: "varmod-localtime.mk" line 60: Invalid time value: ${:U1593536400}} != "mtime=11593536400}"
make: "varmod-localtime.mk" line 60: Malformed conditional (${%Y:L:localtime=${:U1593536400}} != "mtime=11593536400}")
make: "varmod-localtime.mk" line 70: Invalid time value: -1} != ""
make: "varmod-localtime.mk" line 70: Malformed conditional (${:L:localtime=-1} != "")
make: "varmod-localtime.mk" line 79: Invalid time value:  1} != ""
make: "varmod-localtime.mk" line 79: Malformed conditional (${:L:localtime= 1} != "")
make: "varmod-localtime.mk" line 118: Invalid time value: 10000000000000000000000000000000} != ""
make: "varmod-localtime.mk" line 118: Malformed conditional (${:L:localtime=10000000000000000000000000000000} != "")
make: "varmod-localtime.mk" line 129: Invalid time value: error} != ""
make: "varmod-localtime.mk" line 129: Malformed conditional (${:L:localtime=error} != "")
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
