# $FreeBSD: src/sys/modules/ti/Makefile,v 1.17.10.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/ti

KMOD=	if_ti
SRCS=	if_ti.c device_if.h bus_if.h pci_if.h opt_ti.h opt_zero.h

.include <bsd.kmod.mk>
