# $FreeBSD: src/sys/modules/mxge/mxge_rss_eth_z8e/Makefile,v 1.1.2.1.8.1 2010/12/21 17:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../dev/mxge
KMOD=	mxge_rss_eth_z8e
SRCS=	mxge_rss_eth_z8e.c

.include <bsd.kmod.mk>
