PACKAGE=	tests

ATF_TESTS_SH=	locale_test

${PACKAGE}FILES+=	k_flag_posix_monetary.out
${PACKAGE}FILES+=	k_flag_posix_numeric.out
${PACKAGE}FILES+=	k_flag_posix_time.out
${PACKAGE}FILES+=	k_flag_posix_messages.out
${PACKAGE}FILES+=	no_flags_posix_monetary.out
${PACKAGE}FILES+=	no_flags_posix_numeric.out
${PACKAGE}FILES+=	no_flags_posix_time.out
${PACKAGE}FILES+=	no_flags_posix_messages.out

.include <bsd.test.mk>
