# $FreeBSD: src/usr.sbin/newsyslog/Makefile,v 1.16.28.1 2009/04/15 03:14:26 kensmith Exp $

PROG=	newsyslog
MAN=	newsyslog.8 newsyslog.conf.5
SRCS=	newsyslog.c ptimes.c

WARNS?=	2

.include <bsd.prog.mk>
