# $FreeBSD: src/sys/modules/sound/driver/envy24/Makefile,v 1.3.12.1.8.1 2012/03/03 06:15:13 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_envy24
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	envy24.c

.include <bsd.kmod.mk>
