#	From: @(#)Makefile	8.3 (Berkeley) 1/25/94
# $FreeBSD: src/usr.sbin/mountd/Makefile,v 1.13 2003/04/04 17:49:15 obrien Exp $

PROG=	mountd
MAN=	exports.5 netgroup.5 mountd.8

WARNS?=	0

.include <bsd.prog.mk>
