#	@(#)Makefile	8.6 (Berkeley) 5/8/95
#	$Id: Makefile,v 1.5 1997/08/25 20:38:35 bde Exp $

PROG=	mount
SRCS=	mount.c mount_ufs.c getmntopts.c vfslist.c
MAN8=	mount.8
# We do NOT install the getmntopts.3 man page.

.include <bsd.prog.mk>
