# $FreeBSD: src/sys/modules/digi/digi_CX/Makefile,v 1.1.36.1.8.1 2012/03/03 06:15:13 kensmith Exp $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_CX
SRCS=	CX.c CX.bios.h CX.fepos.h digi_mod.h

.include <bsd.kmod.mk>
