# $FreeBSD: src/include/arpa/Makefile,v 1.3.22.1.2.1 2009/10/25 01:10:29 kensmith Exp $

NO_OBJ=
INCS=	ftp.h inet.h nameser.h nameser_compat.h telnet.h tftp.h
INCSDIR=${INCLUDEDIR}/arpa

.include <bsd.prog.mk>
