# $FreeBSD: src/sys/modules/syscons/star/Makefile,v 1.16.36.1.8.1 2012/03/03 06:15:13 kensmith Exp $

.PATH:	${.CURDIR}/../../../dev/syscons/star

KMOD=	star_saver
SRCS=	star_saver.c

.include <bsd.kmod.mk>
