#!/bin/sh
#
# $P4: //depot/projects/trustedbsd/openbsm/etc/audit_warn#3 $
# $FreeBSD: src/contrib/openbsm/etc/audit_warn,v 1.2.12.1.8.1 2012/03/03 06:15:13 kensmith Exp $
#
logger -p security.warning "audit warning: $@"
