#!/bin/sh
#
# $P4: //depot/projects/trustedbsd/openbsm/etc/audit_warn#3 $
# $FreeBSD: src/contrib/openbsm/etc/audit_warn,v 1.2.8.1 2008/11/25 02:59:29 kensmith Exp $
#
logger -p security.warning "audit warning: $@"
