#!/bin/sh
#
# $P4: //depot/projects/trustedbsd/openbsm/etc/audit_warn#3 $
# $FreeBSD: src/contrib/openbsm/etc/audit_warn,v 1.2.12.1.6.1 2010/12/21 17:09:25 kensmith Exp $
#
logger -p security.warning "audit warning: $@"
