# $FreeBSD: src/sys/modules/epic/Makefile,v 1.1.2.2.6.1 2012/03/03 06:15:13 kensmith Exp $

.PATH: ${.CURDIR}/../../sparc64/ebus

KMOD=	epic
SRCS=	device_if.h epic.c bus_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
