.\"	@(#)praliases.8	8.1 (Berkeley) 9/21/96
.Dd April 25, 1996
.Dt PRALIASES 1
.Os BSD 3
.Sh NAME
.Nm praliases
.Nd display system mail aliases
.Sh SYNOPSIS
.Nm praliases
.Op Fl f Ar file
.Sh DESCRIPTION
The
.Nm praliases
utility displays the current system aliases,
one per line, in no particular order.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f
Read the specified file instead of the default
.Nm sendmail
system aliases file.
.El
.Pp
The
.Nm praliases
utility exits 0 on success, and >0 if an error occurs.
.Sh FILES
.Bl -tag -width /var/log/sendmail.stXX -compact
.It Pa /etc/aliases
The default
.Nm sendmail
system aliases file.
.It Pa /etc/aliases.db
The database version of the
.Pa /etc/aliases
file.
.El
.Sh SEE ALSO
.Xr mailq 1 ,
.Xr sendmail 8
