LIB    = libutil.a
CC     = gcc
AR     = ar
CFLAGS = -O -I../lib -I/usr/include/db
OBJS   = tag.o tab.o strop.o mgets.o lookup.o gtagsopen.o getdbpath.o \
	 find.o dbname.o dbio.o test.o makepath.o locatestring.o
all: $(LIB)

$(LIB): $(OBJS)
	$(AR) cq $(LIB) $(OBJS)
install:
	@echo -n
clean:
	rm -f $(LIB) $(OBJS)
