#
# Makefile.tmpl,v 3.1 1993/07/06 01:09:28 jbj Exp
#
PROGRAM=	ntpq
#
# ntpq - control mode query program
#
COMPILER= cc
COPTS= -O
BINDIR=	/usr/local
INSTALL= install
DEFS=
DEFS_OPT=
DEFS_LOCAL=
RESLIB=
COMPAT=
#
INCL=		-I../include
CFLAGS=		$(COPTS) $(DEFS) $(DEFS_LOCAL) $(INCL)
CC=		$(COMPILER)
LIB=		../lib/libntp.a
LINTLIB=	../lib/llib-llibntp.ln
MAKE=		make
TOP=../
#
OBJS=	ntpq.o ntpq_ops.o
SOURCE=	ntpq.c ntpq_ops.c

all:	$(PROGRAM)

$(PROGRAM): $(OBJS) $(LIB) version.o 
	$(CC) $(COPTS) -o $@ $(OBJS) version.o $(LIB) $(RESLIB) $(COMPAT)

install:	$(BINDIR)/$(PROGRAM)

$(BINDIR)/$(PROGRAM): $(PROGRAM)
	$(INSTALL) -c -m 0755 $(PROGRAM) $(BINDIR)

tags:
	ctags *.c *.h

depend:
	mkdep $(CFLAGS) $(SOURCE)

clean:
	-@rm -f $(PROGRAM) *.o *.out tags make.log Makefile.bak lint.errs .version

distclean:	clean
	-@rm -f *.orig *.rej .version Makefile

lint:	$(LINTLIB)
	lint -x -u $(DEFS) $(DEFS_LOCAL) $(INCL) $(LINTLIB) $(SOURCE) >lint.errs

../lib/llib-llibntp.ln:
	cd ../lib && $(MAKE) $(MFLAGS) MFLAGS="$(MFLAGS)" lintlib

../lib/libntp.a:
	cd ../lib && $(MAKE) $(MFLAGS) MFLAGS="$(MFLAGS)"

#
# we want to build the current version string here
#
version.o: ../VERSION
	../scripts/mkversion $(PROGRAM)
	$(CC) $(COPTS) $(INCL) -c version.c

../VERSION:
	-@rm -f .version
