# $FreeBSD: src/sys/modules/syscons/Makefile,v 1.11 1999/10/02 03:56:40 nsayer Exp $

SUBDIR =
SUBDIR += apm
SUBDIR += blank
SUBDIR += daemon
SUBDIR += fade
SUBDIR += fire
SUBDIR += green
SUBDIR += logo
SUBDIR += rain
SUBDIR += snake
SUBDIR += star
SUBDIR += warp

.include <bsd.subdir.mk>
