/* @generated by `generate-fortify-tests.lua "unistd"` */

#define	_FORTIFY_SOURCE	2
#define	TMPFILE_SIZE	(1024 * 32)

#include <sys/param.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sysexits.h>
#include <unistd.h>
#include <atf-c.h>

/*
 * Create a new symlink to use for readlink(2) style tests, we'll just use a
 * random target name to have something interesting to look at.
 */
static const char * __unused
new_symlink(size_t __len)
{
	static const char linkname[] = "link";
	char target[MAXNAMLEN];
	int error;

	ATF_REQUIRE(__len <= sizeof(target));

	arc4random_buf(target, sizeof(target));

	error = unlink(linkname);
	ATF_REQUIRE(error == 0 || errno == ENOENT);

	error = symlink(target, linkname);
	ATF_REQUIRE(error == 0);

	return (linkname);
}

/*
 * Constructs a tmpfile that we can use for testing read(2) and friends.
 */
static int __unused
new_tmpfile(void)
{
	char buf[1024];
	ssize_t rv;
	size_t written;
	int fd;

	fd = open("tmpfile", O_RDWR | O_CREAT | O_TRUNC, 0644);
	ATF_REQUIRE(fd >= 0);

	written = 0;
	while (written < TMPFILE_SIZE) {
		rv = write(fd, buf, sizeof(buf));
		ATF_REQUIRE(rv > 0);

		written += rv;
	}

	ATF_REQUIRE_EQ(0, lseek(fd, 0, SEEK_SET));
	return (fd);
}

static void
disable_coredumps(void)
{
	struct rlimit rl = { 0 };

	if (setrlimit(RLIMIT_CORE, &rl) == -1)
		_exit(EX_OSERR);
}

ATF_TC_WITHOUT_HEAD(getcwd_before_end);
ATF_TC_BODY(getcwd_before_end, tc)
{
#define BUF &__stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char __buf[8];
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(__stack.__buf);
	const size_t __len = 8 - 1;
	const size_t __idx __unused = __len - 1;

	getcwd(__stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(getcwd_end);
ATF_TC_BODY(getcwd_end, tc)
{
#define BUF &__stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char __buf[8];
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(__stack.__buf);
	const size_t __len = 8;
	const size_t __idx __unused = __len - 1;

	getcwd(__stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(getcwd_heap_before_end);
ATF_TC_BODY(getcwd_heap_before_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (8);
	const size_t __len = 8 - 1;
	const size_t __idx __unused = __len - 1;

	__stack.__buf = malloc(__bufsz);

	getcwd(__stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(getcwd_heap_end);
ATF_TC_BODY(getcwd_heap_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (8);
	const size_t __len = 8;
	const size_t __idx __unused = __len - 1;

	__stack.__buf = malloc(__bufsz);

	getcwd(__stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(getcwd_heap_after_end);
ATF_TC_BODY(getcwd_heap_after_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (8);
	const size_t __len = 8 + 1;
	const size_t __idx __unused = __len - 1;
	pid_t __child;
	int __status;

	__child = fork();
	ATF_REQUIRE(__child >= 0);
	if (__child > 0)
		goto monitor;

	/* Child */
	disable_coredumps();
	__stack.__buf = malloc(__bufsz);

	getcwd(__stack.__buf, __len);
	_exit(EX_SOFTWARE);	/* Should have aborted. */

monitor:
	while (waitpid(__child, &__status, 0) != __child) {
		ATF_REQUIRE_EQ(EINTR, errno);
	}

	if (!WIFSIGNALED(__status)) {
		switch (WEXITSTATUS(__status)) {
		case EX_SOFTWARE:
			atf_tc_fail("FORTIFY_SOURCE failed to abort");
			break;
		case EX_OSERR:
			atf_tc_fail("setrlimit(2) failed");
			break;
		default:
			atf_tc_fail("child exited with status %d",
			    WEXITSTATUS(__status));
		}
	} else {
		ATF_REQUIRE_EQ(SIGABRT, WTERMSIG(__status));
	}
#undef BUF

}

ATF_TC_WITHOUT_HEAD(read_before_end);
ATF_TC_BODY(read_before_end, tc)
{
#define BUF &__stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char __buf[41];
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(__stack.__buf);
	const size_t __len = 41 - 1;
	const size_t __idx __unused = __len - 1;
	int fd;

	fd = new_tmpfile();	/* Cannot fail */

	read(fd, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(read_end);
ATF_TC_BODY(read_end, tc)
{
#define BUF &__stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char __buf[41];
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(__stack.__buf);
	const size_t __len = 41;
	const size_t __idx __unused = __len - 1;
	int fd;

	fd = new_tmpfile();	/* Cannot fail */

	read(fd, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(read_heap_before_end);
ATF_TC_BODY(read_heap_before_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (41);
	const size_t __len = 41 - 1;
	const size_t __idx __unused = __len - 1;
	int fd;

	__stack.__buf = malloc(__bufsz);
	fd = new_tmpfile();	/* Cannot fail */

	read(fd, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(read_heap_end);
ATF_TC_BODY(read_heap_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (41);
	const size_t __len = 41;
	const size_t __idx __unused = __len - 1;
	int fd;

	__stack.__buf = malloc(__bufsz);
	fd = new_tmpfile();	/* Cannot fail */

	read(fd, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(read_heap_after_end);
ATF_TC_BODY(read_heap_after_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (41);
	const size_t __len = 41 + 1;
	const size_t __idx __unused = __len - 1;
	pid_t __child;
	int __status;
	int fd;

	__child = fork();
	ATF_REQUIRE(__child >= 0);
	if (__child > 0)
		goto monitor;

	/* Child */
	disable_coredumps();
	__stack.__buf = malloc(__bufsz);
	fd = new_tmpfile();	/* Cannot fail */

	read(fd, __stack.__buf, __len);
	_exit(EX_SOFTWARE);	/* Should have aborted. */

monitor:
	while (waitpid(__child, &__status, 0) != __child) {
		ATF_REQUIRE_EQ(EINTR, errno);
	}

	if (!WIFSIGNALED(__status)) {
		switch (WEXITSTATUS(__status)) {
		case EX_SOFTWARE:
			atf_tc_fail("FORTIFY_SOURCE failed to abort");
			break;
		case EX_OSERR:
			atf_tc_fail("setrlimit(2) failed");
			break;
		default:
			atf_tc_fail("child exited with status %d",
			    WEXITSTATUS(__status));
		}
	} else {
		ATF_REQUIRE_EQ(SIGABRT, WTERMSIG(__status));
	}
#undef BUF

}

ATF_TC_WITHOUT_HEAD(readlink_before_end);
ATF_TC_BODY(readlink_before_end, tc)
{
#define BUF &__stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char __buf[42];
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(__stack.__buf);
	const size_t __len = 42 - 1;
	const size_t __idx __unused = __len - 1;
	const char *path;

	path = new_symlink(__len);		/* Cannot fail */

	readlink(path, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(readlink_end);
ATF_TC_BODY(readlink_end, tc)
{
#define BUF &__stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char __buf[42];
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(__stack.__buf);
	const size_t __len = 42;
	const size_t __idx __unused = __len - 1;
	const char *path;

	path = new_symlink(__len);		/* Cannot fail */

	readlink(path, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(readlink_heap_before_end);
ATF_TC_BODY(readlink_heap_before_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (42);
	const size_t __len = 42 - 1;
	const size_t __idx __unused = __len - 1;
	const char *path;

	__stack.__buf = malloc(__bufsz);
	path = new_symlink(__len);		/* Cannot fail */

	readlink(path, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(readlink_heap_end);
ATF_TC_BODY(readlink_heap_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (42);
	const size_t __len = 42;
	const size_t __idx __unused = __len - 1;
	const char *path;

	__stack.__buf = malloc(__bufsz);
	path = new_symlink(__len);		/* Cannot fail */

	readlink(path, __stack.__buf, __len);
#undef BUF

}

ATF_TC_WITHOUT_HEAD(readlink_heap_after_end);
ATF_TC_BODY(readlink_heap_after_end, tc)
{
#define BUF __stack.__buf
	struct {
		uint8_t padding_l;
		unsigned char * __buf;
		uint8_t padding_r;
	} __stack;
	const size_t __bufsz __unused = sizeof(*__stack.__buf) * (42);
	const size_t __len = 42 + 1;
	const size_t __idx __unused = __len - 1;
	pid_t __child;
	int __status;
	const char *path;

	__child = fork();
	ATF_REQUIRE(__child >= 0);
	if (__child > 0)
		goto monitor;

	/* Child */
	disable_coredumps();
	__stack.__buf = malloc(__bufsz);
	path = new_symlink(__len);		/* Cannot fail */

	readlink(path, __stack.__buf, __len);
	_exit(EX_SOFTWARE);	/* Should have aborted. */

monitor:
	while (waitpid(__child, &__status, 0) != __child) {
		ATF_REQUIRE_EQ(EINTR, errno);
	}

	if (!WIFSIGNALED(__status)) {
		switch (WEXITSTATUS(__status)) {
		case EX_SOFTWARE:
			atf_tc_fail("FORTIFY_SOURCE failed to abort");
			break;
		case EX_OSERR:
			atf_tc_fail("setrlimit(2) failed");
			break;
		default:
			atf_tc_fail("child exited with status %d",
			    WEXITSTATUS(__status));
		}
	} else {
		ATF_REQUIRE_EQ(SIGABRT, WTERMSIG(__status));
	}
#undef BUF

}

ATF_TP_ADD_TCS(tp)
{
	ATF_TP_ADD_TC(tp, getcwd_before_end);
	ATF_TP_ADD_TC(tp, getcwd_end);
	ATF_TP_ADD_TC(tp, getcwd_heap_before_end);
	ATF_TP_ADD_TC(tp, getcwd_heap_end);
	ATF_TP_ADD_TC(tp, getcwd_heap_after_end);
	ATF_TP_ADD_TC(tp, read_before_end);
	ATF_TP_ADD_TC(tp, read_end);
	ATF_TP_ADD_TC(tp, read_heap_before_end);
	ATF_TP_ADD_TC(tp, read_heap_end);
	ATF_TP_ADD_TC(tp, read_heap_after_end);
	ATF_TP_ADD_TC(tp, readlink_before_end);
	ATF_TP_ADD_TC(tp, readlink_end);
	ATF_TP_ADD_TC(tp, readlink_heap_before_end);
	ATF_TP_ADD_TC(tp, readlink_heap_end);
	ATF_TP_ADD_TC(tp, readlink_heap_after_end);
	return (atf_no_error());
}
