#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/psd/16.lex/Makefile,v 1.7.26.1 2010/12/21 17:10:29 kensmith Exp $

VOLUME=		psd/16.lex
SRCS=		lex.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
