#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/psd/16.lex/Makefile,v 1.6.8.1 2005/02/13 07:23:23 obrien Exp $

VOLUME=		psd/16.lex
SRCS=		lex.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
