# $FreeBSD: src/sys/boot/i386/btx/lib/Makefile,v 1.13.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $

PROG=	crt0.o
INTERNALPROG=
NO_MAN=
SRCS=	btxcsu.s btxsys.s btxv86.s
LDFLAGS=-Wl,-r

.include <bsd.prog.mk>
