#	$Id:$

OBJS=		btxcsu.o btxsys.o btxv86.o
LDFLAGS+=	-elf
CLEANFILES+=	crt0.o
INTERNALLIB=	true
NOMAN=		true
NOPIC=		true
NOPROFILE=	true

all: crt0.o

crt0.o: ${OBJS}
	${LD} ${LDFLAGS} -i -o ${.TARGET} ${OBJS}

.include <bsd.lib.mk>
