# Makefile copyright Andreas Klemm <andreas@FreeBSD.ORG> 1998
#
# $FreeBSD: src/gnu/usr.bin/dc/doc/Makefile,v 1.4.54.1 2009/04/15 03:14:26 kensmith Exp $

.PATH:	${.CURDIR}/../../../../contrib/bc/doc

INFO = dc
INFOSECTION= "System Utilities"
INFOENTRY_dc= "* DC: (dc).			The GNU Desktop Calculator."

.include <bsd.info.mk>
