#define O_ALTWERASE 0
#define O_AUTOINDENT 1
#define O_AUTOPRINT 2
#define O_AUTOWRITE 3
#define O_BACKUP 4
#define O_BEAUTIFY 5
#define O_CDPATH 6
#define O_CEDIT 7
#define O_COLUMNS 8
#define O_COMBINED 9
#define O_COMMENT 10
#define O_TMPDIR 11
#define O_EDCOMPATIBLE 12
#define O_ERRORBELLS 13
#define O_ESCAPETIME 14
#define O_EXPANDTAB 15
#define O_EXRC 16
#define O_EXTENDED 17
#define O_FILEC 18
#define O_FILEENCODING 19
#define O_FLASH 20
#define O_HARDTABS 21
#define O_ICLOWER 22
#define O_IGNORECASE 23
#define O_INPUTENCODING 24
#define O_KEYTIME 25
#define O_LEFTRIGHT 26
#define O_LINES 27
#define O_LISP 28
#define O_LIST 29
#define O_LOCKFILES 30
#define O_MAGIC 31
#define O_MATCHCHARS 32
#define O_MATCHTIME 33
#define O_MESG 34
#define O_MODELINE 35
#define O_MSGCAT 36
#define O_NOPRINT 37
#define O_NUMBER 38
#define O_OCTAL 39
#define O_OPEN 40
#define O_OPTIMIZE 41
#define O_PARAGRAPHS 42
#define O_PATH 43
#define O_PRINT 44
#define O_PROMPT 45
#define O_READONLY 46
#define O_RECDIR 47
#define O_REDRAW 48
#define O_REMAP 49
#define O_REPORT 50
#define O_RULER 51
#define O_SCROLL 52
#define O_SEARCHINCR 53
#define O_SECTIONS 54
#define O_SECURE 55
#define O_SHELL 56
#define O_SHELLMETA 57
#define O_SHIFTWIDTH 58
#define O_SHOWMATCH 59
#define O_SHOWMODE 60
#define O_SIDESCROLL 61
#define O_SLOWOPEN 62
#define O_SOURCEANY 63
#define O_TABSTOP 64
#define O_TAGLENGTH 65
#define O_TAGS 66
#define O_TERM 67
#define O_TERSE 68
#define O_TILDEOP 69
#define O_TIMEOUT 70
#define O_TTYWERASE 71
#define O_VERBOSE 72
#define O_W1200 73
#define O_W300 74
#define O_W9600 75
#define O_WARN 76
#define O_WINDOW 77
#define O_WINDOWNAME 78
#define O_WRAPLEN 79
#define O_WRAPMARGIN 80
#define O_WRAPSCAN 81
#define O_WRITEANY 82
#define O_OPTIONCOUNT 83
