#
# $Id: Makefile,v 1.8 1998/03/08 12:27:04 obrien Exp $
#

PROG =	c++
SRCS =	g++.c
BINDIR=	/usr/bin
LINKS=	${BINDIR}/c++ ${BINDIR}/g++
LINKS+=	${BINDIR}/c++ ${BINDIR}/CC
NOMAN=	1

.include <bsd.prog.mk>
