#	$Id: Makefile,v 1.12 1995/08/24 09:06:17 phk Exp $

SUBDIR=	cd9660 coff fdesc ibcs2 if_disc if_ppp if_sl if_tun \
	ipfw kernfs linux msdos nfs nullfs \
	pcic portal procfs syscons umapfs union
#
# Doesn't work:
# mfs
#

.include <bsd.subdir.mk>
