#	$Id: Makefile,v 1.9.4.1 1995/09/06 15:16:06 davidg Exp $

SUBDIR=	cd9660 coff fdesc ibcs2 if_disc if_ppp if_sl if_tun \
	ipfw kernfs linux msdos nfs nullfs \
	portal procfs socksys syscons umapfs union
#
# Doesn't work:
# ip_mrouter_mod mfs
#

.include <bsd.subdir.mk>
