# $FreeBSD: src/sys/modules/netgraph/cisco/Makefile,v 1.11.30.1 2008/10/02 02:57:24 kensmith Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=	ng_cisco
SRCS= 	ng_cisco.c

.include <bsd.kmod.mk>
