# $FreeBSD: src/sys/modules/netgraph/cisco/Makefile,v 1.11.34.1 2009/04/15 03:14:26 kensmith Exp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=	ng_cisco
SRCS= 	ng_cisco.c

.include <bsd.kmod.mk>
