$ $FreeBSD$
$
$set 1
$quote "
1 "(entrada estándar)"
2 "opción desconocida de %s"
3 "uso: %s [-abcDEFGHhIiLlmnOoPqRSsUVvwxz] [-A no] [-B no] [-C[no]]\n"
4 "\t[-e pauta] [-f fichero] [--binary-files=valor] [--color=cuando]\n"
5 "\t[--context[=no]] [--directories=acción] [--label] [--line-buffered]\n"
6 "\t[--null] [pauta] [fichero ...]\n"
7 "fichero binario %s se ajusta\n"
8 "%s (BSD grep) %s\n"
9 "%s (BSD grep, GNU compatible) %s\n"
