$ $FreeBSD$
$
$set 1
$quote "
1 "(szabványos bemenet)"
2 "ismeretlen %s opció"
3 "használat: %s [-abcDEFGHhIiLlmnOoPqRSsUVvwxz] [-A szám] [-B szám] [-C[szám]]\n"
4 "\t[-e minta] [-f fájl] [--binary-files=érték] [--color=mikor]\n"
5 "\t[--context[=szám]] [--directories=mûvelet] [--label] [--line-buffered]\n"
6 "\t[--null] [minta] [fájl ...]\n"
7 "%s bináris fájl illeszkedik\n"
8 "%s (BSD grep) %s\n"
9 "%s (BSD grep, GNU compatible) %s\n"
