$ $FreeBSD$
$
$set 1
$quote "
1 "(szabványos bemenet)"
2 "bzip2 tömörített fájl nem olvasható"
3 "ismeretlen --color opció"
4 "használat: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZ] [-A szám] [-B szám] [-C[szám]]\n"
5 "\t[-e minta] [-f fájl] [--binary-files=érték] [--color=mikor]\n"
6 "\t[--context[=szám]] [--directories=mûvelet] [--label] [--line-buffered]\n"
7 "\t[--null] [minta] [fájl ...]\n"
8 "ismeretlen --binary-files opció"
9 "%s bináris fájl illeszkedik\n"
10 "%s (BSD grep) %s\n"
