$ $FreeBSD$
$set 1
$quote "
1 "(стандартний ввід)"
2 "не можу прочитати стиснутий bzip2 файл"
3 "невiдома опція %s"
4 "використання: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZ] [-A чис] [-B чис] [-C[чис]]\n"
5 "\t[-e шаблон] [-f файл] [--binary-files=значення] [--color=коли]\n"
6 "\t[--context[=чис] [--directories=дія] [--label] [--line-buffered]\n"
7 "\t[--null] [шаблон] [файл ...]\n"
8 "двійковий файл %s співпадає\n"
9 "%s (BSD grep) %s\n"
