!define KFW_TARGETDIR %BUILDDIR%\target
!define KFW_EXTRADIR "%BUILDDIR%\target"
!define KFW_VERSION %VERSION_MAJOR%.%VERSION_MINOR%
!define KFW_MAJORVERSION %VERSION_MAJOR%
!define KFW_MINORVERSION %VERSION_MINOR%
!define KFW_PATCHLEVEL %VERSION_PATCH%
!define CL_1310

