!define KFW_TARGETDIR %TARGETDIR%
!define KFW_CONFIG_DIR %CONFIGDIR-NSI%
!define KFW_MAJORVERSION %VERSION_MAJOR%
!define KFW_MINORVERSION %VERSION_MINOR%
!define KFW_PATCHLEVEL %VERSION_PATCH%
!define CL_1310

!define RELEASE
!define NOT_DEBUG
!define BETA 1
!define SAMPLE_CONFIG_REALM "ATHENA.MIT.EDU"
!define HTTP_CONFIG_URL     "[Obtain a URL from your Kerberos administrator]"

