# $FreeBSD: src/gnu/usr.bin/groff/src/preproc/soelim/Makefile,v 1.1.2.3 2003/06/26 13:13:55 ru Exp $

PROG_CXX=	soelim
SRCS=		soelim.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
