# $FreeBSD: src/gnu/usr.bin/cc/collect2/Makefile,v 1.9.18.1 2008/11/25 02:59:29 kensmith Exp $

.include "../Makefile.inc"

.PATH: ${GCCDIR}

PROG=	collect2
SRCS=	collect2.c tlink.c version.c
NO_MAN=

.include <bsd.prog.mk>
