Making remove-archive
rm -f libprog.a

Making libprog.a out-of-date archive.mk modmisc.mk varmisc.mk
ar cru libprog.a archive.mk modmisc.mk varmisc.mk
ranlib libprog.a

Making create-archive out-of-date libprog.a

Making list-archive out-of-date libprog.a
ar t libprog.a
archive.mk
modmisc.mk
varmisc.mk

Making list-archive-wildcard out-of-date archive-suffix.mk archive.mk ternary.mk
list-archive-wildcard: archive-suffix.mk
list-archive-wildcard: archive.mk
list-archive-wildcard: ternary.mk

Making depend-on-existing-member out-of-date archive.mk
depend-on-existing-member

`depend-on-nonexistent-member' is up to date.
Making remove-archive
rm -f libprog.a

exit status 0
