make: cond-op-or.mk:36: Variable "UNDEF" is undefined
make: cond-op-or.mk:41: Variable "UNDEF" is undefined
make: cond-op-or.mk:44: Variable "UNDEF" is undefined
make: cond-op-or.mk:60: Unknown operator "|"
make: cond-op-or.mk:66: Unknown operator "|"
make: cond-op-or.mk:72: Unknown operator "|"
make: cond-op-or.mk:78: Unknown operator "|"
make: cond-op-or.mk:87: Unknown operator "|"
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
