make: "directive-warning.mk" line 11: Unknown directive "warn"
make: "directive-warning.mk" line 12: Unknown directive "warn"
make: "directive-warning.mk" line 13: Unknown directive "warnin"
make: "directive-warning.mk" line 14: Unknown directive "warnin"
make: "directive-warning.mk" line 15: Missing argument for ".warning"
make: "directive-warning.mk" line 16: warning: message
make: "directive-warning.mk" line 17: Unknown directive "warnings"
make: "directive-warning.mk" line 18: Unknown directive "warnings"
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
