make: directive-for-empty.mk:22: 2
For: end for 1
For: loop body with i = value:
# The identifier 'empty' can only be used in conditions such as .if, .ifdef or
# .elif.  In other lines the string 'empty(' must be preserved.
CPPFLAGS+=	-Dmessage="empty(i)"
# There may be whitespace between 'empty' and '('.
.if ! empty (i)
.  error
.endif
# Even in conditions, the string 'empty(' is not always a function call, it
# can occur in a string literal as well.
.if "empty\(i)" != "empty(i)"
.  error
.endif
# In comments like 'empty(i)', the text must be preserved as well.
#
# Conditions, including function calls to 'empty', can not only occur in
# condition directives, they can also occur in the modifier ':?', see
# varmod-ifelse.mk.
CPPFLAGS+=	-Dmacro="${empty(i):?empty:not-empty}"
exit status 0
