make: directive-else.mk:14: The .else directive does not take arguments
make: directive-else.mk:16: ok
make: directive-else.mk:21: ok
make: directive-else.mk:23: The .else directive does not take arguments
make: directive-else.mk:29: if-less else
make: directive-else.mk:36: ok
make: directive-else.mk:38: warning: extra else
make: directive-else.mk:51: The .else directive does not take arguments
make: Fatal errors encountered -- cannot continue
make: stopped making "all" in unit-tests
exit status 1
