make: "directive-for.mk" line 117: outer
make: "directive-for.mk" line 135: a:\ a:\file.txt
make: "directive-for.mk" line 135: d:\\
make: "directive-for.mk" line 135: d:\\file.txt
make: "directive-for.mk" line 146: ( ( (
make: "directive-for.mk" line 146: [ [ [
make: "directive-for.mk" line 146: { { {
make: "directive-for.mk" line 146: ) ) )
make: "directive-for.mk" line 146: ] ] ]
make: "directive-for.mk" line 146: } } }
make: "directive-for.mk" line 146: (()) (()) (())
make: "directive-for.mk" line 146: [[]] [[]] [[]]
make: "directive-for.mk" line 146: {{}} {{}} {{}}
make: "directive-for.mk" line 146: )( )( )(
make: "directive-for.mk" line 146: ][ ][ ][
make: "directive-for.mk" line 146: }{ }{ }{
make: "directive-for.mk" line 166: invalid character ':' in .for loop variable name
make: "directive-for.mk" line 173: invalid character '$' in .for loop variable name
make: "directive-for.mk" line 185: invalid character '$' in .for loop variable name
make: "directive-for.mk" line 196: Unknown modifier "Z"
make: "directive-for.mk" line 197: XXX: Not reached word1
make: "directive-for.mk" line 197: XXX: Not reached word3
make: "directive-for.mk" line 204: no iteration variables in for
make: "directive-for.mk" line 230: 1 open conditional
make: "directive-for.mk" line 246: for-less endfor
make: "directive-for.mk" line 247: if-less endif
make: "directive-for.mk" line 255: if-less endif
For: new loop 2
For: end for 2
For: end for 1
For: loop body with outer = o:
.\
   for inner in i
.\
   endfor
For: end for 1
For: loop body with inner = i:
make: "directive-for.mk" line 303: newline-item=(a)
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
