make: "directive-ifmake.mk" line 14: ok: positive condition works
make: "directive-ifmake.mk" line 26: ok: negation works
make: "directive-ifmake.mk" line 36: ok: double negation works
make: "directive-ifmake.mk" line 44: ok: both mentioned
make: "directive-ifmake.mk" line 52: ok: only those mentioned
make: "directive-ifmake.mk" line 63: Targets can even be added at parse time.
make: "directive-ifmake.mk" line 82: ok
: first
: second
: late-target
make: don't know how to make !edge (continuing)

Stop.
make: stopped in unit-tests
exit status 1
