make: "directive-elif.mk" line 48: Unknown directive "elsif"
make: "directive-elif.mk" line 54: This branch is taken.
make: "directive-elif.mk" line 62: Unknown directive "elsif"
make: "directive-elif.mk" line 66: This branch is taken.
make: "directive-elif.mk" line 73: This branch is taken.
make: "directive-elif.mk" line 94: Unknown directive "elsif"
make: "directive-elif.mk" line 96: This misspelling is detected.
make: "directive-elif.mk" line 98: This branch is taken because of the .else.
make: "directive-elif.mk" line 117: What happens on misspelling in a skipped branch?
make: "directive-elif.mk" line 128: else
make: "directive-elif.mk" line 132: What happens on misspelling in a taken branch?
make: "directive-elif.mk" line 135: 1-then
make: "directive-elif.mk" line 137: Unknown directive "elsif"
make: "directive-elif.mk" line 139: 1-elsif
make: "directive-elif.mk" line 141: Unknown directive "elsif"
make: "directive-elif.mk" line 143: 2-elsif
make: "directive-elif.mk" line 149: if-less elif
make: "directive-elif.mk" line 154: warning: extra elif
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
