make: "directive-else.mk" line 14: The .else directive does not take arguments
make: "directive-else.mk" line 16: ok
make: "directive-else.mk" line 21: ok
make: "directive-else.mk" line 23: The .else directive does not take arguments
make: "directive-else.mk" line 29: if-less else
make: "directive-else.mk" line 36: ok
make: "directive-else.mk" line 38: warning: extra else
make: "directive-else.mk" line 51: The .else directive does not take arguments
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
