make: include-main.mk:15: main-before-ok
make: include-main.mk:23: main-before-for-ok
make: include-sub.inc:4: sub-before-ok
make: include-sub.inc:14: sub-before-for-ok
Parsing include-subsub.inc:5: .  info subsub-ok
make: include-subsub.inc:5: subsub-ok
	in .for loop from include-sub.inc:31 with i = include
	in .for loop from include-sub.inc:30 with i = nested
	in .for loop from include-sub.inc:29 with i = deeply
	in include-main.mk:29
Parsing include-subsub.inc:6: .MAKEFLAGS: -d0
ParseDependency(.MAKEFLAGS: -d0)
make: include-sub.inc:38: sub-after-ok
make: include-sub.inc:45: sub-after-for-ok
make: include-main.mk:33: main-after-ok
make: include-main.mk:41: main-after-for-ok
exit status 0
