direct compat
false
*** Error code 1 (continuing)

Stop.
make: stopped in unit-tests
exited 1

direct jobs
false
*** [direct] Error code 1

make: stopped in unit-tests
exited 1

indirect compat
false
*** Error code 1 (continuing)
`indirect' not remade because of errors.

Stop.
make: stopped in unit-tests
exited 1

indirect jobs
false
*** [direct] Error code 1

make: stopped in unit-tests
exited 1

exit status 0
