make: "opt-debug-lint.mk" line 21: Variable "X" is undefined
make: "opt-debug-lint.mk" line 21: Malformed conditional ($X)
make: "opt-debug-lint.mk" line 45: Variable "UNDEF" is undefined
make: "opt-debug-lint.mk" line 45: Malformed conditional (${UNDEF})
make: "opt-debug-lint.mk" line 67: Missing delimiter ':' after modifier "L"
make: "opt-debug-lint.mk" line 67: Missing delimiter ':' after modifier "P"
make: "opt-debug-lint.mk" line 76: Unknown modifier "${"
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
