For: new loop 2
For: end for 2
For: end for 1
For: loop body with outer = a:
.  for inner in 1 2
VAR.${:Ua}${inner}=	value
.  endfor
For: end for 1
For: loop body with inner = 1:
VAR.${:Ua}${:U1}=	value
For: loop body with inner = 2:
VAR.${:Ua}${:U2}=	value
For: loop body with outer = b:
.  for inner in 1 2
VAR.${:Ub}${inner}=	value
.  endfor
For: end for 1
For: loop body with inner = 1:
VAR.${:Ub}${:U1}=	value
For: loop body with inner = 2:
VAR.${:Ub}${:U2}=	value
exit status 0
