echo '3   spaces'; false
3   spaces

*** Failed target: fail-spaces
*** In directory: <curdir>
*** Failed commands:
	echo '3   spaces'; false
*** [fail-spaces] Error code 1

make: stopped making "all" in unit-tests
echo \  indented; false
  indented

*** Failed target: fail-escaped-space
*** In directory: <curdir>
*** Failed commands:
	echo \  indented; false
*** [fail-escaped-space] Error code 1

make: stopped making "all" in unit-tests
echo 'line1
line2'; false
line1
line2

*** Failed target: fail-newline
*** In directory: <curdir>
*** Failed commands:
	echo 'line1${.newline}line2'; false
	=> echo 'line1
line2'; false
*** [fail-newline] Error code 1

make: stopped making "all" in unit-tests
echo 'line1 line2'; false
line1 line2

*** Failed target: fail-multiline
*** In directory: <curdir>
*** Failed commands:
	echo 'line1 line2'; false
*** [fail-multiline] Error code 1

make: stopped making "all" in unit-tests
echo	'word1'							 'word2'; false
word1 word2

*** Failed target: fail-multiline-intention
*** In directory: <curdir>
*** Failed commands:
	echo	'word1'							 'word2'; false
*** [fail-multiline-intention] Error code 1

make: stopped making "all" in unit-tests

*** Failed target: fail-vars
*** In directory: <curdir>
*** Failed commands:
	@${COMPILE_C} ${COMPILE_C_FLAGS}
	=> @false c-compiler flag1 -macro="several words"
*** [fail-vars] Error code 1

make: stopped making "all" in unit-tests
exit status 1
