make -r -f /dev/null -V MAKEFLAGS
 -r -k -d 0 

make -:
usage: make [-BeikNnqrSstWwX]
            [-C directory] [-D variable] [-d flags] [-f makefile]
            [-I directory] [-J private] [-j max_jobs] [-m directory] [-T file]
            [-V variable] [-v variable] [variable=value] [target ...]
*** Error code 2 (ignored)

make -r -f /dev/null -- -VAR=value -f /dev/null
make: don't know how to make -f (continuing)
`/dev/null' is up to date.

make -?
usage: make [-BeikNnqrSstWwX]
            [-C directory] [-D variable] [-d flags] [-f makefile]
            [-I directory] [-J private] [-j max_jobs] [-m directory] [-T file]
            [-V variable] [-v variable] [variable=value] [target ...]
*** Error code 2 (ignored)

exit status 0
