ParseReadLine (9): '.SUFFIXES:'
ParseDoDependency(.SUFFIXES:)
Clearing all suffixes
ParseReadLine (11): '.SUFFIXES: .a .b .c'
ParseDoDependency(.SUFFIXES: .a .b .c)
Adding suffix ".a"
Adding suffix ".b"
Adding suffix ".c"
ParseReadLine (17): '.a.b:'
ParseDoDependency(.a.b:)
defining transformation from `.a' to `.b'
inserting ".a" (1) at end of list
inserting ".b" (2) at end of list
ParseReadLine (21): '.a.c: ${.PREFIX}.dependency'
deleting incomplete transformation from `.a' to `.b'
ParseDoDependency(.a.c: ${.PREFIX}.dependency)
defining transformation from `.a' to `.c'
inserting ".a" (1) at end of list
inserting ".c" (3) at end of list
# LinkSource: added child .a.c - ${.PREFIX}.dependency
# .a.c, made UNMADE, type OP_DEPENDS|OP_TRANSFORM, flags none
# ${.PREFIX}.dependency, made UNMADE, type none, flags none
ParseReadLine (23): '.DEFAULT:'
transformation .a.c complete
ParseDoDependency(.DEFAULT:)
ParseReadLine (24): '	: Making ${.TARGET} from ${.IMPSRC} all ${.ALLSRC} by default.'
transformation .DEFAULT complete
Wildcard expanding "all"...
SuffFindDeps "all"
	No known suffix on all. Using .NULL suffix
adding suffix rules
Wildcard expanding "suff-incomplete.c"...suffix is ".c"...
SuffFindDeps "suff-incomplete.c"
	trying suff-incomplete.a...not there
Wildcard expanding "suff-incomplete.c"...suffix is ".c"...
: Making suff-incomplete.c from suff-incomplete.c all  by default.
Wildcard expanding "all"...
SuffFindDeps ".END"
	No known suffix on .END. Using .NULL suffix
adding suffix rules
Wildcard expanding ".END"...
exit status 0
