VarFind-aliases.to: long explicit-dependency VarFind-aliases.from
VarFind-aliases.to: abbr explicit-dependency VarFind-aliases.from
VarFind-aliases.to: long
VarFind-aliases.to: abbr
VarFind-aliases.to: long VarFind-aliases.from
VarFind-aliases.to: abbr VarFind-aliases.from
VarFind-aliases.to: long
VarFind-aliases.to: abbr
VarFind-aliases.to: long explicit-dependency VarFind-aliases.from
VarFind-aliases.to: abbr explicit-dependency VarFind-aliases.from
VarFind-aliases.to: long VarFind-aliases
VarFind-aliases.to: abbr VarFind-aliases
VarFind-aliases.to: long VarFind-aliases.to
VarFind-aliases.to: abbr VarFind-aliases.to
exit status 0
