make: "varmod-edge.mk" line 60: Unclosed expression, expecting '}' for modifier "U*)"
	while evaluating "${:U*)" with value "*)"
	while evaluating variable "INP" with value "(parentheses)"
	while evaluating variable "MOD" with value "${INP:M${:U*)}}"
make: "varmod-edge.mk" line 88: Unfinished character list in pattern '[[' of modifier ':M'
	while evaluating variable "INP" with value "[ [[ [[["
	while evaluating variable "MOD" with value "${INP:M${:U[[}}"
make: "varmod-edge.mk" line 178: Unfinished modifier ('=' missing)
	while evaluating variable "INP" with value "file.c file..."
	while evaluating variable "MOD" with value "${INP:a\=b}"
make: "varmod-edge.mk" line 194: Unknown modifier ":"
	while evaluating variable "INP" with value "value"
	while evaluating variable "MOD" with value "${INP::::}"
make: "varmod-edge.mk" line 194: Unknown modifier ":"
	while evaluating variable "INP" with value ""
	while evaluating variable "MOD" with value "${INP::::}"
make: "varmod-edge.mk" line 200: Unknown modifier "Z"
	while evaluating "${:Z}" with value ""
make: "varmod-edge.mk" line 213: Unfinished modifier (',' missing)
	while evaluating "${:S,}" with value ""
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
