make: "varmod-edge.mk" line 166: ok M-paren
make: "varmod-edge.mk" line 166: ok M-mixed
make: "varmod-edge.mk" line 166: ok M-unescape
make: Unclosed variable specification (expecting '}') for "" (value "*)") modifier U
make: "varmod-edge.mk" line 166: ok M-nest-mix
make: "varmod-edge.mk" line 166: ok M-nest-brk
make: "varmod-edge.mk" line 166: ok M-pat-err
make: "varmod-edge.mk" line 166: ok M-bsbs
make: "varmod-edge.mk" line 166: ok M-bs1-par
make: "varmod-edge.mk" line 166: ok M-bs2-par
make: "varmod-edge.mk" line 166: ok M-128
make: "varmod-edge.mk" line 166: ok eq-ext
make: "varmod-edge.mk" line 166: ok eq-q
make: "varmod-edge.mk" line 166: ok eq-bs
make: Unfinished modifier for INP.eq-esc ('=' missing)
make: "varmod-edge.mk" line 166: ok eq-esc
make: "varmod-edge.mk" line 166: ok colon
make: "varmod-edge.mk" line 165: Unknown modifier ':'
make: "varmod-edge.mk" line 165: Unknown modifier ':'
make: "varmod-edge.mk" line 166: ok colons
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
