Global: VAR{{{}}} = 3 braces
Var_Parse: ${VAR{{{}}}}" != "3 braces" (eval)
Global: VARNAME = VAR(((
Var_Parse: ${VARNAME} (eval)
Global: VAR((( = 3 open parentheses
Var_Parse: ${VAR(((}}}}" != "3 open parentheses}}}" (eval)
Global: .ALLTARGETS =  VAR(((=)
make: "varname.mk" line 32: Missing ')' in archive specification
make: "varname.mk" line 32: Error in archive specification: "VAR"
Var_Parse: ${:UVAR\(\(\(}=	try2 (eval)
Evaluating modifier ${:U...} on value "" (eval, undefined)
Result of ${:UVAR\(\(\(} is "VAR\(\(\(" (eval, defined)
Global: .ALLTARGETS =  VAR(((=) VAR\(\(\(=
make: "varname.mk" line 38: Invalid line '${:UVAR\(\(\(}=	try2', expanded to 'VAR\(\(\(=	try2'
Var_Parse: ${VARNAME} (eval)
Global: VAR((( = try3
Global: .MAKEFLAGS =  -r -k -d v -d
Global: .MAKEFLAGS =  -r -k -d v -d 0
make: Fatal errors encountered -- cannot continue
make: stopped making "all" in unit-tests
exit status 1
