# $FreeBSD$

.PATH: ${BSDSRCTOP}/sbin/dump

PROG = restore

SRCS = \
	dirs.c \
	dumprmt.c \
	interactive.c \
	main.c \
	restore.c \
	symtab.c \
	tape.c \
	utilities.c

WARNS?=	0

CFLAGS += -DRRESTORE

SRCDIRDEP= sbin/dump
DIRDEP= gnu/lib/csu gnu/lib/libgcc include include/machine include/protocols lib/csu/MACHINE_ARCH lib/libc stage sys/MACHINE_ARCH/include sys/netinet sys/netinet6 sys/sys sys/ufs/ufs sys/vm
.include <bsd.prog.mk>
