# $FreeBSD: src/sys/modules/my/Makefile,v 1.1.2.1 2002/04/16 20:38:52 julian Exp $

.PATH: ${.CURDIR}/../../dev/my

KMOD=	if_my
SRCS=	if_my.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
