# $Id: Makefile,v 1.1.1.1.2.4 1997/03/15 23:31:34 jkh Exp $
# Original revision: 1.22
# The FreeBSD Japanese Documentation Project

DOC=	handbook
DOCDIR=${SHAREDIR}/doc/ja_JP.EUC
FORMATS= html roff
# this won't work for old sgmlfmt in 2.2 branch
#SGMLOPTS+=-e EUC-JP

SRCS= authors.sgml basics.sgml bibliography.sgml boothelp.sgml
SRCS+= booting.sgml contrib.sgml crypt.sgml ctm.sgml current.sgml cvsup.sgml
SRCS+= cyclades.sgml development.sgml dialup.sgml dialout.sgml
SRCS+= diskless.sgml dma.sgml eresources.sgml esdi.sgml 
SRCS+= firewalls.sgml glossary.sgml goals.sgml
SRCS+= handbook.sgml history.sgml hw.sgml install.sgml isdn.sgml
SRCS+= kerberos.sgml kernelconfig.sgml kerneldebug.sgml kernelopts.sgml
SRCS+= lists.sgml mail.sgml memoryuse.sgml
SRCS+= mirrors.sgml nfs.sgml nutshell.sgml pgpkeys.sgml policies.sgml
SRCS+= porting.sgml ports.sgml ppp.sgml printing.sgml
SRCS+= quotas.sgml relnotes.sgml routing.sgml russian.sgml
SRCS+= serial.sgml scsi.sgml sections.sgml sio.sgml skey.sgml slipc.sgml 
SRCS+= slips.sgml stable.sgml submitters.sgml sup.sgml synching.sgml 
SRCS+= term.sgml userppp.sgml uart.sgml linuxemu.sgml
SRCS+= jcontrib.sgml jmembers.sgml

.include <bsd.sgml.mk>
