# $FreeBSD: src/gnu/usr.bin/texinfo/infokey/Makefile,v 1.4.18.1 2008/11/25 02:59:29 kensmith Exp $

PROG=	infokey
SRCS=	infokey.c key.c

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/info ${TXIDIR}/doc
