#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: src/usr.bin/rlogin/Makefile,v 1.28.22.1.6.1 2010/12/21 17:09:25 kensmith Exp $

PROG=	rlogin

BINOWN=	root
BINMODE=4555
PRECIOUSPROG=

.include <bsd.prog.mk>
