#---------------------------------------------------------------------------
#
#	german holidays file 2001 / bundeseinheitliche Feiertage 2001
#	-------------------------------------------------------------
#
#	last edit-date: [Wed Jan 10 13:24:19 2001]
#
#	ref: http://hamburg.de/Services/ferien/ferien.htm
#
#	This file is only of value for installations which are
#	using the german Telekom "T-ISDN XXL" tariff where calls
#	on sundays and holidays are free of charge. Additional
#	configuration of /etc/isdnd.rc has to take place to enable
#	support for this tariff, see output of "man isdnd.rc" and
#	search for keyword "valid".
#
# $FreeBSD$
#
#---------------------------------------------------------------------------
#
# same day/month each year
#
1.1		Neujahr
1.5		1. Mai
3.10		Tag der deutschen Einheit
25.12		1. Weihnachtsfeiertag
26.12		2. Weihnachtsfeiertag
#
# different day/month each year
#
13.4.2001	Karfreitag
16.4.2001	Ostermontag
24.5.2001	Himmelfahrt
4.6.2001	Pfingstmontag
