# $FreeBSD: src/usr.sbin/named.reload/Makefile,v 1.9.18.1 2008/11/25 02:59:29 kensmith Exp $

SCRIPTS=	named.reload.sh
MAN=		named.reload.8

LINKS=		${BINDIR}/named.reload ${BINDIR}/named.reconfig
MLINKS=		named.reload.8 named.reconfig.8

.include <bsd.prog.mk>
