/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2015-2018, The Linux Foundation. All rights reserved. */
#ifndef	__DT_BINDINGS_QCOM_TCSR_H__
#define	__DT_BINDINGS_QCOM_TCSR_H__

#define	TCSR_USB_SELECT_USB3_P0			0x1
#define	TCSR_USB_SELECT_USB3_P1			0x2
#define	TCSR_USB_SELECT_USB3_DUAL		0x3

#define	TCSR_USB_HSPHY_HOST_MODE		0x00E700E7
#define	TCSR_USB_HSPHY_DEVICE_MODE		0x00C700E7

#define	TCSR_ESS_PSGMII			0
#define	TCSR_ESS_PSGMII_RGMII5		1
#define	TCSR_ESS_PSGMII_RMII0		2
#define	TCSR_ESS_PSGMII_RMII1		4
#define	TCSR_ESS_PSGMII_RMII0_RMII1	6
#define	TCSR_ESS_PSGMII_RGMII4	9

#define	TCSR_WIFI_GLB_CFG		0x41000000

#define	TCSR_WIFI_NOC_MEMTYPE_M0_M2	0x02222222

#define	IPQ806X_TCSR_REG_A_ADM_CRCI_MUX_SEL	0
#define	IPQ806X_TCSR_REG_B_ADM_CRCI_MUX_SEL	1

#endif
