# $FreeBSD: src/sys/modules/ugen/Makefile,v 1.14.24.1 2010/12/21 17:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	ugen
SRCS=	bus_if.h device_if.h opt_usb.h ugen.c usbdevs.h

.include <bsd.kmod.mk>
