# $FreeBSD: src/usr.sbin/lpr/Makefile,v 1.10.32.1.6.1 2010/12/21 17:09:25 kensmith Exp $

SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru SMM.doc

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
