# $FreeBSD$

SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru SMM.doc

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
