#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/usr.sbin/route6d/Makefile,v 1.12.14.1 2010/12/21 17:10:29 kensmith Exp $

PROG=	route6d
MAN=	route6d.8

CFLAGS+= -DHAVE_POLL_H

.include <bsd.prog.mk>
