#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/usr.sbin/route6d/Makefile,v 1.12.12.1 2010/02/10 00:26:20 kensmith Exp $

PROG=	route6d
MAN=	route6d.8

CFLAGS+= -DHAVE_POLL_H

.include <bsd.prog.mk>
