# $FreeBSD: src/sys/modules/ata/ataisa/Makefile,v 1.1.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $

.PATH: ${.CURDIR}/../../../dev/ata

KMOD=	ataisa
SRCS=	ata-isa.c
SRCS+=	opt_ata.h ata_if.h device_if.h bus_if.h isa_if.h

.include <bsd.kmod.mk>
