.\" $FreeBSD$
.\"
.Dd Feb 3, 1995
.Dt "PIANO" 6
.Os
.Sh NAME
.Nm piano
.Nd "a piano emulator"
.Sh SYNOPSIS
.Nm
.Op Fl vV
.Op Fl i Ar string
.Sh DESCRIPTION
The
.Nm
plays note by typing
.Em "QWERTYUIOP[]"
or
.Em "12 45 789 -=" .
Type
.Em ESC
key to quit
.Nm .
.Nm Piano
uses
.Em /dev/speaker .
.Pp
Available option:
.Bl -tag -width flag
.It Fl v
The
.Fl v
option causes
.Nm
to generate
.Em "play-string language" .
.It Fl V
The
.Fl V
option is for 
.Nm
usage.
.It Fl i Ar string
The
.Fl i
option initializes
.Em /dev/speaker
by
.Ar string .
The default value is 't160 o1 l16 ml'.
.El
.Sh FILES
.Bl -tag -width /dev/speakerxx
.It Pa /dev/speaker
speaker device file
.Sh SEE ALSO
.Xr spkr 4
.Sh AUTHORS
.An Toshihiro Kanda Aq candy@kgc.co.jp
Nov. 1993
