# $FreeBSD: src/include/protocols/Makefile,v 1.3.20.1 2009/04/15 03:14:26 kensmith Exp $

NO_OBJ=
INCS=	dumprestore.h routed.h rwhod.h talkd.h timed.h
INCSDIR=${INCLUDEDIR}/protocols

.include <bsd.prog.mk>
