.\"
.\" Copyright (c) 1992, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\" All rights reserved.
.\"
.\" This code is derived from software donated to Berkeley by
.\" Jan-Simon Pendry.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)mount_procfs.8	8.2 (Berkeley) 3/27/94
.\"
.\"
.Dd March 27, 1994
.Dt MOUNT_PROCFS 8
.Os BSD 4.4
.Sh NAME
.Nm mount_procfs
.Nd mount the process file system
.Sh SYNOPSIS
.Nm mount_procfs
.Op Fl o Ar options
.Pa /proc
.Pa mount_point
.Sh DESCRIPTION
The
.Nm mount_procfs
command attaches an instance of the process
namespace to the global filesystem namespace.
The conventional mount point is
.Pa /proc .
This command is normally executed by
.Xr mount 8
at boot time.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o
Options are specified with a
.Fl o
flag followed by a comma separated string of options.
See the
.Xr mount 8
man page for possible options and their meanings.
.El
.Pp
The root of the process filesystem
contains an entry for each active process.
These processes are visible as a directory whose
name is the process' pid.
In addition, the special entry
.Pa curproc
references the current process.
.Pp
Each directory contains several files.  See
.Xr procfs 5
for a detailed description of each file.
.Sh FILES
.Bl -tag -width /proc/curproc -compact
.It Pa /proc
normal mount point for the
.Nm procfs .
.It Pa /proc/pid
directory containg process information for process
.Pa pid .
.It Pa /proc/curproc
directory containing process information for the current process
.El
.Sh SEE ALSO
.Xr mount 2 ,
.Xr unmount 2 ,
.Xr procfs 5
.Sh CAVEATS
.Pp
This filesystem may not be NFS-exported
since most of the functionality of
.Dv procfs
requires that state be maintained.
.Sh HISTORY
The
.Nm mount_procfs
utility first appeared in
.Bx 4.4 .
