PACKAGE=	tests

ATF_TESTS_SH=	nuage utils nuageinit

${PACKAGE}FILES+=	addgroup.lua
${PACKAGE}FILES+=	addsshkey.lua
${PACKAGE}FILES+=	adduser.lua
${PACKAGE}FILES+=	dirname.lua
${PACKAGE}FILES+=	err.lua
${PACKAGE}FILES+=	sethostname.lua
${PACKAGE}FILES+=	warn.lua

.include <bsd.test.mk>
