#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/secure/usr.bin/bdes/Makefile,v 1.14.30.1.6.1 2010/12/21 17:09:25 kensmith Exp $

PROG=	bdes

WARNS?=	2

DPADD=	${LIBCRYPTO}
LDADD=	-lcrypto

.include <bsd.prog.mk>
