# $Id: Makefile,v 1.2 2000/07/14 18:16:25 iwasaki Exp $
# $FreeBSD: src/usr.sbin/acpi/acpiconf/Makefile,v 1.5 2004/11/13 01:54:22 philip Exp $

PROG=	acpiconf
MAN=	acpiconf.8
WARNS?=	6

.include <bsd.prog.mk>
