# $Id: Makefile,v 1.2 2000/07/14 18:16:25 iwasaki Exp $
# $FreeBSD: src/usr.sbin/acpi/acpiconf/Makefile,v 1.5.18.1 2008/11/25 02:59:29 kensmith Exp $

PROG=	acpiconf
MAN=	acpiconf.8
WARNS?=	6

.include <bsd.prog.mk>
