# $FreeBSD$

.PATH:	${BSDSRCTOP}/contrib/pf/authpf
.PATH:	${BSDSRCTOP}/contrib/pf/pfctl

PROG=	authpf

CFLAGS += -I${BSDSRCTOP}/contrib/pf/pfctl

# XXX ALTQ:
CFLAGS += -DENABLE_ALTQ

LDADD += -lm -lmd -lutil

SRCDIRDEP= contrib/pf/authpf
DIRDEP= gnu/lib/csu gnu/lib/libgcc include include/arpa lib/csu/MACHINE_ARCH lib/libc lib/libmd lib/libutil lib/msun stage sys/MACHINE_ARCH/include sys/net sys/netinet sys/netinet6 sys/sys sys/vm
.include <bsd.prog.mk>
