FILESDIR=	${FNTDIR}/devpost/charlib
FILES=	~= 12 \
	14 \
	34 \
	BRACKETS_NOTE \
	bx \
	ci \
	ff \
	Fi \
	Fl \
	L1 \
	L1.map \
	Lb \
	Lb.map \
	lc \
	lf \
	lh \
	LH_uc \
	LH.map \
	ob \
	OLD_LH \
	OLD_LH.map \
	rc \
	README \
	rf \
	rh \
	Sl \
	sq

.include <bsd.prog.mk>
.PATH: ${DOCTOOLSDIR}/troff/troff.d/font/devpost/charlib
