# $FreeBSD: src/sys/modules/alc/Makefile,v 1.1.4.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/alc

KMOD=	if_alc
SRCS=	if_alc.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
