# $FreeBSD: src/share/security/Makefile,v 1.4.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $

FILES=	lomac-policy.contexts
NO_OBJ=
FILESDIR=	${BINDIR}/security

.include "${.CURDIR}/../Makefile.inc"
.include <bsd.prog.mk>
