
# $FreeBSD: src/sys/modules/pps/Makefile,v 1.3.32.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH:	${.CURDIR}/../../dev/ppbus
KMOD=	pps
SRCS=	bus_if.h device_if.h ppbus_if.h \
	pps.c

.include <bsd.kmod.mk>
