#	From: @(#)Makefile	8.2 (Berkeley) 2/28/94
# $FreeBSD: src/share/doc/smm/08.sendmailop/Makefile,v 1.9.18.1 2008/11/25 02:59:29 kensmith Exp $

VOLUME=		smm/08.sendmailop
SRCS=		op.me
MACROS=		-me
USE_PIC=
USE_EQN=
SRCDIR=		${.CURDIR}/../../../../contrib/sendmail/doc/op

.include <bsd.doc.mk>
