#	From: @(#)Makefile	8.2 (Berkeley) 2/28/94
#	$FreeBSD$

VOLUME=	smm/08.sendmailop
SRCS=	op.me
MACROS=	-me

SRCDIR=	${.CURDIR}/../../../../usr.sbin/sendmail/doc/op

USE_PIC=	yes
USE_EQN=	yes

.include <bsd.doc.mk>
