/*
 * ntp_keyword.h
 * 
 * NOTE: edit this file with caution, it is generated by keyword-gen.c
 *	 Generated 2010-04-06 04:38:11 UTC	  diff_ignore_line
 *
 */
#include "ntp_scanner.h"
#include "ntp_parser.h"

#define LOWEST_KEYWORD_ID 258

const char * const keyword_text[163] = {
	/* 0       258                T_Age */	"age",
	/* 1       259                T_All */	"all",
	/* 2       260              T_Allan */	"allan",
	/* 3       261               T_Auth */	"auth",
	/* 4       262            T_Autokey */	"autokey",
	/* 5       263            T_Automax */	"automax",
	/* 6       264            T_Average */	"average",
	/* 7       265            T_Bclient */	"bclient",
	/* 8       266             T_Beacon */	"beacon",
	/* 9       267               T_Bias */	"bias",
	/* 10      268          T_Broadcast */	"broadcast",
	/* 11      269    T_Broadcastclient */	"broadcastclient",
	/* 12      270     T_Broadcastdelay */	"broadcastdelay",
	/* 13      271              T_Burst */	"burst",
	/* 14      272          T_Calibrate */	"calibrate",
	/* 15      273          T_Calldelay */	"calldelay",
	/* 16      274            T_Ceiling */	"ceiling",
	/* 17      275         T_Clockstats */	"clockstats",
	/* 18      276             T_Cohort */	"cohort",
	/* 19      277         T_ControlKey */	"controlkey",
	/* 20      278             T_Crypto */	"crypto",
	/* 21      279        T_Cryptostats */	"cryptostats",
	/* 22      280                T_Day */	"day",
	/* 23      281            T_Default */	"default",
	/* 24      282             T_Digest */	"digest",
	/* 25      283            T_Disable */	"disable",
	/* 26      284            T_Discard */	"discard",
	/* 27      285         T_Dispersion */	"dispersion",
	/* 28      286             T_Double */	NULL,
	/* 29      287          T_Driftfile */	"driftfile",
	/* 30      288               T_Drop */	"drop",
	/* 31      289           T_Ellipsis */	"...",
	/* 32      290             T_Enable */	"enable",
	/* 33      291                T_End */	"end",
	/* 34      292              T_False */	NULL,
	/* 35      293               T_File */	"file",
	/* 36      294            T_Filegen */	"filegen",
	/* 37      295              T_Flag1 */	"flag1",
	/* 38      296              T_Flag2 */	"flag2",
	/* 39      297              T_Flag3 */	"flag3",
	/* 40      298              T_Flag4 */	"flag4",
	/* 41      299              T_Flake */	"flake",
	/* 42      300              T_Floor */	"floor",
	/* 43      301               T_Freq */	"freq",
	/* 44      302              T_Fudge */	"fudge",
	/* 45      303               T_Host */	"host",
	/* 46      304           T_Huffpuff */	"huffpuff",
	/* 47      305             T_Iburst */	"iburst",
	/* 48      306              T_Ident */	"ident",
	/* 49      307             T_Ignore */	"ignore",
	/* 50      308        T_Includefile */	"includefile",
	/* 51      309            T_Integer */	NULL,
	/* 52      310          T_Interface */	"interface",
	/* 53      311               T_Ipv4 */	"ipv4",
	/* 54      312          T_Ipv4_flag */	"-4",
	/* 55      313               T_Ipv6 */	"ipv6",
	/* 56      314          T_Ipv6_flag */	"-6",
	/* 57      315             T_Kernel */	"kernel",
	/* 58      316                T_Key */	"key",
	/* 59      317               T_Keys */	"keys",
	/* 60      318            T_Keysdir */	"keysdir",
	/* 61      319                T_Kod */	"kod",
	/* 62      320             T_Mssntp */	"mssntp",
	/* 63      321           T_Leapfile */	"leapfile",
	/* 64      322            T_Limited */	"limited",
	/* 65      323               T_Link */	"link",
	/* 66      324             T_Listen */	"listen",
	/* 67      325          T_Logconfig */	"logconfig",
	/* 68      326            T_Logfile */	"logfile",
	/* 69      327          T_Loopstats */	"loopstats",
	/* 70      328        T_Lowpriotrap */	"lowpriotrap",
	/* 71      329     T_Manycastclient */	"manycastclient",
	/* 72      330     T_Manycastserver */	"manycastserver",
	/* 73      331               T_Mask */	"mask",
	/* 74      332           T_Maxclock */	"maxclock",
	/* 75      333            T_Maxdist */	"maxdist",
	/* 76      334            T_Maxpoll */	"maxpoll",
	/* 77      335           T_Minclock */	"minclock",
	/* 78      336            T_Mindist */	"mindist",
	/* 79      337            T_Minimum */	"minimum",
	/* 80      338            T_Minpoll */	"minpoll",
	/* 81      339            T_Minsane */	"minsane",
	/* 82      340               T_Mode */	"mode",
	/* 83      341            T_Monitor */	"monitor",
	/* 84      342              T_Month */	"month",
	/* 85      343    T_Multicastclient */	"multicastclient",
	/* 86      344                T_Nic */	"nic",
	/* 87      345             T_Nolink */	"nolink",
	/* 88      346           T_Nomodify */	"nomodify",
	/* 89      347               T_None */	"none",
	/* 90      348             T_Nopeer */	"nopeer",
	/* 91      349            T_Noquery */	"noquery",
	/* 92      350           T_Noselect */	"noselect",
	/* 93      351            T_Noserve */	"noserve",
	/* 94      352             T_Notrap */	"notrap",
	/* 95      353            T_Notrust */	"notrust",
	/* 96      354                T_Ntp */	"ntp",
	/* 97      355            T_Ntpport */	"ntpport",
	/* 98      356     T_NtpSignDsocket */	"ntpsigndsocket",
	/* 99      357             T_Orphan */	"orphan",
	/* 100     358              T_Panic */	"panic",
	/* 101     359               T_Peer */	"peer",
	/* 102     360          T_Peerstats */	"peerstats",
	/* 103     361              T_Phone */	"phone",
	/* 104     362                T_Pid */	"pid",
	/* 105     363            T_Pidfile */	"pidfile",
	/* 106     364               T_Pool */	"pool",
	/* 107     365               T_Port */	"port",
	/* 108     366            T_Preempt */	"preempt",
	/* 109     367             T_Prefer */	"prefer",
	/* 110     368         T_Protostats */	"protostats",
	/* 111     369                 T_Pw */	"pw",
	/* 112     370                T_Qos */	"qos",
	/* 113     371           T_Randfile */	"randfile",
	/* 114     372           T_Rawstats */	"rawstats",
	/* 115     373              T_Refid */	"refid",
	/* 116     374         T_Requestkey */	"requestkey",
	/* 117     375           T_Restrict */	"restrict",
	/* 118     376             T_Revoke */	"revoke",
	/* 119     377      T_Saveconfigdir */	"saveconfigdir",
	/* 120     378             T_Server */	"server",
	/* 121     379             T_Setvar */	"setvar",
	/* 122     380               T_Sign */	"sign",
	/* 123     381         T_Statistics */	"statistics",
	/* 124     382              T_Stats */	"stats",
	/* 125     383           T_Statsdir */	"statsdir",
	/* 126     384               T_Step */	"step",
	/* 127     385            T_Stepout */	"stepout",
	/* 128     386            T_Stratum */	"stratum",
	/* 129     387             T_String */	NULL,
	/* 130     388           T_Sysstats */	"sysstats",
	/* 131     389               T_Tick */	"tick",
	/* 132     390              T_Time1 */	"time1",
	/* 133     391              T_Time2 */	"time2",
	/* 134     392        T_Timingstats */	"timingstats",
	/* 135     393             T_Tinker */	"tinker",
	/* 136     394                T_Tos */	"tos",
	/* 137     395               T_Trap */	"trap",
	/* 138     396               T_True */	"true",
	/* 139     397         T_Trustedkey */	"trustedkey",
	/* 140     398                T_Ttl */	"ttl",
	/* 141     399               T_Type */	"type",
	/* 142     400           T_Unconfig */	"unconfig",
	/* 143     401             T_Unpeer */	"unpeer",
	/* 144     402            T_Version */	"version",
	/* 145     403    T_WanderThreshold */	NULL,
	/* 146     404               T_Week */	"week",
	/* 147     405           T_Wildcard */	"wildcard",
	/* 148     406             T_Xleave */	"xleave",
	/* 149     407               T_Year */	"year",
	/* 150     408               T_Flag */	NULL,
	/* 151     409               T_Void */	NULL,
	/* 152     410                T_EOC */	NULL,
	/* 153     411           T_Simulate */	"simulate",
	/* 154     412         T_Beep_Delay */	"beep_delay",
	/* 155     413       T_Sim_Duration */	"simulation_duration",
	/* 156     414      T_Server_Offset */	"server_offset",
	/* 157     415           T_Duration */	"duration",
	/* 158     416        T_Freq_Offset */	"freq_offset",
	/* 159     417             T_Wander */	"wander",
	/* 160     418             T_Jitter */	"jitter",
	/* 161     419         T_Prop_Delay */	"prop_delay",
	/* 162     420         T_Proc_Delay */	"proc_delay"
};

#define SCANNER_INIT_S 742

const scan_state sst[745] = {
/*SS_T( ch,	f-by, match, other ),				 */
  0,				      /*     0                   */
  S_ST( '-',	3,      314,     0 ), /*     1                   */
  S_ST( '.',	3,        3,     1 ), /*     2                   */
  S_ST( '.',	3,      289,     0 ), /*     3                   */
  S_ST( 'a',	3,       15,     2 ), /*     4                   */
  S_ST( 'g',	3,      258,     0 ), /*     5                   */
  S_ST( 'l',	3,      259,     5 ), /*     6                   */
  S_ST( 'a',	3,      260,     0 ), /*     7                   */
  S_ST( 'u',	3,        9,     6 ), /*     8                   */
  S_ST( 't',	3,       10,     0 ), /*     9                   */
  S_ST( 'o',	3,       13,   261 ), /*    10                   */
  S_ST( 'k',	3,       12,     0 ), /*    11                   */
  S_ST( 'e',	3,      262,     0 ), /*    12                   */
  S_ST( 'm',	3,       14,    11 ), /*    13                   */
  S_ST( 'a',	3,      263,     0 ), /*    14                   */
  S_ST( 'v',	3,       16,     8 ), /*    15                   */
  S_ST( 'e',	3,       17,     0 ), /*    16                   */
  S_ST( 'r',	3,       18,     0 ), /*    17                   */
  S_ST( 'a',	3,       19,     0 ), /*    18                   */
  S_ST( 'g',	3,      264,     0 ), /*    19                   */
  S_ST( 'b',	3,       55,     4 ), /*    20                   */
  S_ST( 'c',	3,       22,     0 ), /*    21                   */
  S_ST( 'l',	3,       23,     0 ), /*    22                   */
  S_ST( 'i',	3,       24,     0 ), /*    23                   */
  S_ST( 'e',	3,       25,     0 ), /*    24                   */
  S_ST( 'n',	3,      265,     0 ), /*    25                   */
  S_ST( 'e',	3,       30,    21 ), /*    26                   */
  S_ST( 'a',	3,       28,     0 ), /*    27                   */
  S_ST( 'c',	3,       29,     0 ), /*    28                   */
  S_ST( 'o',	3,      266,     0 ), /*    29                   */
  S_ST( 'e',	3,       31,    27 ), /*    30                   */
  S_ST( 'p',	3,       32,     0 ), /*    31                   */
  S_ST( '_',	3,       33,     0 ), /*    32                   */
  S_ST( 'd',	3,       34,     0 ), /*    33                   */
  S_ST( 'e',	3,       35,     0 ), /*    34                   */
  S_ST( 'l',	3,       36,     0 ), /*    35                   */
  S_ST( 'a',	3,      412,     0 ), /*    36                   */
  S_ST( 'i',	3,       38,    26 ), /*    37                   */
  S_ST( 'a',	3,      267,     0 ), /*    38                   */
  S_ST( 'r',	3,       40,    37 ), /*    39                   */
  S_ST( 'o',	3,       41,     0 ), /*    40                   */
  S_ST( 'a',	3,       42,     0 ), /*    41                   */
  S_ST( 'd',	3,       43,     0 ), /*    42                   */
  S_ST( 'c',	3,       44,     0 ), /*    43                   */
  S_ST( 'a',	3,       45,     0 ), /*    44                   */
  S_ST( 's',	3,      268,     0 ), /*    45                   */
  S_ST( 'c',	3,       47,     0 ), /*    46                   */
  S_ST( 'l',	3,       48,     0 ), /*    47                   */
  S_ST( 'i',	3,       49,     0 ), /*    48                   */
  S_ST( 'e',	3,       50,     0 ), /*    49                   */
  S_ST( 'n',	3,      269,     0 ), /*    50                   */
  S_ST( 'd',	3,       52,    46 ), /*    51                   */
  S_ST( 'e',	3,       53,     0 ), /*    52                   */
  S_ST( 'l',	3,       54,     0 ), /*    53                   */
  S_ST( 'a',	3,      270,     0 ), /*    54                   */
  S_ST( 'u',	3,       56,    39 ), /*    55                   */
  S_ST( 'r',	3,       57,     0 ), /*    56                   */
  S_ST( 's',	3,      271,     0 ), /*    57                   */
  S_ST( 'c',	3,       95,    20 ), /*    58                   */
  S_ST( 'a',	3,       60,     0 ), /*    59                   */
  S_ST( 'l',	3,       66,     0 ), /*    60                   */
  S_ST( 'i',	3,       62,     0 ), /*    61                   */
  S_ST( 'b',	3,       63,     0 ), /*    62                   */
  S_ST( 'r',	3,       64,     0 ), /*    63                   */
  S_ST( 'a',	3,       65,     0 ), /*    64                   */
  S_ST( 't',	3,      272,     0 ), /*    65                   */
  S_ST( 'l',	3,       67,    61 ), /*    66                   */
  S_ST( 'd',	3,       68,     0 ), /*    67                   */
  S_ST( 'e',	3,       69,     0 ), /*    68                   */
  S_ST( 'l',	3,       70,     0 ), /*    69                   */
  S_ST( 'a',	3,      273,     0 ), /*    70                   */
  S_ST( 'e',	3,       72,    59 ), /*    71                   */
  S_ST( 'i',	3,       73,     0 ), /*    72                   */
  S_ST( 'l',	3,       74,     0 ), /*    73                   */
  S_ST( 'i',	3,       75,     0 ), /*    74                   */
  S_ST( 'n',	3,      274,     0 ), /*    75                   */
  S_ST( 'l',	3,       77,    71 ), /*    76                   */
  S_ST( 'o',	3,       78,     0 ), /*    77                   */
  S_ST( 'c',	3,       79,     0 ), /*    78                   */
  S_ST( 'k',	3,       80,     0 ), /*    79                   */
  S_ST( 's',	3,       81,     0 ), /*    80                   */
  S_ST( 't',	3,       82,     0 ), /*    81                   */
  S_ST( 'a',	3,       83,     0 ), /*    82                   */
  S_ST( 't',	3,      275,     0 ), /*    83                   */
  S_ST( 'o',	3,       88,    76 ), /*    84                   */
  S_ST( 'h',	3,       86,     0 ), /*    85                   */
  S_ST( 'o',	3,       87,     0 ), /*    86                   */
  S_ST( 'r',	3,      276,     0 ), /*    87                   */
  S_ST( 'n',	3,       89,    85 ), /*    88                   */
  S_ST( 't',	3,       90,     0 ), /*    89                   */
  S_ST( 'r',	3,       91,     0 ), /*    90                   */
  S_ST( 'o',	3,       92,     0 ), /*    91                   */
  S_ST( 'l',	3,       93,     0 ), /*    92                   */
  S_ST( 'k',	3,       94,     0 ), /*    93                   */
  S_ST( 'e',	3,      277,     0 ), /*    94                   */
  S_ST( 'r',	3,       96,    84 ), /*    95                   */
  S_ST( 'y',	3,       97,     0 ), /*    96                   */
  S_ST( 'p',	3,       98,     0 ), /*    97                   */
  S_ST( 't',	3,      278,     0 ), /*    98                   */
  S_ST( 's',	3,      100,     0 ), /*    99                   */
  S_ST( 't',	3,      101,     0 ), /*   100                   */
  S_ST( 'a',	3,      102,     0 ), /*   101                   */
  S_ST( 't',	3,      279,     0 ), /*   102                   */
  S_ST( 'd',	3,      135,    58 ), /*   103                   */
  S_ST( 'a',	3,      280,     0 ), /*   104                   */
  S_ST( 'e',	3,      106,   104 ), /*   105                   */
  S_ST( 'f',	3,      107,     0 ), /*   106                   */
  S_ST( 'a',	3,      108,     0 ), /*   107                   */
  S_ST( 'u',	3,      109,     0 ), /*   108                   */
  S_ST( 'l',	3,      281,     0 ), /*   109                   */
  S_ST( 'i',	3,      114,   105 ), /*   110                   */
  S_ST( 'g',	3,      112,     0 ), /*   111                   */
  S_ST( 'e',	3,      113,     0 ), /*   112                   */
  S_ST( 's',	3,      282,     0 ), /*   113                   */
  S_ST( 's',	3,      121,   111 ), /*   114                   */
  S_ST( 'a',	3,      116,     0 ), /*   115                   */
  S_ST( 'b',	3,      117,     0 ), /*   116                   */
  S_ST( 'l',	3,      283,     0 ), /*   117                   */
  S_ST( 'c',	3,      119,   115 ), /*   118                   */
  S_ST( 'a',	3,      120,     0 ), /*   119                   */
  S_ST( 'r',	3,      284,     0 ), /*   120                   */
  S_ST( 'p',	3,      122,   118 ), /*   121                   */
  S_ST( 'e',	3,      123,     0 ), /*   122                   */
  S_ST( 'r',	3,      124,     0 ), /*   123                   */
  S_ST( 's',	3,      125,     0 ), /*   124                   */
  S_ST( 'i',	3,      126,     0 ), /*   125                   */
  S_ST( 'o',	3,      285,     0 ), /*   126                   */
  S_ST( 'r',	3,      134,   110 ), /*   127                   */
  S_ST( 'i',	3,      129,     0 ), /*   128                   */
  S_ST( 'f',	3,      130,     0 ), /*   129                   */
  S_ST( 't',	3,      131,     0 ), /*   130                   */
  S_ST( 'f',	3,      132,     0 ), /*   131                   */
  S_ST( 'i',	3,      133,     0 ), /*   132                   */
  S_ST( 'l',	3,      287,     0 ), /*   133                   */
  S_ST( 'o',	3,      288,   128 ), /*   134                   */
  S_ST( 'u',	3,      136,   127 ), /*   135                   */
  S_ST( 'r',	3,      137,     0 ), /*   136                   */
  S_ST( 'a',	3,      138,     0 ), /*   137                   */
  S_ST( 't',	3,      139,     0 ), /*   138                   */
  S_ST( 'i',	3,      140,     0 ), /*   139                   */
  S_ST( 'o',	3,      415,     0 ), /*   140                   */
  S_ST( 'e',	3,      142,   103 ), /*   141                   */
  S_ST( 'n',	3,      291,     0 ), /*   142                   */
  S_ST( 'a',	3,      144,     0 ), /*   143                   */
  S_ST( 'b',	3,      145,     0 ), /*   144                   */
  S_ST( 'l',	3,      290,     0 ), /*   145                   */
  S_ST( 'f',	3,      165,   141 ), /*   146                   */
  S_ST( 'i',	3,      148,     0 ), /*   147                   */
  S_ST( 'l',	3,      293,     0 ), /*   148                   */
  S_ST( 'g',	3,      150,     0 ), /*   149                   */
  S_ST( 'e',	3,      294,     0 ), /*   150                   */
  S_ST( 'l',	3,      155,   147 ), /*   151                   */
  S_ST( 'a',	3,      154,     0 ), /*   152                   */
  S_ST( 'g',	3,      298,     0 ), /*   153                   */
  S_ST( 'k',	3,      299,   153 ), /*   154                   */
  S_ST( 'o',	3,      156,   152 ), /*   155                   */
  S_ST( 'o',	3,      300,     0 ), /*   156                   */
  S_ST( 'r',	3,      158,   151 ), /*   157                   */
  S_ST( 'e',	3,      301,     0 ), /*   158                   */
  S_ST( '_',	3,      160,     0 ), /*   159                   */
  S_ST( 'o',	3,      161,     0 ), /*   160                   */
  S_ST( 'f',	3,      162,     0 ), /*   161                   */
  S_ST( 'f',	3,      163,     0 ), /*   162                   */
  S_ST( 's',	3,      164,     0 ), /*   163                   */
  S_ST( 'e',	3,      416,     0 ), /*   164                   */
  S_ST( 'u',	3,      166,   157 ), /*   165                   */
  S_ST( 'd',	3,      167,     0 ), /*   166                   */
  S_ST( 'g',	3,      302,     0 ), /*   167                   */
  S_ST( 'h',	3,      171,   146 ), /*   168                   */
  S_ST( 'o',	3,      170,     0 ), /*   169                   */
  S_ST( 's',	3,      303,     0 ), /*   170                   */
  S_ST( 'u',	3,      172,   169 ), /*   171                   */
  S_ST( 'f',	3,      173,     0 ), /*   172                   */
  S_ST( 'f',	3,      174,     0 ), /*   173                   */
  S_ST( 'p',	3,      175,     0 ), /*   174                   */
  S_ST( 'u',	3,      176,     0 ), /*   175                   */
  S_ST( 'f',	3,      304,     0 ), /*   176                   */
  S_ST( 'i',	3,      204,   168 ), /*   177                   */
  S_ST( 'b',	3,      179,     0 ), /*   178                   */
  S_ST( 'u',	3,      180,     0 ), /*   179                   */
  S_ST( 'r',	3,      181,     0 ), /*   180                   */
  S_ST( 's',	3,      305,     0 ), /*   181                   */
  S_ST( 'd',	3,      183,   178 ), /*   182                   */
  S_ST( 'e',	3,      184,     0 ), /*   183                   */
  S_ST( 'n',	3,      306,     0 ), /*   184                   */
  S_ST( 'g',	3,      186,   182 ), /*   185                   */
  S_ST( 'n',	3,      187,     0 ), /*   186                   */
  S_ST( 'o',	3,      188,     0 ), /*   187                   */
  S_ST( 'r',	3,      307,     0 ), /*   188                   */
  S_ST( 'n',	3,      198,   185 ), /*   189                   */
  S_ST( 'c',	3,      191,     0 ), /*   190                   */
  S_ST( 'l',	3,      192,     0 ), /*   191                   */
  S_ST( 'u',	3,      193,     0 ), /*   192                   */
  S_ST( 'd',	3,      194,     0 ), /*   193                   */
  S_ST( 'e',	3,      195,     0 ), /*   194                   */
  S_ST( 'f',	3,      196,     0 ), /*   195                   */
  S_ST( 'i',	3,      197,     0 ), /*   196                   */
  S_ST( 'l',	3,      308,     0 ), /*   197                   */
  S_ST( 't',	3,      199,   190 ), /*   198                   */
  S_ST( 'e',	3,      200,     0 ), /*   199                   */
  S_ST( 'r',	3,      201,     0 ), /*   200                   */
  S_ST( 'f',	3,      202,     0 ), /*   201                   */
  S_ST( 'a',	3,      203,     0 ), /*   202                   */
  S_ST( 'c',	3,      310,     0 ), /*   203                   */
  S_ST( 'p',	3,      205,   189 ), /*   204                   */
  S_ST( 'v',	3,      313,     0 ), /*   205                   */
  S_ST( 'j',	3,      207,   177 ), /*   206                   */
  S_ST( 'i',	3,      208,     0 ), /*   207                   */
  S_ST( 't',	3,      209,     0 ), /*   208                   */
  S_ST( 't',	3,      210,     0 ), /*   209                   */
  S_ST( 'e',	3,      418,     0 ), /*   210                   */
  S_ST( 'k',	3,      218,   206 ), /*   211                   */
  S_ST( 'e',	3,      316,     0 ), /*   212                   */
  S_ST( 'r',	3,      214,     0 ), /*   213                   */
  S_ST( 'n',	3,      215,     0 ), /*   214                   */
  S_ST( 'e',	3,      315,     0 ), /*   215                   */
  S_ST( 'd',	3,      217,     0 ), /*   216                   */
  S_ST( 'i',	3,      318,     0 ), /*   217                   */
  S_ST( 'o',	3,      319,   212 ), /*   218                   */
  S_ST( 'l',	3,      235,   211 ), /*   219                   */
  S_ST( 'e',	3,      221,     0 ), /*   220                   */
  S_ST( 'a',	3,      222,     0 ), /*   221                   */
  S_ST( 'p',	3,      223,     0 ), /*   222                   */
  S_ST( 'f',	3,      224,     0 ), /*   223                   */
  S_ST( 'i',	3,      225,     0 ), /*   224                   */
  S_ST( 'l',	3,      321,     0 ), /*   225                   */
  S_ST( 'i',	3,      232,   220 ), /*   226                   */
  S_ST( 'm',	3,      228,     0 ), /*   227                   */
  S_ST( 'i',	3,      229,     0 ), /*   228                   */
  S_ST( 't',	3,      230,     0 ), /*   229                   */
  S_ST( 'e',	3,      322,     0 ), /*   230                   */
  S_ST( 'n',	3,      323,   227 ), /*   231                   */
  S_ST( 's',	3,      233,   231 ), /*   232                   */
  S_ST( 't',	3,      234,     0 ), /*   233                   */
  S_ST( 'e',	3,      324,     0 ), /*   234                   */
  S_ST( 'o',	3,      251,   226 ), /*   235                   */
  S_ST( 'g',	3,      242,     0 ), /*   236                   */
  S_ST( 'c',	3,      238,     0 ), /*   237                   */
  S_ST( 'o',	3,      239,     0 ), /*   238                   */
  S_ST( 'n',	3,      240,     0 ), /*   239                   */
  S_ST( 'f',	3,      241,     0 ), /*   240                   */
  S_ST( 'i',	3,      325,     0 ), /*   241                   */
  S_ST( 'f',	3,      243,   237 ), /*   242                   */
  S_ST( 'i',	3,      244,     0 ), /*   243                   */
  S_ST( 'l',	3,      326,     0 ), /*   244                   */
  S_ST( 'o',	3,      246,   236 ), /*   245                   */
  S_ST( 'p',	3,      247,     0 ), /*   246                   */
  S_ST( 's',	3,      248,     0 ), /*   247                   */
  S_ST( 't',	3,      249,     0 ), /*   248                   */
  S_ST( 'a',	3,      250,     0 ), /*   249                   */
  S_ST( 't',	3,      327,     0 ), /*   250                   */
  S_ST( 'w',	3,      252,   245 ), /*   251                   */
  S_ST( 'p',	3,      253,     0 ), /*   252                   */
  S_ST( 'r',	3,      254,     0 ), /*   253                   */
  S_ST( 'i',	3,      255,     0 ), /*   254                   */
  S_ST( 'o',	3,      256,     0 ), /*   255                   */
  S_ST( 't',	3,      257,     0 ), /*   256                   */
  S_ST( 'r',	3,      286,     0 ), /*   257                   */
  S_ST( 'e',	0,        0,     0 ), /*   258 T_Age             */
  S_ST( 'l',	0,        7,     0 ), /*   259 T_All             */
  S_ST( 'n',	0,        0,     0 ), /*   260 T_Allan           */
  S_ST( 'h',	0,        0,     0 ), /*   261 T_Auth            */
  S_ST( 'y',	0,        0,     0 ), /*   262 T_Autokey         */
  S_ST( 'x',	0,        0,     0 ), /*   263 T_Automax         */
  S_ST( 'e',	0,        0,     0 ), /*   264 T_Average         */
  S_ST( 't',	0,        0,     0 ), /*   265 T_Bclient         */
  S_ST( 'n',	0,        0,     0 ), /*   266 T_Beacon          */
  S_ST( 's',	0,        0,     0 ), /*   267 T_Bias            */
  S_ST( 't',	1,       51,     0 ), /*   268 T_Broadcast       */
  S_ST( 't',	0,        0,     0 ), /*   269 T_Broadcastclient */
  S_ST( 'y',	0,        0,     0 ), /*   270 T_Broadcastdelay  */
  S_ST( 't',	0,        0,     0 ), /*   271 T_Burst           */
  S_ST( 'e',	0,        0,     0 ), /*   272 T_Calibrate       */
  S_ST( 'y',	0,        0,     0 ), /*   273 T_Calldelay       */
  S_ST( 'g',	0,        0,     0 ), /*   274 T_Ceiling         */
  S_ST( 's',	0,        0,     0 ), /*   275 T_Clockstats      */
  S_ST( 't',	0,        0,     0 ), /*   276 T_Cohort          */
  S_ST( 'y',	0,        0,     0 ), /*   277 T_ControlKey      */
  S_ST( 'o',	0,       99,     0 ), /*   278 T_Crypto          */
  S_ST( 's',	0,        0,     0 ), /*   279 T_Cryptostats     */
  S_ST( 'y',	0,        0,     0 ), /*   280 T_Day             */
  S_ST( 't',	0,        0,     0 ), /*   281 T_Default         */
  S_ST( 't',	1,        0,     0 ), /*   282 T_Digest          */
  S_ST( 'e',	0,        0,     0 ), /*   283 T_Disable         */
  S_ST( 'd',	0,        0,     0 ), /*   284 T_Discard         */
  S_ST( 'n',	0,        0,     0 ), /*   285 T_Dispersion      */
  S_ST( 'a',	3,      328,     0 ), /*   286                   */
  S_ST( 'e',	1,        0,     0 ), /*   287 T_Driftfile       */
  S_ST( 'p',	0,        0,     0 ), /*   288 T_Drop            */
  S_ST( '.',	0,        0,     0 ), /*   289 T_Ellipsis        */
  S_ST( 'e',	0,        0,     0 ), /*   290 T_Enable          */
  S_ST( 'd',	0,        0,   143 ), /*   291 T_End             */
  S_ST( 'm',	3,      473,   219 ), /*   292                   */
  S_ST( 'e',	1,      149,     0 ), /*   293 T_File            */
  S_ST( 'n',	0,        0,     0 ), /*   294 T_Filegen         */
  S_ST( '1',	0,        0,     0 ), /*   295 T_Flag1           */
  S_ST( '2',	0,        0,   295 ), /*   296 T_Flag2           */
  S_ST( '3',	0,        0,   296 ), /*   297 T_Flag3           */
  S_ST( '4',	0,        0,   297 ), /*   298 T_Flag4           */
  S_ST( 'e',	0,        0,     0 ), /*   299 T_Flake           */
  S_ST( 'r',	0,        0,     0 ), /*   300 T_Floor           */
  S_ST( 'q',	0,      159,     0 ), /*   301 T_Freq            */
  S_ST( 'e',	1,        0,     0 ), /*   302 T_Fudge           */
  S_ST( 't',	1,        0,     0 ), /*   303 T_Host            */
  S_ST( 'f',	0,        0,     0 ), /*   304 T_Huffpuff        */
  S_ST( 't',	0,        0,     0 ), /*   305 T_Iburst          */
  S_ST( 't',	1,        0,     0 ), /*   306 T_Ident           */
  S_ST( 'e',	0,        0,     0 ), /*   307 T_Ignore          */
  S_ST( 'e',	1,        0,     0 ), /*   308 T_Includefile     */
  S_ST( 'a',	3,      433,     0 ), /*   309                   */
  S_ST( 'e',	0,        0,     0 ), /*   310 T_Interface       */
  S_ST( '4',	0,        0,     0 ), /*   311 T_Ipv4            */
  S_ST( '4',	0,        0,     0 ), /*   312 T_Ipv4_flag       */
  S_ST( '6',	0,        0,   311 ), /*   313 T_Ipv6            */
  S_ST( '6',	0,        0,   312 ), /*   314 T_Ipv6_flag       */
  S_ST( 'l',	0,        0,     0 ), /*   315 T_Kernel          */
  S_ST( 'y',	0,      317,   213 ), /*   316 T_Key             */
  S_ST( 's',	1,      216,     0 ), /*   317 T_Keys            */
  S_ST( 'r',	1,        0,     0 ), /*   318 T_Keysdir         */
  S_ST( 'd',	0,        0,     0 ), /*   319 T_Kod             */
  S_ST( 'p',	0,        0,     0 ), /*   320 T_Mssntp          */
  S_ST( 'e',	1,        0,     0 ), /*   321 T_Leapfile        */
  S_ST( 'd',	0,        0,     0 ), /*   322 T_Limited         */
  S_ST( 'k',	0,        0,     0 ), /*   323 T_Link            */
  S_ST( 'n',	0,        0,     0 ), /*   324 T_Listen          */
  S_ST( 'g',	2,        0,     0 ), /*   325 T_Logconfig       */
  S_ST( 'e',	1,        0,     0 ), /*   326 T_Logfile         */
  S_ST( 's',	0,        0,     0 ), /*   327 T_Loopstats       */
  S_ST( 'p',	0,        0,     0 ), /*   328 T_Lowpriotrap     */
  S_ST( 't',	1,        0,     0 ), /*   329 T_Manycastclient  */
  S_ST( 'r',	2,        0,     0 ), /*   330 T_Manycastserver  */
  S_ST( 'k',	0,        0,     0 ), /*   331 T_Mask            */
  S_ST( 'k',	0,        0,     0 ), /*   332 T_Maxclock        */
  S_ST( 't',	0,        0,     0 ), /*   333 T_Maxdist         */
  S_ST( 'l',	0,        0,     0 ), /*   334 T_Maxpoll         */
  S_ST( 'k',	0,        0,     0 ), /*   335 T_Minclock        */
  S_ST( 't',	0,        0,     0 ), /*   336 T_Mindist         */
  S_ST( 'm',	0,        0,     0 ), /*   337 T_Minimum         */
  S_ST( 'l',	0,        0,     0 ), /*   338 T_Minpoll         */
  S_ST( 'e',	0,        0,     0 ), /*   339 T_Minsane         */
  S_ST( 'e',	0,        0,     0 ), /*   340 T_Mode            */
  S_ST( 'r',	0,        0,     0 ), /*   341 T_Monitor         */
  S_ST( 'h',	0,        0,     0 ), /*   342 T_Month           */
  S_ST( 't',	2,        0,     0 ), /*   343 T_Multicastclient */
  S_ST( 'c',	0,        0,     0 ), /*   344 T_Nic             */
  S_ST( 'k',	0,        0,     0 ), /*   345 T_Nolink          */
  S_ST( 'y',	0,        0,     0 ), /*   346 T_Nomodify        */
  S_ST( 'e',	0,        0,     0 ), /*   347 T_None            */
  S_ST( 'r',	0,        0,     0 ), /*   348 T_Nopeer          */
  S_ST( 'y',	0,        0,     0 ), /*   349 T_Noquery         */
  S_ST( 't',	0,        0,     0 ), /*   350 T_Noselect        */
  S_ST( 'e',	0,        0,     0 ), /*   351 T_Noserve         */
  S_ST( 'p',	0,        0,     0 ), /*   352 T_Notrap          */
  S_ST( 't',	0,        0,     0 ), /*   353 T_Notrust         */
  S_ST( 'p',	0,      521,     0 ), /*   354 T_Ntp             */
  S_ST( 't',	0,        0,     0 ), /*   355 T_Ntpport         */
  S_ST( 't',	1,        0,     0 ), /*   356 T_NtpSignDsocket  */
  S_ST( 'n',	0,        0,     0 ), /*   357 T_Orphan          */
  S_ST( 'c',	0,        0,     0 ), /*   358 T_Panic           */
  S_ST( 'r',	1,      542,     0 ), /*   359 T_Peer            */
  S_ST( 's',	0,        0,     0 ), /*   360 T_Peerstats       */
  S_ST( 'e',	2,        0,     0 ), /*   361 T_Phone           */
  S_ST( 'd',	0,      550,     0 ), /*   362 T_Pid             */
  S_ST( 'e',	1,        0,     0 ), /*   363 T_Pidfile         */
  S_ST( 'l',	1,        0,     0 ), /*   364 T_Pool            */
  S_ST( 't',	0,        0,     0 ), /*   365 T_Port            */
  S_ST( 't',	0,        0,     0 ), /*   366 T_Preempt         */
  S_ST( 'r',	0,        0,     0 ), /*   367 T_Prefer          */
  S_ST( 's',	0,        0,     0 ), /*   368 T_Protostats      */
  S_ST( 'w',	1,        0,   556 ), /*   369 T_Pw              */
  S_ST( 's',	0,        0,     0 ), /*   370 T_Qos             */
  S_ST( 'e',	1,        0,     0 ), /*   371 T_Randfile        */
  S_ST( 's',	0,        0,     0 ), /*   372 T_Rawstats        */
  S_ST( 'd',	1,        0,     0 ), /*   373 T_Refid           */
  S_ST( 'y',	0,        0,     0 ), /*   374 T_Requestkey      */
  S_ST( 't',	0,        0,     0 ), /*   375 T_Restrict        */
  S_ST( 'e',	0,        0,     0 ), /*   376 T_Revoke          */
  S_ST( 'r',	1,        0,     0 ), /*   377 T_Saveconfigdir   */
  S_ST( 'r',	1,      630,     0 ), /*   378 T_Server          */
  S_ST( 'r',	1,        0,     0 ), /*   379 T_Setvar          */
  S_ST( 'n',	1,        0,     0 ), /*   380 T_Sign            */
  S_ST( 's',	0,        0,     0 ), /*   381 T_Statistics      */
  S_ST( 's',	0,      665,   660 ), /*   382 T_Stats           */
  S_ST( 'r',	1,        0,     0 ), /*   383 T_Statsdir        */
  S_ST( 'p',	0,      668,     0 ), /*   384 T_Step            */
  S_ST( 't',	0,        0,     0 ), /*   385 T_Stepout         */
  S_ST( 'm',	0,        0,     0 ), /*   386 T_Stratum         */
  S_ST( 'n',	3,      403,     0 ), /*   387                   */
  S_ST( 's',	0,        0,     0 ), /*   388 T_Sysstats        */
  S_ST( 'k',	0,        0,     0 ), /*   389 T_Tick            */
  S_ST( '1',	0,        0,     0 ), /*   390 T_Time1           */
  S_ST( '2',	0,        0,   390 ), /*   391 T_Time2           */
  S_ST( 's',	0,        0,     0 ), /*   392 T_Timingstats     */
  S_ST( 'r',	0,        0,     0 ), /*   393 T_Tinker          */
  S_ST( 's',	0,        0,     0 ), /*   394 T_Tos             */
  S_ST( 'p',	1,        0,     0 ), /*   395 T_Trap            */
  S_ST( 'e',	0,        0,     0 ), /*   396 T_True            */
  S_ST( 'y',	0,        0,     0 ), /*   397 T_Trustedkey      */
  S_ST( 'l',	0,        0,     0 ), /*   398 T_Ttl             */
  S_ST( 'e',	0,        0,     0 ), /*   399 T_Type            */
  S_ST( 'g',	1,        0,     0 ), /*   400 T_Unconfig        */
  S_ST( 'r',	1,        0,     0 ), /*   401 T_Unpeer          */
  S_ST( 'n',	0,        0,     0 ), /*   402 T_Version         */
  S_ST( 'y',	3,      408,     0 ), /*   403                   */
  S_ST( 'k',	0,        0,     0 ), /*   404 T_Week            */
  S_ST( 'd',	0,        0,     0 ), /*   405 T_Wildcard        */
  S_ST( 'e',	0,        0,     0 ), /*   406 T_Xleave          */
  S_ST( 'r',	0,        0,     0 ), /*   407 T_Year            */
  S_ST( 'c',	3,      409,     0 ), /*   408                   */
  S_ST( 'a',	3,      410,     0 ), /*   409                   */
  S_ST( 's',	3,      421,     0 ), /*   410                   */
  S_ST( 'e',	0,        0,     0 ), /*   411 T_Simulate        */
  S_ST( 'y',	0,        0,     0 ), /*   412 T_Beep_Delay      */
  S_ST( 'n',	0,        0,     0 ), /*   413 T_Sim_Duration    */
  S_ST( 't',	0,        0,     0 ), /*   414 T_Server_Offset   */
  S_ST( 'n',	0,        0,     0 ), /*   415 T_Duration        */
  S_ST( 't',	0,        0,     0 ), /*   416 T_Freq_Offset     */
  S_ST( 'r',	0,        0,     0 ), /*   417 T_Wander          */
  S_ST( 'r',	0,        0,     0 ), /*   418 T_Jitter          */
  S_ST( 'y',	0,        0,     0 ), /*   419 T_Prop_Delay      */
  S_ST( 'y',	0,        0,     0 ), /*   420 T_Proc_Delay      */
  S_ST( 't',	3,      427,     0 ), /*   421                   */
  S_ST( 'c',	3,      423,     0 ), /*   422                   */
  S_ST( 'l',	3,      424,     0 ), /*   423                   */
  S_ST( 'i',	3,      425,     0 ), /*   424                   */
  S_ST( 'e',	3,      426,     0 ), /*   425                   */
  S_ST( 'n',	3,      329,     0 ), /*   426                   */
  S_ST( 's',	3,      428,   422 ), /*   427                   */
  S_ST( 'e',	3,      429,     0 ), /*   428                   */
  S_ST( 'r',	3,      430,     0 ), /*   429                   */
  S_ST( 'v',	3,      431,     0 ), /*   430                   */
  S_ST( 'e',	3,      330,     0 ), /*   431                   */
  S_ST( 's',	3,      331,   387 ), /*   432                   */
  S_ST( 'x',	3,      441,   432 ), /*   433                   */
  S_ST( 'c',	3,      435,     0 ), /*   434                   */
  S_ST( 'l',	3,      436,     0 ), /*   435                   */
  S_ST( 'o',	3,      437,     0 ), /*   436                   */
  S_ST( 'c',	3,      332,     0 ), /*   437                   */
  S_ST( 'd',	3,      439,   434 ), /*   438                   */
  S_ST( 'i',	3,      440,     0 ), /*   439                   */
  S_ST( 's',	3,      333,     0 ), /*   440                   */
  S_ST( 'p',	3,      442,   438 ), /*   441                   */
  S_ST( 'o',	3,      443,     0 ), /*   442                   */
  S_ST( 'l',	3,      334,     0 ), /*   443                   */
  S_ST( 'i',	3,      445,   309 ), /*   444                   */
  S_ST( 'n',	3,      459,     0 ), /*   445                   */
  S_ST( 'c',	3,      447,     0 ), /*   446                   */
  S_ST( 'l',	3,      448,     0 ), /*   447                   */
  S_ST( 'o',	3,      449,     0 ), /*   448                   */
  S_ST( 'c',	3,      335,     0 ), /*   449                   */
  S_ST( 'd',	3,      451,   446 ), /*   450                   */
  S_ST( 'i',	3,      452,     0 ), /*   451                   */
  S_ST( 's',	3,      336,     0 ), /*   452                   */
  S_ST( 'i',	3,      454,   450 ), /*   453                   */
  S_ST( 'm',	3,      455,     0 ), /*   454                   */
  S_ST( 'u',	3,      337,     0 ), /*   455                   */
  S_ST( 'p',	3,      457,   453 ), /*   456                   */
  S_ST( 'o',	3,      458,     0 ), /*   457                   */
  S_ST( 'l',	3,      338,     0 ), /*   458                   */
  S_ST( 's',	3,      460,   456 ), /*   459                   */
  S_ST( 'a',	3,      461,     0 ), /*   460                   */
  S_ST( 'n',	3,      339,     0 ), /*   461                   */
  S_ST( 'o',	3,      464,   444 ), /*   462                   */
  S_ST( 'd',	3,      340,     0 ), /*   463                   */
  S_ST( 'n',	3,      468,   463 ), /*   464                   */
  S_ST( 'i',	3,      466,     0 ), /*   465                   */
  S_ST( 't',	3,      467,     0 ), /*   466                   */
  S_ST( 'o',	3,      341,     0 ), /*   467                   */
  S_ST( 't',	3,      342,   465 ), /*   468                   */
  S_ST( 's',	3,      470,   462 ), /*   469                   */
  S_ST( 's',	3,      471,     0 ), /*   470                   */
  S_ST( 'n',	3,      472,     0 ), /*   471                   */
  S_ST( 't',	3,      320,     0 ), /*   472                   */
  S_ST( 'u',	3,      474,   469 ), /*   473                   */
  S_ST( 'l',	3,      475,     0 ), /*   474                   */
  S_ST( 't',	3,      476,     0 ), /*   475                   */
  S_ST( 'i',	3,      477,     0 ), /*   476                   */
  S_ST( 'c',	3,      478,     0 ), /*   477                   */
  S_ST( 'a',	3,      479,     0 ), /*   478                   */
  S_ST( 's',	3,      480,     0 ), /*   479                   */
  S_ST( 't',	3,      481,     0 ), /*   480                   */
  S_ST( 'c',	3,      482,     0 ), /*   481                   */
  S_ST( 'l',	3,      483,     0 ), /*   482                   */
  S_ST( 'i',	3,      484,     0 ), /*   483                   */
  S_ST( 'e',	3,      485,     0 ), /*   484                   */
  S_ST( 'n',	3,      343,     0 ), /*   485                   */
  S_ST( 'n',	3,      517,   292 ), /*   486                   */
  S_ST( 'i',	3,      344,     0 ), /*   487                   */
  S_ST( 'o',	3,      512,   487 ), /*   488                   */
  S_ST( 'l',	3,      490,     0 ), /*   489                   */
  S_ST( 'i',	3,      491,     0 ), /*   490                   */
  S_ST( 'n',	3,      345,     0 ), /*   491                   */
  S_ST( 'm',	3,      493,   489 ), /*   492                   */
  S_ST( 'o',	3,      494,     0 ), /*   493                   */
  S_ST( 'd',	3,      495,     0 ), /*   494                   */
  S_ST( 'i',	3,      496,     0 ), /*   495                   */
  S_ST( 'f',	3,      346,     0 ), /*   496                   */
  S_ST( 'n',	3,      347,   492 ), /*   497                   */
  S_ST( 'p',	3,      499,   497 ), /*   498                   */
  S_ST( 'e',	3,      500,     0 ), /*   499                   */
  S_ST( 'e',	3,      348,     0 ), /*   500                   */
  S_ST( 'q',	3,      502,   498 ), /*   501                   */
  S_ST( 'u',	3,      503,     0 ), /*   502                   */
  S_ST( 'e',	3,      504,     0 ), /*   503                   */
  S_ST( 'r',	3,      349,     0 ), /*   504                   */
  S_ST( 's',	3,      506,   501 ), /*   505                   */
  S_ST( 'e',	3,      510,     0 ), /*   506                   */
  S_ST( 'l',	3,      508,     0 ), /*   507                   */
  S_ST( 'e',	3,      509,     0 ), /*   508                   */
  S_ST( 'c',	3,      350,     0 ), /*   509                   */
  S_ST( 'r',	3,      511,   507 ), /*   510                   */
  S_ST( 'v',	3,      351,     0 ), /*   511                   */
  S_ST( 't',	3,      513,   505 ), /*   512                   */
  S_ST( 'r',	3,      515,     0 ), /*   513                   */
  S_ST( 'a',	3,      352,     0 ), /*   514                   */
  S_ST( 'u',	3,      516,   514 ), /*   515                   */
  S_ST( 's',	3,      353,     0 ), /*   516                   */
  S_ST( 't',	3,      354,   488 ), /*   517                   */
  S_ST( 'p',	3,      519,     0 ), /*   518                   */
  S_ST( 'o',	3,      520,     0 ), /*   519                   */
  S_ST( 'r',	3,      355,     0 ), /*   520                   */
  S_ST( 's',	3,      522,   518 ), /*   521                   */
  S_ST( 'i',	3,      523,     0 ), /*   522                   */
  S_ST( 'g',	3,      524,     0 ), /*   523                   */
  S_ST( 'n',	3,      525,     0 ), /*   524                   */
  S_ST( 'd',	3,      526,     0 ), /*   525                   */
  S_ST( 's',	3,      527,     0 ), /*   526                   */
  S_ST( 'o',	3,      528,     0 ), /*   527                   */
  S_ST( 'c',	3,      529,     0 ), /*   528                   */
  S_ST( 'k',	3,      530,     0 ), /*   529                   */
  S_ST( 'e',	3,      356,     0 ), /*   530                   */
  S_ST( 'o',	3,      532,   486 ), /*   531                   */
  S_ST( 'r',	3,      533,     0 ), /*   532                   */
  S_ST( 'p',	3,      534,     0 ), /*   533                   */
  S_ST( 'h',	3,      535,     0 ), /*   534                   */
  S_ST( 'a',	3,      357,     0 ), /*   535                   */
  S_ST( 'p',	3,      369,   531 ), /*   536                   */
  S_ST( 'a',	3,      538,     0 ), /*   537                   */
  S_ST( 'n',	3,      539,     0 ), /*   538                   */
  S_ST( 'i',	3,      358,     0 ), /*   539                   */
  S_ST( 'e',	3,      541,   537 ), /*   540                   */
  S_ST( 'e',	3,      359,     0 ), /*   541                   */
  S_ST( 's',	3,      543,     0 ), /*   542                   */
  S_ST( 't',	3,      544,     0 ), /*   543                   */
  S_ST( 'a',	3,      545,     0 ), /*   544                   */
  S_ST( 't',	3,      360,     0 ), /*   545                   */
  S_ST( 'h',	3,      547,   540 ), /*   546                   */
  S_ST( 'o',	3,      548,     0 ), /*   547                   */
  S_ST( 'n',	3,      361,     0 ), /*   548                   */
  S_ST( 'i',	3,      362,   546 ), /*   549                   */
  S_ST( 'f',	3,      551,     0 ), /*   550                   */
  S_ST( 'i',	3,      552,     0 ), /*   551                   */
  S_ST( 'l',	3,      363,     0 ), /*   552                   */
  S_ST( 'o',	3,      555,   549 ), /*   553                   */
  S_ST( 'o',	3,      364,     0 ), /*   554                   */
  S_ST( 'r',	3,      365,   554 ), /*   555                   */
  S_ST( 'r',	3,      563,   553 ), /*   556                   */
  S_ST( 'e',	3,      561,     0 ), /*   557                   */
  S_ST( 'e',	3,      559,     0 ), /*   558                   */
  S_ST( 'm',	3,      560,     0 ), /*   559                   */
  S_ST( 'p',	3,      366,     0 ), /*   560                   */
  S_ST( 'f',	3,      562,   558 ), /*   561                   */
  S_ST( 'e',	3,      367,     0 ), /*   562                   */
  S_ST( 'o',	3,      576,   557 ), /*   563                   */
  S_ST( 'c',	3,      565,     0 ), /*   564                   */
  S_ST( '_',	3,      566,     0 ), /*   565                   */
  S_ST( 'd',	3,      567,     0 ), /*   566                   */
  S_ST( 'e',	3,      568,     0 ), /*   567                   */
  S_ST( 'l',	3,      569,     0 ), /*   568                   */
  S_ST( 'a',	3,      420,     0 ), /*   569                   */
  S_ST( 'p',	3,      571,   564 ), /*   570                   */
  S_ST( '_',	3,      572,     0 ), /*   571                   */
  S_ST( 'd',	3,      573,     0 ), /*   572                   */
  S_ST( 'e',	3,      574,     0 ), /*   573                   */
  S_ST( 'l',	3,      575,     0 ), /*   574                   */
  S_ST( 'a',	3,      419,     0 ), /*   575                   */
  S_ST( 't',	3,      577,   570 ), /*   576                   */
  S_ST( 'o',	3,      578,     0 ), /*   577                   */
  S_ST( 's',	3,      579,     0 ), /*   578                   */
  S_ST( 't',	3,      580,     0 ), /*   579                   */
  S_ST( 'a',	3,      581,     0 ), /*   580                   */
  S_ST( 't',	3,      368,     0 ), /*   581                   */
  S_ST( 'q',	3,      583,   536 ), /*   582                   */
  S_ST( 'o',	3,      370,     0 ), /*   583                   */
  S_ST( 'r',	3,      596,   582 ), /*   584                   */
  S_ST( 'a',	3,      591,     0 ), /*   585                   */
  S_ST( 'n',	3,      587,     0 ), /*   586                   */
  S_ST( 'd',	3,      588,     0 ), /*   587                   */
  S_ST( 'f',	3,      589,     0 ), /*   588                   */
  S_ST( 'i',	3,      590,     0 ), /*   589                   */
  S_ST( 'l',	3,      371,     0 ), /*   590                   */
  S_ST( 'w',	3,      592,   586 ), /*   591                   */
  S_ST( 's',	3,      593,     0 ), /*   592                   */
  S_ST( 't',	3,      594,     0 ), /*   593                   */
  S_ST( 'a',	3,      595,     0 ), /*   594                   */
  S_ST( 't',	3,      372,     0 ), /*   595                   */
  S_ST( 'e',	3,      611,   585 ), /*   596                   */
  S_ST( 'f',	3,      598,     0 ), /*   597                   */
  S_ST( 'i',	3,      373,     0 ), /*   598                   */
  S_ST( 'q',	3,      600,   597 ), /*   599                   */
  S_ST( 'u',	3,      601,     0 ), /*   600                   */
  S_ST( 'e',	3,      602,     0 ), /*   601                   */
  S_ST( 's',	3,      603,     0 ), /*   602                   */
  S_ST( 't',	3,      604,     0 ), /*   603                   */
  S_ST( 'k',	3,      605,     0 ), /*   604                   */
  S_ST( 'e',	3,      374,     0 ), /*   605                   */
  S_ST( 's',	3,      607,   599 ), /*   606                   */
  S_ST( 't',	3,      608,     0 ), /*   607                   */
  S_ST( 'r',	3,      609,     0 ), /*   608                   */
  S_ST( 'i',	3,      610,     0 ), /*   609                   */
  S_ST( 'c',	3,      375,     0 ), /*   610                   */
  S_ST( 'v',	3,      612,   606 ), /*   611                   */
  S_ST( 'o',	3,      613,     0 ), /*   612                   */
  S_ST( 'k',	3,      376,     0 ), /*   613                   */
  S_ST( 's',	3,      674,   584 ), /*   614                   */
  S_ST( 'a',	3,      616,     0 ), /*   615                   */
  S_ST( 'v',	3,      617,     0 ), /*   616                   */
  S_ST( 'e',	3,      618,     0 ), /*   617                   */
  S_ST( 'c',	3,      619,     0 ), /*   618                   */
  S_ST( 'o',	3,      620,     0 ), /*   619                   */
  S_ST( 'n',	3,      621,     0 ), /*   620                   */
  S_ST( 'f',	3,      622,     0 ), /*   621                   */
  S_ST( 'i',	3,      623,     0 ), /*   622                   */
  S_ST( 'g',	3,      624,     0 ), /*   623                   */
  S_ST( 'd',	3,      625,     0 ), /*   624                   */
  S_ST( 'i',	3,      377,     0 ), /*   625                   */
  S_ST( 'e',	3,      636,   615 ), /*   626                   */
  S_ST( 'r',	3,      628,     0 ), /*   627                   */
  S_ST( 'v',	3,      629,     0 ), /*   628                   */
  S_ST( 'e',	3,      378,     0 ), /*   629                   */
  S_ST( '_',	3,      631,     0 ), /*   630                   */
  S_ST( 'o',	3,      632,     0 ), /*   631                   */
  S_ST( 'f',	3,      633,     0 ), /*   632                   */
  S_ST( 'f',	3,      634,     0 ), /*   633                   */
  S_ST( 's',	3,      635,     0 ), /*   634                   */
  S_ST( 'e',	3,      414,     0 ), /*   635                   */
  S_ST( 't',	3,      637,   627 ), /*   636                   */
  S_ST( 'v',	3,      638,     0 ), /*   637                   */
  S_ST( 'a',	3,      379,     0 ), /*   638                   */
  S_ST( 'i',	3,      641,   626 ), /*   639                   */
  S_ST( 'g',	3,      380,     0 ), /*   640                   */
  S_ST( 'm',	3,      642,   640 ), /*   641                   */
  S_ST( 'u',	3,      643,     0 ), /*   642                   */
  S_ST( 'l',	3,      644,     0 ), /*   643                   */
  S_ST( 'a',	3,      645,     0 ), /*   644                   */
  S_ST( 't',	3,      646,     0 ), /*   645                   */
  S_ST( 'i',	3,      647,   411 ), /*   646                   */
  S_ST( 'o',	3,      648,     0 ), /*   647                   */
  S_ST( 'n',	3,      649,     0 ), /*   648                   */
  S_ST( '_',	3,      650,     0 ), /*   649                   */
  S_ST( 'd',	3,      651,     0 ), /*   650                   */
  S_ST( 'u',	3,      652,     0 ), /*   651                   */
  S_ST( 'r',	3,      653,     0 ), /*   652                   */
  S_ST( 'a',	3,      654,     0 ), /*   653                   */
  S_ST( 't',	3,      655,     0 ), /*   654                   */
  S_ST( 'i',	3,      656,     0 ), /*   655                   */
  S_ST( 'o',	3,      413,     0 ), /*   656                   */
  S_ST( 't',	3,      670,   639 ), /*   657                   */
  S_ST( 'a',	3,      659,     0 ), /*   658                   */
  S_ST( 't',	3,      382,     0 ), /*   659                   */
  S_ST( 'i',	3,      661,     0 ), /*   660                   */
  S_ST( 's',	3,      662,     0 ), /*   661                   */
  S_ST( 't',	3,      663,     0 ), /*   662                   */
  S_ST( 'i',	3,      664,     0 ), /*   663                   */
  S_ST( 'c',	3,      381,     0 ), /*   664                   */
  S_ST( 'd',	3,      666,     0 ), /*   665                   */
  S_ST( 'i',	3,      383,     0 ), /*   666                   */
  S_ST( 'e',	3,      384,   658 ), /*   667                   */
  S_ST( 'o',	3,      669,     0 ), /*   668                   */
  S_ST( 'u',	3,      385,     0 ), /*   669                   */
  S_ST( 'r',	3,      671,   667 ), /*   670                   */
  S_ST( 'a',	3,      672,     0 ), /*   671                   */
  S_ST( 't',	3,      673,     0 ), /*   672                   */
  S_ST( 'u',	3,      386,     0 ), /*   673                   */
  S_ST( 'y',	3,      675,   657 ), /*   674                   */
  S_ST( 's',	3,      676,     0 ), /*   675                   */
  S_ST( 's',	3,      677,     0 ), /*   676                   */
  S_ST( 't',	3,      678,     0 ), /*   677                   */
  S_ST( 'a',	3,      679,     0 ), /*   678                   */
  S_ST( 't',	3,      388,     0 ), /*   679                   */
  S_ST( 't',	3,      706,   614 ), /*   680                   */
  S_ST( 'i',	3,      692,     0 ), /*   681                   */
  S_ST( 'c',	3,      389,     0 ), /*   682                   */
  S_ST( 'm',	3,      685,   682 ), /*   683                   */
  S_ST( 'e',	3,      391,     0 ), /*   684                   */
  S_ST( 'i',	3,      686,   684 ), /*   685                   */
  S_ST( 'n',	3,      687,     0 ), /*   686                   */
  S_ST( 'g',	3,      688,     0 ), /*   687                   */
  S_ST( 's',	3,      689,     0 ), /*   688                   */
  S_ST( 't',	3,      690,     0 ), /*   689                   */
  S_ST( 'a',	3,      691,     0 ), /*   690                   */
  S_ST( 't',	3,      392,     0 ), /*   691                   */
  S_ST( 'n',	3,      693,   683 ), /*   692                   */
  S_ST( 'k',	3,      694,     0 ), /*   693                   */
  S_ST( 'e',	3,      393,     0 ), /*   694                   */
  S_ST( 'o',	3,      394,   681 ), /*   695                   */
  S_ST( 'r',	3,      698,   695 ), /*   696                   */
  S_ST( 'a',	3,      395,     0 ), /*   697                   */
  S_ST( 'u',	3,      699,   697 ), /*   698                   */
  S_ST( 's',	3,      700,   396 ), /*   699                   */
  S_ST( 't',	3,      701,     0 ), /*   700                   */
  S_ST( 'e',	3,      702,     0 ), /*   701                   */
  S_ST( 'd',	3,      703,     0 ), /*   702                   */
  S_ST( 'k',	3,      704,     0 ), /*   703                   */
  S_ST( 'e',	3,      397,     0 ), /*   704                   */
  S_ST( 't',	3,      398,   696 ), /*   705                   */
  S_ST( 'y',	3,      707,   705 ), /*   706                   */
  S_ST( 'p',	3,      399,     0 ), /*   707                   */
  S_ST( 'u',	3,      709,   680 ), /*   708                   */
  S_ST( 'n',	3,      715,     0 ), /*   709                   */
  S_ST( 'c',	3,      711,     0 ), /*   710                   */
  S_ST( 'o',	3,      712,     0 ), /*   711                   */
  S_ST( 'n',	3,      713,     0 ), /*   712                   */
  S_ST( 'f',	3,      714,     0 ), /*   713                   */
  S_ST( 'i',	3,      400,     0 ), /*   714                   */
  S_ST( 'p',	3,      716,   710 ), /*   715                   */
  S_ST( 'e',	3,      717,     0 ), /*   716                   */
  S_ST( 'e',	3,      401,     0 ), /*   717                   */
  S_ST( 'v',	3,      719,   708 ), /*   718                   */
  S_ST( 'e',	3,      720,     0 ), /*   719                   */
  S_ST( 'r',	3,      721,     0 ), /*   720                   */
  S_ST( 's',	3,      722,     0 ), /*   721                   */
  S_ST( 'i',	3,      723,     0 ), /*   722                   */
  S_ST( 'o',	3,      402,     0 ), /*   723                   */
  S_ST( 'w',	3,      731,   718 ), /*   724                   */
  S_ST( 'a',	3,      726,     0 ), /*   725                   */
  S_ST( 'n',	3,      727,     0 ), /*   726                   */
  S_ST( 'd',	3,      728,     0 ), /*   727                   */
  S_ST( 'e',	3,      417,     0 ), /*   728                   */
  S_ST( 'e',	3,      730,   725 ), /*   729                   */
  S_ST( 'e',	3,      404,     0 ), /*   730                   */
  S_ST( 'i',	3,      732,   729 ), /*   731                   */
  S_ST( 'l',	3,      733,     0 ), /*   732                   */
  S_ST( 'd',	3,      734,     0 ), /*   733                   */
  S_ST( 'c',	3,      735,     0 ), /*   734                   */
  S_ST( 'a',	3,      736,     0 ), /*   735                   */
  S_ST( 'r',	3,      405,     0 ), /*   736                   */
  S_ST( 'x',	3,      738,   724 ), /*   737                   */
  S_ST( 'l',	3,      739,     0 ), /*   738                   */
  S_ST( 'e',	3,      740,     0 ), /*   739                   */
  S_ST( 'a',	3,      741,     0 ), /*   740                   */
  S_ST( 'v',	3,      406,     0 ), /*   741                   */
  S_ST( 'y',	3,      743,   737 ), /*   742 initial state     */
  S_ST( 'e',	3,      744,     0 ), /*   743                   */
  S_ST( 'a',	3,      407,     0 )  /*   744                   */
};

