# $FreeBSD: src/sys/modules/sound/driver/t4dwave/Makefile,v 1.3.34.1.2.1 2009/10/25 01:10:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_t4dwave
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	t4dwave.c

.include <bsd.kmod.mk>
