# $FreeBSD: src/usr.sbin/i4b/isdnphone/Makefile,v 1.4.38.1 2010/02/10 00:26:20 kensmith Exp $

PROG=	isdnphone
MAN=	isdnphone.8
SRCS=	main.c display.c audio.c isdn.c

DPADD=	${LIBCURSES}
LDADD=	-lcurses

.include <bsd.prog.mk>
