#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD$

.include <src.opts.mk>

PACKAGE=runtime
CONFS=	sysctl.conf
PROG=	sysctl
WARNS?=	3
MAN=	sysctl.8

HAS_TESTS=
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
