#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/smm/04.quotas/Makefile,v 1.5.52.1 2008/11/25 02:59:29 kensmith Exp $

VOLUME=	smm/04.quotas
SRCS=	quotas.ms
MACROS=	-ms

.include <bsd.doc.mk>
