#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/skel/Makefile,v 1.11 2004/12/21 08:46:54 ru Exp $

FILESGROUPS=	FILES1 FILES2
FILES1=		dot.cshrc dot.login dot.login_conf dot.mailrc dot.profile \
		dot.shrc
FILES2=		dot.mail_aliases dot.rhosts 
FILES1DIR=	/usr/share/skel
FILES2DIR=	/usr/share/skel
FILES1MODE=	0644
FILES2MODE=	0600
NO_OBJ=

.include <bsd.prog.mk>
