# $FreeBSD: src/tools/tools/mfc/Makefile,v 1.1.22.1.4.1 2010/06/14 02:09:06 kensmith Exp $

BINDIR?=	${HOME}/bin
BINOWN?=	`id -u`
BINGRP?=	`id -g`

SCRIPTS=	mfc.sh
MAN=		# none

.include <bsd.prog.mk>
