# $FreeBSD: src/tools/tools/mfc/Makefile,v 1.1.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $

BINDIR?=	${HOME}/bin
BINOWN?=	`id -u`
BINGRP?=	`id -g`

SCRIPTS=	mfc.sh
MAN=		# none

.include <bsd.prog.mk>
