# $FreeBSD: src/tools/tools/ath/athregs/Makefile,v 1.2.2.1.2.1 2009/10/25 01:10:29 kensmith Exp $

PROG=	athregs

.PATH.c: ${.CURDIR}/../common

SRCS=	dumpregs.c
SRCS+=	dumpregs_5210.c
SRCS+=	dumpregs_5211.c
SRCS+=	dumpregs_5212.c
SRCS+=	dumpregs_5416.c

.include <../Makefile.inc>

.include <bsd.prog.mk>
