# $FreeBSD$

MOUNT = ${BSDSRCTOP}/sbin/mount

PROG = mount_reiserfs

.PATH: ${MOUNT}

SRCS = \
	getmntopts.c \
	mount_reiserfs.c

WARNS ?= 6

CFLAGS += -I${MOUNT}

SRCDIRDEP= sbin/mount
DIRDEP= gnu/lib/csu gnu/lib/libgcc include include/machine lib/csu/MACHINE_ARCH lib/libc stage sys/MACHINE_ARCH/include sys/bsm sys/sys
.include <bsd.prog.mk>
