.\"	@(#) $FreeBSD$
.Dd May 2, 1995
.Dt PPPSTATS 8
.Sh NAME
.Nm pppstats
.Nd print PPP statistics
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl r
.Op Fl c
.Op Fl i Ar secs
.Op Ar unit#
.Sh DESCRIPTION
.Nm pppstats
prints PPP-related statistics.
.Pp
The
.Fl v
flag causes
.Nm
to display additional statistics, such as the number of packets tossed
(that is, which the VJ TCP header decompression code rejected).
.Pp
The
.Fl r
flag causes
.Nm
to display the overall packet compression rate.  The rate value is
between 0 and 1, with 0 meaning that the data is incompressible.
.Pp
The
.Fl c
flag is used to specify an alternate display mode that shows
packet compression statistics: the number of packets and bytes
uncompressed (that is, before compression or after decompression),
compressed, and incompressible (packets which did not shrink on
compression and were transmitted uncompressed), and the recent
compression rate.  This rate reflects the recent performance of the
compression code rather than the overall rate achieved since
compression was enabled.
.Pp
The
.Fl i
flag is used to specify the interval between printouts. The default is
5 seconds.
.Pp
.Ar unit#
specifies which interface to use for gathering statistics.
.Sh SEE ALSO
.Xr pppd 8
