# $FreeBSD: src/sys/modules/canbus/Makefile,v 1.1.32.1 2008/11/25 02:59:29 kensmith Exp $

.PATH:	${.CURDIR}/../../pc98/pc98
KMOD	= canbus
SRCS	= canbus.c
SRCS	+= device_if.h bus_if.h canbus_if.h canbus_if.c

.include <bsd.kmod.mk>
