# $FreeBSD: src/sys/modules/sound/driver/vibes/Makefile,v 1.4.34.1.6.1 2010/12/21 17:09:25 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_vibes
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	vibes.c

.include <bsd.kmod.mk>
