#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/unifdef/Makefile,v 1.6.34.1 2010/02/10 00:26:20 kensmith Exp $

PROG=	unifdef
SCRIPTS=unifdefall.sh
MLINKS=	unifdef.1 unifdefall.1
WARNS?=	5

.include <bsd.prog.mk>
