.\"
.\" Copyright (c) 1996, 1997, 1998 Shigio Yamaguchi. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Shigio Yamaguchi.
.\" 4. Neither the name of the author nor the names of any co-contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: src/contrib/global/htags/htags.1,v 1.6 1999/10/10 07:46:38 mharo Exp $
.\"
.Dd Oct 11, 1998
.Dt HTAGS 1
.Os BSD 4
.Sh NAME
.Nm htags
.Nd generate hypertext from C, Yacc and Java source code
.Sh SYNOPSIS
.Nm htags
.Op Fl a
.Op Fl c
.Op Fl f
.Op Fl h
.Op Fl l
.Op Fl n
.Op Fl v
.Op Fl w
.Op Fl d Ar tagdir
.Op Fl t Ar title
.Op Ar dir
.Sh DESCRIPTION
.Nm Htags
makes hypertext from C, Yacc and Java source code using GLOBAL database (GTAGS, GRTAGS).
.Pp
In advance of using this command, you must execute
.Xr gtags 1
from the root directory of the source tree.
Then you can execute
.Nm htags
from the same place.
.Nm Htags
makes an HTML directory and generates hypertext in it.
.Pp
You can start browsing from 'HTML/index.html'.
Once the hypertext is generated, you can move it anywhere and browse it
in any browsers.
.Pp
.br
.Bl -tag -width Ds
.It Fl a
Make an alphabetical function index, suitable for a large project.
.It Fl c
Compress html files  by
.Xr gzip 1 .
You need to set up an HTTP server so that
.Xr gzip 1
is invoked for each compressed
files. See skelton file 'HTML/.htaccess.skel' that is generated by htags.
.It Fl f
Support an input form and a dynamic index with a CGI program.
You need to set up an HTTP server for this.
.It Fl h
Add title header frame. By default, doesn't add this.
.It Fl l
Make a name tag(<A NAME=line number>) for each line, so that other hypertext
can link to any line of this hypertext.
By default, htags makes it only for lines that are referred to by an object.
.It Fl n
Print the line numbers (they are not printed by default).
.It Fl v
Verbose mode.
.It Fl w
Print a warning message.
.It Fl d Ar tagdir
Specifies the directory in which GTAGS and GRTAGS exist. The default is the
current directory.
.It Fl t Ar title
The title of this hypertext. Defaults to the last component of the current
path.
.It Ar dir
The directory in which hypertext is generated. The default is the current
directory.
.Sh EXAMPLES
  % cd /usr/src/sys
  # gtags -o
  # htags -fnvat 'Welcome to FreeBSD kernel source tour!'
  % lynx HTML/index.html
.Sh FILES
.Bl -tag -width tags -compact
.It Pa HTML/index.html
Index file.
.It Pa GTAGS
Tags file for function definitions.
.It Pa GRTAGS
Tags file for function references.
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of htags.
.Pp
.Bl -tag -width indent
.It Ev TMPDIR
If this variable is set, its value is used as the directory to make temporary files.
The default is /tmp.
.Sh DIAGNOSTICS
.Nm Htags
exits with a non 0 value if an error occurred, 0 otherwise.
.Sh SEE ALSO
.Xr btreeop 1 ,
.Xr global 1 ,
.Xr gtags 1 .
.Sh BUG
Generated hypertext is VERY LARGE. In advance, check the space of your disk.
.Sh AUTHORS
Shigio Yamaguchi (shigio@wafu.netgate.net)
.Sh HISTORY
The
.Nm
command appeared in FreeBSD 2.2.2.
