# $FreeBSD$

.PATH: ${.CURDIR}/../../../kern

KMOD=		dtio
SRCS=		dtio_kdtrace.c \
		vnode_if.h

CFLAGS+=	-I${.CURDIR}/../../../cddl/compat/opensolaris \
		-I${.CURDIR}/../../../cddl/contrib/opensolaris/uts/common \
		-I${.CURDIR}/../../..

.include <bsd.kmod.mk>
