.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Arthur David Olson of the National Cancer Institute.
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)tzfile.5	8.1 (Berkeley) 6/8/93
.\"
.Dd June 8, 1993
.Dt TZFILE 5
.Os
.Sh NAME
.Nm tzfile
.Nd time zone information
.Sh SYNOPSIS
.Fd #include <tzfile.h>
.Sh DESCRIPTION
The time zone information files used by
.Xr tzset 3
begin with bytes reserved for future use,
followed by four four-byte values of type
.Em long ,
written in a ``standard'' byte order
(the high-order byte of the value is written first).
These values are,
in order:
.Bl -tag -width tzh_ttisstdcnt
.It Fa tzh_ttisstdcnt
The number of standard/wall indicators stored in the file.
.It Fa tzh_leapcnt
The number of leap seconds for which data is stored in the file.
.It Fa tzh_timecnt
The number of "transition times" for which data is stored
in the file.
.It Fa tzh_typecnt
The number of "local time types" for which data is stored
in the file (must not be zero).
.It Fa tzh_charcnt
The number of characters of "time zone abbreviation strings"
stored in the file.
.El
.Pp
The above header is followed by
.Fa tzh_timecnt
four-byte values of type
.Em long ,
sorted in ascending order.
These values are written in ``standard'' byte order.
Each is used as a transition time (as returned by
.Xr time 2 )
at which the rules for computing local time change.
Next come
.Fa tzh_timecnt
one-byte values of type
.Fa unsigned char ;
each one tells which of the different types of ``local time'' types
described in the file is associated with the same-indexed transition time.
These values serve as indices into an array of
.Fa ttinfo
structures that appears next in the file; 
these structures are defined as follows:
.Bd -literal -offset indent
struct ttinfo {	
	long	tt_gmtoff;
	int	tt_isdst;
	unsigned int	tt_abbrind;
};
.Ed
.Pp
Each structure is written as a four-byte value for
.Fa tt_gmtoff
of type
.Em long ,
in a standard byte order, followed by a one-byte value for
.Fa tt_isdst
and a one-byte value for
.Fa tt_abbrind .
In each structure,
.Fa tt_gmtoff
gives the number of seconds to be added to
.Tn GMT ,
.Fa tt_isdst
tells whether
.Fa tm_isdst
should be set by
.Xr localtime 3
and
.Fa tt_abbrind
serves as an index into the array of time zone abbreviation characters
that follow the
.Fa ttinfo
structure(s) in the file.
.Pp
Then there are
.Fa tzh_leapcnt
pairs of four-byte values, written in standard byte order;
the first value of each pair gives the time
(as returned by 
.Xr time 2 )
at which a leap second occurs;
the second gives the
.Em total
number of leap seconds to be applied after the given time.
The pairs of values are sorted in ascending order by time.
.Pp
Finally there are
.Fa tzh_ttisstdcnt
standard/wall indicators, each stored as a one-byte value;
they tell whether the transition times associated with local time types
were specified as standard time or wall clock time,
and are used when a time zone file is used in handling
.Tn POSIX Ns -style
time zone environment variables.
.Pp
.Fa Localtime
uses the first standard-time
.Fa ttinfo
structure in the file
(or simply the first
.Fa ttinfo
structure in the absence of a standard-time structure)
if either
.Fa tzh_timecnt
is zero or the time argument is less than the first transition time recorded
in the file.
.Sh SEE ALSO
.Xr ctime 3
.Sh HISTORY
The
.Nm tzfile
file format appeared in
.Bx 4.3 tahoe.
