 # $FreeBSD: src/sys/modules/exca/Makefile,v 1.2.24.1 2008/10/02 02:57:24 kensmith Exp $

.PATH: ${.CURDIR}/../../dev/exca

KMOD=	exca
SRCS=	exca.c device_if.h bus_if.h power_if.h card_if.h pccarddevs.h

.include <bsd.kmod.mk>
