/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /a/cvs/386BSD/src/usr.bin/lex/initscan.c,v 1.2 1993/06/29 03:27:12 nate Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR unsigned char
# line 1 "scan.l"
#define INITIAL 0
/* scan.l - scanner for flex input */
# line 5 "scan.l"
/*-
 * Copyright (c) 1990 The Regents of the University of California.
 * All rights reserved.
 *
 * This code is derived from software contributed to Berkeley by
 * Vern Paxson.
 * 
 * The United States Government has rights in this work pursuant
 * to contract no. DE-AC03-76SF00098 between the United States
 * Department of Energy and the University of California.
 *
 * Redistribution and use in source and binary forms are permitted provided
 * that: (1) source distributions retain this entire copyright notice and
 * comment, and (2) distributions including binaries display the following
 * acknowledgement:  ``This product includes software developed by the
 * University of California, Berkeley and its contributors'' in the
 * documentation or other materials provided with the distribution and in
 * all advertising materials mentioning features or use of this software.
 * Neither the name of the University nor the names of its contributors may
 * be used to endorse or promote products derived from this software without
 * specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef lint
static char rcsid[] =
    "@(#) $Header: /a/cvs/386BSD/src/usr.bin/lex/initscan.c,v 1.2 1993/06/29 03:27:12 nate Exp $ (LBL)";
#endif

#undef yywrap

#include "flexdef.h"
#include "parse.h"

#define ACTION_ECHO fprintf( temp_action_file, "%s", yytext )
#define MARK_END_OF_PROLOG fprintf( temp_action_file, "%%%% end of prolog\n" );

#undef YY_DECL
#define YY_DECL \
	int flexscan()

#define RETURNCHAR \
	yylval = yytext[0]; \
	return ( CHAR );

#define RETURNNAME \
	(void) strcpy( nmstr, (char *) yytext ); \
	return ( NAME );

#define PUT_BACK_STRING(str, start) \
	for ( i = strlen( (char *) (str) ) - 1; i >= start; --i ) \
	    unput((str)[i])

#define CHECK_REJECT(str) \
	if ( all_upper( str ) ) \
	    reject = true;

#define CHECK_YYMORE(str) \
	if ( all_lower( str ) ) \
	    yymore_used = true;
#define SECT2 1
#define SECT2PROLOG 2
#define SECT3 3
#define CODEBLOCK 4
#define PICKUPDEF 5
#define SC 6
#define CARETISBOL 7
#define NUM 8
#define QUOTE 9
#define FIRSTCCL 10
#define CCL 11
#define ACTION 12
#define RECOVER 13
#define BRACEERROR 14
#define C_COMMENT 15
#define ACTION_COMMENT 16
#define ACTION_STRING 17
#define PERCENT_BRACE_ACTION 18
#define USED_LIST 19
#define CODEBLOCK_2 20
#define XLATION 21
# line 84 "scan.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 121
typedef int yy_state_type;
static const short int yy_accept[342] =
    {   0,
        0,    0,    0,    0,    0,    0,  119,  119,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  121,   19,    7,   18,   19,   16,
        1,   17,   19,   19,   19,   15,   67,   59,   60,   53,
       67,   66,   51,   67,   67,   67,   50,   49,   67,   52,
      120,   47,  119,  119,   28,   29,   28,   28,   28,   28,
       31,   30,   32,   73,  120,   69,   70,   72,   74,   88,
       89,   86,   85,   87,   75,   77,   76,   75,   81,   80,

       81,   81,   83,   83,   83,   84,   99,  104,  103,  105,
      105,  100,  100,  100,   97,   98,  120,   33,   91,   90,
       22,   24,   23,  107,  109,  108,  111,  113,  114,  115,
       95,   95,   96,   95,   95,   95,   95,   38,   35,   34,
       38,   38,   44,   42,   45,   44,   44,   41,   41,   41,
       40,   41,    7,   18,    0,   16,    1,   17,    0,    2,
       14,    8,    0,   12,    4,    0,    0,    5,    0,    3,
       15,   59,   60,    0,    0,   56,    0,    0,    0,  117,
      117,  117,   55,   54,   55,   50,   49,   63,   50,    0,
       47,   46,  119,  119,   28,   28,   28,   28,   28,   31,

       30,   71,   72,   85,  118,  118,  118,   78,   79,   82,
       99,    0,  102,    0,  101,  100,  100,  100,    0,   33,
       22,   20,  107,  106,  111,  112,   95,   95,   95,   92,
       95,   95,   95,   38,   35,   38,   38,   42,    0,   43,
       43,   43,   42,   40,    0,   13,   14,    8,    8,    0,
       12,    4,    0,    0,    0,    5,    0,    6,   57,    0,
       58,    0,   64,    0,    0,  117,  117,   55,   55,   65,
       63,   28,   28,   28,   25,    0,  118,  118,  100,  100,
        0,   21,   92,   92,   95,   95,   38,   38,    0,   39,
       43,   43,    0,    0,   11,    4,    0,   11,    0,    0,

        5,    0,    0,    0,  117,   28,   28,  118,  100,  100,
       95,   95,   38,   38,   43,    0,    9,    0,    0,    0,
       28,   28,  100,  100,   95,   95,   38,   38,    0,    0,
       26,   27,   93,   94,   93,   94,   36,   37,   10,   62,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    8,    1,    9,   10,
       10,   11,   10,   12,   13,   10,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
        1,   17,   10,    1,   23,   24,   25,   26,   27,   28,
       22,   22,   22,   29,   30,   22,   31,   32,   33,   30,
       22,   34,   35,   36,   37,   22,   22,   38,   39,   22,
       18,   19,   20,   21,   22,    1,   23,   24,   25,   26,

       27,   28,   22,   22,   22,   29,   30,   22,   31,   32,
       33,   30,   22,   34,   35,   36,   37,   22,   22,   38,
       39,   22,   40,   41,   42,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[43] =
    {   0,
        1,    2,    3,    2,    4,    1,    1,    1,    5,    1,
        6,    1,    7,    5,    8,    1,    1,    1,    9,   10,
        1,   11,   12,   12,   12,   12,   12,   12,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,    5,
        1,   13
    } ;

static const short int yy_base[405] =
    {   0,
        0,   42,   83,  123, 1401, 1400, 1399, 1398,  164, 1391,
      101,  104,  206,    0, 1377, 1376,  106,  107,   93,  110,
      132,  133,  137,  246,  266,    0, 1382, 1378,  113,  117,
       89,  247,  249,  250,  306,  307,  326,    0,  367,  370,
        0,    0,  373,  376, 1380, 1405,  158, 1405, 1343,    0,
      252, 1405, 1360,  402, 1351,    0, 1405,  385, 1405, 1405,
      260, 1405, 1345, 1338,   76,  442,  483, 1405,  103, 1405,
     1353,    0, 1348, 1405,    0, 1405,    0, 1323, 1294, 1290,
        0,  311, 1405, 1405, 1405, 1405, 1310,    0, 1405, 1405,
     1405, 1405, 1300, 1405, 1405, 1405, 1405,  367, 1405, 1405,

      370, 1301, 1405,    0,  375, 1405,    0, 1405, 1405,  305,
     1302,    0, 1274, 1250, 1405, 1405, 1282, 1405, 1405, 1405,
        0, 1405, 1270,    0, 1405, 1269,    0, 1405, 1405,    0,
        0,  314, 1405, 1199,    0, 1201, 1176,    0,  315, 1405,
     1187, 1171, 1405,  319, 1405, 1173,  379, 1405,  396, 1169,
     1189,  381,  412, 1405,  418,    0,  486, 1405, 1193, 1405,
      395,  426,  429,  490,    0,  493,  351,    0, 1180, 1405,
        0,  496, 1405, 1136, 1168, 1405, 1143,  383,  403, 1405,
     1145,    0,    0, 1405,  537,  499, 1405,    0, 1405, 1154,
        0, 1405, 1144, 1405,    0,    0, 1115, 1095,  579,    0,

      504, 1405,    0, 1110, 1405, 1097,    0, 1405, 1405, 1405,
        0,  496, 1405,    0, 1405,    0, 1075, 1072, 1099, 1405,
        0, 1093,    0, 1405,    0, 1405,    0,  508, 1047,  621,
        0, 1047, 1032,    0,  507, 1029, 1026,  515,  518, 1405,
     1029,    0,  521, 1024,  524, 1405,  527,    0,  528,  531,
      662,    0,  665, 1001, 1007,    0, 1030, 1405, 1405, 1022,
     1405,  966, 1405,  655,  661,  983,    0,    0,    0, 1405,
        0,  946,  934,    0, 1405,  957,  940,    0,  927,  891,
      920, 1405,    0,    0,  679,  672,  677,  670,  669, 1405,
      687,    0,  698,  675, 1405,    0,  688, 1405,  665,  670,

        0,  667,  678,  684, 1405,  669,  631, 1405,  599,  484,
      468,  411,  399,  378, 1405,  380, 1405,  303,  494,  663,
      228,  230,  215,  131,  111,  111,   96,   90,   69,   72,
        0,    0,    0,    0,    0,    0,    0,    0, 1405, 1405,
     1405,  712,  725,  738,  751,  764,  777,  790,  803,  816,
      829,  842,  855,  868,  881,  894,  907,  914,  926,  939,
      945,  957,  970,  983,  996, 1009, 1022, 1029, 1041, 1048,
     1060, 1073, 1086, 1099, 1109, 1116, 1128, 1141, 1154, 1167,
     1180, 1193, 1200, 1212, 1225, 1238, 1241, 1243, 1255, 1268,
     1274, 1286, 1298, 1304, 1316, 1322, 1334, 1341, 1347, 1352,

     1364, 1370, 1382, 1388
    } ;

static const short int yy_def[405] =
    {   0,
      341,  341,  342,  342,  343,  343,  344,  344,  341,    9,
      345,  345,  341,   13,  346,  346,  347,  347,  348,  348,
      349,  349,  350,  350,  341,   25,  351,  351,  346,  346,
      352,  352,  353,  353,  354,  354,  341,   37,  355,  355,
       37,   37,  356,  357,  341,  341,  341,  341,  341,  358,
      341,  341,  359,  360,  341,  361,  341,  341,  341,  341,
      341,  341,  341,  362,  363,  341,  341,  341,  341,  341,
      364,  365,  366,  341,  367,  341,  368,  368,  368,  367,
      369,  341,  341,  341,  341,  341,  341,  370,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  363,  341,  341,

      371,  372,  341,  373,  363,  341,  374,  341,  341,  375,
      341,  376,  376,  376,  341,  341,  377,  341,  341,  341,
      378,  341,  341,  379,  341,  341,  380,  341,  341,  381,
      382,  382,  341,  382,  383,  383,  383,  384,  341,  341,
      384,  384,  341,  341,  341,  341,  385,  341,  341,  341,
      341,  385,  341,  341,  341,  358,  341,  341,  359,  341,
      341,  386,  341,  341,  387,  341,  341,  388,  389,  341,
      361,  341,  341,  341,  390,  341,  341,  362,  362,  341,
      341,  391,  392,  341,  341,  341,  341,  393,  341,  364,
      365,  341,  366,  341,  367,  368,  368,  368,  341,  369,

      341,  341,  370,  341,  341,  341,  394,  341,  341,  341,
      374,  375,  341,  375,  341,  376,  376,  376,  377,  341,
      378,  395,  379,  341,  380,  341,  382,  382,  382,  341,
      383,  383,  383,  384,  341,  384,  384,  341,  341,  341,
      341,  396,  341,  341,  341,  341,  341,  386,  386,  397,
      341,  398,  397,  341,  341,  399,  389,  341,  341,  390,
      341,  341,  341,  362,  362,  341,  400,  392,  185,  341,
      393,  368,  368,  199,  341,  401,  341,  402,  376,  376,
      395,  341,  230,  403,  383,  383,  384,  384,  341,  341,
      341,  404,  397,  397,  341,  398,  397,  341,  341,  341,

      399,  341,  362,  265,  341,  368,  368,  341,  376,  376,
      383,  383,  384,  384,  341,  341,  341,  341,  362,  362,
      368,  368,  376,  376,  383,  383,  384,  384,  341,  341,
      368,  368,  376,  376,  383,  383,  384,  384,  341,  341,
        0,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341
    } ;

static const short int yy_nxt[1448] =
    {   0,
       46,   47,   48,   47,   46,   46,   46,   49,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   46,
       46,   46,   46,   51,   52,   51,   46,   53,   46,   54,
       46,   46,   46,   46,   46,   55,   46,   46,   46,   46,
       46,   46,   46,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   46,   46,   46,   58,   59,   58,   60,  340,   61,
      181,  122,   62,   62,  339,   96,   62,   97,   63,  123,

       64,   65,   82,   83,   82,   82,   83,   82,   91,   91,
      188,   98,   96,  182,   97,  119,  338,   92,   92,  119,
       93,   93,   66,   62,   67,   68,   67,   60,   98,   61,
       69,  337,   62,   62,   85,   85,   62,  336,   63,   85,
       64,   65,  189,   70,  100,  100,  335,   94,   94,  104,
      101,  101,  102,  102,  120,  105,  106,  334,  120,  153,
      154,  153,   66,   62,   75,   75,   76,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   78,   77,   77,

       77,   77,   79,   75,   75,   75,   84,   84,   85,   84,
       84,   84,   84,   84,   84,   84,   84,   86,   84,   84,
       84,   84,   87,   84,   84,   84,   84,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   84,   84,   84,   85,  122,
      333,  125,  125,  157,  158,  157,  332,  123,  104,  126,
      126,  176,  176,  331,  105,  106,  107,  107,  108,  107,
      109,  107,  107,  107,  110,  107,  107,  107,  107,  111,
      107,  107,  107,  107,  107,  107,  107,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  113,

      112,  112,  112,  112,  114,  115,  107,  116,  128,  128,
      129,  129,  201,  213,  201,  228,  235,  228,  235,  330,
      238,  229,  238,  214,  130,  130,  131,  132,  133,  132,
      131,  131,  131,  134,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  136,
      135,  135,  135,  135,  137,  131,  131,  131,  139,  140,
      139,  139,  140,  139,  144,  145,  144,  149,  145,  149,
      146,  181,  254,  150,  206,  255,  172,  173,  172,  181,
      151,  147,  174,  241,  152,  241,  247,  243,  247,  243,

      141,  179,  263,  141,  182,  142,  329,  207,  142,  162,
      244,  328,  182,  153,  154,  153,  242,  264,  242,  245,
      246,  245,  178,  327,  163,  175,  164,  249,  163,  249,
      250,  163,  250,  163,  163,  164,  165,  166,  167,  168,
      265,  169,  183,  183,  326,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  184,  183,  183,  183,
      183,  183,  183,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  183,  183,  183,  186,  187,  186,  157,  158,  157,
      174,  251,  325,  251,  253,  246,  253,  172,  173,  172,

      186,  187,  186,  174,  213,  201,  174,  201,  235,  228,
      235,  228,  179,  263,  214,  229,  238,  324,  238,  289,
      290,  289,  243,  175,  243,  245,  246,  245,  247,  249,
      247,  249,  294,  295,  294,  244,  175,  268,  268,  175,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  269,
      268,  269,  268,  268,  268,  268,  268,  268,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  268,  268,  270,  274,
      274,  275,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  274,  274,
      274,  283,  283,  323,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      283,  283,  283,  251,  322,  251,  297,  298,  297,  303,
      289,  290,  289,  179,  263,  304,  294,  295,  294,  179,
      263,  179,  263,  304,  304,  304,  304,  304,  304,  297,
      298,  297,  319,  321,  318,  317,  179,  263,  320,  316,

      295,  240,  314,  313,  312,  311,  320,  320,  320,  320,
      320,  320,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,  143,  143,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      156,  156,  282,  310,  156,  156,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  171,  171,  309,  205,  171,  171,  178,  178,  275,
      178,  178,  178,  178,  178,  178,  307,  178,  178,  178,
      180,  180,  306,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  192,  180,  302,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  195,  195,  261,  195,  195,  195,  195,  195,
      195,  195,  258,  300,  195,  196,  196,  299,  244,  196,
      196,  200,  200,  291,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  203,  203,  288,  287,  203,  203,
      205,  205,  286,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  208,  208,  285,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  210,  210,  230,  210,
      210,  210,  210,  210,  210,  282,  210,  210,  210,  211,

      211,  220,  280,  279,  211,  211,  211,  211,  211,  212,
      212,  277,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  216,  216,  204,  273,  216,  216,  219,  219,
      219,  219,  219,  219,  219,  219,  219,  219,  219,  219,
      219,  221,  221,  272,  221,  221,  194,  221,  221,  221,
      221,  221,  221,  221,  223,  223,  191,  223,  223,  266,
      223,  223,  223,  223,  223,  223,  223,  225,  225,  262,
      261,  225,  225,  225,  225,  259,  225,  225,  225,  225,
      226,  226,  258,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  227,  227,  160,  227,  227,  227,  227,

      227,  227,  227,  244,  239,  227,  231,  231,  239,  237,
      231,  231,  234,  236,  233,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  240,  240,  232,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  248,  248,
      230,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  252,  252,  256,  256,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  267,  224,  222,  220,  267,  268,  268,  218,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  271,  271,

      217,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  278,  215,  209,  204,  278,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  292,
      202,  199,  198,  292,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  296,  296,  197,
      194,  296,  296,  301,  301,  191,  179,  301,  301,  305,
      177,  170,  160,  305,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  308,  155,  341,
      118,  308,  284,  284,  118,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  315,   89,   89,   80,  315,

       74,   74,   72,   72,   45,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341
    } ;

static const short int yy_chk[1448] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    3,    3,    3,    3,  330,    3,
       65,   31,    3,    3,  329,   19,    3,   19,    3,   31,

        3,    3,   11,   11,   11,   12,   12,   12,   17,   18,
       69,   19,   20,   65,   20,   29,  328,   17,   18,   30,
       17,   18,    3,    3,    4,    4,    4,    4,   20,    4,
        4,  327,    4,    4,   21,   22,    4,  326,    4,   23,
        4,    4,   69,    4,   21,   22,  325,   17,   18,   23,
       21,   22,   21,   22,   29,   23,   23,  324,   30,   47,
       47,   47,    4,    4,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   24,   32,
      323,   33,   34,   51,   51,   51,  322,   32,   24,   33,
       34,   61,   61,  321,   24,   24,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   35,   36,
       35,   36,   82,  110,   82,  132,  139,  132,  139,  318,
      144,  132,  144,  110,   35,   36,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   39,   39,
       39,   40,   40,   40,   43,   43,   43,   44,   44,   44,
       43,   98,  167,   44,  101,  167,   58,   58,   58,  105,
       44,   43,   58,  147,   44,  152,  161,  149,  161,  149,

       39,  178,  178,   40,   98,   39,  316,  101,   40,   54,
      149,  314,  105,  153,  153,  153,  147,  179,  152,  155,
      155,  155,  179,  313,   54,   58,   54,  162,   54,  162,
      163,   54,  163,   54,   54,   54,   54,   54,   54,   54,
      179,   54,   66,   66,  312,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   67,   67,   67,  157,  157,  157,
       67,  164,  311,  164,  166,  166,  166,  172,  172,  172,

      186,  186,  186,  172,  212,  201,  186,  201,  235,  228,
      235,  228,  319,  319,  212,  228,  238,  310,  238,  239,
      239,  239,  243,   67,  243,  245,  245,  245,  247,  249,
      247,  249,  250,  250,  250,  243,  172,  185,  185,  186,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  230,  230,  309,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  251,  307,  251,  253,  253,  253,  264,
      289,  289,  289,  264,  264,  265,  294,  294,  294,  265,
      265,  320,  320,  265,  265,  265,  265,  265,  265,  297,
      297,  297,  303,  306,  302,  300,  303,  303,  304,  299,

      293,  291,  288,  287,  286,  285,  304,  304,  304,  304,
      304,  304,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      358,  358,  281,  280,  358,  358,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  361,  361,  279,  277,  361,  361,  362,  362,  276,
      362,  362,  362,  362,  362,  362,  273,  362,  362,  362,
      363,  363,  272,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  365,  266,  262,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  367,  367,  260,  367,  367,  367,  367,  367,
      367,  367,  257,  255,  367,  368,  368,  254,  244,  368,
      368,  369,  369,  241,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  370,  370,  237,  236,  370,  370,
      371,  371,  233,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  372,  372,  232,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  373,  373,  229,  373,
      373,  373,  373,  373,  373,  222,  373,  373,  373,  374,

      374,  219,  218,  217,  374,  374,  374,  374,  374,  375,
      375,  206,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  376,  376,  204,  198,  376,  376,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  378,  378,  197,  378,  378,  193,  378,  378,  378,
      378,  378,  378,  378,  379,  379,  190,  379,  379,  181,
      379,  379,  379,  379,  379,  379,  379,  380,  380,  177,
      175,  380,  380,  380,  380,  174,  380,  380,  380,  380,
      381,  381,  169,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  382,  382,  159,  382,  382,  382,  382,

      382,  382,  382,  151,  150,  382,  383,  383,  146,  142,
      383,  383,  384,  141,  137,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  385,  385,  136,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  386,  386,
      134,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  387,  387,  388,  388,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  391,  126,  123,  117,  391,  392,  392,  114,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  393,  393,

      113,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  394,  111,  102,   93,  394,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  396,
       87,   80,   79,  396,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  398,  398,   78,
       73,  398,  398,  399,  399,   71,   64,  399,  399,  400,
       63,   55,   53,  400,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  402,   49,   45,
       28,  402,  403,  403,   27,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  404,   16,   15,   10,  404,

        8,    7,    6,    5,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;


    static int bracelevel, didadef;
    int i, indented_code, checking_used, new_xlation;
    int doing_codeblock = false;
    Char nmdef[MAXLINE], myesc();


    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	if ( yy_bp[-1] == '\n' )
	    ++yy_current_state;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 342 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 341 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 90 "scan.l"
indented_code = true; BEGIN(CODEBLOCK);
	YY_BREAK
case 2:
# line 91 "scan.l"
++linenum; /* treat as a comment */
	YY_BREAK
case 3:
# line 92 "scan.l"
ECHO; BEGIN(C_COMMENT);
	YY_BREAK
case 4:
# line 93 "scan.l"
return ( SCDECL );
	YY_BREAK
case 5:
# line 94 "scan.l"
return ( XSCDECL );
	YY_BREAK
case 6:
# line 95 "scan.l"
{
			++linenum;
			line_directive_out( stdout );
			indented_code = false;
			BEGIN(CODEBLOCK);
			}
	YY_BREAK
case 7:
# line 102 "scan.l"
return ( WHITESPACE );
	YY_BREAK
case 8:
# line 104 "scan.l"
{
			sectnum = 2;
			line_directive_out( stdout );
			BEGIN(SECT2PROLOG);
			return ( SECTEND );
			}
	YY_BREAK
case 9:
# line 111 "scan.l"
{
	pinpoint_message( "warning - %%used/%%unused have been deprecated" );
			checking_used = REALLY_USED; BEGIN(USED_LIST);
			}
	YY_BREAK
case 10:
# line 115 "scan.l"
{
			checking_used = REALLY_NOT_USED; BEGIN(USED_LIST);
	pinpoint_message( "warning - %%used/%%unused have been deprecated" );
			checking_used = REALLY_NOT_USED; BEGIN(USED_LIST);
			}
	YY_BREAK
case 11:
# line 122 "scan.l"
{
#ifdef NOTDEF
			fprintf( stderr,
			     "old-style lex command at line %d ignored:\n\t%s",
				 linenum, yytext );
#endif
			++linenum;
			}
	YY_BREAK
case 12:
# line 131 "scan.l"
/* ignore old lex directive */
	YY_BREAK
case 13:
# line 133 "scan.l"
{
			++linenum;
			xlation =
			    (int *) malloc( sizeof( int ) * (unsigned) csize );

			if ( ! xlation )
			    flexfatal(
				"dynamic memory failure building %t table" );

			for ( i = 0; i < csize; ++i )
			    xlation[i] = 0;

			num_xlations = 0;

			BEGIN(XLATION);
			}
	YY_BREAK
case 14:
# line 150 "scan.l"
synerr( "unrecognized '%' directive" );
	YY_BREAK
case 15:
# line 152 "scan.l"
{
			(void) strcpy( nmstr, (char *) yytext );
			didadef = false;
			BEGIN(PICKUPDEF);
			}
	YY_BREAK
case 16:
# line 158 "scan.l"
RETURNNAME;
	YY_BREAK
case 17:
# line 159 "scan.l"
++linenum; /* allows blank lines in section 1 */
	YY_BREAK
case 18:
# line 160 "scan.l"
++linenum; return ( '\n' );
	YY_BREAK
case 19:
# line 161 "scan.l"
synerr( "illegal character" ); BEGIN(RECOVER);
	YY_BREAK
case 20:
# line 164 "scan.l"
ECHO; BEGIN(INITIAL);
	YY_BREAK
case 21:
# line 165 "scan.l"
++linenum; ECHO; BEGIN(INITIAL);
	YY_BREAK
case 22:
# line 166 "scan.l"
ECHO;
	YY_BREAK
case 23:
# line 167 "scan.l"
ECHO;
	YY_BREAK
case 24:
# line 168 "scan.l"
++linenum; ECHO;
	YY_BREAK
case 25:
# line 171 "scan.l"
++linenum; BEGIN(INITIAL);
	YY_BREAK
case 26:
# line 172 "scan.l"
ECHO; CHECK_REJECT(yytext);
	YY_BREAK
case 27:
# line 173 "scan.l"
ECHO; CHECK_YYMORE(yytext);
	YY_BREAK
case 28:
# line 174 "scan.l"
ECHO;
	YY_BREAK
case 29:
# line 175 "scan.l"
{
			++linenum;
			ECHO;
			if ( indented_code )
			    BEGIN(INITIAL);
			}
	YY_BREAK
case 30:
# line 183 "scan.l"
/* separates name and definition */
	YY_BREAK
case 31:
# line 185 "scan.l"
{
			(void) strcpy( (char *) nmdef, (char *) yytext );

			for ( i = strlen( (char *) nmdef ) - 1;
			      i >= 0 &&
			      nmdef[i] == ' ' || nmdef[i] == '\t';
			      --i )
			    ;

			nmdef[i + 1] = '\0';

                        ndinstal( nmstr, nmdef );
			didadef = true;
			}
	YY_BREAK
case 32:
# line 200 "scan.l"
{
			if ( ! didadef )
			    synerr( "incomplete name definition" );
			BEGIN(INITIAL);
			++linenum;
			}
	YY_BREAK
case 33:
# line 207 "scan.l"
++linenum; BEGIN(INITIAL); RETURNNAME;
	YY_BREAK
case 34:
# line 210 "scan.l"
++linenum; BEGIN(INITIAL);
	YY_BREAK
case 35:
# line 211 "scan.l"

	YY_BREAK
case 36:
# line 212 "scan.l"
{
			if ( all_upper( yytext ) )
			    reject_really_used = checking_used;
			else
			    synerr( "unrecognized %used/%unused construct" );
			}
	YY_BREAK
case 37:
# line 218 "scan.l"
{
			if ( all_lower( yytext ) )
			    yymore_really_used = checking_used;
			else
			    synerr( "unrecognized %used/%unused construct" );
			}
	YY_BREAK
case 38:
# line 224 "scan.l"
synerr( "unrecognized %used/%unused construct" );
	YY_BREAK
case 39:
# line 227 "scan.l"
++linenum; BEGIN(INITIAL);
	YY_BREAK
case 40:
# line 228 "scan.l"
++num_xlations; new_xlation = true;
	YY_BREAK
case 41:
# line 229 "scan.l"
synerr( "bad row in translation table" );
	YY_BREAK
case 42:
# line 230 "scan.l"
/* ignore whitespace */
	YY_BREAK
case 43:
# line 232 "scan.l"
{
			xlation[myesc( yytext )] =
				(new_xlation ? num_xlations : -num_xlations);
			new_xlation = false;
			}
	YY_BREAK
case 44:
# line 237 "scan.l"
{
			xlation[yytext[0]] =
				(new_xlation ? num_xlations : -num_xlations);
			new_xlation = false;
			}
	YY_BREAK
case 45:
# line 243 "scan.l"
++linenum;
	YY_BREAK
case 46:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 246 "scan.l"
{
			++linenum;
			ACTION_ECHO;
			MARK_END_OF_PROLOG;
			BEGIN(SECT2);
			}
	YY_BREAK
case 47:
# line 253 "scan.l"
++linenum; ACTION_ECHO;
	YY_BREAK
case YY_STATE_EOF(SECT2PROLOG):
# line 255 "scan.l"
MARK_END_OF_PROLOG; yyterminate();
	YY_BREAK
case 49:
# line 257 "scan.l"
++linenum; /* allow blank lines in section 2 */
	YY_BREAK
case 50:
# line 259 "scan.l"
{
			indented_code = (yytext[0] != '%');
			doing_codeblock = true;
			bracelevel = 1;

			if ( indented_code )
			    ACTION_ECHO;

			BEGIN(CODEBLOCK_2);
			}
	YY_BREAK
case 51:
# line 270 "scan.l"
BEGIN(SC); return ( '<' );
	YY_BREAK
case 52:
# line 271 "scan.l"
return ( '^' );
	YY_BREAK
case 53:
# line 272 "scan.l"
BEGIN(QUOTE); return ( '"' );
	YY_BREAK
case 54:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 273 "scan.l"
BEGIN(NUM); return ( '{' );
	YY_BREAK
case 55:
# line 274 "scan.l"
BEGIN(BRACEERROR);
	YY_BREAK
case 56:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 275 "scan.l"
return ( '$' );
	YY_BREAK
case 57:
# line 277 "scan.l"
{
			bracelevel = 1;
			BEGIN(PERCENT_BRACE_ACTION);
			return ( '\n' );
			}
	YY_BREAK
case 58:
# line 282 "scan.l"
continued_action = true; ++linenum; return ( '\n' );
	YY_BREAK
case 59:
# line 284 "scan.l"
{
			/* this rule is separate from the one below because
			 * otherwise we get variable trailing context, so
			 * we can't build the scanner using -{f,F}
			 */
			bracelevel = 0;
			continued_action = false;
			BEGIN(ACTION);
			return ( '\n' );
			}
	YY_BREAK
case 60:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 295 "scan.l"
{
			bracelevel = 0;
			continued_action = false;
			BEGIN(ACTION);
			return ( '\n' );
			}
	YY_BREAK
case 61:
# line 302 "scan.l"
++linenum; return ( '\n' );
	YY_BREAK
case 62:
# line 304 "scan.l"
return ( EOF_OP );
	YY_BREAK
case 63:
# line 306 "scan.l"
{
			sectnum = 3;
			BEGIN(SECT3);
			return ( EOF ); /* to stop the parser */
			}
	YY_BREAK
case 64:
# line 312 "scan.l"
{
			int cclval;

			(void) strcpy( nmstr, (char *) yytext );

			/* check to see if we've already encountered this ccl */
			if ( (cclval = ccllookup( (Char *) nmstr )) )
			    {
			    yylval = cclval;
			    ++cclreuse;
			    return ( PREVCCL );
			    }
			else
			    {
			    /* we fudge a bit.  We know that this ccl will
			     * soon be numbered as lastccl + 1 by cclinit
			     */
			    cclinstal( (Char *) nmstr, lastccl + 1 );

			    /* push back everything but the leading bracket
			     * so the ccl can be rescanned
			     */
			    PUT_BACK_STRING((Char *) nmstr, 1);

			    BEGIN(FIRSTCCL);
			    return ( '[' );
			    }
			}
	YY_BREAK
case 65:
# line 341 "scan.l"
{
			register Char *nmdefptr;
			Char *ndlookup();

			(void) strcpy( nmstr, (char *) yytext );
			nmstr[yyleng - 1] = '\0';  /* chop trailing brace */

			/* lookup from "nmstr + 1" to chop leading brace */
			if ( ! (nmdefptr = ndlookup( nmstr + 1 )) )
			    synerr( "undefined {name}" );

			else
			    { /* push back name surrounded by ()'s */
			    unput(')');
			    PUT_BACK_STRING(nmdefptr, 0);
			    unput('(');
			    }
			}
	YY_BREAK
case 66:
# line 360 "scan.l"
return ( yytext[0] );
	YY_BREAK
case 67:
# line 361 "scan.l"
RETURNCHAR;
	YY_BREAK
case 68:
# line 362 "scan.l"
++linenum; return ( '\n' );
	YY_BREAK
case 69:
# line 365 "scan.l"
return ( ',' );
	YY_BREAK
case 70:
# line 366 "scan.l"
BEGIN(SECT2); return ( '>' );
	YY_BREAK
case 71:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 367 "scan.l"
BEGIN(CARETISBOL); return ( '>' );
	YY_BREAK
case 72:
# line 368 "scan.l"
RETURNNAME;
	YY_BREAK
case 73:
# line 369 "scan.l"
synerr( "bad start condition name" );
	YY_BREAK
case 74:
# line 371 "scan.l"
BEGIN(SECT2); return ( '^' );
	YY_BREAK
case 75:
# line 374 "scan.l"
RETURNCHAR;
	YY_BREAK
case 76:
# line 375 "scan.l"
BEGIN(SECT2); return ( '"' );
	YY_BREAK
case 77:
# line 377 "scan.l"
{
			synerr( "missing quote" );
			BEGIN(SECT2);
			++linenum;
			return ( '"' );
			}
	YY_BREAK
case 78:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 385 "scan.l"
BEGIN(CCL); return ( '^' );
	YY_BREAK
case 79:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 386 "scan.l"
return ( '^' );
	YY_BREAK
case 80:
# line 387 "scan.l"
BEGIN(CCL); yylval = '-'; return ( CHAR );
	YY_BREAK
case 81:
# line 388 "scan.l"
BEGIN(CCL); RETURNCHAR;
	YY_BREAK
case 82:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 390 "scan.l"
return ( '-' );
	YY_BREAK
case 83:
# line 391 "scan.l"
RETURNCHAR;
	YY_BREAK
case 84:
# line 392 "scan.l"
BEGIN(SECT2); return ( ']' );
	YY_BREAK
case 85:
# line 395 "scan.l"
{
			yylval = myctoi( yytext );
			return ( NUMBER );
			}
	YY_BREAK
case 86:
# line 400 "scan.l"
return ( ',' );
	YY_BREAK
case 87:
# line 401 "scan.l"
BEGIN(SECT2); return ( '}' );
	YY_BREAK
case 88:
# line 403 "scan.l"
{
			synerr( "bad character inside {}'s" );
			BEGIN(SECT2);
			return ( '}' );
			}
	YY_BREAK
case 89:
# line 409 "scan.l"
{
			synerr( "missing }" );
			BEGIN(SECT2);
			++linenum;
			return ( '}' );
			}
	YY_BREAK
case 90:
# line 417 "scan.l"
synerr( "bad name in {}'s" ); BEGIN(SECT2);
	YY_BREAK
case 91:
# line 418 "scan.l"
synerr( "missing }" ); ++linenum; BEGIN(SECT2);
	YY_BREAK
case 92:
# line 421 "scan.l"
bracelevel = 0;
	YY_BREAK
case 93:
# line 422 "scan.l"
{
			ACTION_ECHO;
			CHECK_REJECT(yytext);
			}
	YY_BREAK
case 94:
# line 426 "scan.l"
{
			ACTION_ECHO;
			CHECK_YYMORE(yytext);
			}
	YY_BREAK
case 95:
# line 430 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 96:
# line 431 "scan.l"
{
			++linenum;
			ACTION_ECHO;
			if ( bracelevel == 0 ||
			     (doing_codeblock && indented_code) )
			    {
			    if ( ! doing_codeblock )
				fputs( "\tYY_BREAK\n", temp_action_file );
			    
			    doing_codeblock = false;
			    BEGIN(SECT2);
			    }
			}
	YY_BREAK
	/* Reject and YYmore() are checked for above, in PERCENT_BRACE_ACTION */
case 97:
# line 447 "scan.l"
ACTION_ECHO; ++bracelevel;
	YY_BREAK
case 98:
# line 448 "scan.l"
ACTION_ECHO; --bracelevel;
	YY_BREAK
case 99:
# line 449 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 100:
# line 450 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 101:
# line 451 "scan.l"
ACTION_ECHO; BEGIN(ACTION_COMMENT);
	YY_BREAK
case 102:
# line 452 "scan.l"
ACTION_ECHO; /* character constant */
	YY_BREAK
case 103:
# line 453 "scan.l"
ACTION_ECHO; BEGIN(ACTION_STRING);
	YY_BREAK
case 104:
# line 454 "scan.l"
{
			++linenum;
			ACTION_ECHO;
			if ( bracelevel == 0 )
			    {
			    fputs( "\tYY_BREAK\n", temp_action_file );
			    BEGIN(SECT2);
			    }
			}
	YY_BREAK
case 105:
# line 463 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 106:
# line 465 "scan.l"
ACTION_ECHO; BEGIN(ACTION);
	YY_BREAK
case 107:
# line 466 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 108:
# line 467 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 109:
# line 468 "scan.l"
++linenum; ACTION_ECHO;
	YY_BREAK
case 110:
# line 469 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 111:
# line 471 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 112:
# line 472 "scan.l"
ACTION_ECHO;
	YY_BREAK
case 113:
# line 473 "scan.l"
++linenum; ACTION_ECHO;
	YY_BREAK
case 114:
# line 474 "scan.l"
ACTION_ECHO; BEGIN(ACTION);
	YY_BREAK
case 115:
# line 475 "scan.l"
ACTION_ECHO;
	YY_BREAK
case YY_STATE_EOF(ACTION):
case YY_STATE_EOF(ACTION_COMMENT):
case YY_STATE_EOF(ACTION_STRING):
# line 477 "scan.l"
{
			synerr( "EOF encountered inside an action" );
			yyterminate();
			}
	YY_BREAK
case 117:
# line 483 "scan.l"
{
			yylval = myesc( yytext );
			return ( CHAR );
			}
	YY_BREAK
case 118:
# line 488 "scan.l"
{
			yylval = myesc( yytext );
			BEGIN(CCL);
			return ( CHAR );
			}
	YY_BREAK
case 119:
# line 495 "scan.l"
ECHO;
	YY_BREAK
case 120:
# line 496 "scan.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SECT2):
case YY_STATE_EOF(SECT3):
case YY_STATE_EOF(CODEBLOCK):
case YY_STATE_EOF(PICKUPDEF):
case YY_STATE_EOF(SC):
case YY_STATE_EOF(CARETISBOL):
case YY_STATE_EOF(NUM):
case YY_STATE_EOF(QUOTE):
case YY_STATE_EOF(FIRSTCCL):
case YY_STATE_EOF(CCL):
case YY_STATE_EOF(RECOVER):
case YY_STATE_EOF(BRACEERROR):
case YY_STATE_EOF(C_COMMENT):
case YY_STATE_EOF(PERCENT_BRACE_ACTION):
case YY_STATE_EOF(USED_LIST):
case YY_STATE_EOF(CODEBLOCK_2):
case YY_STATE_EOF(XLATION):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    register YY_CHAR *yy_bp = yytext;

    yy_current_state = yy_start;
    if ( yy_bp[-1] == '\n' )
	++yy_current_state;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 342 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 342 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 341);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 496 "scan.l"



int yywrap()

    {
    if ( --num_input_files > 0 )
	{
	set_input_file( *++input_files );
	return ( 0 );
	}

    else
	return ( 1 );
    }


/* set_input_file - open the given file (if NULL, stdin) for scanning */

void set_input_file( file )
char *file;

    {
    if ( file )
	{
	infilename = file;
	yyin = fopen( infilename, "r" );

	if ( yyin == NULL )
	    lerrsf( "can't open %s", file );
	}

    else
	{
	yyin = stdin;
	infilename = "<stdin>";
	}
    }
