#	@(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: src/share/doc/usd/21.troff/Makefile,v 1.6.22.1.6.1 2010/12/21 17:09:25 kensmith Exp $

VOLUME=		usd/21.troff
SRCS=		m.mac m0 m0a m1 m2 m3 m4 m5 table1 table2
USE_TBL=

.include <bsd.doc.mk>
