#	From: @(#)Makefile	5.2 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/beyond4.3/Makefile,v 1.9.36.1.6.1 2010/12/21 17:09:25 kensmith Exp $

VOLUME=	papers
DOC=	beyond43
SRCS=	beyond43.ms
MACROS=	-ms

.include <bsd.doc.mk>
