# $FreeBSD: src/sys/modules/pmc/Makefile,v 1.3.20.1 2009/04/15 03:14:26 kensmith Exp $

.PATH: ${.CURDIR}/../../pc98/cbus

KMOD=	pmc
SRCS=	pmc.c
SRCS+=	bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
