# $FreeBSD: src/sys/modules/sysvipc/sysvmsg/Makefile,v 1.5.2.1.6.1 2010/12/21 17:09:25 kensmith Exp $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvmsg
SRCS=	sysv_msg.c opt_sysvipc.h

.include <bsd.kmod.mk>
