# $FreeBSD: src/sys/modules/sysvipc/sysvmsg/Makefile,v 1.4.18.1 2008/11/25 02:59:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvmsg
SRCS=	sysv_msg.c opt_mac.h opt_sysvipc.h

.include <bsd.kmod.mk>
