.\"
.\" Copyright (c) 1998, 2000
.\" 	Justin T. Gibbs.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd February 13, 2000
.Dt ADV 4
.Os
.Sh NAME
.Nm adv
.Nd Advansys ISA/VL/EISA/PCI 8bit SCSI Host adapter driver
.Sh SYNOPSIS
For one or more ISA or VL cards:
.Cd device isa
.Cd device "adv0 at isa? port ? irq ? drq ?"
.Pp
For one or more EISA cards:
.Cd device eisa
.Cd device adv
.Pp
For one or more PCI cards:
.Cd device pci
.Cd device adv
.Pp
For one or more SCSI busses:
.Cd device scbus0 at adv0
.Sh DESCRIPTION
This driver provides access to the 8bit
.Tn SCSI
bus connected to the Advanced Systems Products, Inc.
.Tn ASC900 ,
.Tn ASC1000 ,
.Tn ASC1090 ,
.Tn ASC1200 ,
.Tn ASC3030 ,
.Tn ASC3050 ,
and
.Tn ASC3150
host adapter chips.
The following tables list the AdvanSys products using these chips,
their bus attachment type, maximum sync rate, and the maximum number of
commands that can be handled by the adapter concurrently.
.Pp
.Bd -ragged -offset indent
.Bl -column "ABP510/5150 " "ISA PnP " "Yes " "10MHz " "Commands " Footnotes
Connectivity Products:
.Pp
.Em "Adapter       Bus   Floppy      MaxSync   Commands  Footnotes"
ABP510/5150   ISA     No         10MHz       240    1
ABP5140     ISA PnP   No         10MHz       16     1, 3
ABP5142     ISA PnP   Yes        10MHz       16     4
ABP[3]902     PCI     No         10MHz       16
ABP3905       PCI     No         10MHz       16
ABP915        PCI     No         10MHz       16
ABP920        PCI     No         10MHz       16
ABP3922       PCI     No         10MHz       16
ABP3925       PCI     No         10MHz       16
ABP930        PCI     No         10MHz       16     5
ABP930U       PCI     No         20MHz       16
ABP930UA      PCI     No         20MHz       16
ABP960        PCI     No         10MHz       16
ABP960U       PCI     No         20MHz       16
.El
.Pp
Footnotes:
.Bl -enum -compact
.It
This board has been shipped by HP with the 4020i CD-R drive.
The board has no BIOS so it cannot control a boot device, but
it can control any secondary SCSI device.
.It
This board has been sold by Iomega as a Jaz Jet PCI adapter.
.It
This board has been sold by SIIG as the i540 SpeedMaster.
.It
This board has been sold by SIIG as the i542 SpeedMaster.
.It
This board has been sold by SIIG as the Fast SCSI Pro PCI.
.El
.Ed
.Pp
.Bd -ragged -offset indent
.Bl -column "ABP510/5150 " "ISA PnP " "Yes " "10MHz " Commands
Single Channel Products:
.Pp
.Em "Adapter       Bus   Floppy      MaxSync   Commands"
ABP542        ISA     Yes        10MHz       240
ABP742        EISA    Yes        10MHz       240
ABP842        VL      Yes        10MHz       240
ABP940        PCI     No         10MHz       240
ABP[3]940UA   PCI     No         20MHz       240
ABP940U       PCI     No         20MHz       240
ABP3960UA     PCI     No         20MHz       240
ABP970        PCI     No         10MHz       240
ABP970U       PCI     No         20MHz       240
.El
.Ed
.Pp
.Bd -ragged -offset indent
.Bl -column "ABP510/5150 " "ISA PnP " "Yes " "10MHz " "Commands " "Channels "
Multi Channel Products (Commands are per-channel):
.Pp
.Em "Adapter       Bus   Floppy      MaxSync   Commands  Channels"
ABP752       EISA     Yes        10MHz       240      2
ABP852        VL      Yes        10MHz       240      2
ABP950        PCI     No         10MHz       240      2
ABP980        PCI     No         10MHz       240      4
ABP980U       PCI     No         20MHz       240      4
ABP[3]980UA   PCI     No         20MHz       16       4
.El
.Ed
.Pp
For ISA or Vesa Local Bus adapters, one kernel config entry is required
for every card to be attached by the system.  Specific values for the port
address, irq, and drq may be specified.  If wildcard values are used, the
driver will query the device for its current settings and use those.  If
the port address is a wildcard, the driver consults an internal table of
possible port address locations and attaches to the first unattached card
it finds.  The possible port addresses for these card are 0x110, 0x130,
0x150, 0x190, 0x210, 0x230, 0x250, and 0x330.
.Pp
Per target configuration performed in the
.Tn AdvanceWare
menu, which is accessible at boot,
is honored by this driver.
This includes synchronous/asynchronous transfers,
maximum synchronous negotiation rate, disconnection, tagged queueing,
and the host adapter's SCSI ID.
The global setting for the maximum number of tagged transactions allowed
per target is not honored as the CAM SCSI system will automatically determine
the maximum number of tags a device can receive as well as guarantee fair
resource allocation among devices.
.Sh SEE ALSO
.Xr adw 4 ,
.Xr aha 4 ,
.Xr ahb 4 ,
.Xr ahc 4 ,
.Xr cd 4 ,
.Xr da 4 ,
.Xr sa 4 ,
.Xr scsi 4
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was ported by
.An Justin T. Gibbs
from the Linux driver
written by
.An Bob Frey
of Advanced System Products, Inc.
Many thanks to AdvanSys for providing the original driver under a suitable
license for use in
.Fx .
.Sh HISTORY
The
.Nm
driver appeared in
.Fx 3.0 .
