.\"
.\" Copyright (c) 2009 Lawrence Stewart <lstewart@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions, and the following disclaimer,
.\"    without modification, immediately at the beginning of the file.
.\" 2. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd July 3, 2009
.Dt CC_NEWRENO 4
.Os
.Sh NAME
.Nm cc_newreno
.Nd NewReno Congestion Control Algorithm
.Sh DESCRIPTION
The
.N
congestion control algorithm
.Ss Runtime Configuration
There are currently no tunable variables.
.Sh SEE ALSO
.Xr cc 9
.Sh HISTORY
The
.Nm
congestion control module first appeared in
.Fx 8.0 .
.Sh AUTHORS
.An -nosplit
The
.Nm
congestion control module was written by
.An James Healy Aq jimmy@deefa.com
and
.An Lawrence Stewart Aq lstewart@FreeBSD.org
while working at the Centre for Advanced Internet Architectures,
Swinburne University (http://caia.swin.edu.au/).
.Pp
This manual page was written by
.An Lawrence Stewart Aq lstewart@FreeBSD.org .
.Sh ACKNOWLEDGMENTS
Development of this software was made possible in part by a grant from the
Cisco University Research Program Fund at Community Foundation Silicon Valley.
