#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/tput/Makefile,v 1.4.36.1.6.1 2010/12/21 17:09:25 kensmith Exp $

PROG=	tput
DPADD=	${LIBTERMCAP}
LDADD=	-ltermcap
SCRIPTS=clear.sh
MLINKS=	tput.1 clear.1

.include <bsd.prog.mk>
