#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/tput/Makefile,v 1.4.30.1 2008/10/02 02:57:24 kensmith Exp $

PROG=	tput
DPADD=	${LIBTERMCAP}
LDADD=	-ltermcap
SCRIPTS=clear.sh
MLINKS=	tput.1 clear.1

.include <bsd.prog.mk>
