
# $FreeBSD: src/sys/modules/plip/Makefile,v 1.2 2002/01/11 15:48:56 ru Exp $

.PATH:	${.CURDIR}/../../dev/ppbus
KMOD=	plip
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_plip.h \
	if_plip.c

.include <bsd.kmod.mk>
