# $FreeBSD: src/sys/modules/netgraph/sppp/Makefile,v 1.1.32.1 2010/02/10 00:26:20 kensmith Exp $
# Cronyx Id: ng_sppp.Makefile,v 1.1.2.1 2002/12/25 08:37:25 rik Exp $

KMOD=	ng_sppp
SRCS= 	ng_sppp.c

.include <bsd.kmod.mk>
