# $FreeBSD: src/sys/modules/mac_biba/Makefile,v 1.2.36.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../security/mac_biba

KMOD=	mac_biba
SRCS=	vnode_if.h \
	mac_biba.c

.include <bsd.kmod.mk>
