#	$FreeBSD: src/tools/regression/net80211/ccmp/Makefile,v 1.1.16.1 2008/10/02 02:57:24 kensmith Exp $

.PATH:	${.CURDIR}/../../../../sys/net80211

KMOD=	test_ccmp
SRCS+=	test_ccmp.c

.include <bsd.kmod.mk>
