#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
#	Makefile,v 1.2 1994/10/02 04:48:18 davidg Exp

BINDIR=/usr/sbin
PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1
MAN1=	rtprio.1
MAN2=	rtprio.2

.include <bsd.prog.mk>
