#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: src/usr.sbin/rtprio/Makefile,v 1.8.36.1.6.1 2010/12/21 17:09:25 kensmith Exp $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

.include <bsd.prog.mk>
