#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: src/usr.sbin/rtprio/Makefile,v 1.8.36.1.4.1 2010/06/14 02:09:06 kensmith Exp $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

.include <bsd.prog.mk>
