# Makefile to build LCD control software for ppi(4) interface.
#
# $FreeBSD: src/share/examples/ppi/Makefile,v 1.6.20.1 2009/04/15 03:14:26 kensmith Exp $

PROG=	ppilcd
NO_MAN=

.include <bsd.prog.mk>
