# Makefile to build LCD control software for ppi(4) interface.
#
# $FreeBSD: src/share/examples/ppi/Makefile,v 1.6.22.1.8.1 2012/03/03 06:15:13 kensmith Exp $

PROG=	ppilcd
NO_MAN=

.include <bsd.prog.mk>
