# $FreeBSD: src/sys/modules/ex/Makefile,v 1.2.30.1.4.1 2010/06/14 02:09:06 kensmith Exp $
#

.PATH:	${.CURDIR}/../../dev/ex

KMOD=	if_ex
SRCS=	if_ex.c \
	if_ex_isa.c isa_if.h \
	if_ex_pccard.c card_if.h \
	bus_if.h device_if.h pccarddevs.h

.include <bsd.kmod.mk>
