# $FreeBSD: src/gnu/lib/Makefile.inc,v 1.6.2.1 1999/08/29 14:28:32 peter Exp $

SHLIB_MAJOR?= 2
SHLIB_MINOR?= 0


# NB: SHLIB major and minor nos. must also be specified in libg++/Makefile.inc
# (This is due to the deeper tree structure of libg++)
