#
# $FreeBSD: src/tools/regression/sockets/socketpair/Makefile,v 1.1 2004/08/04 03:46:35 rwatson Exp $
#

PROG=	socketpair
NOMAN=	yes

socketpair: socketpair.c
	gcc -Wall -o socketpair socketpair.c

.include <bsd.prog.mk>
