#! /bin/sh

LOGF=make.log

CONFIG_ARGS="$@"

IAM=`hostname || uname -n`

#set -e
#set -x

CVO=`./config.guess`
case "$CVO" in
 *-*-*) ;;
 *) echo "config.guess returned <$CVO>, which makes no sense to me."
    exit 1
    ;;
esac

MYNAME=`IFS=. ; set $IAM ; echo $1`

case "$IAM" in
 *.udel.edu)
    BDIR=A.$MYNAME
    ;;
 *)
    BDIR=A.$CVO
    ;;
esac

CCSUF=""

case "$CC" in
 '') ;;
 *) CCSUF="-$CC"
    ;;
esac

BDIR="$BDIR$CCSUF"

[ -d "$BDIR" ] || mkdir $BDIR
[ -f "$BDIR/.buildcvo" ] || echo $CVO > $BDIR/.buildcvo
[ -f "$BDIR/.buildhost" ] || echo $IAM > $BDIR/.buildhost

cd $BDIR

(
[ -f config.status ] || ../configure $CONFIG_ARGS

case "$MAKE" in
 '') make && make check
     ;;
 *)  $MAKE && $MAKE check
     ;;
esac
) > $LOGF 2>&1
