# $FreeBSD: src/sys/modules/geom/geom_mirror/Makefile,v 1.1 2004/07/30 23:13:44 pjd Exp $

.PATH: ${.CURDIR}/../../../geom/mirror

KMOD=	geom_mirror
SRCS=	g_mirror.c
SRCS+=	g_mirror_ctl.c

.include <bsd.kmod.mk>
