# $FreeBSD: src/sys/modules/geom/geom_mirror/Makefile,v 1.1.26.1 2008/11/25 02:59:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../geom/mirror

KMOD=	geom_mirror
SRCS=	g_mirror.c
SRCS+=	g_mirror_ctl.c

.include <bsd.kmod.mk>
