#	@(#)Makefile	8.1 (Berkeley) 6/29/93
#	$FreeBSD: src/usr.bin/gprof/Makefile,v 1.8.24.1 2008/10/02 02:57:24 kensmith Exp $

PROG=	gprof
SRCS=	gprof.c aout.c arcs.c dfn.c elf.c lookup.c hertz.c \
	printgprof.c printlist.c kernel.c
FILES=	gprof.flat gprof.callg
FILESDIR=	${SHAREDIR}/misc

.include <bsd.prog.mk>
