.\" -*- nroff -*-
.TH @G@SOELIM @MAN1EXT@ "@MDATE@" "Groff Version @VERSION@"
.SH NAME
@g@soelim \- interpret .so requests in groff input
.SH SYNOPSIS
.B @g@soelim
[
.B \-Cv
]
[
.IR files \|.\|.\|.\|
]
.SH DESCRIPTION
.B @g@soelim
reads
.I files
and replaces lines of the form
.IP
.BI .so\  file
.LP
by the contents of
.IR file .
It is useful if files included with
.B so
need to be preprocessed.
Normally,
.B @g@soelim
should be invoked with the
.B \-s
option of
.BR groff .
.SH OPTIONS
.TP
.B \-C
Recognize
.B .so
even when followed by a character other than space or newline.
.TP
.B \-v
Print the version number.
.SH "SEE ALSO"
.BR groff (@MAN1EXT@)
