# $FreeBSD: src/lib/libgpib/Makefile,v 1.6.6.1 2008/11/25 02:59:29 kensmith Exp $

LIB=		gpib
SHLIB_MAJOR=	2
INCS=		gpib.h
INCSDIR=	${INCLUDEDIR}/gpib
SRCS=		ibfoo.c
WARNS?=		6

.include <bsd.lib.mk>
