.\" Copyright (c) 2011 Sandvine Incorporated. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd August 23, 2010
.Dt NETDUMPSRV 8
.Os
.Sh NAME
.Nm netdumpsrv
.Nd receive kernel core dumps over the network
.Sh SYNOPSIS
.Nm
.Op Fl a Ar addr
.Op Fl D
.Op Fl d Ar dumpdir
.Op Fl i Ar script
.Sh DESCRIPTION
The
.Nm
utility listens on a UDP socket for incoming connections
from a
.Fx
kernel core dumping over the network.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl a
Bind the daemon to the given address
.Dq Pa addr .
.It Fl D
Run the utility in debugging mode.
The daemon version is not entered while the output
is printed entirely on the console.
.It Fl d
Save the core dumps to the specified
.Dq Pa dumpdir
directory.
.It Fl i
Execute the script
.Dq Pa script
after each dump received.
The script accepts the following strings as parameters:
its name,
reasons for invokation,
the client address,
the client hostname,
the info file name and the core dump file name.
.El
.Sh SEE ALSO
.Xr dumpon 8
.Sh HISTORY
The
.Nm
utility appeared in
.Fx 9.0 .
