#	From: @(#)Makefile	8.2 (Berkeley) 4/20/94
#	$Id: Makefile,v 1.4 1995/01/11 19:51:46 wollman Exp $

# The following modules are encumbered:
# 01.begin 02.learn 03.shell 05.dc 06.bc 09.edtut 10.edadv 15.sed 16.awk
# 17.msmacros 21.troff 22.trofftut 23.eqn 24.eqnguide 25.tbl 26.refer
# 27.invert 28.bib 29.diction 

# The following modules are not provided:
# 14.jove

BINDIR=	/usr/share/doc/psd
SUBDIR=	title contents 05.sysman 12.make 18.gprof 19.curses 20.ipctut \
	21.ipc 22.rpcgen 23.rpc 24.xdr 25.xdrrfc 26.rpcrfc 27.nfsrpc

.include <bsd.subdir.mk>
