#
# $FreeBSD: src/gnu/usr.bin/binutils/as/i386-winnt/Makefile,v 1.1.2.1 2000/07/06 22:15:43 obrien Exp $
#

.include "${.CURDIR}/../Makefile.inc0"

PROG=		as
NOMAN=		1
BINDIR=		/usr/libexec/cross/i386-winnt
SRCS+=		obj-coff.c tc-i386.c

.include <bsd.prog.mk>
