# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: src/usr.sbin/amd/mk-amd-map/Makefile,v 1.10.2.1 2001/04/25 12:09:15 ru Exp $
#

.PATH:		${.CURDIR}/../../../contrib/amd/mk-amd-map

PROG=		mk-amd-map
MAN=		mk-amd-map.8

.include <bsd.prog.mk>
