#	$FreeBSD: src/sbin/ipf/Makefile,v 1.16.22.1.6.1 2010/12/21 17:09:25 kensmith Exp $

#.WAIT
SUBDIR=		libipf
SUBDIR+=	ipf ipfs ipfstat ipftest ipmon ipnat ippool ipresend
#SUBDIR+=	ipsend iptest rules

.include <bsd.subdir.mk>
