# $FreeBSD$

PROG = sdpd

SRCS = \
	bgd.c \
	dun.c \
	ftrn.c \
	gn.c \
	irmc.c \
	irmc_command.c \
	lan.c \
	log.c \
	main.c \
	nap.c \
	opush.c \
	panu.c \
	profile.c \
	provider.c \
	sar.c \
	scr.c \
	sd.c \
	server.c \
	sp.c \
	srr.c \
	ssar.c \
	ssr.c \
	sur.c \
	uuid.c

WARNS ?= 2

CFLAGS += -I${.CURDIR}

.include <bsd.prog.mk>
