# $FreeBSD: src/sys/modules/sound/driver/envy24ht/Makefile,v 1.2.12.1.4.1 2010/06/14 02:09:06 kensmith Exp $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_envy24ht
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	envy24ht.c

.include <bsd.kmod.mk>
