#	$FreeBSD: src/sbin/ipf/iptest/Makefile,v 1.1.24.1 2010/02/10 00:26:20 kensmith Exp $

.include <bsd.own.mk>

PROG=		iptest
SRCS=		iptest.c iptests.c ip.c sbpf.c sock.c 44arp.c
MAN=		iptest.1

.PATH:		${NETBSDSRCDIR}/dist/ipf/ipsend

.include <bsd.prog.mk>
