# $FreeBSD$

PROG = nos-tun

WARNS ?= 0

DIRDEP= gnu/lib/csu gnu/lib/libgcc include include/arpa lib/csu/MACHINE_ARCH lib/libc stage sys/MACHINE_ARCH/include sys/net sys/netinet sys/netinet6 sys/sys
.include <bsd.prog.mk>

