# $FreeBSD$

.include <bsd.own.mk>

LIB=	lldbHostCommon

SRCDIR=	tools/lldb/source/Host/common
SRCS=	Condition.cpp \
	Editline.cpp \
	File.cpp \
	FileSpec.cpp \
	FileSystem.cpp \
	GetOptInc.cpp \
	Host.cpp \
	HostInfoBase.cpp \
	HostNativeThreadBase.cpp \
	HostProcess.cpp \
	HostThread.cpp \
	IOObject.cpp \
	LockFileBase.cpp \
	MonitoringProcessLauncher.cpp \
	Mutex.cpp \
	NativeRegisterContext.cpp \
	OptionParser.cpp \
	PipeBase.cpp \
	ProcessRunLock.cpp \
	Socket.cpp \
	SocketAddress.cpp \
	SoftwareBreakpoint.cpp \
	StringConvert.cpp \
	Symbols.cpp \
	TCPSocket.cpp \
	Terminal.cpp \
	ThisThread.cpp \
	ThreadLauncher.cpp \
	TimeValue.cpp \
	XML.cpp \
	UDPSocket.cpp

TGHDRS=	AttrList \
	Attrs \
	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
