# $FreeBSD: src/usr.sbin/zic/Makefile,v 1.6.36.1.2.1 2009/10/25 01:10:29 kensmith Exp $

# Vendor contact: tz@elsie.nci.nih.gov
MAINTAINER=	wollman@FreeBSD.org

SUBDIR=	zic zdump

.include <bsd.subdir.mk>
