# $FreeBSD: src/sys/modules/syscons/fire/Makefile,v 1.9.36.1.2.1 2009/10/25 01:10:29 kensmith Exp $

.PATH:	${.CURDIR}/../../../dev/syscons/fire

KMOD=	fire_saver
SRCS=	fire_saver.c

.include <bsd.kmod.mk>
