name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  FreeBSD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bs: [autotools, cmake]
    steps:
    - name: Build and test on a FreeBSD 15 firecracker VM
      uses: acj/freebsd-firecracker-action@ff79eb955fd19c697a708a02834995e47a6e58ed # v0.10.0
      with:
        run-in-vm: |
          chflags -R noschg / && \
          fetch -o - https://download.freebsd.org/releases/amd64/15.0-RELEASE/base.txz | bsdtar -x -C / -f - && \
          pkg bootstrap -y && \
          cd firecracker-freebsd && \
          env BS=${{ matrix.bs }} ./build/ci/github_actions/freebsd.sh prepare && \
          env BS=${{ matrix.bs }} CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./build/ci/build.sh -a autogen && \
          env BS=${{ matrix.bs }} MAKE=gmake CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./build/ci/build.sh -a configure && \
          env BS=${{ matrix.bs }} MAKE=gmake MAKE_ARGS="-j 2" ./build/ci/build.sh -a build && \
          env BS=${{ matrix.bs }} MAKE=gmake SKIP_TEST_RESTORE_ATIME=1 MAKE_ARGS="-j 2" ./build/ci/build.sh -a test && \
          env BS=${{ matrix.bs }} ./build/ci/github_actions/freebsd.sh test && \
          env BS=${{ matrix.bs }} MAKE=gmake MAKE_ARGS="-j 2" ./build/ci/build.sh -a install
  MacOS:
    runs-on: macos-15
    strategy:
      matrix:
        bs: [autotools, cmake]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install dependencies
      run: ./build/ci/github_actions/install-macos-dependencies.sh
    - name: Autogen
      run: ./build/ci/build.sh -a autogen
      env:
        BS: ${{ matrix.bs }}
    - name: Configure
      run: ./build/ci/build.sh -a configure
      env:
        BS: ${{ matrix.bs }}
        # Avoid using liblzma from the Xcode 16 / MacOSX15.0.sdk, which fails RISCV filter tests.
        CMAKE_ARGS: -D LIBLZMA_LIBRARY=/opt/homebrew/lib/liblzma.dylib -D LIBLZMA_INCLUDE_DIR=/opt/homebrew/include/lzma.h
    - name: Build
      run: ./build/ci/build.sh -a build
      env:
        BS: ${{ matrix.bs }}
        MAKE_ARGS: -j3
    - name: Test
      run: ./build/ci/build.sh -a test
      env:
        BS: ${{ matrix.bs }}
        SKIP_OPEN_FD_ERR_TEST: 1
        IGNORE_TRAVERSALS_TEST4: 1
        MAKE_ARGS: -j3
        CTEST_OUTPUT_ON_FAILURE: ON
    - name: Install
      run: ./build/ci/build.sh -a install
      env:
        BS: ${{ matrix.bs }}
        MAKE_ARGS: -j3
    - name: Artifact
      run: ./build/ci/build.sh -a artifact
      env:
        BS: ${{ matrix.bs }}
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: libarchive-macos-${{ matrix.bs }}-${{ github.sha }}
        path: libarchive.tar.xz

  Ubuntu:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        bs: [autotools, cmake]
        crypto: [mbedtls, nettle, openssl]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Update apt cache
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake build-essential cmake git libssl-dev nettle-dev libmbedtls-dev libacl1-dev libbz2-dev liblzma-dev liblz4-dev libzstd-dev lzop pkg-config zlib1g-dev
    - name: Autogen
      run: ./build/ci/build.sh -a autogen
      env:
        BS: ${{ matrix.bs }}
    - name: Configure
      run: ./build/ci/build.sh -a configure
      env:
        BS: ${{ matrix.bs }}
        CRYPTO: ${{ matrix.crypto }}
    - name: Build
      run: ./build/ci/build.sh -a build
      env:
        BS: ${{ matrix.bs }}
        MAKE_ARGS: -j4
    - name: Test
      run: ./build/ci/build.sh -a test
      env:
        BS: ${{ matrix.bs }}
        SKIP_OPEN_FD_ERR_TEST: 1
        MAKE_ARGS: -j4
        CTEST_OUTPUT_ON_FAILURE: ON
    - name: Install
      run: ./build/ci/build.sh -a install
      env:
        BS: ${{ matrix.bs }}
    - name: Artifact
      run: ./build/ci/build.sh -a artifact
      env:
        BS: ${{ matrix.bs }}
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: libarchive-ubuntu-${{ matrix.bs }}-${{ matrix.crypto }}-${{ github.sha }}
        path: libarchive.tar.xz
  Ubuntu-distcheck:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Update package definitions
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y autoconf automake bsdmainutils build-essential cmake ghostscript git groff libssl-dev libacl1-dev libbz2-dev liblzma-dev liblz4-dev libzstd-dev lzop pkg-config zip zlib1g-dev
    - name: Autogen
      run: ./build/ci/build.sh -a autogen
    - name: Configure
      run: ./build/ci/build.sh -a configure
    - name: Distcheck
      run: ./build/ci/build.sh -a distcheck
      env:
        SKIP_OPEN_FD_ERR_TEST: 1
    - name: Dist-Artifact
      run: ./build/ci/build.sh -a dist-artifact
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: libarchive-${{ github.sha }}
        path: libarchive-dist.tar

  Windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        be: [mingw-gcc, cygwin-gcc, msvc]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@3f0a3f9f988f7e96b8c18098ae05eaec175f5b52 # v6
      if:  ${{ matrix.be=='cygwin-gcc' }}
      with:
        install-dir: "D:\\cygwin"
        packages: |-
          make autoconf automake cmake
          gcc-core binutils libtool pkg-config
          bison zlib-devel libbz2-devel liblzma-devel
          liblz4-devel libiconv-devel libxml2-devel
          libzstd-devel libssl-devel
    - name: Install MinGW (msys2)
      uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
      if:  ${{ matrix.be=='mingw-gcc' }}
      with:
        location: "D:\\"
        install: |-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-autotools
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-bzip2
          mingw-w64-x86_64-xz
          mingw-w64-x86_64-zstd
    - name: Configure
      run: ./build/ci/github_actions/ci.cmd configure
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Build
      run: ./build/ci/github_actions/ci.cmd build
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Test
      run: ./build/ci/github_actions/ci.cmd test
      shell: cmd
      env:
        BE: ${{ matrix.be }}
        CTEST_OUTPUT_ON_FAILURE: ON
    - name: Install
      run: ./build/ci/github_actions/ci.cmd install
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - name: Artifact
      run: ./build/ci/github_actions/ci.cmd artifact
      shell: cmd
      env:
        BE: ${{ matrix.be }}
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: libarchive-windows-${{ matrix.be }}-${{ github.sha }}
        path: ${{ matrix.be=='cygwin-gcc' && 'libarchive.tar.xz' || 'libarchive.zip' }}
