SUBDIR=	beyond4.3 \
	bufbio \
	contents \
	devfs \
	diskperf \
	fsinterface \
	jail \
	kernmalloc \
	kerntune \
	newvm \
	relengr \
	sysperf \
	timecounter

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
