#-
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2019 Ahsan Barkati
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#

. $(atf_get_srcdir)/utils.subr

setup_tests()
{   
	tests=""
	while [ $# -gt 0 ]; do
		if [ $(is_firewall $1) -eq  1 ]; then
			fw=$1
			shift
			if [ -z "${testcase}" ]; then
				echo "no testcase passed to setup_test"
				return
			fi
			atf_test_case "${fw}_${testcase}" "cleanup"
			eval "${fw}_${testcase}_head(){ ${testcase}_head; }"
			eval "${fw}_${testcase}_body(){ ${testcase}_body $fw; }"
			eval "${fw}_${testcase}_cleanup(){ ${testcase}_cleanup $fw; }"
			tests="$tests ${fw}_${testcase}"
		else
			testcase=$1
			shift
		fi
	done
	init_testcases "$tests"
}


init_testcases()
{
	args="$@"
	atf_init_test_cases()
	{
		for testcase in $args;
		do 
			atf_add_test_case "$testcase"
		done
	}
}