#	from: @(#)Makefile	5.1.1.1 (Berkeley) 5/7/91
#	Makefile,v 1.3 1993/07/31 15:29:22 mycroft Exp

#Missing: index iso papers ps2 ucs

SUBDIR=	ps1 smm usd

all paper print clean: _SUBDIRUSE

depend lint tags:

.include <bsd.subdir.mk>
